// scripts/demo-seed/lib/content/guides.mjs
// =============================================================================
// Las 3 GUÍAS del apartamento demo: llegada, piscina/exteriores y salida.
//
// ⚠️ POR QUÉ SON TEXTO NUMERADO Y NO `guide_info_steps`:
// La tabla guide_info_steps existe y el admin sabe escribirla, pero
// workerGuide.js (la respuesta pública de GET /guide/:slug) NO devuelve `steps`
// — se comprobó con grep antes de escribir esto: 'guide_step' aparece en
// workerGuideAdmin.js (alta/edición/borrado) y en ningún sitio más. El
// GuideDetailModal del huésped tiene el render de pasos preparado y nunca
// recibe datos, así que un bloque con is_sequential=1 hoy enseña su `content`
// y punto. Por eso los pasos van dentro de `content` con saltos de línea: el
// modal lo pinta con whitespace-pre-wrap y se lee igual de bien.
//
// Si algún día workerGuide.js empieza a servir `steps`, migrar esto es partir
// cada content por '\n' — no hay nada más que rehacer.
//
// SIN MARKDOWN: InfoSection/GuideDetailModal renderizan texto plano
// (CLAUDE.md §4). Un **negrita** saldría con los asteriscos literales.
// =============================================================================

export const GUIDES = [
    {
        key: 'checkin',
        order: 10,
        // Foto propia del bloque (guide_apartment_media). El manifiesto de
        // assets la pide con este nombre; si no existe, la tarjeta cae al
        // MediaPlaceholder y la demo sigue funcionando.
        image: 'checkin.jpg',
        content: {
            es: `1. Antes de salir\nLa entrada es a partir de las {{checkin_time}}. Escríbenos por WhatsApp cuando salgas hacia {{town}} y te esperamos con todo listo.\n\n2. Cómo llegar\n{{address}}. Los últimos 300 metros son camino de tierra llano: cualquier coche pasa sin problema, solo ve despacio.\n\n3. Abrir la puerta\nLa caja de llaves está a la derecha de la entrada principal. Marca el código {{door_code}}, saca las llaves y gira la ruedecilla al cerrarla.\n\n4. Al entrar\nEl cuadro de luz está en el recibidor, a mano izquierda. Si la casa está a oscuras, sube el interruptor general.\n\n5. Ponerte cómodo\nLa red wifi es {{wifi_ssid}}. Los mandos del aire están en cada dormitorio y el agua caliente tarda un minuto en llegar. Cualquier cosa, {{host_name}} está a un mensaje.`,
            en: `1. Before you set off\nCheck-in is from {{checkin_time}}. Send us a WhatsApp when you leave for {{town}} and we'll have everything ready.\n\n2. Getting here\n{{address}}. The last 300 metres are a flat dirt track: any car makes it without trouble, just take it slowly.\n\n3. Opening the door\nThe key box is on the right of the main entrance. Enter code {{door_code}}, take the keys and spin the dial when you close it.\n\n4. As you walk in\nThe fuse box is in the hallway, on your left. If the house is dark, flip the main switch up.\n\n5. Settling in\nThe wifi network is {{wifi_ssid}}. Air conditioning remotes are in each bedroom and the hot water takes a minute to come through. Anything you need, {{host_name}} is one message away.`,
            fr: `1. Avant de partir\nL'arrivée se fait à partir de {{checkin_time}}. Envoyez-nous un WhatsApp quand vous partez vers {{town}} et tout sera prêt.\n\n2. Pour venir\n{{address}}. Les 300 derniers mètres sont un chemin de terre plat : toutes les voitures passent sans problème, roulez simplement doucement.\n\n3. Ouvrir la porte\nLa boîte à clés se trouve à droite de l'entrée principale. Composez le code {{door_code}}, prenez les clés et tournez la molette en refermant.\n\n4. En entrant\nLe tableau électrique est dans l'entrée, à gauche. Si la maison est dans le noir, remontez l'interrupteur général.\n\n5. Vous installer\nLe réseau wifi est {{wifi_ssid}}. Les télécommandes de la climatisation sont dans chaque chambre et l'eau chaude met une minute à arriver. Pour tout besoin, {{host_name}} est à un message.`,
            de: `1. Vor der Abfahrt\nDer Check-in ist ab {{checkin_time}} möglich. Schreiben Sie uns per WhatsApp, wenn Sie nach {{town}} losfahren, dann ist alles vorbereitet.\n\n2. Anfahrt\n{{address}}. Die letzten 300 Meter sind ein ebener Feldweg: Jedes Auto kommt problemlos durch, fahren Sie einfach langsam.\n\n3. Tür öffnen\nDer Schlüsselkasten hängt rechts neben dem Haupteingang. Code {{door_code}} eingeben, Schlüssel entnehmen und beim Schließen das Rädchen verdrehen.\n\n4. Beim Hereinkommen\nDer Sicherungskasten ist im Flur auf der linken Seite. Wenn es dunkel ist, legen Sie den Hauptschalter nach oben.\n\n5. Ankommen\nDas WLAN heißt {{wifi_ssid}}. Die Klimafernbedienungen liegen in jedem Schlafzimmer, und das warme Wasser braucht eine Minute. Bei Fragen ist {{host_name}} nur eine Nachricht entfernt.`,
            it: `1. Prima di partire\nIl check-in è dalle {{checkin_time}}. Scrivici su WhatsApp quando parti verso {{town}} e troverai tutto pronto.\n\n2. Come arrivare\n{{address}}. Gli ultimi 300 metri sono una strada sterrata pianeggiante: qualsiasi auto passa senza problemi, vai solo piano.\n\n3. Aprire la porta\nLa cassetta delle chiavi è a destra dell'ingresso principale. Componi il codice {{door_code}}, prendi le chiavi e gira la rotella quando la richiudi.\n\n4. Appena entri\nIl quadro elettrico è nell'ingresso, a sinistra. Se la casa è al buio, alza l'interruttore generale.\n\n5. Sistemarti\nLa rete wifi è {{wifi_ssid}}. I telecomandi del condizionatore sono in ogni camera e l'acqua calda ci mette un minuto ad arrivare. Per qualsiasi cosa, {{host_name}} è a un messaggio di distanza.`,
            pt: `1. Antes de sair\nA entrada é a partir das {{checkin_time}}. Envie-nos uma mensagem de WhatsApp quando sair em direção a {{town}} e estará tudo pronto.\n\n2. Como chegar\n{{address}}. Os últimos 300 metros são um caminho de terra plano: qualquer carro passa sem problemas, basta ir devagar.\n\n3. Abrir a porta\nA caixa das chaves está à direita da entrada principal. Marque o código {{door_code}}, retire as chaves e gire a roda ao fechá-la.\n\n4. Ao entrar\nO quadro elétrico fica na entrada, à esquerda. Se a casa estiver às escuras, levante o interruptor geral.\n\n5. Instalar-se\nA rede wifi é {{wifi_ssid}}. Os comandos do ar condicionado estão em cada quarto e a água quente demora um minuto a chegar. Para o que precisar, {{host_name}} está a uma mensagem.`,
            ca: `1. Abans de sortir\nL'entrada és a partir de les {{checkin_time}}. Escriu-nos per WhatsApp quan surtis cap a {{town}} i t'esperem amb tot a punt.\n\n2. Com arribar-hi\n{{address}}. Els darrers 300 metres són un camí de terra pla: qualsevol cotxe hi passa sense problemes, només cal anar a poc a poc.\n\n3. Obrir la porta\nLa caixa de claus és a la dreta de l'entrada principal. Marca el codi {{door_code}}, treu les claus i gira la rodeta en tancar-la.\n\n4. En entrar\nEl quadre de llum és al rebedor, a mà esquerra. Si la casa és a les fosques, apuja l'interruptor general.\n\n5. Posar-te còmode\nLa xarxa wifi és {{wifi_ssid}}. Els comandaments de l'aire són a cada habitació i l'aigua calenta triga un minut a arribar. Per a qualsevol cosa, {{host_name}} és a un missatge.`,
            ar: `١. قبل أن تنطلق\nيبدأ تسجيل الوصول من الساعة {{checkin_time}}. راسلنا على واتساب عند مغادرتك باتجاه {{town}} وسيكون كل شيء جاهزًا.\n\n٢. كيفية الوصول\n{{address}}. آخر ٣٠٠ متر طريق ترابي مستوٍ: تمر منه أي سيارة دون مشكلة، فقط سر ببطء.\n\n٣. فتح الباب\nصندوق المفاتيح على يمين المدخل الرئيسي. أدخل الرمز {{door_code}}، خذ المفاتيح وأدر القرص عند إغلاقه.\n\n٤. عند الدخول\nلوحة الكهرباء في المدخل على اليسار. إذا كان المنزل مظلمًا، ارفع المفتاح الرئيسي.\n\n٥. الاستقرار\nشبكة الواي فاي هي {{wifi_ssid}}. أجهزة التحكم بالتكييف في كل غرفة نوم، والماء الساخن يحتاج دقيقة ليصل. لأي شيء، {{host_name}} على بُعد رسالة واحدة.`,
            ru: `1. Перед выездом\nЗаезд с {{checkin_time}}. Напишите нам в WhatsApp, когда выедете в сторону {{town}}, и всё будет готово.\n\n2. Как добраться\n{{address}}. Последние 300 метров — ровная грунтовая дорога: проедет любая машина, просто не спешите.\n\n3. Открыть дверь\nКлючница находится справа от главного входа. Наберите код {{door_code}}, достаньте ключи и прокрутите колёсико, когда закроете её.\n\n4. При входе\nЭлектрощиток в прихожей слева. Если в доме темно, поднимите главный рубильник.\n\n5. Обустроиться\nСеть Wi-Fi — {{wifi_ssid}}. Пульты от кондиционера лежат в каждой спальне, горячая вода идёт примерно через минуту. По любому вопросу {{host_name}} на связи.`,
            uk: `1. Перед виїздом\nЗаїзд із {{checkin_time}}. Напишіть нам у WhatsApp, коли виїдете в бік {{town}}, і все буде готове.\n\n2. Як дістатися\n{{address}}. Останні 300 метрів — рівна ґрунтова дорога: проїде будь-яке авто, просто їдьте повільно.\n\n3. Відчинити двері\nКлючниця праворуч від головного входу. Наберіть код {{door_code}}, візьміть ключі та прокрутіть коліщатко, коли зачините її.\n\n4. Коли зайдете\nЕлектрощиток у передпокої ліворуч. Якщо в домі темно, підніміть головний вимикач.\n\n5. Влаштуватися\nМережа Wi-Fi — {{wifi_ssid}}. Пульти від кондиціонера є в кожній спальні, гаряча вода йде приблизно за хвилину. З будь-якого питання {{host_name}} на зв'язку.`,
            zh: `1. 出发前\n入住时间为 {{checkin_time}} 起。出发前往{{town}}时请用 WhatsApp 告诉我们，我们会把一切准备好。\n\n2. 如何抵达\n{{address}}。最后 300 米是平坦的土路：任何车辆都能顺利通过，慢行即可。\n\n3. 开门\n钥匙盒在正门右侧。输入密码 {{door_code}}，取出钥匙，关上后转动转盘。\n\n4. 进门之后\n配电箱在玄关左手边。如果屋内没电，请把总开关向上推。\n\n5. 安顿下来\nWi-Fi 网络名称是 {{wifi_ssid}}。每间卧室都有空调遥控器，热水需要约一分钟才会来。有任何需要，给 {{host_name}} 发条消息即可。`,
            ja: `1. 出発前に\nチェックインは{{checkin_time}}からです。{{town}}へ向けて出発される際にWhatsAppでご連絡いただければ、すべて整えてお待ちしています。\n\n2. アクセス\n{{address}}。最後の300メートルは平らな未舗装路です。どんな車でも問題なく通れますので、ゆっくりお進みください。\n\n3. ドアを開ける\nキーボックスは正面玄関の右側にあります。暗証番号{{door_code}}を入力して鍵を取り出し、閉めたらダイヤルを回してください。\n\n4. 中に入ったら\n分電盤は玄関の左手にあります。家が暗い場合はメインスイッチを上げてください。\n\n5. くつろぐ\nWi-Fiのネットワーク名は{{wifi_ssid}}です。エアコンのリモコンは各寝室にあり、お湯は1分ほどで出ます。何かあれば{{host_name}}にメッセージをどうぞ。`,
            ko: `1. 출발 전\n체크인은 {{checkin_time}}부터입니다. {{town}}(으)로 출발하실 때 WhatsApp으로 알려주시면 모든 준비를 마쳐두겠습니다.\n\n2. 오시는 길\n{{address}}. 마지막 300미터는 평평한 흙길입니다. 어떤 차량이든 문제없이 지날 수 있으니 천천히 오세요.\n\n3. 문 열기\n키박스는 정문 오른쪽에 있습니다. 코드 {{door_code}}을(를) 입력해 열쇠를 꺼내고, 닫은 뒤에는 다이얼을 돌려주세요.\n\n4. 들어오시면\n두꺼비집은 현관 왼쪽에 있습니다. 집이 어두우면 메인 스위치를 올려주세요.\n\n5. 자리 잡기\nWi-Fi 네트워크는 {{wifi_ssid}}입니다. 에어컨 리모컨은 각 침실에 있고, 온수는 1분 정도 후에 나옵니다. 필요하신 게 있으면 {{host_name}}에게 메시지 주세요.`,
        },
    },
    {
        key: 'pool',
        order: 20,
        image: 'pool.jpg',
        content: {
            es: `1. Horario\nLa piscina está abierta de 09:00 a 22:00. Fuera de ese horario te pedimos que uses la zona chill out: estamos en un entorno tranquilo y con vecinos cerca.\n\n2. Niños\nNo hay socorrista. Los menores tienen que estar siempre acompañados por un adulto, también en la zona de la escalera.\n\n3. Antes de bañarte\nUsa la ducha exterior. Las cremas solares son, con diferencia, lo que más ensucia el agua.\n\n4. Toallas\nLas toallas de piscina son las azules del armario del pasillo. Las blancas del baño no salen de la casa, gracias.\n\n5. Barbacoa y cenador\nLa barbacoa está lista para usar y el carbón lo dejamos en el cobertizo. Apágala del todo antes de irte a dormir y deja la parrilla cepillada en caliente.`,
            en: `1. Opening hours\nThe pool is open from 09:00 to 22:00. Outside those hours please use the chill-out area: this is a quiet spot with neighbours nearby.\n\n2. Children\nThere is no lifeguard. Children must always be supervised by an adult, including around the steps.\n\n3. Before you swim\nUse the outdoor shower. Sun cream is by far the main thing that clouds the water.\n\n4. Towels\nPool towels are the blue ones in the hallway cupboard. Please keep the white bathroom towels indoors.\n\n5. Barbecue and gazebo\nThe barbecue is ready to use and there is charcoal in the shed. Put it out completely before bed and brush the grill while it's still hot.`,
            fr: `1. Horaires\nLa piscine est ouverte de 09h00 à 22h00. En dehors de ces heures, merci d'utiliser l'espace chill out : l'endroit est calme et il y a des voisins tout près.\n\n2. Enfants\nIl n'y a pas de maître-nageur. Les enfants doivent toujours être accompagnés d'un adulte, y compris près de l'échelle.\n\n3. Avant de vous baigner\nUtilisez la douche extérieure. La crème solaire est de loin ce qui trouble le plus l'eau.\n\n4. Serviettes\nLes serviettes de piscine sont les bleues dans le placard du couloir. Merci de laisser les blanches de la salle de bain à l'intérieur.\n\n5. Barbecue et pergola\nLe barbecue est prêt à l'emploi et le charbon se trouve dans l'abri. Éteignez-le complètement avant d'aller dormir et brossez la grille encore chaude.`,
            de: `1. Öffnungszeiten\nDer Pool ist von 09:00 bis 22:00 Uhr geöffnet. Außerhalb dieser Zeiten nutzen Sie bitte den Chill-out-Bereich: Die Gegend ist ruhig und die Nachbarn sind nah.\n\n2. Kinder\nEs gibt keinen Bademeister. Kinder müssen immer von einem Erwachsenen beaufsichtigt werden, auch an der Leiter.\n\n3. Vor dem Baden\nBitte die Außendusche benutzen. Sonnencreme trübt das Wasser mit Abstand am stärksten.\n\n4. Handtücher\nDie Pooltücher sind die blauen im Flurschrank. Die weißen Badezimmertücher bleiben bitte im Haus.\n\n5. Grill und Pavillon\nDer Grill ist einsatzbereit, Holzkohle liegt im Schuppen. Löschen Sie ihn vor dem Schlafengehen vollständig und bürsten Sie den Rost, solange er heiß ist.`,
            it: `1. Orario\nLa piscina è aperta dalle 09:00 alle 22:00. Fuori da questo orario ti chiediamo di usare la zona chill out: siamo in un posto tranquillo e con vicini vicini.\n\n2. Bambini\nNon c'è bagnino. I minori devono essere sempre accompagnati da un adulto, anche vicino alla scaletta.\n\n3. Prima del bagno\nUsa la doccia esterna. Le creme solari sono di gran lunga ciò che sporca di più l'acqua.\n\n4. Asciugamani\nGli asciugamani da piscina sono quelli azzurri nell'armadio del corridoio. Quelli bianchi del bagno restano in casa, grazie.\n\n5. Barbecue e gazebo\nIl barbecue è pronto all'uso e la carbonella è nel capanno. Spegnilo completamente prima di andare a dormire e spazzola la griglia ancora calda.`,
            pt: `1. Horário\nA piscina está aberta das 09:00 às 22:00. Fora desse horário, pedimos que use a zona chill out: estamos num sítio tranquilo e com vizinhos por perto.\n\n2. Crianças\nNão há nadador-salvador. Os menores têm de estar sempre acompanhados por um adulto, incluindo junto à escada.\n\n3. Antes de entrar na água\nUse o chuveiro exterior. Os protetores solares são, de longe, o que mais suja a água.\n\n4. Toalhas\nAs toalhas de piscina são as azuis do armário do corredor. As brancas da casa de banho ficam dentro de casa, obrigado.\n\n5. Churrasqueira e alpendre\nA churrasqueira está pronta a usar e o carvão fica no barracão. Apague-a por completo antes de ir dormir e escove a grelha ainda quente.`,
            ca: `1. Horari\nLa piscina és oberta de 09:00 a 22:00. Fora d'aquest horari et demanem que facis servir la zona chill out: som en un entorn tranquil i amb veïns a prop.\n\n2. Infants\nNo hi ha socorrista. Els menors han d'estar sempre acompanyats d'un adult, també a la zona de l'escala.\n\n3. Abans de banyar-te\nFes servir la dutxa exterior. Les cremes solars són, de bon tros, el que més embruta l'aigua.\n\n4. Tovalloles\nLes tovalloles de piscina són les blaves de l'armari del passadís. Les blanques del bany es queden dins de casa, gràcies.\n\n5. Barbacoa i cenador\nLa barbacoa és a punt i el carbó és al cobert. Apaga-la del tot abans d'anar a dormir i raspalla la graella en calent.`,
            ar: `١. المواعيد\nالمسبح مفتوح من الساعة ٠٩:٠٠ حتى ٢٢:٠٠. خارج هذه الأوقات نرجو استخدام منطقة الاسترخاء: المكان هادئ والجيران قريبون.\n\n٢. الأطفال\nلا يوجد منقذ. يجب أن يكون الأطفال دائمًا برفقة شخص بالغ، بما في ذلك عند السلّم.\n\n٣. قبل السباحة\nاستخدم الدش الخارجي. كريمات الشمس هي أكثر ما يعكّر الماء بفارق كبير.\n\n٤. المناشف\nمناشف المسبح هي الزرقاء الموجودة في خزانة الممر. نرجو إبقاء المناشف البيضاء الخاصة بالحمام داخل المنزل.\n\n٥. الشواء والجلسة الخارجية\nالشواية جاهزة للاستخدام والفحم في المخزن. أطفئها تمامًا قبل النوم ونظّف الشبكة وهي ساخنة.`,
            ru: `1. Часы работы\nБассейн открыт с 09:00 до 22:00. В остальное время просим пользоваться зоной отдыха: место тихое, соседи рядом.\n\n2. Дети\nСпасателя нет. Дети должны всегда находиться под присмотром взрослых, в том числе у лестницы.\n\n3. Перед купанием\nВоспользуйтесь наружным душем. Солнцезащитный крем сильнее всего мутит воду.\n\n4. Полотенца\nПолотенца для бассейна — синие, в шкафу в коридоре. Белые из ванной, пожалуйста, оставляйте в доме.\n\n5. Барбекю и беседка\nМангал готов к использованию, уголь лежит в сарае. Полностью потушите его перед сном и почистите решётку, пока она горячая.`,
            uk: `1. Години роботи\nБасейн відкритий із 09:00 до 22:00. В інший час просимо користуватися зоною відпочинку: місце тихе, сусіди поруч.\n\n2. Діти\nРятувальника немає. Діти мають завжди бути під наглядом дорослих, зокрема біля драбини.\n\n3. Перед купанням\nСкористайтеся вуличним душем. Сонцезахисний крем найбільше каламутить воду.\n\n4. Рушники\nРушники для басейну — сині, у шафі в коридорі. Білі з ванної, будь ласка, залишайте в домі.\n\n5. Барбекю та альтанка\nМангал готовий до використання, вугілля — у сараї. Повністю загасіть його перед сном і почистіть решітку, поки вона гаряча.`,
            zh: `1. 开放时间\n泳池开放时间为 09:00 至 22:00。其他时段请使用休闲区：这里环境安静，邻居就在附近。\n\n2. 儿童\n没有救生员。未成年人必须全程有成人陪同，包括在扶梯附近。\n\n3. 下水之前\n请先用户外淋浴冲洗。防晒霜是让池水变浑最主要的原因。\n\n4. 毛巾\n泳池毛巾是走廊柜子里的蓝色那批。浴室的白毛巾请留在室内，谢谢。\n\n5. 烧烤与凉亭\n烧烤炉可直接使用，木炭放在储物棚里。睡前请彻底熄灭，并趁热刷干净烤架。`,
            ja: `1. 利用時間\nプールは9:00から22:00までご利用いただけます。それ以外の時間帯はチルアウトエリアをお使いください。静かな環境で、ご近所も近いためです。\n\n2. お子さま\n監視員はおりません。はしごの周辺も含め、お子さまは常に大人の方が付き添ってください。\n\n3. 泳ぐ前に\n屋外シャワーをお使いください。水が濁る最大の原因は日焼け止めです。\n\n4. タオル\nプール用タオルは廊下の戸棚にある青いものです。浴室の白いタオルは屋内でお使いください。\n\n5. バーベキューとガゼボ\nバーベキューはすぐに使える状態で、炭は物置にあります。就寝前に完全に消し、熱いうちに網をブラシで掃除してください。`,
            ko: `1. 이용 시간\n수영장은 09:00부터 22:00까지 이용하실 수 있습니다. 그 외 시간에는 칠아웃 공간을 이용해 주세요. 조용한 동네이고 이웃이 가까이 있습니다.\n\n2. 어린이\n안전요원이 없습니다. 사다리 주변을 포함해 미성년자는 항상 성인이 동행해야 합니다.\n\n3. 입수 전에\n야외 샤워를 이용해 주세요. 물을 가장 탁하게 만드는 것은 선크림입니다.\n\n4. 수건\n수영장용 수건은 복도 수납장의 파란색입니다. 욕실의 흰 수건은 실내에서만 사용해 주세요.\n\n5. 바비큐와 정자\n바비큐 그릴은 바로 사용 가능하고 숯은 창고에 있습니다. 주무시기 전에 완전히 끄시고, 뜨거울 때 석쇠를 솔로 닦아주세요.`,
        },
    },
    {
        key: 'checkout',
        order: 30,
        image: 'checkout.jpg',
        content: {
            es: `1. La hora\nLa salida es antes de las {{checkout_time}}. Si necesitas más tiempo, pídenos la salida tardía en la Tienda: si el piso está libre ese día, es tuya.\n\n2. Cocina\nDeja el lavavajillas puesto y la nevera vacía. No hace falta que friegues nada a mano.\n\n3. Basura\nBaja las bolsas a los contenedores del camino, a 200 metros a la derecha del portón.\n\n4. La casa\nCierra ventanas y persianas, apaga el aire de todas las habitaciones y baja el interruptor general si eres el último en salir.\n\n5. Llaves\nDevuelve las llaves a la caja, gira la ruedecilla y avísanos por WhatsApp. Ya está: gracias por cuidar la casa.`,
            en: `1. The time\nCheck-out is before {{checkout_time}}. If you need longer, ask for late check-out in the Store: if the house is free that day, it's yours.\n\n2. Kitchen\nLeave the dishwasher running and the fridge empty. There's no need to wash anything by hand.\n\n3. Rubbish\nTake the bags down to the bins on the track, 200 metres to the right of the gate.\n\n4. The house\nClose the windows and blinds, switch off the air conditioning in every room, and flip the main switch down if you're the last to leave.\n\n5. Keys\nPut the keys back in the box, spin the dial and drop us a WhatsApp. That's it — thank you for looking after the house.`,
            fr: `1. L'heure\nLe départ se fait avant {{checkout_time}}. S'il vous faut plus de temps, demandez le départ tardif dans la Boutique : si la maison est libre ce jour-là, il est pour vous.\n\n2. Cuisine\nLaissez le lave-vaisselle en marche et le réfrigérateur vide. Inutile de laver quoi que ce soit à la main.\n\n3. Poubelles\nDescendez les sacs jusqu'aux conteneurs du chemin, à 200 mètres à droite du portail.\n\n4. La maison\nFermez les fenêtres et les volets, éteignez la climatisation dans toutes les pièces et baissez l'interrupteur général si vous êtes le dernier à partir.\n\n5. Clés\nRemettez les clés dans la boîte, tournez la molette et prévenez-nous par WhatsApp. C'est tout — merci d'avoir pris soin de la maison.`,
            de: `1. Die Uhrzeit\nDer Check-out ist vor {{checkout_time}}. Wenn Sie mehr Zeit brauchen, fragen Sie im Shop nach dem späten Check-out: Ist das Haus an dem Tag frei, gehört er Ihnen.\n\n2. Küche\nLassen Sie die Spülmaschine laufen und den Kühlschrank leer. Von Hand muss nichts gespült werden.\n\n3. Müll\nBringen Sie die Säcke zu den Containern am Weg, 200 Meter rechts vom Tor.\n\n4. Das Haus\nSchließen Sie Fenster und Rollläden, schalten Sie die Klimaanlage in allen Räumen aus und legen Sie den Hauptschalter um, wenn Sie als Letzte gehen.\n\n5. Schlüssel\nLegen Sie die Schlüssel zurück in den Kasten, verdrehen Sie das Rädchen und schreiben Sie uns per WhatsApp. Das war's — danke, dass Sie auf das Haus aufgepasst haben.`,
            it: `1. L'orario\nIl check-out è prima delle {{checkout_time}}. Se ti serve più tempo, chiedi l'uscita posticipata nel Negozio: se la casa è libera quel giorno, è tua.\n\n2. Cucina\nLascia la lavastoviglie in funzione e il frigo vuoto. Non serve lavare nulla a mano.\n\n3. Rifiuti\nPorta i sacchi ai cassonetti sulla strada, 200 metri a destra del cancello.\n\n4. La casa\nChiudi finestre e tapparelle, spegni il condizionatore in tutte le stanze e abbassa l'interruttore generale se sei l'ultimo a uscire.\n\n5. Chiavi\nRimetti le chiavi nella cassetta, gira la rotella e avvisaci su WhatsApp. Tutto qui — grazie per aver avuto cura della casa.`,
            pt: `1. A hora\nA saída é antes das {{checkout_time}}. Se precisar de mais tempo, peça a saída tardia na Loja: se a casa estiver livre nesse dia, é sua.\n\n2. Cozinha\nDeixe a máquina de lavar loiça a trabalhar e o frigorífico vazio. Não precisa de lavar nada à mão.\n\n3. Lixo\nLeve os sacos até aos contentores do caminho, 200 metros à direita do portão.\n\n4. A casa\nFeche janelas e estores, desligue o ar condicionado em todos os quartos e baixe o interruptor geral se for o último a sair.\n\n5. Chaves\nDevolva as chaves à caixa, gire a roda e avise-nos por WhatsApp. É tudo — obrigado por ter cuidado da casa.`,
            ca: `1. L'hora\nLa sortida és abans de les {{checkout_time}}. Si necessites més temps, demana'ns la sortida tardana a la Botiga: si la casa és lliure aquell dia, és teva.\n\n2. Cuina\nDeixa el rentaplats posat i la nevera buida. No cal que rentis res a mà.\n\n3. Escombraries\nBaixa les bosses als contenidors del camí, a 200 metres a la dreta del portal.\n\n4. La casa\nTanca finestres i persianes, apaga l'aire de totes les habitacions i abaixa l'interruptor general si ets l'últim a sortir.\n\n5. Claus\nTorna les claus a la caixa, gira la rodeta i avisa'ns per WhatsApp. Ja està — gràcies per tenir cura de la casa.`,
            ar: `١. الموعد\nيجب المغادرة قبل الساعة {{checkout_time}}. إذا احتجت وقتًا إضافيًا، اطلب المغادرة المتأخرة من المتجر: إن كان المنزل شاغرًا ذلك اليوم فهي لك.\n\n٢. المطبخ\nاترك غسالة الصحون تعمل والثلاجة فارغة. لا داعي لغسل أي شيء يدويًا.\n\n٣. النفايات\nانزل بالأكياس إلى الحاويات على الطريق، على بُعد ٢٠٠ متر يمين البوابة.\n\n٤. المنزل\nأغلق النوافذ والستائر، وأطفئ التكييف في جميع الغرف، واخفض المفتاح الرئيسي إن كنت آخر من يغادر.\n\n٥. المفاتيح\nأعد المفاتيح إلى الصندوق، وأدر القرص، وأخبرنا على واتساب. هذا كل شيء — شكرًا لاعتنائك بالمنزل.`,
            ru: `1. Время\nВыезд до {{checkout_time}}. Если нужно больше времени, закажите поздний выезд в Магазине: если в этот день дом свободен, он ваш.\n\n2. Кухня\nОставьте посудомоечную машину включённой, а холодильник пустым. Мыть что-либо вручную не нужно.\n\n3. Мусор\nОтнесите пакеты к контейнерам на дороге, в 200 метрах справа от ворот.\n\n4. Дом\nЗакройте окна и жалюзи, выключите кондиционеры во всех комнатах и опустите главный рубильник, если уходите последними.\n\n5. Ключи\nВерните ключи в ключницу, прокрутите колёсико и напишите нам в WhatsApp. Вот и всё — спасибо, что берегли дом.`,
            uk: `1. Час\nВиїзд до {{checkout_time}}. Якщо потрібно більше часу, замовте пізній виїзд у Крамниці: якщо того дня будинок вільний, він ваш.\n\n2. Кухня\nЗалиште посудомийну машину увімкненою, а холодильник порожнім. Мити щось вручну не потрібно.\n\n3. Сміття\nВіднесіть пакети до контейнерів на дорозі, за 200 метрів праворуч від воріт.\n\n4. Будинок\nЗачиніть вікна та жалюзі, вимкніть кондиціонери в усіх кімнатах і опустіть головний вимикач, якщо йдете останніми.\n\n5. Ключі\nПоверніть ключі до ключниці, прокрутіть коліщатко й напишіть нам у WhatsApp. Ось і все — дякуємо, що дбали про дім.`,
            zh: `1. 时间\n退房时间为 {{checkout_time}} 之前。如需更多时间，可在商店里申请延迟退房：若当天房子空着，就归你使用。\n\n2. 厨房\n请让洗碗机运行，冰箱清空。不需要手洗任何餐具。\n\n3. 垃圾\n请把垃圾袋拿到路边的垃圾桶，位于大门右侧 200 米处。\n\n4. 房子\n关好门窗和百叶帘，关闭所有房间的空调；如果你是最后离开的人，请把总开关拉下。\n\n5. 钥匙\n把钥匙放回钥匙盒，转动转盘，然后用 WhatsApp 通知我们。这样就好了——谢谢你爱护这个家。`,
            ja: `1. 時間\nチェックアウトは{{checkout_time}}までです。もっと時間が必要な場合は、ストアからレイトチェックアウトをご依頼ください。その日に空きがあればご利用いただけます。\n\n2. キッチン\n食洗機は運転したまま、冷蔵庫は空にしてお出かけください。手洗いは不要です。\n\n3. ごみ\nごみ袋は、門を出て右へ200メートルの道沿いにあるコンテナへお願いします。\n\n4. 家の中\n窓とブラインドを閉め、全室のエアコンを切り、最後に出られる場合はメインスイッチを下げてください。\n\n5. 鍵\n鍵はキーボックスに戻してダイヤルを回し、WhatsAppでお知らせください。以上です。大切に使ってくださりありがとうございました。`,
            ko: `1. 시간\n체크아웃은 {{checkout_time}} 이전입니다. 시간이 더 필요하시면 스토어에서 레이트 체크아웃을 신청해 주세요. 그날 집이 비어 있으면 이용하실 수 있습니다.\n\n2. 주방\n식기세척기는 작동시킨 채로, 냉장고는 비워두고 나가시면 됩니다. 손으로 설거지하실 필요는 없습니다.\n\n3. 쓰레기\n쓰레기봉투는 정문에서 오른쪽으로 200미터 떨어진 길가 수거함에 놓아주세요.\n\n4. 집\n창문과 블라인드를 닫고 모든 방의 에어컨을 끄신 뒤, 마지막에 나가시는 분은 메인 스위치를 내려주세요.\n\n5. 열쇠\n열쇠는 키박스에 넣고 다이얼을 돌린 뒤 WhatsApp으로 알려주세요. 이것으로 끝입니다. 집을 아껴주셔서 감사합니다.`,
        },
    },
];
