// scripts/demo-seed/lib/content/info.mjs
// =============================================================================
// Bloques de información del apartamento demo (guide_apartment_info).
//
// `key` es a la vez info_key y category_key: todas las claves de aquí existen
// en el catálogo global guide_info_categories (migración 0083), así que el
// TÍTULO y el icono los pone el catálogo, ya traducido a los 13 idiomas para
// toda la plataforma. Por eso aquí solo se escribe `content`: es lo único que
// de verdad cambia de un piso a otro.
//
// use_custom_title se queda en FALSE: si se pusiera a TRUE habría que traducir
// también el título en 13 idiomas por cada demo, a cambio de nada.
//
// Texto plano, sin markdown (ver la nota de guides.mjs).
// =============================================================================

export const INFO_BLOCKS = [
    {
        key: 'wifi',
        order: 40,
        image: null,
        content: {
            es: `Red: {{wifi_ssid}}\nContraseña: {{wifi_password}}\n\nCubre toda la casa y la zona de la piscina. Si un dispositivo pierde la señal, el router está en el mueble del salón: desenchúfalo diez segundos y vuelve a enchufarlo.`,
            en: `Network: {{wifi_ssid}}\nPassword: {{wifi_password}}\n\nIt covers the whole house and the pool area. If a device drops the signal, the router is in the living room cabinet: unplug it for ten seconds and plug it back in.`,
            fr: `Réseau : {{wifi_ssid}}\nMot de passe : {{wifi_password}}\n\nIl couvre toute la maison et l'espace piscine. Si un appareil perd le signal, le routeur se trouve dans le meuble du salon : débranchez-le dix secondes et rebranchez-le.`,
            de: `Netzwerk: {{wifi_ssid}}\nPasswort: {{wifi_password}}\n\nEs deckt das ganze Haus und den Poolbereich ab. Verliert ein Gerät das Signal, steht der Router im Wohnzimmerschrank: zehn Sekunden ausstecken und wieder einstecken.`,
            it: `Rete: {{wifi_ssid}}\nPassword: {{wifi_password}}\n\nCopre tutta la casa e la zona piscina. Se un dispositivo perde il segnale, il router è nel mobile del salotto: staccalo per dieci secondi e riattaccalo.`,
            pt: `Rede: {{wifi_ssid}}\nPalavra-passe: {{wifi_password}}\n\nCobre toda a casa e a zona da piscina. Se algum dispositivo perder o sinal, o router está no móvel da sala: desligue-o dez segundos e volte a ligá-lo.`,
            ca: `Xarxa: {{wifi_ssid}}\nContrasenya: {{wifi_password}}\n\nCobreix tota la casa i la zona de la piscina. Si un dispositiu perd el senyal, el router és al moble del menjador: desendolla'l deu segons i torna'l a endollar.`,
            ar: `الشبكة: {{wifi_ssid}}\nكلمة المرور: {{wifi_password}}\n\nتغطي المنزل بالكامل ومنطقة المسبح. إذا فقد أحد الأجهزة الإشارة، فالراوتر موجود في خزانة الصالة: افصله عشر ثوانٍ ثم أعد توصيله.`,
            ru: `Сеть: {{wifi_ssid}}\nПароль: {{wifi_password}}\n\nПокрывает весь дом и зону бассейна. Если устройство теряет сигнал, роутер стоит в тумбе в гостиной: отключите его на десять секунд и включите снова.`,
            uk: `Мережа: {{wifi_ssid}}\nПароль: {{wifi_password}}\n\nПокриває весь будинок і зону басейну. Якщо пристрій втрачає сигнал, роутер стоїть у тумбі у вітальні: вимкніть його на десять секунд і увімкніть знову.`,
            zh: `网络名称：{{wifi_ssid}}\n密码：{{wifi_password}}\n\n信号覆盖整栋房子和泳池区域。如果设备断线，路由器在客厅的柜子里：拔掉电源十秒后重新插上即可。`,
            ja: `ネットワーク名: {{wifi_ssid}}\nパスワード: {{wifi_password}}\n\n家全体とプールエリアをカバーしています。接続が切れた場合、ルーターはリビングのキャビネットの中にあります。10秒ほど電源を抜いて、再度差し込んでください。`,
            ko: `네트워크: {{wifi_ssid}}\n비밀번호: {{wifi_password}}\n\n집 전체와 수영장 구역까지 연결됩니다. 기기가 연결이 끊기면 거실 수납장 안에 공유기가 있습니다. 10초간 전원을 뽑았다가 다시 꽂아주세요.`,
        },
    },
    {
        key: 'parking',
        order: 50,
        image: null,
        content: {
            es: `Aparcamiento privado y gratuito dentro de la finca, con sitio de sobra para tres coches. Entra por el portón y deja libre el paso hasta la puerta principal. No hace falta ticket ni registrar la matrícula.`,
            en: `Free private parking inside the grounds, with room for three cars. Come in through the gate and keep the path to the front door clear. No ticket or number plate registration needed.`,
            fr: `Parking privé et gratuit dans la propriété, avec de la place pour trois voitures. Entrez par le portail et laissez le passage vers la porte d'entrée dégagé. Ni ticket ni enregistrement de plaque.`,
            de: `Kostenlose Privatparkplätze auf dem Grundstück, Platz für drei Autos. Fahren Sie durch das Tor und halten Sie den Weg zur Haustür frei. Weder Ticket noch Kennzeichen-Registrierung nötig.`,
            it: `Parcheggio privato e gratuito dentro la proprietà, con posto per tre auto. Entra dal cancello e lascia libero il passaggio fino alla porta principale. Non serve ticket né registrare la targa.`,
            pt: `Estacionamento privado e gratuito dentro da propriedade, com lugar para três carros. Entre pelo portão e deixe livre a passagem até à porta principal. Não é preciso bilhete nem registar a matrícula.`,
            ca: `Aparcament privat i gratuït dins de la finca, amb lloc de sobres per a tres cotxes. Entra pel portal i deixa lliure el pas fins a la porta principal. No cal tiquet ni registrar la matrícula.`,
            ar: `موقف خاص ومجاني داخل المزرعة يتسع لثلاث سيارات. ادخل من البوابة واترك الممر إلى الباب الرئيسي خاليًا. لا حاجة لتذكرة ولا لتسجيل رقم اللوحة.`,
            ru: `Бесплатная частная парковка на территории, места хватает на три машины. Въезжайте через ворота и не перекрывайте проход к главной двери. Талон и регистрация номера не нужны.`,
            uk: `Безкоштовна приватна парковка на території, місця вистачає на три автомобілі. Заїжджайте через ворота й не перекривайте прохід до головних дверей. Талон і реєстрація номера не потрібні.`,
            zh: `庄园内设有免费私人停车位，可停三辆车。请从大门进入，并保持通往正门的通道畅通。无需取票，也不用登记车牌。`,
            ja: `敷地内に無料の専用駐車場があり、3台まで駐車できます。門から入り、玄関までの通路は空けておいてください。駐車券もナンバー登録も不要です。`,
            ko: `부지 안에 무료 전용 주차 공간이 있으며 차량 3대까지 주차하실 수 있습니다. 대문으로 들어오시고 현관까지 가는 길은 비워두세요. 주차권이나 차량 번호 등록은 필요 없습니다.`,
        },
    },
    {
        key: 'air_conditioning',
        order: 60,
        image: null,
        content: {
            es: `Hay aire acondicionado frío y calor en los cuatro dormitorios y en el salón. Cada mando controla solo su habitación. Te pedimos dos cosas: apágalo al salir de casa y no lo bajes de 23 ºC. La casa es grande y así enfría mucho mejor.`,
            en: `There is heating and cooling in all four bedrooms and in the living room. Each remote controls only its own room. Two small favours: switch it off when you leave the house, and don't set it below 23 °C. The house is large and it cools far better that way.`,
            fr: `Climatisation réversible dans les quatre chambres et au salon. Chaque télécommande ne pilote que sa pièce. Deux petites choses : éteignez-la en quittant la maison et ne descendez pas en dessous de 23 °C. La maison est grande et elle refroidit bien mieux ainsi.`,
            de: `In allen vier Schlafzimmern und im Wohnzimmer gibt es Klimaanlagen zum Kühlen und Heizen. Jede Fernbedienung steuert nur ihren Raum. Zwei kleine Bitten: beim Verlassen des Hauses ausschalten und nicht unter 23 °C stellen. Das Haus ist groß und kühlt so deutlich besser.`,
            it: `C'è aria condizionata caldo/freddo nelle quattro camere e in salotto. Ogni telecomando controlla solo la sua stanza. Ti chiediamo due cose: spegnerla quando esci di casa e non scendere sotto i 23 °C. La casa è grande e così raffredda molto meglio.`,
            pt: `Há ar condicionado com frio e calor nos quatro quartos e na sala. Cada comando controla apenas o seu quarto. Pedimos-lhe duas coisas: desligue-o ao sair de casa e não o coloque abaixo dos 23 °C. A casa é grande e assim arrefece muito melhor.`,
            ca: `Hi ha aire condicionat fred i calor a les quatre habitacions i al menjador. Cada comandament controla només la seva habitació. Et demanem dues coses: apaga'l en sortir de casa i no el baixis de 23 °C. La casa és gran i així refreda molt millor.`,
            ar: `يوجد تكييف بارد وساخن في غرف النوم الأربع وفي الصالة. كل جهاز تحكم يشغّل غرفته فقط. نرجو منك أمرين: أطفئه عند مغادرة المنزل، ولا تخفضه دون ٢٣ درجة مئوية. المنزل كبير وبهذه الطريقة يبرد بشكل أفضل بكثير.`,
            ru: `Кондиционеры с обогревом есть во всех четырёх спальнях и в гостиной. Каждый пульт управляет только своей комнатой. Две просьбы: выключайте его, уходя из дома, и не ставьте ниже 23 °C. Дом большой, и так он охлаждается гораздо лучше.`,
            uk: `Кондиціонери з обігрівом є в усіх чотирьох спальнях і у вітальні. Кожен пульт керує лише своєю кімнатою. Два прохання: вимикайте його, коли виходите з дому, і не ставте нижче 23 °C. Будинок великий, і так він охолоджується значно краще.`,
            zh: `四间卧室和客厅都配有冷暖空调。每个遥控器只控制所在房间。两个小请求：外出时请关闭空调，温度不要低于 23 ℃。房子面积大，这样制冷效果反而更好。`,
            ja: `4つの寝室とリビングに冷暖房エアコンがあります。リモコンはそれぞれの部屋専用です。2点だけお願いがあります。外出時には必ずお切りいただくことと、設定温度を23℃より下げないこと。家が広いため、そのほうがよく冷えます。`,
            ko: `침실 네 곳과 거실에 냉난방 에어컨이 있습니다. 리모컨은 각 방 전용입니다. 두 가지만 부탁드립니다. 외출하실 때는 꺼주시고, 23 ℃ 아래로는 설정하지 말아 주세요. 집이 넓어서 그편이 훨씬 잘 시원해집니다.`,
        },
    },
    {
        key: 'fireplace',
        order: 70,
        image: 'fireplace.jpg',
        content: {
            es: `La chimenea del salón funciona con leña y dejamos el cesto lleno al lado. Abre el tiro (la palanca metálica de arriba) antes de encenderla y ciérralo cuando se haya apagado del todo. Nunca la dejes encendida al irte a dormir ni al salir de casa.`,
            en: `The living room fireplace burns wood, and we leave the basket beside it full. Open the flue (the metal lever at the top) before lighting it and close it once the fire is completely out. Never leave it burning when you go to bed or leave the house.`,
            fr: `La cheminée du salon fonctionne au bois et nous laissons le panier plein à côté. Ouvrez le clapet (le levier métallique en haut) avant de l'allumer et refermez-le une fois le feu totalement éteint. Ne la laissez jamais allumée en allant vous coucher ni en quittant la maison.`,
            de: `Der Kamin im Wohnzimmer wird mit Holz befeuert, der Korb daneben ist gefüllt. Öffnen Sie den Zug (der Metallhebel oben), bevor Sie ihn anzünden, und schließen Sie ihn, wenn das Feuer ganz aus ist. Lassen Sie ihn nie brennen, wenn Sie schlafen gehen oder das Haus verlassen.`,
            it: `Il camino del salotto va a legna e lasciamo il cesto pieno accanto. Apri il tiraggio (la leva metallica in alto) prima di accenderlo e chiudilo quando il fuoco si è spento del tutto. Non lasciarlo mai acceso quando vai a dormire o esci di casa.`,
            pt: `A lareira da sala funciona a lenha e deixamos o cesto cheio ao lado. Abra a chaminé (a alavanca metálica em cima) antes de a acender e feche-a quando o fogo estiver completamente apagado. Nunca a deixe acesa ao ir dormir nem ao sair de casa.`,
            ca: `La xemeneia del menjador funciona amb llenya i deixem el cistell ple al costat. Obre el tir (la palanca metàl·lica de dalt) abans d'encendre-la i tanca'l quan s'hagi apagat del tot. No la deixis mai encesa en anar a dormir ni en sortir de casa.`,
            ar: `مدفأة الصالة تعمل بالحطب ونترك السلة ممتلئة بجانبها. افتح المدخنة (الذراع المعدنية في الأعلى) قبل إشعالها وأغلقها بعد أن تنطفئ تمامًا. لا تتركها مشتعلة أبدًا عند الذهاب للنوم أو مغادرة المنزل.`,
            ru: `Камин в гостиной топится дровами, корзину рядом мы оставляем полной. Откройте заслонку (металлический рычаг сверху) перед розжигом и закройте её, когда огонь полностью погаснет. Никогда не оставляйте камин горящим, уходя спать или из дома.`,
            uk: `Камін у вітальні топиться дровами, кошик поруч ми залишаємо повним. Відкрийте заслінку (металевий важіль зверху) перед розпалюванням і закрийте її, коли вогонь повністю згасне. Ніколи не залишайте камін, що горить, ідучи спати чи з дому.`,
            zh: `客厅的壁炉烧木柴，旁边的柴筐我们已经装满。点火前请打开烟道（上方的金属拉杆），完全熄灭后再关上。就寝或外出时切勿让壁炉继续燃烧。`,
            ja: `リビングの暖炉は薪式で、隣のかごには薪をご用意しています。火をつける前に上部の金属レバー（ダンパー）を開け、完全に消えてから閉じてください。就寝時や外出時に火をつけたままにしないでください。`,
            ko: `거실 벽난로는 장작을 사용하며, 옆 바구니에 장작을 채워두었습니다. 불을 붙이기 전에 위쪽 금속 레버(연통 댐퍼)를 열고, 불이 완전히 꺼진 뒤에 닫아주세요. 주무시러 가거나 외출하실 때 불을 켜둔 채로 두지 마세요.`,
        },
    },
    {
        key: 'washing_machine',
        order: 80,
        image: null,
        content: {
            es: `El cuarto de lavandería está junto a la cocina, con lavadora y secadora. El detergente está en el estante de arriba. Para el día a día, programa corto a 40 ºC (una hora). La secadora necesita que vacíes el filtro de pelusa antes de cada uso, o tarda el doble.`,
            en: `The laundry room is next to the kitchen, with a washing machine and a dryer. Detergent is on the top shelf. For everyday loads, use the short 40 °C cycle (one hour). Empty the dryer's lint filter before every use or it takes twice as long.`,
            fr: `La buanderie se trouve à côté de la cuisine, avec lave-linge et sèche-linge. La lessive est sur l'étagère du haut. Au quotidien, programme court à 40 °C (une heure). Videz le filtre à peluches du sèche-linge avant chaque utilisation, sinon il met deux fois plus de temps.`,
            de: `Der Waschraum liegt neben der Küche, mit Waschmaschine und Trockner. Das Waschmittel steht im obersten Regal. Für den Alltag das Kurzprogramm bei 40 °C (eine Stunde). Leeren Sie das Flusensieb des Trockners vor jedem Gang, sonst dauert er doppelt so lange.`,
            it: `La lavanderia è accanto alla cucina, con lavatrice e asciugatrice. Il detersivo è sulla mensola in alto. Per tutti i giorni, programma corto a 40 °C (un'ora). L'asciugatrice ha bisogno che svuoti il filtro della lanugine prima di ogni uso, altrimenti ci mette il doppio.`,
            pt: `A lavandaria fica ao lado da cozinha, com máquina de lavar e de secar. O detergente está na prateleira de cima. Para o dia a dia, programa curto a 40 °C (uma hora). A máquina de secar precisa que esvazie o filtro de cotão antes de cada utilização, senão demora o dobro.`,
            ca: `El safareig és al costat de la cuina, amb rentadora i assecadora. El detergent és al prestatge de dalt. Per al dia a dia, programa curt a 40 °C (una hora). L'assecadora necessita que buidis el filtre de borrissol abans de cada ús, o triga el doble.`,
            ar: `غرفة الغسيل بجانب المطبخ وفيها غسالة ومجفف. المنظف على الرف العلوي. للاستخدام اليومي، اختر البرنامج القصير على ٤٠ درجة مئوية (ساعة واحدة). يجب تفريغ فلتر الوبر في المجفف قبل كل استخدام، وإلا استغرق ضعف الوقت.`,
            ru: `Прачечная находится рядом с кухней, там стиральная и сушильная машины. Порошок — на верхней полке. Для повседневной стирки используйте короткую программу на 40 °C (один час). Перед каждым запуском сушки очищайте фильтр от ворса, иначе она сушит вдвое дольше.`,
            uk: `Пральня розташована поруч із кухнею, там пральна та сушильна машини. Порошок — на верхній полиці. Для щоденного прання використовуйте коротку програму на 40 °C (одна година). Перед кожним запуском сушарки очищайте фільтр від ворсу, інакше вона сушить удвічі довше.`,
            zh: `洗衣房在厨房旁边，配有洗衣机和烘干机。洗衣液放在最上层的架子上。日常衣物请使用 40 ℃ 快洗程序（约一小时）。每次使用烘干机前请清空绒毛滤网，否则时间会延长一倍。`,
            ja: `ランドリールームはキッチンの隣にあり、洗濯機と乾燥機を備えています。洗剤は上の棚です。普段のお洗濯には40℃の短時間コース（約1時間）をどうぞ。乾燥機は毎回、使用前に糸くずフィルターを空にしてください。そうしないと乾燥時間が倍かかります。`,
            ko: `세탁실은 주방 옆에 있으며 세탁기와 건조기가 있습니다. 세제는 맨 위 선반에 있습니다. 일상 세탁은 40 ℃ 단축 코스(약 1시간)를 사용하세요. 건조기는 사용 전마다 보풀 필터를 비워주셔야 합니다. 그러지 않으면 시간이 두 배로 걸립니다.`,
        },
    },
    {
        key: 'coffee_machine',
        order: 90,
        image: null,
        content: {
            es: `Cafetera de grano: llena el depósito de agua, echa café en el compartimento de arriba y pulsa la taza que quieras. El primer paquete de café va de nuestra parte. Cuando parpadee la luz naranja, vacía el cajón de posos y ya vuelve a funcionar.`,
            en: `Bean-to-cup coffee machine: fill the water tank, add beans to the compartment on top and press the cup you fancy. The first bag of coffee is on us. When the orange light blinks, empty the grounds drawer and it's ready again.`,
            fr: `Machine à café à grains : remplissez le réservoir d'eau, versez les grains dans le compartiment du haut et appuyez sur la tasse souhaitée. Le premier paquet de café est offert. Quand le voyant orange clignote, videz le bac à marc et elle repart.`,
            de: `Kaffeevollautomat: Wassertank füllen, Bohnen in das Fach oben geben und die gewünschte Tassengröße drücken. Die erste Packung Kaffee geht auf uns. Blinkt das orange Licht, leeren Sie den Satzbehälter, dann läuft sie wieder.`,
            it: `Macchina del caffè in grani: riempi il serbatoio dell'acqua, metti i chicchi nello scomparto in alto e premi la tazza che preferisci. Il primo pacchetto di caffè lo offriamo noi. Quando lampeggia la spia arancione, svuota il cassetto dei fondi e riparte.`,
            pt: `Máquina de café em grão: encha o depósito de água, deite grãos no compartimento de cima e prima a chávena que quiser. O primeiro pacote de café é por nossa conta. Quando a luz laranja piscar, esvazie a gaveta das borras e volta a funcionar.`,
            ca: `Cafetera de gra: omple el dipòsit d'aigua, posa cafè al compartiment de dalt i prem la tassa que vulguis. El primer paquet de cafè el posem nosaltres. Quan parpellegi el llum taronja, buida el calaix del marro i ja torna a funcionar.`,
            ar: `آلة قهوة بحبوب كاملة: املأ خزان الماء، وضع الحبوب في الحجرة العلوية، ثم اضغط على حجم الفنجان الذي تريده. أول كيس قهوة على حسابنا. عندما يومض الضوء البرتقالي، أفرغ درج التفل وستعمل من جديد.`,
            ru: `Кофемашина на зерне: наполните резервуар водой, засыпьте зёрна в отсек сверху и нажмите нужный размер чашки. Первая пачка кофе — за наш счёт. Когда замигает оранжевый индикатор, опорожните контейнер для жмыха, и она снова готова.`,
            uk: `Кавомашина на зернах: наповніть резервуар водою, засипте зерна у відсік зверху й натисніть потрібний розмір чашки. Перша пачка кави — за наш рахунок. Коли заблимає помаранчевий індикатор, спорожніть контейнер для жмиху, і вона знову готова.`,
            zh: `全自动咖啡机：加满水箱，把咖啡豆倒入上方豆仓，按下想要的杯量即可。第一包咖啡豆由我们招待。橙色指示灯闪烁时，请清空渣盒，之后即可继续使用。`,
            ja: `全自動コーヒーメーカー：水タンクを満たし、上部の容器に豆を入れて、お好みのカップサイズを押してください。最初の一袋は当方からのサービスです。オレンジのランプが点滅したら、かす受けを空にすれば再び使えます。`,
            ko: `원두 자동 커피머신입니다. 물통을 채우고 위쪽 칸에 원두를 넣은 뒤 원하는 잔 크기를 누르세요. 첫 원두 한 봉지는 저희가 준비해 두었습니다. 주황색 불이 깜빡이면 찌꺼기 서랍을 비워주시면 다시 작동합니다.`,
        },
    },
    {
        key: 'bbq',
        order: 100,
        image: 'bbq.jpg',
        content: {
            es: `La barbacoa está en el cenador exterior, junto a la mesa grande. Dejamos carbón y pastillas de encendido en el cobertizo. La parrilla de arriba es para la carne y la de abajo para verduras. Cepíllala en caliente al terminar y todo el mundo te lo agradecerá.`,
            en: `The barbecue is in the outdoor gazebo, next to the big table. There's charcoal and firelighters in the shed. Use the upper grill for meat and the lower one for vegetables. Brush it while it's still hot and whoever comes next will thank you.`,
            fr: `Le barbecue se trouve dans la pergola extérieure, à côté de la grande table. Charbon et allume-feu sont dans l'abri. La grille du haut est pour la viande, celle du bas pour les légumes. Brossez-la encore chaude, tout le monde vous en remerciera.`,
            de: `Der Grill steht im Gartenpavillon neben dem großen Tisch. Holzkohle und Anzünder finden Sie im Schuppen. Der obere Rost ist für Fleisch, der untere für Gemüse. Bürsten Sie ihn, solange er heiß ist — alle danken es Ihnen.`,
            it: `Il barbecue è nel gazebo esterno, accanto al tavolo grande. Carbonella e accendifuoco sono nel capanno. La griglia in alto è per la carne, quella in basso per le verdure. Spazzolala da calda e chi viene dopo ti ringrazierà.`,
            pt: `A churrasqueira está no alpendre exterior, junto à mesa grande. Há carvão e acendalhas no barracão. A grelha de cima é para a carne e a de baixo para os legumes. Escove-a ainda quente e quem vier a seguir vai agradecer.`,
            ca: `La barbacoa és al cenador exterior, al costat de la taula gran. Deixem carbó i pastilles d'encesa al cobert. La graella de dalt és per a la carn i la de baix per a la verdura. Raspalla-la en calent en acabar i tothom t'ho agrairà.`,
            ar: `الشواية موجودة في الجلسة الخارجية بجانب الطاولة الكبيرة. الفحم وأقراص الإشعال في المخزن. الشبكة العلوية للحوم والسفلية للخضار. نظّفها بالفرشاة وهي ساخنة عند الانتهاء وسيشكرك الجميع.`,
            ru: `Мангал стоит в беседке рядом с большим столом. Уголь и розжиг лежат в сарае. Верхняя решётка — для мяса, нижняя — для овощей. Почистите её щёткой, пока она горячая, и следующие гости скажут вам спасибо.`,
            uk: `Мангал стоїть в альтанці поруч із великим столом. Вугілля та розпалювачі лежать у сараї. Верхня решітка — для м'яса, нижня — для овочів. Почистіть її щіткою, поки вона гаряча, і наступні гості скажуть вам дякую.`,
            zh: `烧烤炉在户外凉亭里，靠近大餐桌。木炭和引火块放在储物棚中。上层烤架用来烤肉，下层烤蔬菜。用完后趁热刷干净，下一位客人会感谢你。`,
            ja: `バーベキューコンロは屋外のガゼボ、大きなテーブルの横にあります。炭と着火剤は物置にあります。上の網は肉用、下の網は野菜用です。使い終わったら熱いうちにブラシをかけていただけると、次の方が喜びます。`,
            ko: `바비큐 그릴은 야외 정자, 큰 테이블 옆에 있습니다. 숯과 착화제는 창고에 있습니다. 위쪽 석쇠는 고기용, 아래쪽은 채소용입니다. 다 쓰신 뒤 뜨거울 때 솔로 닦아주시면 다음 분들이 고마워할 거예요.`,
        },
    },
    {
        key: 'trash',
        order: 110,
        image: null,
        content: {
            es: `Los contenedores están a 200 metros del portón, a la derecha del camino. Las bolsas de basura están debajo del fregadero. Aquí se separa en tres: vidrio (verde), envases y plásticos (amarillo) y papel y cartón (azul).`,
            en: `The bins are 200 metres from the gate, on the right-hand side of the track. Bin bags are under the kitchen sink. Waste is separated three ways here: glass (green), packaging and plastic (yellow), paper and card (blue).`,
            fr: `Les conteneurs sont à 200 mètres du portail, à droite du chemin. Les sacs poubelle sont sous l'évier. Le tri se fait en trois : verre (vert), emballages et plastiques (jaune), papier et carton (bleu).`,
            de: `Die Container stehen 200 Meter vom Tor entfernt, rechts am Weg. Müllbeutel liegen unter der Spüle. Getrennt wird hier dreifach: Glas (grün), Verpackungen und Plastik (gelb), Papier und Karton (blau).`,
            it: `I cassonetti sono a 200 metri dal cancello, sulla destra della strada. I sacchi della spazzatura sono sotto il lavello. Qui si separa in tre: vetro (verde), imballaggi e plastica (giallo), carta e cartone (blu).`,
            pt: `Os contentores ficam a 200 metros do portão, à direita do caminho. Os sacos do lixo estão debaixo do lava-loiça. Aqui separa-se em três: vidro (verde), embalagens e plásticos (amarelo), papel e cartão (azul).`,
            ca: `Els contenidors són a 200 metres del portal, a la dreta del camí. Les bosses d'escombraries són sota l'aigüera. Aquí se separa en tres: vidre (verd), envasos i plàstics (groc) i paper i cartró (blau).`,
            ar: `الحاويات على بُعد ٢٠٠ متر من البوابة، على يمين الطريق. أكياس القمامة تحت حوض المطبخ. يُفصل النفايات هنا إلى ثلاثة: الزجاج (أخضر)، والعبوات والبلاستيك (أصفر)، والورق والكرتون (أزرق).`,
            ru: `Контейнеры стоят в 200 метрах от ворот, справа от дороги. Мусорные пакеты — под кухонной раковиной. Здесь мусор сортируют на три вида: стекло (зелёный), упаковка и пластик (жёлтый), бумага и картон (синий).`,
            uk: `Контейнери стоять за 200 метрів від воріт, праворуч від дороги. Пакети для сміття — під кухонною раковиною. Тут сміття сортують на три види: скло (зелений), упаковка та пластик (жовтий), папір і картон (синій).`,
            zh: `垃圾桶在距离大门 200 米处，位于路的右侧。垃圾袋放在厨房水槽下方。这里分三类回收：玻璃（绿色）、包装和塑料（黄色）、纸和纸板（蓝色）。`,
            ja: `ごみコンテナは門から200メートル、道の右手にあります。ごみ袋はキッチンのシンク下です。ここでは3分別です。ガラス（緑）、容器包装・プラスチック（黄）、紙・段ボール（青）。`,
            ko: `쓰레기 수거함은 대문에서 200미터 떨어진 길 오른쪽에 있습니다. 쓰레기봉투는 주방 싱크대 아래에 있습니다. 이곳은 세 가지로 분리배출합니다. 유리(초록), 포장재·플라스틱(노랑), 종이·판지(파랑).`,
        },
    },
    {
        key: 'rules',
        order: 120,
        image: null,
        content: {
            es: `No se fuma dentro de la casa, tampoco en las habitaciones. En el exterior, sin problema.\n\nMascotas bienvenidas avisando antes.\n\nNo se celebran fiestas ni eventos sin acuerdo previo con {{host_name}}.\n\nA partir de las 23:00 bajamos la música: es un entorno tranquilo y hay vecinos cerca.`,
            en: `No smoking inside the house, bedrooms included. Outdoors is no problem.\n\nPets are welcome as long as you tell us in advance.\n\nNo parties or events without agreeing it first with {{host_name}}.\n\nFrom 23:00 we turn the music down: this is a quiet spot and there are neighbours nearby.`,
            fr: `Il est interdit de fumer à l'intérieur, chambres comprises. À l'extérieur, aucun souci.\n\nLes animaux sont les bienvenus si vous nous prévenez à l'avance.\n\nPas de fêtes ni d'événements sans accord préalable avec {{host_name}}.\n\nÀ partir de 23h00, on baisse la musique : l'endroit est calme et il y a des voisins tout près.`,
            de: `Im Haus wird nicht geraucht, auch nicht in den Schlafzimmern. Draußen gerne.\n\nHaustiere sind willkommen, wenn Sie uns vorher Bescheid geben.\n\nKeine Partys oder Veranstaltungen ohne vorherige Absprache mit {{host_name}}.\n\nAb 23:00 Uhr drehen wir die Musik leiser: Die Gegend ist ruhig und die Nachbarn sind nah.`,
            it: `Non si fuma dentro casa, nemmeno nelle camere. All'aperto nessun problema.\n\nGli animali sono benvenuti avvisando prima.\n\nNiente feste o eventi senza accordo preventivo con {{host_name}}.\n\nDalle 23:00 si abbassa la musica: è un posto tranquillo e ci sono vicini vicini.`,
            pt: `Não se fuma dentro de casa, nem nos quartos. No exterior, sem problema.\n\nAnimais são bem-vindos avisando com antecedência.\n\nNão se realizam festas nem eventos sem acordo prévio com {{host_name}}.\n\nA partir das 23:00 baixamos a música: é um sítio tranquilo e há vizinhos por perto.`,
            ca: `No es fuma dins de casa, tampoc a les habitacions. A fora, cap problema.\n\nMascotes benvingudes avisant abans.\n\nNo s'hi celebren festes ni esdeveniments sense acord previ amb {{host_name}}.\n\nA partir de les 23:00 abaixem la música: és un entorn tranquil i hi ha veïns a prop.`,
            ar: `التدخين ممنوع داخل المنزل، بما في ذلك غرف النوم. أما في الخارج فلا مانع.\n\nالحيوانات الأليفة مرحب بها بشرط إخبارنا مسبقًا.\n\nلا تُقام حفلات أو فعاليات دون اتفاق مسبق مع {{host_name}}.\n\nاعتبارًا من الساعة ٢٣:٠٠ نخفض الموسيقى: المكان هادئ والجيران قريبون.`,
            ru: `В доме не курят, в том числе в спальнях. На улице — пожалуйста.\n\nС питомцами рады, если предупредите заранее.\n\nВечеринки и мероприятия — только по предварительной договорённости с {{host_name}}.\n\nПосле 23:00 делаем музыку тише: место тихое, соседи рядом.`,
            uk: `У будинку не палять, зокрема й у спальнях. Надворі — будь ласка.\n\nІз улюбленцями раді, якщо попередите заздалегідь.\n\nВечірки та заходи — лише за попередньою домовленістю з {{host_name}}.\n\nПісля 23:00 робимо музику тихішою: місце тихе, сусіди поруч.`,
            zh: `室内禁止吸烟，卧室也不例外。户外则没有问题。\n\n欢迎携带宠物，请提前告知我们。\n\n未事先与 {{host_name}} 约定，不得举办派对或活动。\n\n23:00 之后请调低音乐音量：这里环境安静，邻居就在附近。`,
            ja: `屋内は寝室を含め禁煙です。屋外は問題ありません。\n\nペットは事前にお知らせいただければ歓迎です。\n\n{{host_name}}との事前の合意なしにパーティーやイベントを行うことはご遠慮ください。\n\n23:00以降は音楽の音量を下げてください。静かな環境で、ご近所も近いためです。`,
            ko: `실내는 침실을 포함해 금연입니다. 야외에서는 괜찮습니다.\n\n반려동물은 미리 알려주시면 환영합니다.\n\n{{host_name}}와 사전에 협의하지 않은 파티나 행사는 삼가 주세요.\n\n23:00 이후에는 음악 소리를 줄여주세요. 조용한 동네이고 이웃이 가까이 있습니다.`,
        },
    },
    {
        key: 'supermarket',
        order: 130,
        image: null,
        content: {
            es: `El supermercado más cercano está a seis minutos en coche, a la entrada de {{town}}, y abre de 09:00 a 21:30 de lunes a sábado. Los domingos solo abre la tienda de la gasolinera del cruce. Si prefieres llegar con la nevera llena, tienes el servicio de compra en la Tienda.`,
            en: `The nearest supermarket is a six-minute drive away, at the entrance to {{town}}, open 09:00 to 21:30 Monday to Saturday. On Sundays only the shop at the petrol station on the junction opens. If you'd rather arrive to a full fridge, there's a grocery service in the Store.`,
            fr: `Le supermarché le plus proche est à six minutes en voiture, à l'entrée de {{town}}, ouvert de 09h00 à 21h30 du lundi au samedi. Le dimanche, seule la boutique de la station-service du carrefour ouvre. Si vous préférez arriver avec le frigo plein, le service de courses est dans la Boutique.`,
            de: `Der nächste Supermarkt liegt sechs Autominuten entfernt am Ortseingang von {{town}} und öffnet montags bis samstags von 09:00 bis 21:30 Uhr. Sonntags hat nur der Laden der Tankstelle an der Kreuzung offen. Wenn Sie lieber mit vollem Kühlschrank ankommen möchten, finden Sie den Einkaufsservice im Shop.`,
            it: `Il supermercato più vicino è a sei minuti in auto, all'ingresso di {{town}}, e apre dalle 09:00 alle 21:30 dal lunedì al sabato. La domenica apre solo il negozio del distributore all'incrocio. Se preferisci arrivare con il frigo pieno, trovi il servizio spesa nel Negozio.`,
            pt: `O supermercado mais próximo fica a seis minutos de carro, à entrada de {{town}}, e abre das 09:00 às 21:30 de segunda a sábado. Aos domingos só abre a loja da estação de serviço do cruzamento. Se preferir chegar com o frigorífico cheio, tem o serviço de compras na Loja.`,
            ca: `El supermercat més proper és a sis minuts en cotxe, a l'entrada de {{town}}, i obre de 09:00 a 21:30 de dilluns a dissabte. Els diumenges només obre la botiga de la benzinera de la cruïlla. Si prefereixes arribar amb la nevera plena, tens el servei de compra a la Botiga.`,
            ar: `أقرب سوبرماركت يبعد ست دقائق بالسيارة عند مدخل {{town}}، ويفتح من ٠٩:٠٠ حتى ٢١:٣٠ من الاثنين إلى السبت. أيام الأحد يفتح متجر محطة الوقود عند التقاطع فقط. إذا كنت تفضّل الوصول والثلاجة ممتلئة، ستجد خدمة التسوق في المتجر.`,
            ru: `Ближайший супермаркет — шесть минут на машине, при въезде в {{town}}, работает с 09:00 до 21:30 с понедельника по субботу. По воскресеньям открыт только магазин на заправке у развилки. Если хотите приехать к полному холодильнику, в Магазине есть услуга закупки продуктов.`,
            uk: `Найближчий супермаркет — шість хвилин автомобілем, на в'їзді до {{town}}, працює з 09:00 до 21:30 з понеділка по суботу. У неділю відкрита лише крамниця на заправці біля розвилки. Якщо хочете приїхати до повного холодильника, у Крамниці є послуга закупівлі продуктів.`,
            zh: `最近的超市开车六分钟，位于{{town}}入口处，周一至周六 09:00 至 21:30 营业。周日只有路口加油站的便利店开门。如果你希望抵达时冰箱已经装满，可以在商店里预订代购服务。`,
            ja: `いちばん近いスーパーは車で6分、{{town}}の入口にあり、月曜から土曜の9:00〜21:30まで営業しています。日曜は交差点のガソリンスタンド併設の店だけが開いています。冷蔵庫を満たした状態で到着されたい場合は、ストアに買い出しサービスがあります。`,
            ko: `가장 가까운 슈퍼마켓은 차로 6분 거리, {{town}} 입구에 있으며 월요일부터 토요일까지 09:00~21:30에 문을 엽니다. 일요일에는 교차로 주유소 매장만 영업합니다. 도착하실 때 냉장고가 채워져 있길 원하시면 스토어에서 장보기 서비스를 이용하실 수 있습니다.`,
        },
    },
    {
        key: 'host_contact',
        order: 140,
        image: null,
        content: {
            es: `{{host_name}} vive cerca y responde por WhatsApp en el {{host_phone}}, normalmente en menos de una hora. Para cualquier urgencia con la casa —agua, luz, calefacción— llama directamente en vez de escribir: es más rápido.`,
            en: `{{host_name}} lives nearby and answers on WhatsApp at {{host_phone}}, usually within the hour. For anything urgent with the house — water, power, heating — call rather than message: it's faster.`,
            fr: `{{host_name}} habite tout près et répond sur WhatsApp au {{host_phone}}, en général en moins d'une heure. Pour toute urgence dans la maison — eau, électricité, chauffage — appelez plutôt que d'écrire : c'est plus rapide.`,
            de: `{{host_name}} wohnt in der Nähe und antwortet per WhatsApp unter {{host_phone}}, meist innerhalb einer Stunde. Bei Notfällen im Haus — Wasser, Strom, Heizung — rufen Sie lieber an, statt zu schreiben: Das geht schneller.`,
            it: `{{host_name}} abita qui vicino e risponde su WhatsApp al {{host_phone}}, di solito in meno di un'ora. Per qualsiasi urgenza in casa — acqua, luce, riscaldamento — chiama invece di scrivere: è più veloce.`,
            pt: `{{host_name}} vive perto e responde por WhatsApp no {{host_phone}}, normalmente em menos de uma hora. Para qualquer urgência com a casa — água, luz, aquecimento — ligue em vez de escrever: é mais rápido.`,
            ca: `{{host_name}} viu a prop i respon per WhatsApp al {{host_phone}}, normalment en menys d'una hora. Per a qualsevol urgència amb la casa —aigua, llum, calefacció— truca directament en comptes d'escriure: és més ràpid.`,
            ar: `يسكن {{host_name}} في الجوار ويرد على واتساب عبر الرقم {{host_phone}}، عادةً في أقل من ساعة. لأي حالة طارئة في المنزل — ماء أو كهرباء أو تدفئة — اتصل مباشرةً بدل الكتابة: فهو أسرع.`,
            ru: `{{host_name}} живёт рядом и отвечает в WhatsApp по номеру {{host_phone}}, обычно в течение часа. По срочным вопросам с домом — вода, электричество, отопление — лучше позвонить, а не писать: так быстрее.`,
            uk: `{{host_name}} живе поруч і відповідає у WhatsApp за номером {{host_phone}}, зазвичай протягом години. Із терміновими питаннями щодо будинку — вода, електрика, опалення — краще зателефонувати, а не писати: так швидше.`,
            zh: `{{host_name}} 就住在附近，可通过 WhatsApp（{{host_phone}}）联系，通常一小时内回复。若房子出现紧急情况——停水、停电、暖气故障——请直接拨打电话而不是发消息，这样更快。`,
            ja: `{{host_name}}は近くに住んでおり、WhatsApp（{{host_phone}}）で通常1時間以内に返信します。水道・電気・暖房など家に関する急ぎの件は、メッセージより電話のほうが早く対応できます。`,
            ko: `{{host_name}}은(는) 근처에 살고 있으며 WhatsApp({{host_phone}})으로 보통 한 시간 이내에 답장합니다. 물, 전기, 난방 등 집과 관련된 급한 일은 메시지보다 전화가 더 빠릅니다.`,
        },
    },
];
