/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#687a52",
        "primary-fixed": "#ffdbcf",
        "surface-variant": "#e5e2dd",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#2d486d",
        "primary": "#944426",
        "on-primary-fixed-variant": "#793013",
        "inverse-surface": "#31302d",
        "inverse-primary": "#ffb59b",
        "outline": "#88726b",
        "on-secondary-container": "#3e5980",
        "on-tertiary-container": "#f9ffea",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#001c3b",
        "surface-dim": "#dcdad5",
        "tertiary-fixed-dim": "#bacd9e",
        "on-tertiary-fixed-variant": "#3b4c28",
        "secondary-fixed-dim": "#adc8f5",
        "surface-bright": "#fcf9f4",
        "terracotta": "#C96D4B",
        "deep-sea": "#1E3A5F",
        "surface-container-highest": "#e5e2dd",
        "error-container": "#ffdad6",
        "surface-container-high": "#ebe8e3",
        "primary-fixed-dim": "#ffb59b",
        "on-surface-variant": "#55433d",
        "tertiary-fixed": "#d5eab9",
        "outline-variant": "#dbc1b9",
        "secondary-fixed": "#d5e3ff",
        "olive": "#6B7D54",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#111f02",
        "on-background": "#1c1c19",
        "surface-container": "#f0ede9",
        "tertiary": "#50613b",
        "on-primary-fixed": "#380d00",
        "warm-sand": "#F1EBE0",
        "surface-tint": "#974728",
        "on-primary-container": "#fffbff",
        "surface": "#fcf9f4",
        "primary-container": "#b35c3b",
        "surface-container-low": "#f6f3ee",
        "secondary-container": "#b5d0fd",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "inverse-on-surface": "#f3f0eb",
        "secondary": "#455f87",
        "on-primary": "#ffffff",
        "background": "#fcf9f4",
        "on-surface": "#1c1c19",
        "crisp-white": "#FFFFFF"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "2xl": "1rem"
      },
      spacing: {
        "margin-mobile": "20px",
        "gutter": "24px",
        "container-max": "1200px",
        "base": "8px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "label-lg": ["Montserrat"],
        "body-md": ["Montserrat"],
        "display-lg": ["Playfair Display"],
        "headline-lg-mobile": ["Playfair Display"],
        "body-lg": ["Montserrat"],
        "headline-md": ["Playfair Display"],
        "headline-lg": ["Playfair Display"],
        "label-sm": ["Montserrat"]
      },
      fontSize: {
        "label-lg": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "500" }]
      }
    }
  },
  plugins: [],
}
