-- Migration: 0030_delivery_localization_strings.sql
-- Sistema de Delivery: Strings de UI globales para TODOS los idiomas activos

-- modal_title (Título del modal de delivery)
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('delivery', 'modal_title', 'es', 'Pedir a Domicilio', 'Título del modal de delivery'),
('delivery', 'modal_title', 'en', 'Order Delivery', 'Delivery modal title'),
('delivery', 'modal_title', 'fr', 'Commander à Domicile', 'Titre du modal livraison'),
('delivery', 'modal_title', 'de', 'Lieferung Bestellen', 'Lieferung Modal Titel'),
('delivery', 'modal_title', 'it', 'Ordina a Domicilio', 'Titolo modale consegna'),
('delivery', 'modal_title', 'pt', 'Pedir Entrega', 'Título do modal de entrega'),
('delivery', 'modal_title', 'kr', '배달 주문', '배달 모달 제목'),
('delivery', 'modal_title', 'ja', '配達を注文', '配達モーダルタイトル'),
('delivery', 'modal_title', 'bn', 'ডেলিভারি অর্ডার', 'ডেলিভারি মডাল শিরোনাম'),
('delivery', 'modal_title', 'ar', 'طلب توصيل', 'عنوان نافذة التوصيل'),
('delivery', 'modal_title', 'ru', 'Заказать доставку', 'Заголовок окна доставки'),
('delivery', 'modal_title', 'ua', 'Замовити доставку', 'Заголовок вікна доставки'),
('delivery', 'modal_title', 'cn', '订购配送', '配送弹窗标题'),
('delivery', 'modal_title', 'in', 'डिलीवरी ऑर्डर', 'डिलीवरी मॉडल शीर्षक'),
('delivery', 'modal_title', 'nl', 'Bezorging Bestellen', 'Bezorging modal titel'),
('delivery', 'modal_title', 'sv', 'Beställ Leverans', 'Leverans modal titel'),
('delivery', 'modal_title', 'pl', 'Zamów Dostawę', 'Tytuł okna dostawy'),
('delivery', 'modal_title', 'tr', 'Teslimat Siparişi', 'Teslimat modal başlığı'),
('delivery', 'modal_title', 'zh', '訂購配送', '配送彈窗標題'),
('delivery', 'modal_title', 'ko', '배달 주문', '배달 모달 제목');

-- order_summary (Resumen del carrito)
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('delivery', 'order_summary', 'es', 'Tu pedido', 'Resumen del carrito'),
('delivery', 'order_summary', 'en', 'Your order', 'Cart summary'),
('delivery', 'order_summary', 'fr', 'Votre commande', 'Résumé du panier'),
('delivery', 'order_summary', 'de', 'Ihre Bestellung', 'Warenkorb Zusammenfassung'),
('delivery', 'order_summary', 'it', 'Il tuo ordine', 'Riepilogo carrello'),
('delivery', 'order_summary', 'pt', 'Seu pedido', 'Resumo do carrinho'),
('delivery', 'order_summary', 'kr', '주문 내역', '장바구니 요약'),
('delivery', 'order_summary', 'ja', 'ご注文内容', 'カート概要'),
('delivery', 'order_summary', 'bn', 'আপনার অর্ডার', 'কার্ট সারাংশ'),
('delivery', 'order_summary', 'ar', 'طلبك', 'ملخص السلة'),
('delivery', 'order_summary', 'ru', 'Ваш заказ', 'Содержимое корзины'),
('delivery', 'order_summary', 'ua', 'Ваше замовлення', 'Вміст кошика'),
('delivery', 'order_summary', 'cn', '您的订单', '购物车摘要'),
('delivery', 'order_summary', 'in', 'आपका ऑर्डर', 'कार्ट सारांश'),
('delivery', 'order_summary', 'nl', 'Uw bestelling', 'Winkelwagen overzicht'),
('delivery', 'order_summary', 'sv', 'Din beställning', 'Kundvagn sammanfattning'),
('delivery', 'order_summary', 'pl', 'Twoje zamówienie', 'Podsumowanie koszyka'),
('delivery', 'order_summary', 'tr', 'Siparişiniz', 'Sepet özeti'),
('delivery', 'order_summary', 'zh', '您的訂單', '購物車摘要'),
('delivery', 'order_summary', 'ko', '주문 내역', '장바구니 요약');

-- payment_cash (Pago en efectivo)
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('delivery', 'payment_cash', 'es', 'Efectivo', 'Pago en efectivo'),
('delivery', 'payment_cash', 'en', 'Cash', 'Cash payment'),
('delivery', 'payment_cash', 'fr', 'Espèces', 'Paiement espèces'),
('delivery', 'payment_cash', 'de', 'Bargeld', 'Barzahlung'),
('delivery', 'payment_cash', 'it', 'Contanti', 'Pagamento contanti'),
('delivery', 'payment_cash', 'pt', 'Dinheiro', 'Pagamento em dinheiro'),
('delivery', 'payment_cash', 'kr', '현금', '현금 결제'),
('delivery', 'payment_cash', 'ja', '現金', '現金払い'),
('delivery', 'payment_cash', 'bn', 'নগদ', 'নগদ অর্থপ্রদান'),
('delivery', 'payment_cash', 'ar', 'نقداً', 'الدفع نقداً'),
('delivery', 'payment_cash', 'ru', 'Наличные', 'Оплата наличными'),
('delivery', 'payment_cash', 'ua', 'Готівка', 'Оплата готівкою'),
('delivery', 'payment_cash', 'cn', '现金', '现金支付'),
('delivery', 'payment_cash', 'in', 'नकद', 'नकद भुगतान'),
('delivery', 'payment_cash', 'nl', 'Contant', 'Contante betaling'),
('delivery', 'payment_cash', 'sv', 'Kontant', 'Kontant betalning'),
('delivery', 'payment_cash', 'pl', 'Gotówka', 'Płatność gotówką'),
('delivery', 'payment_cash', 'tr', 'Nakit', 'Nakit ödeme'),
('delivery', 'payment_cash', 'zh', '現金', '現金付款'),
('delivery', 'payment_cash', 'ko', '현금', '현금 결제');

-- payment_card (Pago con tarjeta)
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('delivery', 'payment_card', 'es', 'Tarjeta', 'Pago con tarjeta'),
('delivery', 'payment_card', 'en', 'Card', 'Card payment'),
('delivery', 'payment_card', 'fr', 'Carte', 'Paiement carte'),
('delivery', 'payment_card', 'de', 'Karte', 'Kartenzahlung'),
('delivery', 'payment_card', 'it', 'Carta', 'Pagamento carta'),
('delivery', 'payment_card', 'pt', 'Cartão', 'Pagamento com cartão'),
('delivery', 'payment_card', 'kr', '카드', '카드 결제'),
('delivery', 'payment_card', 'ja', 'カード', 'カード払い'),
('delivery', 'payment_card', 'bn', 'কার্ড', 'কার্ড অর্থপ্রদান'),
('delivery', 'payment_card', 'ar', 'بطاقة', 'الدفع بالبطاقة'),
('delivery', 'payment_card', 'ru', 'Карта', 'Оплата картой'),
('delivery', 'payment_card', 'ua', 'Картка', 'Оплата карткою'),
('delivery', 'payment_card', 'cn', '银行卡', '银行卡支付'),
('delivery', 'payment_card', 'in', 'कार्ड', 'कार्ड भुगतान'),
('delivery', 'payment_card', 'nl', 'Kaart', 'Kaart betaling'),
('delivery', 'payment_card', 'sv', 'Kort', 'Kortbetalning'),
('delivery', 'payment_card', 'pl', 'Karta', 'Płatność kartą'),
('delivery', 'payment_card', 'tr', 'Kart', 'Kart ile ödeme'),
('delivery', 'payment_card', 'zh', '銀行卡', '銀行卡付款'),
('delivery', 'payment_card', 'ko', '카드', '카드 결제');

-- shipping (Envío)
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('delivery', 'shipping', 'es', 'Envío', 'Etiqueta envío'),
('delivery', 'shipping', 'en', 'Shipping', 'Shipping label'),
('delivery', 'shipping', 'fr', 'Livraison', 'Étiquette livraison'),
('delivery', 'shipping', 'de', 'Versand', 'Versand Label'),
('delivery', 'shipping', 'it', 'Spedizione', 'Etichetta spedizione'),
('delivery', 'shipping', 'pt', 'Envio', 'Etiqueta envio'),
('delivery', 'shipping', 'kr', '배송', '배송 라벨'),
('delivery', 'shipping', 'ja', '配送', '配送ラベル'),
('delivery', 'shipping', 'bn', 'শিপিং', 'শিপিং লেবেল'),
('delivery', 'shipping', 'ar', 'الشحن', 'تسمية الشحن'),
('delivery', 'shipping', 'ru', 'Доставка', 'Метка доставки'),
('delivery', 'shipping', 'ua', 'Доставка', 'Мітка доставки'),
('delivery', 'shipping', 'cn', '配送', '配送标签'),
('delivery', 'shipping', 'in', 'शिपिंग', 'शिपिंग लेबल'),
('delivery', 'shipping', 'nl', 'Verzending', 'Verzending label'),
('delivery', 'shipping', 'sv', 'Frakt', 'Frakt etikett'),
('delivery', 'shipping', 'pl', 'Dostawa', 'Etykieta dostawy'),
('delivery', 'shipping', 'tr', 'Kargo', 'Kargo etiketi'),
('delivery', 'shipping', 'zh', '配送', '配送標籤'),
('delivery', 'shipping', 'ko', '배송', '배송 라벨');

-- shipping_free (Envío gratis)
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('delivery', 'shipping_free', 'es', 'Gratis', 'Envío gratis'),
('delivery', 'shipping_free', 'en', 'Free', 'Free shipping'),
('delivery', 'shipping_free', 'fr', 'Gratuit', 'Livraison gratuite'),
('delivery', 'shipping_free', 'de', 'Kostenlos', 'Kostenloser Versand'),
('delivery', 'shipping_free', 'it', 'Gratis', 'Spedizione gratuita'),
('delivery', 'shipping_free', 'pt', 'Grátis', 'Envio grátis'),
('delivery', 'shipping_free', 'kr', '무료', '무료 배송'),
('delivery', 'shipping_free', 'ja', '無料', '送料無料'),
('delivery', 'shipping_free', 'bn', 'বিনামূল্যে', 'বিনামূল্যে শিপিং'),
('delivery', 'shipping_free', 'ar', 'مجاناً', 'شحن مجاني'),
('delivery', 'shipping_free', 'ru', 'Бесплатно', 'Бесплатная доставка'),
('delivery', 'shipping_free', 'ua', 'Безкоштовно', 'Безкоштовна доставка'),
('delivery', 'shipping_free', 'cn', '免费', '免费配送'),
('delivery', 'shipping_free', 'in', 'मुफ्त', 'मुफ्त शिपिंग'),
('delivery', 'shipping_free', 'nl', 'Gratis', 'Gratis verzending'),
('delivery', 'shipping_free', 'sv', 'Gratis', 'Fri frakt'),
('delivery', 'shipping_free', 'pl', 'Bezpłatnie', 'Darmowa dostawa'),
('delivery', 'shipping_free', 'tr', 'Ücretsiz', 'Ücretsiz kargo'),
('delivery', 'shipping_free', 'zh', '免費', '免費配送'),
('delivery', 'shipping_free', 'ko', '무료', '무료 배송');

-- total (Total del pedido)
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('delivery', 'total', 'es', 'Total', 'Total del pedido'),
('delivery', 'total', 'en', 'Total', 'Order total'),
('delivery', 'total', 'fr', 'Total', 'Total commande'),
('delivery', 'total', 'de', 'Gesamt', 'Bestellung Gesamt'),
('delivery', 'total', 'it', 'Totale', 'Totale ordine'),
('delivery', 'total', 'pt', 'Total', 'Total do pedido'),
('delivery', 'total', 'kr', '총액', '주문 총액'),
('delivery', 'total', 'ja', '合計', '注文合計'),
('delivery', 'total', 'bn', 'মোট', 'অর্ডার মোট'),
('delivery', 'total', 'ar', 'المجموع', 'إجمالي الطلب'),
('delivery', 'total', 'ru', 'Итого', 'Общая сумма заказа'),
('delivery', 'total', 'ua', 'Разом', 'Загальна сума замовлення'),
('delivery', 'total', 'cn', '总计', '订单总额'),
('delivery', 'total', 'in', 'कुल', 'ऑर्डर कुल'),
('delivery', 'total', 'nl', 'Totaal', 'Bestelling totaal'),
('delivery', 'total', 'sv', 'Totalt', 'Beställning totalt'),
('delivery', 'total', 'pl', 'Suma', 'Suma zamówienia'),
('delivery', 'total', 'tr', 'Toplam', 'Sipariş toplamı'),
('delivery', 'total', 'zh', '總計', '訂單總額'),
('delivery', 'total', 'ko', '총액', '주문 총액');

-- send_whatsapp (Botón principal)
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('delivery', 'send_whatsapp', 'es', 'Enviar pedido por WhatsApp', 'Botón principal'),
('delivery', 'send_whatsapp', 'en', 'Send order via WhatsApp', 'Main button'),
('delivery', 'send_whatsapp', 'fr', 'Envoyer commande par WhatsApp', 'Bouton principal'),
('delivery', 'send_whatsapp', 'de', 'Bestellung per WhatsApp senden', 'Hauptknopf'),
('delivery', 'send_whatsapp', 'it', 'Invia ordine via WhatsApp', 'Pulsante principale'),
('delivery', 'send_whatsapp', 'pt', 'Enviar pedido por WhatsApp', 'Botão principal'),
('delivery', 'send_whatsapp', 'kr', 'WhatsApp으로 주문 보내기', '메인 버튼'),
('delivery', 'send_whatsapp', 'ja', 'WhatsAppで注文を送信', 'メインボタン'),
('delivery', 'send_whatsapp', 'bn', 'WhatsApp এ অর্ডার পাঠান', 'প্রধান বোতাম'),
('delivery', 'send_whatsapp', 'ar', 'إرسال الطلب عبر واتساب', 'الزر الرئيسي'),
('delivery', 'send_whatsapp', 'ru', 'Отправить заказ через WhatsApp', 'Главная кнопка'),
('delivery', 'send_whatsapp', 'ua', 'Надіслати замовлення через WhatsApp', 'Головна кнопка'),
('delivery', 'send_whatsapp', 'cn', '通过WhatsApp发送订单', '主按钮'),
('delivery', 'send_whatsapp', 'in', 'WhatsApp से ऑर्डर भेजें', 'मुख्य बटन'),
('delivery', 'send_whatsapp', 'nl', 'Bestelling via WhatsApp verzenden', 'Hoofdknop'),
('delivery', 'send_whatsapp', 'sv', 'Skicka beställning via WhatsApp', 'Huvudknapp'),
('delivery', 'send_whatsapp', 'pl', 'Wyślij zamówienie przez WhatsApp', 'Główny przycisk'),
('delivery', 'send_whatsapp', 'tr', 'WhatsApp ile sipariş gönder', 'Ana buton'),
('delivery', 'send_whatsapp', 'zh', '通過WhatsApp發送訂單', '主按鈕'),
('delivery', 'send_whatsapp', 'ko', 'WhatsApp으로 주문 보내기', '메인 버튼');

-- call_restaurant (Botón secundario)
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('delivery', 'call_restaurant', 'es', 'Llamar al restaurante', 'Botón secundario'),
('delivery', 'call_restaurant', 'en', 'Call restaurant', 'Secondary button'),
('delivery', 'call_restaurant', 'fr', 'Appeler le restaurant', 'Bouton secondaire'),
('delivery', 'call_restaurant', 'de', 'Restaurant anrufen', 'Sekundärer Knopf'),
('delivery', 'call_restaurant', 'it', 'Chiama ristorante', 'Pulsante secondario'),
('delivery', 'call_restaurant', 'pt', 'Ligar para restaurante', 'Botão secundário'),
('delivery', 'call_restaurant', 'kr', '레스토랑에 전화하기', '보조 버튼'),
('delivery', 'call_restaurant', 'ja', 'レストランに電話', 'サブボタン'),
('delivery', 'call_restaurant', 'bn', 'রেস্তোরাঁয় কল করুন', 'সেকেন্ডারি বোতাম'),
('delivery', 'call_restaurant', 'ar', 'اتصل بالمطعم', 'الزر الثانوي'),
('delivery', 'call_restaurant', 'ru', 'Позвонить в ресторан', 'Вторичная кнопка'),
('delivery', 'call_restaurant', 'ua', 'Зателефонувати в ресторан', 'Вторинна кнопка'),
('delivery', 'call_restaurant', 'cn', '致电餐厅', '次要按钮'),
('delivery', 'call_restaurant', 'in', 'रेस्तरां को कॉल करें', 'सेकेंडरी बटन'),
('delivery', 'call_restaurant', 'nl', 'Bel restaurant', 'Secundaire knop'),
('delivery', 'call_restaurant', 'sv', 'Ring restaurangen', 'Sekundär knapp'),
('delivery', 'call_restaurant', 'pl', 'Zadzwoń do restauracji', 'Przycisk pomocniczy'),
('delivery', 'call_restaurant', 'tr', 'Restoranı ara', 'İkincil buton'),
('delivery', 'call_restaurant', 'zh', '致電餐廳', '次要按鈕'),
('delivery', 'call_restaurant', 'ko', '레스토랑에 전화하기', '보조 버튼');

-- closed_today (Mensaje día cerrado)
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('delivery', 'closed_today', 'es', 'Hoy no hay servicio de reparto', 'Mensaje día cerrado'),
('delivery', 'closed_today', 'en', 'No delivery service today', 'Closed day message'),
('delivery', 'closed_today', 'fr', 'Pas de livraison aujourd''hui', 'Message jour fermé'),
('delivery', 'closed_today', 'de', 'Heute kein Lieferservice', 'Geschlossener Tag'),
('delivery', 'closed_today', 'it', 'Nessun servizio di consegna oggi', 'Giorno chiuso'),
('delivery', 'closed_today', 'pt', 'Sem serviço de entrega hoje', 'Dia fechado'),
('delivery', 'closed_today', 'kr', '오늘은 배달 서비스가 없습니다', '휴무일'),
('delivery', 'closed_today', 'ja', '本日は配達サービスがありません', '休業日'),
('delivery', 'closed_today', 'bn', 'আজ ডেলিভারি সেবা নেই', 'বন্ধের দিন'),
('delivery', 'closed_today', 'ar', 'لا خدمة توصيل اليوم', 'رسالة يوم الإغلاق'),
('delivery', 'closed_today', 'ru', 'Сегодня нет доставки', 'Закрыто'),
('delivery', 'closed_today', 'ua', 'Сьогодні немає доставки', 'Зачинено'),
('delivery', 'closed_today', 'cn', '今天没有配送服务', '休息日'),
('delivery', 'closed_today', 'in', 'आज डिलीवरी सेवा नहीं है', 'बंद दिन'),
('delivery', 'closed_today', 'nl', 'Vandaag geen bezorgservice', 'Gesloten dag'),
('delivery', 'closed_today', 'sv', 'Ingen leverans idag', 'Stängd dag'),
('delivery', 'closed_today', 'pl', 'Dziś brak dostawy', 'Dzień zamknięty'),
('delivery', 'closed_today', 'tr', 'Bugün teslimat yok', 'Kapalı gün'),
('delivery', 'closed_today', 'zh', '今天沒有配送服務', '休息日'),
('delivery', 'closed_today', 'ko', '오늘은 배달 서비스가 없습니다', '휴무일');

-- outside_hours (Fuera de horario)
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('delivery', 'outside_hours', 'es', 'Fuera de horario de reparto', 'Mensaje fuera de horario'),
('delivery', 'outside_hours', 'en', 'Outside delivery hours', 'Outside hours message'),
('delivery', 'outside_hours', 'fr', 'En dehors des heures de livraison', 'Hors horaire'),
('delivery', 'outside_hours', 'de', 'Außerhalb der Lieferzeiten', 'Außerhalb der Zeiten'),
('delivery', 'outside_hours', 'it', 'Fuori orario di consegna', 'Fuori orario'),
('delivery', 'outside_hours', 'pt', 'Fora do horário de entrega', 'Fora do horário'),
('delivery', 'outside_hours', 'kr', '배달 시간 외', '시간 외'),
('delivery', 'outside_hours', 'ja', '配達時間外', '時間外'),
('delivery', 'outside_hours', 'bn', 'ডেলিভারি সময়ের বাইরে', 'সময়ের বাইরে'),
('delivery', 'outside_hours', 'ar', 'خارج أوقات التوصيل', 'خارج الأوقات'),
('delivery', 'outside_hours', 'ru', 'Вне часов доставки', 'Вне времени работы'),
('delivery', 'outside_hours', 'ua', 'Поза годинами доставки', 'Поза робочий час'),
('delivery', 'outside_hours', 'cn', '配送时间外', '非配送时间'),
('delivery', 'outside_hours', 'in', 'डिलीवरी समय के बाहर', 'समय के बाहर'),
('delivery', 'outside_hours', 'nl', 'Buiten bezorgtijden', 'Buiten openingstijden'),
('delivery', 'outside_hours', 'sv', 'Utanför leveranstider', 'Utanför tider'),
('delivery', 'outside_hours', 'pl', 'Poza godzinami dostawy', 'Poza godzinami'),
('delivery', 'outside_hours', 'tr', 'Teslimat saatleri dışında', 'Saat dışı'),
('delivery', 'outside_hours', 'zh', '配送時間外', '非配送時間'),
('delivery', 'outside_hours', 'ko', '배달 시간 외', '시간 외');

-- empty_cart (Carrito vacío)
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('delivery', 'empty_cart', 'es', 'Tu carrito está vacío', 'Carrito vacío'),
('delivery', 'empty_cart', 'en', 'Your cart is empty', 'Empty cart'),
('delivery', 'empty_cart', 'fr', 'Votre panier est vide', 'Panier vide'),
('delivery', 'empty_cart', 'de', 'Ihr Warenkorb ist leer', 'Leerer Warenkorb'),
('delivery', 'empty_cart', 'it', 'Il tuo carrello è vuoto', 'Carrello vuoto'),
('delivery', 'empty_cart', 'pt', 'Seu carrinho está vazio', 'Carrinho vazio'),
('delivery', 'empty_cart', 'kr', '장바구니가 비어있습니다', '빈 장바구니'),
('delivery', 'empty_cart', 'ja', 'カートは空です', '空のカート'),
('delivery', 'empty_cart', 'bn', 'আপনার কার্ট খালি', 'খালি কার্ট'),
('delivery', 'empty_cart', 'ar', 'سلتك فارغة', 'سلة فارغة'),
('delivery', 'empty_cart', 'ru', 'Ваша корзина пуста', 'Пустая корзина'),
('delivery', 'empty_cart', 'ua', 'Ваш кошик порожній', 'Порожній кошик'),
('delivery', 'empty_cart', 'cn', '您的购物车是空的', '空购物车'),
('delivery', 'empty_cart', 'in', 'आपकी कार्ट खाली है', 'खाली कार्ट'),
('delivery', 'empty_cart', 'nl', 'Uw winkelwagen is leeg', 'Lege winkelwagen'),
('delivery', 'empty_cart', 'sv', 'Din kundvagn är tom', 'Tom kundvagn'),
('delivery', 'empty_cart', 'pl', 'Twój koszyk jest pusty', 'Pusty koszyk'),
('delivery', 'empty_cart', 'tr', 'Sepetiniz boş', 'Boş sepet'),
('delivery', 'empty_cart', 'zh', '您的購物車是空的', '空購物車'),
('delivery', 'empty_cart', 'ko', '장바구니가 비어있습니다', '빈 장바구니');

-- minimum_not_reached (Pedido mínimo no alcanzado)
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('delivery', 'minimum_not_reached', 'es', 'No alcanzas el pedido mínimo', 'Mínimo no alcanzado'),
('delivery', 'minimum_not_reached', 'en', 'Minimum order not reached', 'Minimum not reached'),
('delivery', 'minimum_not_reached', 'fr', 'Commande minimum non atteinte', 'Minimum non atteint'),
('delivery', 'minimum_not_reached', 'de', 'Mindestbestellung nicht erreicht', 'Minimum nicht erreicht'),
('delivery', 'minimum_not_reached', 'it', 'Ordine minimo non raggiunto', 'Minimo non raggiunto'),
('delivery', 'minimum_not_reached', 'pt', 'Pedido mínimo não alcançado', 'Mínimo não alcançado'),
('delivery', 'minimum_not_reached', 'kr', '최소 주문 금액 미달', '최소 미달'),
('delivery', 'minimum_not_reached', 'ja', '最低注文金額に達していません', '最低未達'),
('delivery', 'minimum_not_reached', 'bn', 'ন্যূনতম অর্ডার পূরণ হয়নি', 'ন্যূনতম পূরণ হয়নি'),
('delivery', 'minimum_not_reached', 'ar', 'لم يتم الوصول للحد الأدنى', 'الحد الأدنى غير متحقق'),
('delivery', 'minimum_not_reached', 'ru', 'Минимальный заказ не достигнут', 'Минимум не достигнут'),
('delivery', 'minimum_not_reached', 'ua', 'Мінімальне замовлення не досягнуто', 'Мінімум не досягнуто'),
('delivery', 'minimum_not_reached', 'cn', '未达到最低订单', '未达最低'),
('delivery', 'minimum_not_reached', 'in', 'न्यूनतम ऑर्डर पूरा नहीं हुआ', 'न्यूनतम नहीं पहुंचा'),
('delivery', 'minimum_not_reached', 'nl', 'Minimumbestelling niet bereikt', 'Minimum niet bereikt'),
('delivery', 'minimum_not_reached', 'sv', 'Minsta beställning ej uppnådd', 'Minimum ej uppnått'),
('delivery', 'minimum_not_reached', 'pl', 'Nie osiągnięto minimalnego zamówienia', 'Minimum nieosiągnięte'),
('delivery', 'minimum_not_reached', 'tr', 'Minimum sipariş tutarına ulaşılmadı', 'Minimum ulaşılmadı'),
('delivery', 'minimum_not_reached', 'zh', '未達到最低訂單', '未達最低'),
('delivery', 'minimum_not_reached', 'ko', '최소 주문 금액 미달', '최소 미달');

-- delivery_area (Zona de reparto)
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('delivery', 'delivery_area', 'es', 'Zona de reparto', 'Zona de entrega'),
('delivery', 'delivery_area', 'en', 'Delivery area', 'Delivery zone'),
('delivery', 'delivery_area', 'fr', 'Zone de livraison', 'Zone de livraison'),
('delivery', 'delivery_area', 'de', 'Liefergebiet', 'Lieferzone'),
('delivery', 'delivery_area', 'it', 'Zona di consegna', 'Zona consegna'),
('delivery', 'delivery_area', 'pt', 'Zona de entrega', 'Zona de entrega'),
('delivery', 'delivery_area', 'kr', '배달 지역', '배달 구역'),
('delivery', 'delivery_area', 'ja', '配達エリア', '配達地域'),
('delivery', 'delivery_area', 'bn', 'ডেলিভারি এলাকা', 'ডেলিভারি জোন'),
('delivery', 'delivery_area', 'ar', 'منطقة التوصيل', 'نطاق التوصيل'),
('delivery', 'delivery_area', 'ru', 'Зона доставки', 'Район доставки'),
('delivery', 'delivery_area', 'ua', 'Зона доставки', 'Район доставки'),
('delivery', 'delivery_area', 'cn', '配送区域', '配送范围'),
('delivery', 'delivery_area', 'in', 'डिलीवरी क्षेत्र', 'डिलीवरी जोन'),
('delivery', 'delivery_area', 'nl', 'Bezorggebied', 'Bezorgzone'),
('delivery', 'delivery_area', 'sv', 'Leveransområde', 'Leveranszon'),
('delivery', 'delivery_area', 'pl', 'Strefa dostawy', 'Obszar dostawy'),
('delivery', 'delivery_area', 'tr', 'Teslimat bölgesi', 'Teslimat alanı'),
('delivery', 'delivery_area', 'zh', '配送區域', '配送範圍'),
('delivery', 'delivery_area', 'ko', '배달 지역', '배달 구역');

-- wa_new_order (Cabecera mensaje WhatsApp)
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('delivery', 'wa_new_order', 'es', 'Nuevo Pedido', 'Cabecera WhatsApp'),
('delivery', 'wa_new_order', 'en', 'New Order', 'WhatsApp header'),
('delivery', 'wa_new_order', 'fr', 'Nouvelle Commande', 'En-tête WhatsApp'),
('delivery', 'wa_new_order', 'de', 'Neue Bestellung', 'WhatsApp Kopfzeile'),
('delivery', 'wa_new_order', 'it', 'Nuovo Ordine', 'Intestazione WhatsApp'),
('delivery', 'wa_new_order', 'pt', 'Novo Pedido', 'Cabeçalho WhatsApp'),
('delivery', 'wa_new_order', 'kr', '새 주문', 'WhatsApp 헤더'),
('delivery', 'wa_new_order', 'ja', '新規注文', 'WhatsAppヘッダー'),
('delivery', 'wa_new_order', 'bn', 'নতুন অর্ডার', 'WhatsApp হেডার'),
('delivery', 'wa_new_order', 'ar', 'طلب جديد', 'عنوان واتساب'),
('delivery', 'wa_new_order', 'ru', 'Новый заказ', 'Заголовок WhatsApp'),
('delivery', 'wa_new_order', 'ua', 'Нове замовлення', 'Заголовок WhatsApp'),
('delivery', 'wa_new_order', 'cn', '新订单', 'WhatsApp标题'),
('delivery', 'wa_new_order', 'in', 'नया ऑर्डर', 'WhatsApp हेडर'),
('delivery', 'wa_new_order', 'nl', 'Nieuwe Bestelling', 'WhatsApp koptekst'),
('delivery', 'wa_new_order', 'sv', 'Ny Beställning', 'WhatsApp rubrik'),
('delivery', 'wa_new_order', 'pl', 'Nowe Zamówienie', 'Nagłówek WhatsApp'),
('delivery', 'wa_new_order', 'tr', 'Yeni Sipariş', 'WhatsApp başlığı'),
('delivery', 'wa_new_order', 'zh', '新訂單', 'WhatsApp標題'),
('delivery', 'wa_new_order', 'ko', '새 주문', 'WhatsApp 헤더');

-- wa_address (Campo dirección)
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('delivery', 'wa_address', 'es', 'Dirección', 'Campo dirección'),
('delivery', 'wa_address', 'en', 'Address', 'Address field'),
('delivery', 'wa_address', 'fr', 'Adresse', 'Champ adresse'),
('delivery', 'wa_address', 'de', 'Adresse', 'Adresse Feld'),
('delivery', 'wa_address', 'it', 'Indirizzo', 'Campo indirizzo'),
('delivery', 'wa_address', 'pt', 'Endereço', 'Campo endereço'),
('delivery', 'wa_address', 'kr', '주소', '주소 필드'),
('delivery', 'wa_address', 'ja', '住所', '住所欄'),
('delivery', 'wa_address', 'bn', 'ঠিকানা', 'ঠিকানার ক্ষেত্র'),
('delivery', 'wa_address', 'ar', 'العنوان', 'حقل العنوان'),
('delivery', 'wa_address', 'ru', 'Адрес', 'Поле адреса'),
('delivery', 'wa_address', 'ua', 'Адреса', 'Поле адреси'),
('delivery', 'wa_address', 'cn', '地址', '地址字段'),
('delivery', 'wa_address', 'in', 'पता', 'पता फ़ील्ड'),
('delivery', 'wa_address', 'nl', 'Adres', 'Adresveld'),
('delivery', 'wa_address', 'sv', 'Adress', 'Adressfält'),
('delivery', 'wa_address', 'pl', 'Adres', 'Pole adresu'),
('delivery', 'wa_address', 'tr', 'Adres', 'Adres alanı'),
('delivery', 'wa_address', 'zh', '地址', '地址字段'),
('delivery', 'wa_address', 'ko', '주소', '주소 필드');

-- wa_phone (Campo teléfono)
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('delivery', 'wa_phone', 'es', 'Teléfono', 'Campo teléfono'),
('delivery', 'wa_phone', 'en', 'Phone', 'Phone field'),
('delivery', 'wa_phone', 'fr', 'Téléphone', 'Champ téléphone'),
('delivery', 'wa_phone', 'de', 'Telefon', 'Telefon Feld'),
('delivery', 'wa_phone', 'it', 'Telefono', 'Campo telefono'),
('delivery', 'wa_phone', 'pt', 'Telefone', 'Campo telefone'),
('delivery', 'wa_phone', 'kr', '전화', '전화 필드'),
('delivery', 'wa_phone', 'ja', '電話', '電話欄'),
('delivery', 'wa_phone', 'bn', 'ফোন', 'ফোন ক্ষেত্র'),
('delivery', 'wa_phone', 'ar', 'الهاتف', 'حقل الهاتف'),
('delivery', 'wa_phone', 'ru', 'Телефон', 'Поле телефона'),
('delivery', 'wa_phone', 'ua', 'Телефон', 'Поле телефону'),
('delivery', 'wa_phone', 'cn', '电话', '电话字段'),
('delivery', 'wa_phone', 'in', 'फ़ोन', 'फ़ोन फ़ील्ड'),
('delivery', 'wa_phone', 'nl', 'Telefoon', 'Telefoonveld'),
('delivery', 'wa_phone', 'sv', 'Telefon', 'Telefonfält'),
('delivery', 'wa_phone', 'pl', 'Telefon', 'Pole telefonu'),
('delivery', 'wa_phone', 'tr', 'Telefon', 'Telefon alanı'),
('delivery', 'wa_phone', 'zh', '電話', '電話字段'),
('delivery', 'wa_phone', 'ko', '전화', '전화 필드');

-- wa_complete (Placeholder para completar)
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('delivery', 'wa_complete', 'es', '[completar]', 'Placeholder'),
('delivery', 'wa_complete', 'en', '[to complete]', 'Placeholder'),
('delivery', 'wa_complete', 'fr', '[à compléter]', 'Placeholder'),
('delivery', 'wa_complete', 'de', '[auszufüllen]', 'Platzhalter'),
('delivery', 'wa_complete', 'it', '[da completare]', 'Placeholder'),
('delivery', 'wa_complete', 'pt', '[a completar]', 'Placeholder'),
('delivery', 'wa_complete', 'kr', '[작성 필요]', '플레이스홀더'),
('delivery', 'wa_complete', 'ja', '[記入してください]', 'プレースホルダー'),
('delivery', 'wa_complete', 'bn', '[সম্পূর্ণ করুন]', 'প্লেসহোল্ডার'),
('delivery', 'wa_complete', 'ar', '[للإكمال]', 'عنصر نائب'),
('delivery', 'wa_complete', 'ru', '[заполнить]', 'Заполнитель'),
('delivery', 'wa_complete', 'ua', '[заповнити]', 'Заповнювач'),
('delivery', 'wa_complete', 'cn', '[待填写]', '占位符'),
('delivery', 'wa_complete', 'in', '[पूरा करें]', 'प्लेसहोल्डर'),
('delivery', 'wa_complete', 'nl', '[in te vullen]', 'Placeholder'),
('delivery', 'wa_complete', 'sv', '[att fylla i]', 'Platshållare'),
('delivery', 'wa_complete', 'pl', '[do uzupełnienia]', 'Placeholder'),
('delivery', 'wa_complete', 'tr', '[doldurulacak]', 'Yer tutucu'),
('delivery', 'wa_complete', 'zh', '[待填寫]', '佔位符'),
('delivery', 'wa_complete', 'ko', '[작성 필요]', '플레이스홀더');
