-- =====================================================
-- MIGRATION 0083: Catálogo global de categorías de info del guidebook
-- =====================================================
-- Por qué: las guías son únicas por apartamento (las instrucciones de la
-- lavadora no son iguales en dos pisos), pero hoy eso obligaba a duplicar
-- TAMBIÉN lo que no es único — cada bloque de guide_apartment_info guardaba
-- su propio título en 13 idiomas y su propia imagen en R2. Resultado real
-- verificado en producción antes de escribir esto: la info del apartamento
-- solo existe en 2-4 idiomas (0 migraciones de translations tocan
-- entity_type='apartment_info', a diferencia de las 6 que sí traducen POIs),
-- mientras los POIs sí están en los 13.
--
-- Esta migración introduce un catálogo global de categorías (icono + color +
-- nombre traducido UNA VEZ para toda la plataforma) para que el título deje
-- de ser contenido único por apartamento. Lo único que sigue siendo único
-- por apartamento es el texto (guide_apartment_info + translations.content),
-- que es lo que genuinamente varía de un piso a otro.
--
-- 58 categorías en 9 grupos (arrival, connectivity, comfort, appliances,
-- house, outdoor, safety, nearby, hotel) + 1 catch-all ('other' — solo
-- contiene 'custom', para no forzarlo dentro de un grupo temático al que no
-- pertenece; con esto la UI del admin puede pintar 9 secciones temáticas más
-- un "Otro" al final).
--
-- Las 9 claves reales usadas hoy en producción (verificado con
-- SELECT info_key, COUNT(*) FROM guide_apartment_info GROUP BY info_key
-- antes de escribir esta migración: wifi, rules, checkout, parking, trash,
-- transport, supermarket, emergency, checkin — 16 filas en total, incluyendo
-- 'transport' y 'supermarket' que NO estaban en AVAILABLE_KEYS del admin y
-- solo pudieron crearse por SQL directo) están TODAS cubiertas por el
-- catálogo, así que el backfill de category_key no deja huérfanos.
--
-- icon_name usa nombres de Material Symbols (la fuente que ya carga
-- apps/guide/index.html vía <span class="material-symbols-outlined">).
-- Si algún nombre no renderizara bien, es un UPDATE de una fila, no requiere
-- nueva migración.
--
-- color es el fallback visual por GRUPO (no por categoría individual) para
-- que el catálogo sea manejable: una paleta de 10 colores en vez de 58.
-- image_r2_key nace NULL a propósito: añadir fotos reales más adelante es
-- subir un objeto a R2 y un UPDATE, sin migración ni cambio de código.
--
-- Traducciones: 'name' (título visible para el huésped) va en los 13
-- idiomas activos — es imprescindible, es lo que reemplaza el título por
-- apartamento. 'hint' (ayuda solo para el anfitrión al elegir categoría en
-- el admin) va SOLO en 'es': es texto que nunca ve el huésped, el admin no
-- tiene selector de idioma propio, y el negocio opera en español (ver
-- CLAUDE.md) — traducirlo a 13 idiomas sería puro peso en D1 sin lector.
-- Se puede ampliar con más INSERT sueltos el día que el admin tenga su
-- propio i18n, sin tocar el resto del esquema.
--
-- guide_apartment_info gana dos columnas:
--   category_key      -> referencia al catálogo. Backfill: category_key =
--                         info_key (las claves existentes son idénticas a
--                         las del catálogo, ver arriba).
--   use_custom_title   -> FALSE por defecto: el título lo pone la categoría
--                         y no hay nada que traducir. Si el anfitrión escribe
--                         un título propio pasa a TRUE y ENTONCES sí entra en
--                         translations.title como hoy.
-- Se conservan info_key, UNIQUE(apartment_id, info_key) y el id determinista
-- info_${aptId}_${info_key} (workerGuideAdmin.js) — nada de esto rompe
-- traducciones de content ya guardadas.
-- =====================================================

CREATE TABLE IF NOT EXISTS guide_info_categories (
  key           TEXT PRIMARY KEY,
  group_key     TEXT NOT NULL,
  icon_name     TEXT NOT NULL,
  color         TEXT NOT NULL,
  image_r2_key  TEXT,
  order_index   INTEGER DEFAULT 0,
  is_active     BOOLEAN DEFAULT TRUE,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_guide_info_categories_group ON guide_info_categories(group_key, order_index);

-- ---------------------------------------------------------
-- Catálogo (58 categorías)
-- ---------------------------------------------------------
INSERT OR IGNORE INTO guide_info_categories (key, group_key, icon_name, color, order_index) VALUES
('checkin', 'arrival', 'login', '#2563EB', 10),
('door_code', 'arrival', 'key', '#2563EB', 20),
('checkout', 'arrival', 'logout', '#2563EB', 30),
('parking', 'arrival', 'local_parking', '#2563EB', 40),
('luggage', 'arrival', 'luggage', '#2563EB', 50),
('directions', 'arrival', 'directions', '#2563EB', 60),
('wifi', 'connectivity', 'wifi', '#7C3AED', 70),
('tv', 'connectivity', 'tv', '#7C3AED', 80),
('sound_system', 'connectivity', 'speaker', '#7C3AED', 90),
('air_conditioning', 'comfort', 'ac_unit', '#0891B2', 100),
('heating', 'comfort', 'thermostat', '#0891B2', 110),
('hot_water', 'comfort', 'water_drop', '#0891B2', 120),
('blinds', 'comfort', 'blinds', '#0891B2', 130),
('fireplace', 'comfort', 'fireplace', '#0891B2', 140),
('washing_machine', 'appliances', 'local_laundry_service', '#C2410C', 150),
('dryer', 'appliances', 'dry_cleaning', '#C2410C', 160),
('dishwasher', 'appliances', 'soap', '#C2410C', 170),
('oven', 'appliances', 'oven', '#C2410C', 180),
('hob', 'appliances', 'countertops', '#C2410C', 190),
('microwave', 'appliances', 'microwave', '#C2410C', 200),
('coffee_machine', 'appliances', 'coffee_maker', '#C2410C', 210),
('fridge', 'appliances', 'kitchen', '#C2410C', 220),
('extractor_hood', 'appliances', 'air', '#C2410C', 230),
('iron', 'appliances', 'iron', '#C2410C', 240),
('appliances', 'appliances', 'kitchen', '#C2410C', 250),
('trash', 'house', 'delete', '#64748B', 260),
('electricity', 'house', 'bolt', '#64748B', 270),
('water', 'house', 'plumbing', '#64748B', 280),
('rules', 'house', 'gavel', '#64748B', 290),
('noise', 'house', 'volume_off', '#64748B', 300),
('smoking', 'house', 'smoke_free', '#64748B', 310),
('pets', 'house', 'pets', '#64748B', 320),
('linens', 'house', 'bed', '#64748B', 330),
('cleaning', 'house', 'cleaning_services', '#64748B', 340),
('elevator', 'house', 'elevator', '#64748B', 350),
('safe', 'house', 'lock', '#64748B', 360),
('pool', 'outdoor', 'pool', '#16A34A', 370),
('jacuzzi', 'outdoor', 'hot_tub', '#16A34A', 380),
('bbq', 'outdoor', 'outdoor_grill', '#16A34A', 390),
('terrace', 'outdoor', 'deck', '#16A34A', 400),
('garden', 'outdoor', 'yard', '#16A34A', 410),
('gym', 'outdoor', 'fitness_center', '#16A34A', 420),
('beach', 'outdoor', 'beach_access', '#16A34A', 430),
('bikes', 'outdoor', 'directions_bike', '#16A34A', 440),
('emergency', 'safety', 'emergency', '#DC2626', 450),
('host_contact', 'safety', 'call', '#DC2626', 460),
('first_aid', 'safety', 'medical_services', '#DC2626', 470),
('fire_safety', 'safety', 'local_fire_department', '#DC2626', 480),
('supermarket', 'nearby', 'local_grocery_store', '#CA8A04', 490),
('pharmacy', 'nearby', 'local_pharmacy', '#CA8A04', 500),
('transport', 'nearby', 'directions_bus', '#CA8A04', 510),
('taxi', 'nearby', 'local_taxi', '#CA8A04', 520),
('atm', 'nearby', 'local_atm', '#CA8A04', 530),
('reception', 'hotel', 'front_desk', '#DB2777', 540),
('breakfast', 'hotel', 'free_breakfast', '#DB2777', 550),
('housekeeping', 'hotel', 'cleaning_services', '#DB2777', 560),
('room_service', 'hotel', 'room_service', '#DB2777', 570),
('custom', 'other', 'info', '#78716C', 580);

-- ---------------------------------------------------------
-- Traducciones: name (13 idiomas, guest-facing) + hint (solo es, admin-facing)
-- ---------------------------------------------------------
INSERT OR IGNORE INTO translations (entity_id, entity_type, language_code, field, value) VALUES
('checkin', 'info_category', 'es', 'hint', 'Cómo entrar en el alojamiento y hora de llegada.'),
('checkin', 'info_category', 'es', 'name', 'Check-in'),
('checkin', 'info_category', 'en', 'name', 'Check-in'),
('checkin', 'info_category', 'fr', 'name', 'Arrivée'),
('checkin', 'info_category', 'de', 'name', 'Check-in'),
('checkin', 'info_category', 'it', 'name', 'Check-in'),
('checkin', 'info_category', 'pt', 'name', 'Check-in'),
('checkin', 'info_category', 'ca', 'name', 'Check-in'),
('checkin', 'info_category', 'ar', 'name', 'تسجيل الوصول'),
('checkin', 'info_category', 'ru', 'name', 'Заезд'),
('checkin', 'info_category', 'uk', 'name', 'Заїзд'),
('checkin', 'info_category', 'zh', 'name', '入住'),
('checkin', 'info_category', 'ja', 'name', 'チェックイン'),
('checkin', 'info_category', 'ko', 'name', '체크인'),
('door_code', 'info_category', 'es', 'hint', 'El código de la puerta o de la caja de llaves. No se traduce el número.'),
('door_code', 'info_category', 'es', 'name', 'Código de acceso'),
('door_code', 'info_category', 'en', 'name', 'Entry Code'),
('door_code', 'info_category', 'fr', 'name', 'Code d''accès'),
('door_code', 'info_category', 'de', 'name', 'Zugangscode'),
('door_code', 'info_category', 'it', 'name', 'Codice d''accesso'),
('door_code', 'info_category', 'pt', 'name', 'Código de acesso'),
('door_code', 'info_category', 'ca', 'name', 'Codi d''accés'),
('door_code', 'info_category', 'ar', 'name', 'رمز الدخول'),
('door_code', 'info_category', 'ru', 'name', 'Код доступа'),
('door_code', 'info_category', 'uk', 'name', 'Код доступу'),
('door_code', 'info_category', 'zh', 'name', '门禁密码'),
('door_code', 'info_category', 'ja', 'name', '入室コード'),
('door_code', 'info_category', 'ko', 'name', '출입 코드'),
('checkout', 'info_category', 'es', 'hint', 'Hora límite de salida y qué hacer con las llaves.'),
('checkout', 'info_category', 'es', 'name', 'Check-out'),
('checkout', 'info_category', 'en', 'name', 'Check-out'),
('checkout', 'info_category', 'fr', 'name', 'Départ'),
('checkout', 'info_category', 'de', 'name', 'Check-out'),
('checkout', 'info_category', 'it', 'name', 'Check-out'),
('checkout', 'info_category', 'pt', 'name', 'Check-out'),
('checkout', 'info_category', 'ca', 'name', 'Check-out'),
('checkout', 'info_category', 'ar', 'name', 'تسجيل المغادرة'),
('checkout', 'info_category', 'ru', 'name', 'Выезд'),
('checkout', 'info_category', 'uk', 'name', 'Виїзд'),
('checkout', 'info_category', 'zh', 'name', '退房'),
('checkout', 'info_category', 'ja', 'name', 'チェックアウト'),
('checkout', 'info_category', 'ko', 'name', '체크아웃'),
('parking', 'info_category', 'es', 'hint', 'Dónde aparcar y si tiene coste.'),
('parking', 'info_category', 'es', 'name', 'Parking'),
('parking', 'info_category', 'en', 'name', 'Parking'),
('parking', 'info_category', 'fr', 'name', 'Parking'),
('parking', 'info_category', 'de', 'name', 'Parkplatz'),
('parking', 'info_category', 'it', 'name', 'Parcheggio'),
('parking', 'info_category', 'pt', 'name', 'Estacionamento'),
('parking', 'info_category', 'ca', 'name', 'Pàrquing'),
('parking', 'info_category', 'ar', 'name', 'موقف السيارات'),
('parking', 'info_category', 'ru', 'name', 'Парковка'),
('parking', 'info_category', 'uk', 'name', 'Парковка'),
('parking', 'info_category', 'zh', 'name', '停车场'),
('parking', 'info_category', 'ja', 'name', '駐車場'),
('parking', 'info_category', 'ko', 'name', '주차장'),
('luggage', 'info_category', 'es', 'hint', 'Consigna de equipaje antes del check-in o después del check-out.'),
('luggage', 'info_category', 'es', 'name', 'Equipaje'),
('luggage', 'info_category', 'en', 'name', 'Luggage'),
('luggage', 'info_category', 'fr', 'name', 'Bagages'),
('luggage', 'info_category', 'de', 'name', 'Gepäck'),
('luggage', 'info_category', 'it', 'name', 'Bagagli'),
('luggage', 'info_category', 'pt', 'name', 'Bagagem'),
('luggage', 'info_category', 'ca', 'name', 'Equipatge'),
('luggage', 'info_category', 'ar', 'name', 'الأمتعة'),
('luggage', 'info_category', 'ru', 'name', 'Багаж'),
('luggage', 'info_category', 'uk', 'name', 'Багаж'),
('luggage', 'info_category', 'zh', 'name', '行李'),
('luggage', 'info_category', 'ja', 'name', '荷物'),
('luggage', 'info_category', 'ko', 'name', '짐'),
('directions', 'info_category', 'es', 'hint', 'Cómo llegar desde el aeropuerto, estación o carretera.'),
('directions', 'info_category', 'es', 'name', 'Cómo llegar'),
('directions', 'info_category', 'en', 'name', 'Getting There'),
('directions', 'info_category', 'fr', 'name', 'Comment venir'),
('directions', 'info_category', 'de', 'name', 'Anfahrt'),
('directions', 'info_category', 'it', 'name', 'Come arrivare'),
('directions', 'info_category', 'pt', 'name', 'Como chegar'),
('directions', 'info_category', 'ca', 'name', 'Com arribar'),
('directions', 'info_category', 'ar', 'name', 'كيفية الوصول'),
('directions', 'info_category', 'ru', 'name', 'Как добраться'),
('directions', 'info_category', 'uk', 'name', 'Як дістатися'),
('directions', 'info_category', 'zh', 'name', '交通路线'),
('directions', 'info_category', 'ja', 'name', 'アクセス'),
('directions', 'info_category', 'ko', 'name', '오시는 길'),
('wifi', 'info_category', 'es', 'hint', 'Nombre de red y contraseña — mejor usa los campos de WiFi de Ajustes.'),
('wifi', 'info_category', 'es', 'name', 'WiFi'),
('wifi', 'info_category', 'en', 'name', 'WiFi'),
('wifi', 'info_category', 'fr', 'name', 'WiFi'),
('wifi', 'info_category', 'de', 'name', 'WLAN'),
('wifi', 'info_category', 'it', 'name', 'WiFi'),
('wifi', 'info_category', 'pt', 'name', 'WiFi'),
('wifi', 'info_category', 'ca', 'name', 'WiFi'),
('wifi', 'info_category', 'ar', 'name', 'واي فاي'),
('wifi', 'info_category', 'ru', 'name', 'WiFi'),
('wifi', 'info_category', 'uk', 'name', 'WiFi'),
('wifi', 'info_category', 'zh', 'name', 'WiFi'),
('wifi', 'info_category', 'ja', 'name', 'WiFi'),
('wifi', 'info_category', 'ko', 'name', '와이파이'),
('tv', 'info_category', 'es', 'hint', 'Mandos, apps de streaming y cómo iniciar sesión.'),
('tv', 'info_category', 'es', 'name', 'TV y streaming'),
('tv', 'info_category', 'en', 'name', 'TV & Streaming'),
('tv', 'info_category', 'fr', 'name', 'TV et streaming'),
('tv', 'info_category', 'de', 'name', 'TV & Streaming'),
('tv', 'info_category', 'it', 'name', 'TV e streaming'),
('tv', 'info_category', 'pt', 'name', 'TV e streaming'),
('tv', 'info_category', 'ca', 'name', 'TV i streaming'),
('tv', 'info_category', 'ar', 'name', 'التلفاز والبث'),
('tv', 'info_category', 'ru', 'name', 'ТВ и стриминг'),
('tv', 'info_category', 'uk', 'name', 'ТБ і стрімінг'),
('tv', 'info_category', 'zh', 'name', '电视与流媒体'),
('tv', 'info_category', 'ja', 'name', 'テレビ・配信'),
('tv', 'info_category', 'ko', 'name', 'TV 및 스트리밍'),
('sound_system', 'info_category', 'es', 'hint', 'Altavoz Bluetooth u otro equipo de música.'),
('sound_system', 'info_category', 'es', 'name', 'Altavoz / Música'),
('sound_system', 'info_category', 'en', 'name', 'Speaker / Music'),
('sound_system', 'info_category', 'fr', 'name', 'Enceinte / Musique'),
('sound_system', 'info_category', 'de', 'name', 'Lautsprecher / Musik'),
('sound_system', 'info_category', 'it', 'name', 'Altoparlante / Musica'),
('sound_system', 'info_category', 'pt', 'name', 'Coluna / Música'),
('sound_system', 'info_category', 'ca', 'name', 'Altaveu / Música'),
('sound_system', 'info_category', 'ar', 'name', 'مكبر الصوت / الموسيقى'),
('sound_system', 'info_category', 'ru', 'name', 'Колонка / Музыка'),
('sound_system', 'info_category', 'uk', 'name', 'Колонка / Музика'),
('sound_system', 'info_category', 'zh', 'name', '音箱／音乐'),
('sound_system', 'info_category', 'ja', 'name', 'スピーカー・音楽'),
('sound_system', 'info_category', 'ko', 'name', '스피커 / 음악'),
('air_conditioning', 'info_category', 'es', 'hint', 'Cómo encender el aire y usar el mando.'),
('air_conditioning', 'info_category', 'es', 'name', 'Aire acondicionado'),
('air_conditioning', 'info_category', 'en', 'name', 'Air Conditioning'),
('air_conditioning', 'info_category', 'fr', 'name', 'Climatisation'),
('air_conditioning', 'info_category', 'de', 'name', 'Klimaanlage'),
('air_conditioning', 'info_category', 'it', 'name', 'Aria condizionata'),
('air_conditioning', 'info_category', 'pt', 'name', 'Ar condicionado'),
('air_conditioning', 'info_category', 'ca', 'name', 'Aire condicionat'),
('air_conditioning', 'info_category', 'ar', 'name', 'تكييف الهواء'),
('air_conditioning', 'info_category', 'ru', 'name', 'Кондиционер'),
('air_conditioning', 'info_category', 'uk', 'name', 'Кондиціонер'),
('air_conditioning', 'info_category', 'zh', 'name', '空调'),
('air_conditioning', 'info_category', 'ja', 'name', 'エアコン'),
('air_conditioning', 'info_category', 'ko', 'name', '에어컨'),
('heating', 'info_category', 'es', 'hint', 'Cómo encender la calefacción y ajustar la temperatura.'),
('heating', 'info_category', 'es', 'name', 'Calefacción'),
('heating', 'info_category', 'en', 'name', 'Heating'),
('heating', 'info_category', 'fr', 'name', 'Chauffage'),
('heating', 'info_category', 'de', 'name', 'Heizung'),
('heating', 'info_category', 'it', 'name', 'Riscaldamento'),
('heating', 'info_category', 'pt', 'name', 'Aquecimento'),
('heating', 'info_category', 'ca', 'name', 'Calefacció'),
('heating', 'info_category', 'ar', 'name', 'التدفئة'),
('heating', 'info_category', 'ru', 'name', 'Отопление'),
('heating', 'info_category', 'uk', 'name', 'Опалення'),
('heating', 'info_category', 'zh', 'name', '暖气'),
('heating', 'info_category', 'ja', 'name', '暖房'),
('heating', 'info_category', 'ko', 'name', '난방'),
('hot_water', 'info_category', 'es', 'hint', 'Cómo funciona el termo y cuánto tarda en calentar.'),
('hot_water', 'info_category', 'es', 'name', 'Agua caliente'),
('hot_water', 'info_category', 'en', 'name', 'Hot Water'),
('hot_water', 'info_category', 'fr', 'name', 'Eau chaude'),
('hot_water', 'info_category', 'de', 'name', 'Warmwasser'),
('hot_water', 'info_category', 'it', 'name', 'Acqua calda'),
('hot_water', 'info_category', 'pt', 'name', 'Água quente'),
('hot_water', 'info_category', 'ca', 'name', 'Aigua calenta'),
('hot_water', 'info_category', 'ar', 'name', 'الماء الساخن'),
('hot_water', 'info_category', 'ru', 'name', 'Горячая вода'),
('hot_water', 'info_category', 'uk', 'name', 'Гаряча вода'),
('hot_water', 'info_category', 'zh', 'name', '热水'),
('hot_water', 'info_category', 'ja', 'name', 'お湯'),
('hot_water', 'info_category', 'ko', 'name', '온수'),
('blinds', 'info_category', 'es', 'hint', 'Cómo subir/bajar persianas o cerrar mosquiteras.'),
('blinds', 'info_category', 'es', 'name', 'Persianas y mosquiteras'),
('blinds', 'info_category', 'en', 'name', 'Blinds & Screens'),
('blinds', 'info_category', 'fr', 'name', 'Volets et moustiquaires'),
('blinds', 'info_category', 'de', 'name', 'Rollläden & Fliegengitter'),
('blinds', 'info_category', 'it', 'name', 'Tapparelle e zanzariere'),
('blinds', 'info_category', 'pt', 'name', 'Persianas e mosquiteiros'),
('blinds', 'info_category', 'ca', 'name', 'Persianes i mosquiteres'),
('blinds', 'info_category', 'ar', 'name', 'الستائر والشبك'),
('blinds', 'info_category', 'ru', 'name', 'Жалюзи и москитные сетки'),
('blinds', 'info_category', 'uk', 'name', 'Жалюзі та москітні сітки'),
('blinds', 'info_category', 'zh', 'name', '百叶窗与纱窗'),
('blinds', 'info_category', 'ja', 'name', 'ブラインド・網戸'),
('blinds', 'info_category', 'ko', 'name', '블라인드 및 방충망'),
('fireplace', 'info_category', 'es', 'hint', 'Cómo encender la chimenea o estufa de forma segura.'),
('fireplace', 'info_category', 'es', 'name', 'Chimenea / Estufa'),
('fireplace', 'info_category', 'en', 'name', 'Fireplace / Heater'),
('fireplace', 'info_category', 'fr', 'name', 'Cheminée / Poêle'),
('fireplace', 'info_category', 'de', 'name', 'Kamin / Ofen'),
('fireplace', 'info_category', 'it', 'name', 'Camino / Stufa'),
('fireplace', 'info_category', 'pt', 'name', 'Lareira / Aquecedor'),
('fireplace', 'info_category', 'ca', 'name', 'Xemeneia / Estufa'),
('fireplace', 'info_category', 'ar', 'name', 'المدفأة / السخان'),
('fireplace', 'info_category', 'ru', 'name', 'Камин / Обогреватель'),
('fireplace', 'info_category', 'uk', 'name', 'Камін / Обігрівач'),
('fireplace', 'info_category', 'zh', 'name', '壁炉／取暖器'),
('fireplace', 'info_category', 'ja', 'name', '暖炉・ヒーター'),
('fireplace', 'info_category', 'ko', 'name', '벽난로 / 히터'),
('washing_machine', 'info_category', 'es', 'hint', 'Programa recomendado y dónde está el detergente.'),
('washing_machine', 'info_category', 'es', 'name', 'Lavadora'),
('washing_machine', 'info_category', 'en', 'name', 'Washing Machine'),
('washing_machine', 'info_category', 'fr', 'name', 'Lave-linge'),
('washing_machine', 'info_category', 'de', 'name', 'Waschmaschine'),
('washing_machine', 'info_category', 'it', 'name', 'Lavatrice'),
('washing_machine', 'info_category', 'pt', 'name', 'Máquina de lavar'),
('washing_machine', 'info_category', 'ca', 'name', 'Rentadora'),
('washing_machine', 'info_category', 'ar', 'name', 'الغسالة'),
('washing_machine', 'info_category', 'ru', 'name', 'Стиральная машина'),
('washing_machine', 'info_category', 'uk', 'name', 'Пральна машина'),
('washing_machine', 'info_category', 'zh', 'name', '洗衣机'),
('washing_machine', 'info_category', 'ja', 'name', '洗濯機'),
('washing_machine', 'info_category', 'ko', 'name', '세탁기'),
('dryer', 'info_category', 'es', 'hint', 'Cómo usarla y dónde está el filtro de pelusa.'),
('dryer', 'info_category', 'es', 'name', 'Secadora'),
('dryer', 'info_category', 'en', 'name', 'Dryer'),
('dryer', 'info_category', 'fr', 'name', 'Sèche-linge'),
('dryer', 'info_category', 'de', 'name', 'Trockner'),
('dryer', 'info_category', 'it', 'name', 'Asciugatrice'),
('dryer', 'info_category', 'pt', 'name', 'Máquina de secar'),
('dryer', 'info_category', 'ca', 'name', 'Assecadora'),
('dryer', 'info_category', 'ar', 'name', 'مجفف الملابس'),
('dryer', 'info_category', 'ru', 'name', 'Сушильная машина'),
('dryer', 'info_category', 'uk', 'name', 'Сушильна машина'),
('dryer', 'info_category', 'zh', 'name', '烘干机'),
('dryer', 'info_category', 'ja', 'name', '乾燥機'),
('dryer', 'info_category', 'ko', 'name', '건조기'),
('dishwasher', 'info_category', 'es', 'hint', 'Programa recomendado y dónde está el detergente.'),
('dishwasher', 'info_category', 'es', 'name', 'Lavavajillas'),
('dishwasher', 'info_category', 'en', 'name', 'Dishwasher'),
('dishwasher', 'info_category', 'fr', 'name', 'Lave-vaisselle'),
('dishwasher', 'info_category', 'de', 'name', 'Geschirrspüler'),
('dishwasher', 'info_category', 'it', 'name', 'Lavastoviglie'),
('dishwasher', 'info_category', 'pt', 'name', 'Máquina de lavar loiça'),
('dishwasher', 'info_category', 'ca', 'name', 'Rentaplats'),
('dishwasher', 'info_category', 'ar', 'name', 'غسالة الأطباق'),
('dishwasher', 'info_category', 'ru', 'name', 'Посудомоечная машина'),
('dishwasher', 'info_category', 'uk', 'name', 'Посудомийна машина'),
('dishwasher', 'info_category', 'zh', 'name', '洗碗机'),
('dishwasher', 'info_category', 'ja', 'name', '食洗機'),
('dishwasher', 'info_category', 'ko', 'name', '식기세척기'),
('oven', 'info_category', 'es', 'hint', 'Cómo encenderlo y funciones básicas.'),
('oven', 'info_category', 'es', 'name', 'Horno'),
('oven', 'info_category', 'en', 'name', 'Oven'),
('oven', 'info_category', 'fr', 'name', 'Four'),
('oven', 'info_category', 'de', 'name', 'Backofen'),
('oven', 'info_category', 'it', 'name', 'Forno'),
('oven', 'info_category', 'pt', 'name', 'Forno'),
('oven', 'info_category', 'ca', 'name', 'Forn'),
('oven', 'info_category', 'ar', 'name', 'الفرن'),
('oven', 'info_category', 'ru', 'name', 'Духовка'),
('oven', 'info_category', 'uk', 'name', 'Духовка'),
('oven', 'info_category', 'zh', 'name', '烤箱'),
('oven', 'info_category', 'ja', 'name', 'オーブン'),
('oven', 'info_category', 'ko', 'name', '오븐'),
('hob', 'info_category', 'es', 'hint', 'Cómo encender los fuegos o zonas de inducción.'),
('hob', 'info_category', 'es', 'name', 'Vitrocerámica / Inducción'),
('hob', 'info_category', 'en', 'name', 'Stove / Hob'),
('hob', 'info_category', 'fr', 'name', 'Plaque de cuisson'),
('hob', 'info_category', 'de', 'name', 'Kochfeld'),
('hob', 'info_category', 'it', 'name', 'Piano cottura'),
('hob', 'info_category', 'pt', 'name', 'Placa / Fogão'),
('hob', 'info_category', 'ca', 'name', 'Vitroceràmica / Inducció'),
('hob', 'info_category', 'ar', 'name', 'موقد الطبخ'),
('hob', 'info_category', 'ru', 'name', 'Варочная панель'),
('hob', 'info_category', 'uk', 'name', 'Варильна поверхня'),
('hob', 'info_category', 'zh', 'name', '灶台'),
('hob', 'info_category', 'ja', 'name', 'コンロ'),
('hob', 'info_category', 'ko', 'name', '인덕션 / 쿡탑'),
('microwave', 'info_category', 'es', 'hint', 'Funciones básicas si no es evidente.'),
('microwave', 'info_category', 'es', 'name', 'Microondas'),
('microwave', 'info_category', 'en', 'name', 'Microwave'),
('microwave', 'info_category', 'fr', 'name', 'Micro-ondes'),
('microwave', 'info_category', 'de', 'name', 'Mikrowelle'),
('microwave', 'info_category', 'it', 'name', 'Microonde'),
('microwave', 'info_category', 'pt', 'name', 'Micro-ondas'),
('microwave', 'info_category', 'ca', 'name', 'Microones'),
('microwave', 'info_category', 'ar', 'name', 'الميكروويف'),
('microwave', 'info_category', 'ru', 'name', 'Микроволновая печь'),
('microwave', 'info_category', 'uk', 'name', 'Мікрохвильова піч'),
('microwave', 'info_category', 'zh', 'name', '微波炉'),
('microwave', 'info_category', 'ja', 'name', '電子レンジ'),
('microwave', 'info_category', 'ko', 'name', '전자레인지'),
('coffee_machine', 'info_category', 'es', 'hint', 'Cápsulas, molido o cafetera italiana — cómo usarla.'),
('coffee_machine', 'info_category', 'es', 'name', 'Cafetera'),
('coffee_machine', 'info_category', 'en', 'name', 'Coffee Machine'),
('coffee_machine', 'info_category', 'fr', 'name', 'Machine à café'),
('coffee_machine', 'info_category', 'de', 'name', 'Kaffeemaschine'),
('coffee_machine', 'info_category', 'it', 'name', 'Macchina del caffè'),
('coffee_machine', 'info_category', 'pt', 'name', 'Máquina de café'),
('coffee_machine', 'info_category', 'ca', 'name', 'Cafetera'),
('coffee_machine', 'info_category', 'ar', 'name', 'ماكينة القهوة'),
('coffee_machine', 'info_category', 'ru', 'name', 'Кофемашина'),
('coffee_machine', 'info_category', 'uk', 'name', 'Кавомашина'),
('coffee_machine', 'info_category', 'zh', 'name', '咖啡机'),
('coffee_machine', 'info_category', 'ja', 'name', 'コーヒーメーカー'),
('coffee_machine', 'info_category', 'ko', 'name', '커피 머신'),
('fridge', 'info_category', 'es', 'hint', 'Dónde está y cualquier detalle a tener en cuenta.'),
('fridge', 'info_category', 'es', 'name', 'Nevera'),
('fridge', 'info_category', 'en', 'name', 'Fridge'),
('fridge', 'info_category', 'fr', 'name', 'Réfrigérateur'),
('fridge', 'info_category', 'de', 'name', 'Kühlschrank'),
('fridge', 'info_category', 'it', 'name', 'Frigorifero'),
('fridge', 'info_category', 'pt', 'name', 'Frigorífico'),
('fridge', 'info_category', 'ca', 'name', 'Nevera'),
('fridge', 'info_category', 'ar', 'name', 'الثلاجة'),
('fridge', 'info_category', 'ru', 'name', 'Холодильник'),
('fridge', 'info_category', 'uk', 'name', 'Холодильник'),
('fridge', 'info_category', 'zh', 'name', '冰箱'),
('fridge', 'info_category', 'ja', 'name', '冷蔵庫'),
('fridge', 'info_category', 'ko', 'name', '냉장고'),
('extractor_hood', 'info_category', 'es', 'hint', 'Cómo encenderla al cocinar.'),
('extractor_hood', 'info_category', 'es', 'name', 'Campana extractora'),
('extractor_hood', 'info_category', 'en', 'name', 'Extractor Hood'),
('extractor_hood', 'info_category', 'fr', 'name', 'Hotte aspirante'),
('extractor_hood', 'info_category', 'de', 'name', 'Dunstabzugshaube'),
('extractor_hood', 'info_category', 'it', 'name', 'Cappa aspirante'),
('extractor_hood', 'info_category', 'pt', 'name', 'Exaustor'),
('extractor_hood', 'info_category', 'ca', 'name', 'Campana extractora'),
('extractor_hood', 'info_category', 'ar', 'name', 'شفاط المطبخ'),
('extractor_hood', 'info_category', 'ru', 'name', 'Вытяжка'),
('extractor_hood', 'info_category', 'uk', 'name', 'Витяжка'),
('extractor_hood', 'info_category', 'zh', 'name', '抽油烟机'),
('extractor_hood', 'info_category', 'ja', 'name', 'レンジフード'),
('extractor_hood', 'info_category', 'ko', 'name', '후드'),
('iron', 'info_category', 'es', 'hint', 'Dónde está la plancha y la tabla.'),
('iron', 'info_category', 'es', 'name', 'Plancha'),
('iron', 'info_category', 'en', 'name', 'Iron'),
('iron', 'info_category', 'fr', 'name', 'Fer à repasser'),
('iron', 'info_category', 'de', 'name', 'Bügeleisen'),
('iron', 'info_category', 'it', 'name', 'Ferro da stiro'),
('iron', 'info_category', 'pt', 'name', 'Ferro de engomar'),
('iron', 'info_category', 'ca', 'name', 'Planxa'),
('iron', 'info_category', 'ar', 'name', 'المكواة'),
('iron', 'info_category', 'ru', 'name', 'Утюг'),
('iron', 'info_category', 'uk', 'name', 'Праска'),
('iron', 'info_category', 'zh', 'name', '熨斗'),
('iron', 'info_category', 'ja', 'name', 'アイロン'),
('iron', 'info_category', 'ko', 'name', '다리미'),
('appliances', 'info_category', 'es', 'hint', 'Categoría genérica si no encaja en ninguna específica.'),
('appliances', 'info_category', 'es', 'name', 'Electrodomésticos'),
('appliances', 'info_category', 'en', 'name', 'Appliances'),
('appliances', 'info_category', 'fr', 'name', 'Électroménager'),
('appliances', 'info_category', 'de', 'name', 'Haushaltsgeräte'),
('appliances', 'info_category', 'it', 'name', 'Elettrodomestici'),
('appliances', 'info_category', 'pt', 'name', 'Eletrodomésticos'),
('appliances', 'info_category', 'ca', 'name', 'Electrodomèstics'),
('appliances', 'info_category', 'ar', 'name', 'الأجهزة المنزلية'),
('appliances', 'info_category', 'ru', 'name', 'Бытовая техника'),
('appliances', 'info_category', 'uk', 'name', 'Побутова техніка'),
('appliances', 'info_category', 'zh', 'name', '家用电器'),
('appliances', 'info_category', 'ja', 'name', '家電製品'),
('appliances', 'info_category', 'ko', 'name', '가전제품'),
('trash', 'info_category', 'es', 'hint', 'Dónde están los contenedores y cómo separar.'),
('trash', 'info_category', 'es', 'name', 'Basura y reciclaje'),
('trash', 'info_category', 'en', 'name', 'Trash & Recycling'),
('trash', 'info_category', 'fr', 'name', 'Déchets et recyclage'),
('trash', 'info_category', 'de', 'name', 'Müll & Recycling'),
('trash', 'info_category', 'it', 'name', 'Rifiuti e riciclo'),
('trash', 'info_category', 'pt', 'name', 'Lixo e reciclagem'),
('trash', 'info_category', 'ca', 'name', 'Escombraries i reciclatge'),
('trash', 'info_category', 'ar', 'name', 'القمامة وإعادة التدوير'),
('trash', 'info_category', 'ru', 'name', 'Мусор и переработка'),
('trash', 'info_category', 'uk', 'name', 'Сміття та переробка'),
('trash', 'info_category', 'zh', 'name', '垃圾与回收'),
('trash', 'info_category', 'ja', 'name', 'ゴミ・リサイクル'),
('trash', 'info_category', 'ko', 'name', '쓰레기 및 재활용'),
('electricity', 'info_category', 'es', 'hint', 'Dónde está el cuadro y qué hacer si salta la luz.'),
('electricity', 'info_category', 'es', 'name', 'Cuadro eléctrico'),
('electricity', 'info_category', 'en', 'name', 'Fuse Box'),
('electricity', 'info_category', 'fr', 'name', 'Tableau électrique'),
('electricity', 'info_category', 'de', 'name', 'Sicherungskasten'),
('electricity', 'info_category', 'it', 'name', 'Quadro elettrico'),
('electricity', 'info_category', 'pt', 'name', 'Quadro elétrico'),
('electricity', 'info_category', 'ca', 'name', 'Quadre elèctric'),
('electricity', 'info_category', 'ar', 'name', 'لوحة الكهرباء'),
('electricity', 'info_category', 'ru', 'name', 'Электрощиток'),
('electricity', 'info_category', 'uk', 'name', 'Електрощит'),
('electricity', 'info_category', 'zh', 'name', '配电箱'),
('electricity', 'info_category', 'ja', 'name', 'ブレーカー'),
('electricity', 'info_category', 'ko', 'name', '두꺼비집'),
('water', 'info_category', 'es', 'hint', 'Llave de paso general, por si hay una fuga.'),
('water', 'info_category', 'es', 'name', 'Agua y llave de paso'),
('water', 'info_category', 'en', 'name', 'Water & Main Valve'),
('water', 'info_category', 'fr', 'name', 'Eau et robinet d''arrêt'),
('water', 'info_category', 'de', 'name', 'Wasser & Absperrhahn'),
('water', 'info_category', 'it', 'name', 'Acqua e rubinetto principale'),
('water', 'info_category', 'pt', 'name', 'Água e torneira geral'),
('water', 'info_category', 'ca', 'name', 'Aigua i clau de pas'),
('water', 'info_category', 'ar', 'name', 'المياه وصمام الإغلاق'),
('water', 'info_category', 'ru', 'name', 'Вода и запорный кран'),
('water', 'info_category', 'uk', 'name', 'Вода і запірний кран'),
('water', 'info_category', 'zh', 'name', '水源总阀'),
('water', 'info_category', 'ja', 'name', '水道の元栓'),
('water', 'info_category', 'ko', 'name', '수도 및 밸브'),
('rules', 'info_category', 'es', 'hint', 'Normas de convivencia: ruido, fiestas, número de huéspedes...'),
('rules', 'info_category', 'es', 'name', 'Normas de la casa'),
('rules', 'info_category', 'en', 'name', 'House Rules'),
('rules', 'info_category', 'fr', 'name', 'Règlement intérieur'),
('rules', 'info_category', 'de', 'name', 'Hausordnung'),
('rules', 'info_category', 'it', 'name', 'Regole della casa'),
('rules', 'info_category', 'pt', 'name', 'Regras da casa'),
('rules', 'info_category', 'ca', 'name', 'Normes de la casa'),
('rules', 'info_category', 'ar', 'name', 'قواعد المنزل'),
('rules', 'info_category', 'ru', 'name', 'Правила дома'),
('rules', 'info_category', 'uk', 'name', 'Правила дому'),
('rules', 'info_category', 'zh', 'name', '房屋守则'),
('rules', 'info_category', 'ja', 'name', 'ハウスルール'),
('rules', 'info_category', 'ko', 'name', '하우스 룰'),
('noise', 'info_category', 'es', 'hint', 'Horario de silencio y normas con los vecinos.'),
('noise', 'info_category', 'es', 'name', 'Ruido y silencio'),
('noise', 'info_category', 'en', 'name', 'Noise & Quiet Hours'),
('noise', 'info_category', 'fr', 'name', 'Bruit et heures calmes'),
('noise', 'info_category', 'de', 'name', 'Lärm & Ruhezeiten'),
('noise', 'info_category', 'it', 'name', 'Rumore e orari di silenzio'),
('noise', 'info_category', 'pt', 'name', 'Ruído e horário de silêncio'),
('noise', 'info_category', 'ca', 'name', 'Soroll i horari de silenci'),
('noise', 'info_category', 'ar', 'name', 'الضوضاء وساعات الهدوء'),
('noise', 'info_category', 'ru', 'name', 'Шум и тихие часы'),
('noise', 'info_category', 'uk', 'name', 'Шум і тихі години'),
('noise', 'info_category', 'zh', 'name', '噪音与安静时段'),
('noise', 'info_category', 'ja', 'name', '騒音・静粛時間'),
('noise', 'info_category', 'ko', 'name', '소음 및 정숙 시간'),
('smoking', 'info_category', 'es', 'hint', 'Política de fumadores dentro y fuera.'),
('smoking', 'info_category', 'es', 'name', 'Fumar'),
('smoking', 'info_category', 'en', 'name', 'Smoking'),
('smoking', 'info_category', 'fr', 'name', 'Fumer'),
('smoking', 'info_category', 'de', 'name', 'Rauchen'),
('smoking', 'info_category', 'it', 'name', 'Fumare'),
('smoking', 'info_category', 'pt', 'name', 'Fumar'),
('smoking', 'info_category', 'ca', 'name', 'Fumar'),
('smoking', 'info_category', 'ar', 'name', 'التدخين'),
('smoking', 'info_category', 'ru', 'name', 'Курение'),
('smoking', 'info_category', 'uk', 'name', 'Куріння'),
('smoking', 'info_category', 'zh', 'name', '吸烟'),
('smoking', 'info_category', 'ja', 'name', '喫煙'),
('smoking', 'info_category', 'ko', 'name', '흡연'),
('pets', 'info_category', 'es', 'hint', 'Si se permiten mascotas y en qué condiciones.'),
('pets', 'info_category', 'es', 'name', 'Mascotas'),
('pets', 'info_category', 'en', 'name', 'Pets'),
('pets', 'info_category', 'fr', 'name', 'Animaux'),
('pets', 'info_category', 'de', 'name', 'Haustiere'),
('pets', 'info_category', 'it', 'name', 'Animali domestici'),
('pets', 'info_category', 'pt', 'name', 'Animais de estimação'),
('pets', 'info_category', 'ca', 'name', 'Mascotes'),
('pets', 'info_category', 'ar', 'name', 'الحيوانات الأليفة'),
('pets', 'info_category', 'ru', 'name', 'Животные'),
('pets', 'info_category', 'uk', 'name', 'Тварини'),
('pets', 'info_category', 'zh', 'name', '宠物'),
('pets', 'info_category', 'ja', 'name', 'ペット'),
('pets', 'info_category', 'ko', 'name', '반려동물'),
('linens', 'info_category', 'es', 'hint', 'Dónde están toallas y sábanas de repuesto.'),
('linens', 'info_category', 'es', 'name', 'Toallas y ropa de cama'),
('linens', 'info_category', 'en', 'name', 'Towels & Linens'),
('linens', 'info_category', 'fr', 'name', 'Serviettes et linge de lit'),
('linens', 'info_category', 'de', 'name', 'Handtücher & Bettwäsche'),
('linens', 'info_category', 'it', 'name', 'Asciugamani e biancheria'),
('linens', 'info_category', 'pt', 'name', 'Toalhas e roupa de cama'),
('linens', 'info_category', 'ca', 'name', 'Tovalloles i roba de llit'),
('linens', 'info_category', 'ar', 'name', 'المناشف وأغطية السرير'),
('linens', 'info_category', 'ru', 'name', 'Полотенца и постельное белье'),
('linens', 'info_category', 'uk', 'name', 'Рушники та постільна білизна'),
('linens', 'info_category', 'zh', 'name', '毛巾与床上用品'),
('linens', 'info_category', 'ja', 'name', 'タオル・寝具'),
('linens', 'info_category', 'ko', 'name', '수건 및 침구'),
('cleaning', 'info_category', 'es', 'hint', 'Productos de limpieza disponibles y su ubicación.'),
('cleaning', 'info_category', 'es', 'name', 'Limpieza'),
('cleaning', 'info_category', 'en', 'name', 'Cleaning'),
('cleaning', 'info_category', 'fr', 'name', 'Ménage'),
('cleaning', 'info_category', 'de', 'name', 'Reinigung'),
('cleaning', 'info_category', 'it', 'name', 'Pulizia'),
('cleaning', 'info_category', 'pt', 'name', 'Limpeza'),
('cleaning', 'info_category', 'ca', 'name', 'Neteja'),
('cleaning', 'info_category', 'ar', 'name', 'التنظيف'),
('cleaning', 'info_category', 'ru', 'name', 'Уборка'),
('cleaning', 'info_category', 'uk', 'name', 'Прибирання'),
('cleaning', 'info_category', 'zh', 'name', '清洁'),
('cleaning', 'info_category', 'ja', 'name', '清掃'),
('cleaning', 'info_category', 'ko', 'name', '청소'),
('elevator', 'info_category', 'es', 'hint', 'Cómo usarlo si el edificio lo tiene.'),
('elevator', 'info_category', 'es', 'name', 'Ascensor'),
('elevator', 'info_category', 'en', 'name', 'Elevator'),
('elevator', 'info_category', 'fr', 'name', 'Ascenseur'),
('elevator', 'info_category', 'de', 'name', 'Aufzug'),
('elevator', 'info_category', 'it', 'name', 'Ascensore'),
('elevator', 'info_category', 'pt', 'name', 'Elevador'),
('elevator', 'info_category', 'ca', 'name', 'Ascensor'),
('elevator', 'info_category', 'ar', 'name', 'المصعد'),
('elevator', 'info_category', 'ru', 'name', 'Лифт'),
('elevator', 'info_category', 'uk', 'name', 'Ліфт'),
('elevator', 'info_category', 'zh', 'name', '电梯'),
('elevator', 'info_category', 'ja', 'name', 'エレベーター'),
('elevator', 'info_category', 'ko', 'name', '엘리베이터'),
('safe', 'info_category', 'es', 'hint', 'Ubicación y cómo usar la caja fuerte.'),
('safe', 'info_category', 'es', 'name', 'Caja fuerte'),
('safe', 'info_category', 'en', 'name', 'Safe'),
('safe', 'info_category', 'fr', 'name', 'Coffre-fort'),
('safe', 'info_category', 'de', 'name', 'Safe'),
('safe', 'info_category', 'it', 'name', 'Cassaforte'),
('safe', 'info_category', 'pt', 'name', 'Cofre'),
('safe', 'info_category', 'ca', 'name', 'Caixa forta'),
('safe', 'info_category', 'ar', 'name', 'الخزنة'),
('safe', 'info_category', 'ru', 'name', 'Сейф'),
('safe', 'info_category', 'uk', 'name', 'Сейф'),
('safe', 'info_category', 'zh', 'name', '保险箱'),
('safe', 'info_category', 'ja', 'name', '金庫'),
('safe', 'info_category', 'ko', 'name', '금고'),
('pool', 'info_category', 'es', 'hint', 'Horario, normas y profundidad de la piscina.'),
('pool', 'info_category', 'es', 'name', 'Piscina'),
('pool', 'info_category', 'en', 'name', 'Pool'),
('pool', 'info_category', 'fr', 'name', 'Piscine'),
('pool', 'info_category', 'de', 'name', 'Pool'),
('pool', 'info_category', 'it', 'name', 'Piscina'),
('pool', 'info_category', 'pt', 'name', 'Piscina'),
('pool', 'info_category', 'ca', 'name', 'Piscina'),
('pool', 'info_category', 'ar', 'name', 'المسبح'),
('pool', 'info_category', 'ru', 'name', 'Бассейн'),
('pool', 'info_category', 'uk', 'name', 'Басейн'),
('pool', 'info_category', 'zh', 'name', '泳池'),
('pool', 'info_category', 'ja', 'name', 'プール'),
('pool', 'info_category', 'ko', 'name', '수영장'),
('jacuzzi', 'info_category', 'es', 'hint', 'Cómo encenderlo y normas de uso.'),
('jacuzzi', 'info_category', 'es', 'name', 'Jacuzzi'),
('jacuzzi', 'info_category', 'en', 'name', 'Jacuzzi'),
('jacuzzi', 'info_category', 'fr', 'name', 'Jacuzzi'),
('jacuzzi', 'info_category', 'de', 'name', 'Jacuzzi'),
('jacuzzi', 'info_category', 'it', 'name', 'Idromassaggio'),
('jacuzzi', 'info_category', 'pt', 'name', 'Jacuzzi'),
('jacuzzi', 'info_category', 'ca', 'name', 'Jacuzzi'),
('jacuzzi', 'info_category', 'ar', 'name', 'جاكوزي'),
('jacuzzi', 'info_category', 'ru', 'name', 'Джакузи'),
('jacuzzi', 'info_category', 'uk', 'name', 'Джакузі'),
('jacuzzi', 'info_category', 'zh', 'name', '按摩浴缸'),
('jacuzzi', 'info_category', 'ja', 'name', 'ジャグジー'),
('jacuzzi', 'info_category', 'ko', 'name', '자쿠지'),
('bbq', 'info_category', 'es', 'hint', 'Cómo usar la barbacoa y dónde conseguir carbón/gas.'),
('bbq', 'info_category', 'es', 'name', 'Barbacoa'),
('bbq', 'info_category', 'en', 'name', 'BBQ'),
('bbq', 'info_category', 'fr', 'name', 'Barbecue'),
('bbq', 'info_category', 'de', 'name', 'Grill'),
('bbq', 'info_category', 'it', 'name', 'Barbecue'),
('bbq', 'info_category', 'pt', 'name', 'Churrasqueira'),
('bbq', 'info_category', 'ca', 'name', 'Barbacoa'),
('bbq', 'info_category', 'ar', 'name', 'الشواء'),
('bbq', 'info_category', 'ru', 'name', 'Барбекю'),
('bbq', 'info_category', 'uk', 'name', 'Барбекю'),
('bbq', 'info_category', 'zh', 'name', '烧烤架'),
('bbq', 'info_category', 'ja', 'name', 'バーベキュー'),
('bbq', 'info_category', 'ko', 'name', '바비큐'),
('terrace', 'info_category', 'es', 'hint', 'Uso de la terraza o balcón y normas si las hay.'),
('terrace', 'info_category', 'es', 'name', 'Terraza / Balcón'),
('terrace', 'info_category', 'en', 'name', 'Terrace / Balcony'),
('terrace', 'info_category', 'fr', 'name', 'Terrasse / Balcon'),
('terrace', 'info_category', 'de', 'name', 'Terrasse / Balkon'),
('terrace', 'info_category', 'it', 'name', 'Terrazza / Balcone'),
('terrace', 'info_category', 'pt', 'name', 'Terraço / Varanda'),
('terrace', 'info_category', 'ca', 'name', 'Terrassa / Balcó'),
('terrace', 'info_category', 'ar', 'name', 'التراس / الشرفة'),
('terrace', 'info_category', 'ru', 'name', 'Терраса / Балкон'),
('terrace', 'info_category', 'uk', 'name', 'Тераса / Балкон'),
('terrace', 'info_category', 'zh', 'name', '露台／阳台'),
('terrace', 'info_category', 'ja', 'name', 'テラス・バルコニー'),
('terrace', 'info_category', 'ko', 'name', '테라스 / 발코니'),
('garden', 'info_category', 'es', 'hint', 'Zonas ajardinadas y su uso.'),
('garden', 'info_category', 'es', 'name', 'Jardín'),
('garden', 'info_category', 'en', 'name', 'Garden'),
('garden', 'info_category', 'fr', 'name', 'Jardin'),
('garden', 'info_category', 'de', 'name', 'Garten'),
('garden', 'info_category', 'it', 'name', 'Giardino'),
('garden', 'info_category', 'pt', 'name', 'Jardim'),
('garden', 'info_category', 'ca', 'name', 'Jardí'),
('garden', 'info_category', 'ar', 'name', 'الحديقة'),
('garden', 'info_category', 'ru', 'name', 'Сад'),
('garden', 'info_category', 'uk', 'name', 'Сад'),
('garden', 'info_category', 'zh', 'name', '花园'),
('garden', 'info_category', 'ja', 'name', '庭'),
('garden', 'info_category', 'ko', 'name', '정원'),
('gym', 'info_category', 'es', 'hint', 'Horario y normas del gimnasio si el edificio lo tiene.'),
('gym', 'info_category', 'es', 'name', 'Gimnasio'),
('gym', 'info_category', 'en', 'name', 'Gym'),
('gym', 'info_category', 'fr', 'name', 'Salle de sport'),
('gym', 'info_category', 'de', 'name', 'Fitnessraum'),
('gym', 'info_category', 'it', 'name', 'Palestra'),
('gym', 'info_category', 'pt', 'name', 'Ginásio'),
('gym', 'info_category', 'ca', 'name', 'Gimnàs'),
('gym', 'info_category', 'ar', 'name', 'صالة الألعاب الرياضية'),
('gym', 'info_category', 'ru', 'name', 'Тренажёрный зал'),
('gym', 'info_category', 'uk', 'name', 'Тренажерний зал'),
('gym', 'info_category', 'zh', 'name', '健身房'),
('gym', 'info_category', 'ja', 'name', 'ジム'),
('gym', 'info_category', 'ko', 'name', '헬스장'),
('beach', 'info_category', 'es', 'hint', 'Sombrillas, toallas de playa y cómo llegar.'),
('beach', 'info_category', 'es', 'name', 'Playa'),
('beach', 'info_category', 'en', 'name', 'Beach'),
('beach', 'info_category', 'fr', 'name', 'Plage'),
('beach', 'info_category', 'de', 'name', 'Strand'),
('beach', 'info_category', 'it', 'name', 'Spiaggia'),
('beach', 'info_category', 'pt', 'name', 'Praia'),
('beach', 'info_category', 'ca', 'name', 'Platja'),
('beach', 'info_category', 'ar', 'name', 'الشاطئ'),
('beach', 'info_category', 'ru', 'name', 'Пляж'),
('beach', 'info_category', 'uk', 'name', 'Пляж'),
('beach', 'info_category', 'zh', 'name', '海滩'),
('beach', 'info_category', 'ja', 'name', 'ビーチ'),
('beach', 'info_category', 'ko', 'name', '해변'),
('bikes', 'info_category', 'es', 'hint', 'Si hay bicicletas disponibles y cómo usarlas.'),
('bikes', 'info_category', 'es', 'name', 'Bicicletas'),
('bikes', 'info_category', 'en', 'name', 'Bikes'),
('bikes', 'info_category', 'fr', 'name', 'Vélos'),
('bikes', 'info_category', 'de', 'name', 'Fahrräder'),
('bikes', 'info_category', 'it', 'name', 'Biciclette'),
('bikes', 'info_category', 'pt', 'name', 'Bicicletas'),
('bikes', 'info_category', 'ca', 'name', 'Bicicletes'),
('bikes', 'info_category', 'ar', 'name', 'الدراجات'),
('bikes', 'info_category', 'ru', 'name', 'Велосипеды'),
('bikes', 'info_category', 'uk', 'name', 'Велосипеди'),
('bikes', 'info_category', 'zh', 'name', '自行车'),
('bikes', 'info_category', 'ja', 'name', '自転車'),
('bikes', 'info_category', 'ko', 'name', '자전거'),
('emergency', 'info_category', 'es', 'hint', 'Teléfonos de emergencia: policía, sanidad, bomberos.'),
('emergency', 'info_category', 'es', 'name', 'Emergencias'),
('emergency', 'info_category', 'en', 'name', 'Emergency'),
('emergency', 'info_category', 'fr', 'name', 'Urgences'),
('emergency', 'info_category', 'de', 'name', 'Notfall'),
('emergency', 'info_category', 'it', 'name', 'Emergenze'),
('emergency', 'info_category', 'pt', 'name', 'Emergências'),
('emergency', 'info_category', 'ca', 'name', 'Emergències'),
('emergency', 'info_category', 'ar', 'name', 'الطوارئ'),
('emergency', 'info_category', 'ru', 'name', 'Экстренные службы'),
('emergency', 'info_category', 'uk', 'name', 'Екстрені служби'),
('emergency', 'info_category', 'zh', 'name', '紧急情况'),
('emergency', 'info_category', 'ja', 'name', '緊急時'),
('emergency', 'info_category', 'ko', 'name', '응급 상황'),
('host_contact', 'info_category', 'es', 'hint', 'Cómo contactar contigo durante la estancia.'),
('host_contact', 'info_category', 'es', 'name', 'Contacto del anfitrión'),
('host_contact', 'info_category', 'en', 'name', 'Host Contact'),
('host_contact', 'info_category', 'fr', 'name', 'Contact de l''hôte'),
('host_contact', 'info_category', 'de', 'name', 'Kontakt zum Gastgeber'),
('host_contact', 'info_category', 'it', 'name', 'Contatto dell''host'),
('host_contact', 'info_category', 'pt', 'name', 'Contacto do anfitrião'),
('host_contact', 'info_category', 'ca', 'name', 'Contacte de l''amfitrió'),
('host_contact', 'info_category', 'ar', 'name', 'التواصل مع المضيف'),
('host_contact', 'info_category', 'ru', 'name', 'Контакт хозяина'),
('host_contact', 'info_category', 'uk', 'name', 'Контакт господаря'),
('host_contact', 'info_category', 'zh', 'name', '房东联系方式'),
('host_contact', 'info_category', 'ja', 'name', 'ホストへの連絡先'),
('host_contact', 'info_category', 'ko', 'name', '호스트 연락처'),
('first_aid', 'info_category', 'es', 'hint', 'Dónde está el botiquín.'),
('first_aid', 'info_category', 'es', 'name', 'Botiquín'),
('first_aid', 'info_category', 'en', 'name', 'First Aid Kit'),
('first_aid', 'info_category', 'fr', 'name', 'Trousse de secours'),
('first_aid', 'info_category', 'de', 'name', 'Erste-Hilfe-Set'),
('first_aid', 'info_category', 'it', 'name', 'Kit di pronto soccorso'),
('first_aid', 'info_category', 'pt', 'name', 'Kit de primeiros socorros'),
('first_aid', 'info_category', 'ca', 'name', 'Farmaciola'),
('first_aid', 'info_category', 'ar', 'name', 'حقيبة الإسعافات الأولية'),
('first_aid', 'info_category', 'ru', 'name', 'Аптечка'),
('first_aid', 'info_category', 'uk', 'name', 'Аптечка'),
('first_aid', 'info_category', 'zh', 'name', '急救箱'),
('first_aid', 'info_category', 'ja', 'name', '救急箱'),
('first_aid', 'info_category', 'ko', 'name', '구급상자'),
('fire_safety', 'info_category', 'es', 'hint', 'Extintor, salida de emergencia y qué hacer en caso de incendio.'),
('fire_safety', 'info_category', 'es', 'name', 'Seguridad contra incendios'),
('fire_safety', 'info_category', 'en', 'name', 'Fire Safety'),
('fire_safety', 'info_category', 'fr', 'name', 'Sécurité incendie'),
('fire_safety', 'info_category', 'de', 'name', 'Brandschutz'),
('fire_safety', 'info_category', 'it', 'name', 'Sicurezza antincendio'),
('fire_safety', 'info_category', 'pt', 'name', 'Segurança contra incêndios'),
('fire_safety', 'info_category', 'ca', 'name', 'Seguretat contra incendis'),
('fire_safety', 'info_category', 'ar', 'name', 'السلامة من الحرائق'),
('fire_safety', 'info_category', 'ru', 'name', 'Пожарная безопасность'),
('fire_safety', 'info_category', 'uk', 'name', 'Пожежна безпека'),
('fire_safety', 'info_category', 'zh', 'name', '消防安全'),
('fire_safety', 'info_category', 'ja', 'name', '防火・消火'),
('fire_safety', 'info_category', 'ko', 'name', '화재 안전'),
('supermarket', 'info_category', 'es', 'hint', 'Supermercados cercanos y horarios.'),
('supermarket', 'info_category', 'es', 'name', 'Supermercado'),
('supermarket', 'info_category', 'en', 'name', 'Supermarket'),
('supermarket', 'info_category', 'fr', 'name', 'Supermarché'),
('supermarket', 'info_category', 'de', 'name', 'Supermarkt'),
('supermarket', 'info_category', 'it', 'name', 'Supermercato'),
('supermarket', 'info_category', 'pt', 'name', 'Supermercado'),
('supermarket', 'info_category', 'ca', 'name', 'Supermercat'),
('supermarket', 'info_category', 'ar', 'name', 'السوبر ماركت'),
('supermarket', 'info_category', 'ru', 'name', 'Супермаркет'),
('supermarket', 'info_category', 'uk', 'name', 'Супермаркет'),
('supermarket', 'info_category', 'zh', 'name', '超市'),
('supermarket', 'info_category', 'ja', 'name', 'スーパー'),
('supermarket', 'info_category', 'ko', 'name', '슈퍼마켓'),
('pharmacy', 'info_category', 'es', 'hint', 'Farmacia más cercana.'),
('pharmacy', 'info_category', 'es', 'name', 'Farmacia'),
('pharmacy', 'info_category', 'en', 'name', 'Pharmacy'),
('pharmacy', 'info_category', 'fr', 'name', 'Pharmacie'),
('pharmacy', 'info_category', 'de', 'name', 'Apotheke'),
('pharmacy', 'info_category', 'it', 'name', 'Farmacia'),
('pharmacy', 'info_category', 'pt', 'name', 'Farmácia'),
('pharmacy', 'info_category', 'ca', 'name', 'Farmàcia'),
('pharmacy', 'info_category', 'ar', 'name', 'الصيدلية'),
('pharmacy', 'info_category', 'ru', 'name', 'Аптека'),
('pharmacy', 'info_category', 'uk', 'name', 'Аптека'),
('pharmacy', 'info_category', 'zh', 'name', '药店'),
('pharmacy', 'info_category', 'ja', 'name', '薬局'),
('pharmacy', 'info_category', 'ko', 'name', '약국'),
('transport', 'info_category', 'es', 'hint', 'Líneas de autobús, metro o tren cercanas.'),
('transport', 'info_category', 'es', 'name', 'Transporte público'),
('transport', 'info_category', 'en', 'name', 'Public Transport'),
('transport', 'info_category', 'fr', 'name', 'Transports en commun'),
('transport', 'info_category', 'de', 'name', 'Öffentliche Verkehrsmittel'),
('transport', 'info_category', 'it', 'name', 'Trasporto pubblico'),
('transport', 'info_category', 'pt', 'name', 'Transporte público'),
('transport', 'info_category', 'ca', 'name', 'Transport públic'),
('transport', 'info_category', 'ar', 'name', 'النقل العام'),
('transport', 'info_category', 'ru', 'name', 'Общественный транспорт'),
('transport', 'info_category', 'uk', 'name', 'Громадський транспорт'),
('transport', 'info_category', 'zh', 'name', '公共交通'),
('transport', 'info_category', 'ja', 'name', '公共交通機関'),
('transport', 'info_category', 'ko', 'name', '대중교통'),
('taxi', 'info_category', 'es', 'hint', 'Cómo pedir un taxi o VTC en la zona.'),
('taxi', 'info_category', 'es', 'name', 'Taxi'),
('taxi', 'info_category', 'en', 'name', 'Taxi'),
('taxi', 'info_category', 'fr', 'name', 'Taxi'),
('taxi', 'info_category', 'de', 'name', 'Taxi'),
('taxi', 'info_category', 'it', 'name', 'Taxi'),
('taxi', 'info_category', 'pt', 'name', 'Táxi'),
('taxi', 'info_category', 'ca', 'name', 'Taxi'),
('taxi', 'info_category', 'ar', 'name', 'سيارة أجرة'),
('taxi', 'info_category', 'ru', 'name', 'Такси'),
('taxi', 'info_category', 'uk', 'name', 'Таксі'),
('taxi', 'info_category', 'zh', 'name', '出租车'),
('taxi', 'info_category', 'ja', 'name', 'タクシー'),
('taxi', 'info_category', 'ko', 'name', '택시'),
('atm', 'info_category', 'es', 'hint', 'Cajeros automáticos cercanos.'),
('atm', 'info_category', 'es', 'name', 'Cajero'),
('atm', 'info_category', 'en', 'name', 'ATM'),
('atm', 'info_category', 'fr', 'name', 'Distributeur'),
('atm', 'info_category', 'de', 'name', 'Geldautomat'),
('atm', 'info_category', 'it', 'name', 'Bancomat'),
('atm', 'info_category', 'pt', 'name', 'Multibanco'),
('atm', 'info_category', 'ca', 'name', 'Caixer'),
('atm', 'info_category', 'ar', 'name', 'الصراف الآلي'),
('atm', 'info_category', 'ru', 'name', 'Банкомат'),
('atm', 'info_category', 'uk', 'name', 'Банкомат'),
('atm', 'info_category', 'zh', 'name', '自动取款机'),
('atm', 'info_category', 'ja', 'name', 'ATM'),
('atm', 'info_category', 'ko', 'name', '현금인출기'),
('reception', 'info_category', 'es', 'hint', 'Horario y ubicación de recepción.'),
('reception', 'info_category', 'es', 'name', 'Recepción'),
('reception', 'info_category', 'en', 'name', 'Reception'),
('reception', 'info_category', 'fr', 'name', 'Réception'),
('reception', 'info_category', 'de', 'name', 'Rezeption'),
('reception', 'info_category', 'it', 'name', 'Reception'),
('reception', 'info_category', 'pt', 'name', 'Receção'),
('reception', 'info_category', 'ca', 'name', 'Recepció'),
('reception', 'info_category', 'ar', 'name', 'الاستقبال'),
('reception', 'info_category', 'ru', 'name', 'Ресепшен'),
('reception', 'info_category', 'uk', 'name', 'Ресепшн'),
('reception', 'info_category', 'zh', 'name', '前台'),
('reception', 'info_category', 'ja', 'name', 'フロント'),
('reception', 'info_category', 'ko', 'name', '리셉션'),
('breakfast', 'info_category', 'es', 'hint', 'Horario y ubicación del desayuno.'),
('breakfast', 'info_category', 'es', 'name', 'Desayuno'),
('breakfast', 'info_category', 'en', 'name', 'Breakfast'),
('breakfast', 'info_category', 'fr', 'name', 'Petit-déjeuner'),
('breakfast', 'info_category', 'de', 'name', 'Frühstück'),
('breakfast', 'info_category', 'it', 'name', 'Colazione'),
('breakfast', 'info_category', 'pt', 'name', 'Pequeno-almoço'),
('breakfast', 'info_category', 'ca', 'name', 'Esmorzar'),
('breakfast', 'info_category', 'ar', 'name', 'الإفطار'),
('breakfast', 'info_category', 'ru', 'name', 'Завтрак'),
('breakfast', 'info_category', 'uk', 'name', 'Сніданок'),
('breakfast', 'info_category', 'zh', 'name', '早餐'),
('breakfast', 'info_category', 'ja', 'name', '朝食'),
('breakfast', 'info_category', 'ko', 'name', '조식'),
('housekeeping', 'info_category', 'es', 'hint', 'Frecuencia y horario de la limpieza de habitaciones.'),
('housekeeping', 'info_category', 'es', 'name', 'Limpieza de habitaciones'),
('housekeeping', 'info_category', 'en', 'name', 'Housekeeping'),
('housekeeping', 'info_category', 'fr', 'name', 'Ménage des chambres'),
('housekeeping', 'info_category', 'de', 'name', 'Zimmerreinigung'),
('housekeeping', 'info_category', 'it', 'name', 'Pulizia delle camere'),
('housekeeping', 'info_category', 'pt', 'name', 'Limpeza dos quartos'),
('housekeeping', 'info_category', 'ca', 'name', 'Neteja d''habitacions'),
('housekeeping', 'info_category', 'ar', 'name', 'خدمة تنظيف الغرف'),
('housekeeping', 'info_category', 'ru', 'name', 'Уборка номеров'),
('housekeeping', 'info_category', 'uk', 'name', 'Прибирання номерів'),
('housekeeping', 'info_category', 'zh', 'name', '客房清洁'),
('housekeeping', 'info_category', 'ja', 'name', 'ルームクリーニング'),
('housekeeping', 'info_category', 'ko', 'name', '룸 청소'),
('room_service', 'info_category', 'es', 'hint', 'Cómo pedir servicio de habitaciones y horario.'),
('room_service', 'info_category', 'es', 'name', 'Servicio de habitaciones'),
('room_service', 'info_category', 'en', 'name', 'Room Service'),
('room_service', 'info_category', 'fr', 'name', 'Service en chambre'),
('room_service', 'info_category', 'de', 'name', 'Zimmerservice'),
('room_service', 'info_category', 'it', 'name', 'Servizio in camera'),
('room_service', 'info_category', 'pt', 'name', 'Serviço de quartos'),
('room_service', 'info_category', 'ca', 'name', 'Servei d''habitacions'),
('room_service', 'info_category', 'ar', 'name', 'خدمة الغرف'),
('room_service', 'info_category', 'ru', 'name', 'Обслуживание номеров'),
('room_service', 'info_category', 'uk', 'name', 'Обслуговування номерів'),
('room_service', 'info_category', 'zh', 'name', '客房服务'),
('room_service', 'info_category', 'ja', 'name', 'ルームサービス'),
('room_service', 'info_category', 'ko', 'name', '룸서비스'),
('custom', 'info_category', 'es', 'hint', 'Para cualquier cosa que no encaje en las categorías anteriores.'),
('custom', 'info_category', 'es', 'name', 'Personalizado'),
('custom', 'info_category', 'en', 'name', 'Custom'),
('custom', 'info_category', 'fr', 'name', 'Personnalisé'),
('custom', 'info_category', 'de', 'name', 'Benutzerdefiniert'),
('custom', 'info_category', 'it', 'name', 'Personalizzato'),
('custom', 'info_category', 'pt', 'name', 'Personalizado'),
('custom', 'info_category', 'ca', 'name', 'Personalitzat'),
('custom', 'info_category', 'ar', 'name', 'مخصص'),
('custom', 'info_category', 'ru', 'name', 'Своё'),
('custom', 'info_category', 'uk', 'name', 'Власне'),
('custom', 'info_category', 'zh', 'name', '自定义'),
('custom', 'info_category', 'ja', 'name', 'カスタム'),
('custom', 'info_category', 'ko', 'name', '사용자 지정');

-- ---------------------------------------------------------
-- guide_apartment_info: columnas nuevas + backfill
-- ---------------------------------------------------------
ALTER TABLE guide_apartment_info ADD COLUMN category_key TEXT REFERENCES guide_info_categories(key);
ALTER TABLE guide_apartment_info ADD COLUMN use_custom_title BOOLEAN DEFAULT FALSE;

-- Backfill: hoy info_key y category_key coinciden 1:1 (ver verificación en
-- la cabecera). Si algún info_key no existiera en el catálogo, esta fila se
-- quedaría con category_key NULL en vez de fallar — se puede detectar con
-- el SELECT de verificación de más abajo.
UPDATE guide_apartment_info
SET category_key = info_key
WHERE category_key IS NULL
  AND info_key IN (SELECT key FROM guide_info_categories);

CREATE INDEX IF NOT EXISTS idx_guide_apartment_info_category ON guide_apartment_info(category_key);

-- Verificación tras aplicar (no forma parte de la migración en sí):
--   SELECT id, apartment_id, info_key FROM guide_apartment_info WHERE category_key IS NULL;
--   -- debe devolver 0 filas. Si devuelve alguna, ese info_key no está en el
--   -- catálogo y hay que decidir a qué categoría mapearlo a mano.
--   SELECT COUNT(*) FROM guide_info_categories;               -- 58
--   SELECT COUNT(*) FROM translations WHERE entity_type='info_category'; -- 58*14 = 812
