-- 0099: textos de la Carta Mediterránea (apps/client/src/carta) en los 13 idiomas.
-- Claves nuevas con prefijo carta_; las que ya existían (button_add, allergens, see_more…) no se tocan.
-- Idempotente (INSERT OR REPLACE). La respuesta de /restaurants/:slug/reels va cacheada en KV
-- (menu:{slug}:{lang}:v{ver}): tras aplicarla hay que subir ver:restaurant:{slug} de cada carta.
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('reels', 'carta_menu', 'es', 'Carta', 'Carta Mediterránea'),
('reels', 'carta_house_hint', 'es', 'Reservas, avisos y más', 'Carta Mediterránea'),
('reels', 'carta_welcome_kicker', 'es', 'Bienvenidos a', 'Carta Mediterránea'),
('reels', 'carta_start', 'es', 'Ver la carta', 'Carta Mediterránea'),
('reels', 'carta_more_languages', 'es', 'Más idiomas', 'Carta Mediterránea'),
('reels', 'carta_full_portion', 'es', 'Ración', 'Carta Mediterránea'),
('reels', 'carta_choose_portion', 'es', 'Elige ración', 'Carta Mediterránea'),
('reels', 'carta_quantity', 'es', 'Cantidad', 'Carta Mediterránea'),
('reels', 'carta_no_allergens', 'es', 'Sin alérgenos declarados', 'Carta Mediterránea'),
('reels', 'carta_back', 'es', 'Volver', 'Carta Mediterránea'),
('reels', 'carta_back_videos', 'es', 'Volver a los vídeos', 'Carta Mediterránea'),
('reels', 'carta_videos', 'es', 'Vídeos', 'Carta Mediterránea'),
('reels', 'carta_selection', 'es', 'Tu selección', 'Carta Mediterránea'),
('reels', 'carta_to_order', 'es', 'Para pedir', 'Carta Mediterránea'),
('reels', 'carta_total', 'es', 'Total', 'Carta Mediterránea'),
('reels', 'carta_staff_note', 'es', 'No se envía nada: enséñasela al camarero para pedir.', 'Carta Mediterránea'),
('reels', 'carta_show_waiter', 'es', 'Enseñar al camarero', 'Carta Mediterránea'),
('reels', 'carta_keep_browsing', 'es', 'Seguir mirando', 'Carta Mediterránea'),
('reels', 'carta_empty', 'es', 'Aún no has elegido nada.', 'Carta Mediterránea'),
('reels', 'carta_for_waiter', 'es', 'Para el camarero', 'Carta Mediterránea'),
('reels', 'carta_badge_featured', 'es', 'Destacado', 'Carta Mediterránea'),
('reels', 'carta_badge_new', 'es', 'Nuevo', 'Carta Mediterránea'),
('reels', 'carta_badge_vegetarian', 'es', 'Vegetariano', 'Carta Mediterránea'),
('reels', 'carta_badge_vegan', 'es', 'Vegano', 'Carta Mediterránea'),
('reels', 'carta_badge_gluten_free', 'es', 'Sin gluten', 'Carta Mediterránea'),
('reels', 'carta_no_video', 'es', 'Este plato aún no tiene vídeo', 'Carta Mediterránea'),
('reels', 'carta_added', 'es', 'Añadido', 'Carta Mediterránea'),
('reels', 'carta_liked', 'es', 'Guardado en tus me gusta', 'Carta Mediterránea'),
('reels', 'carta_unliked', 'es', 'Quitado de tus me gusta', 'Carta Mediterránea'),
('reels', 'carta_likes_note', 'es', 'Los guardamos en este móvil: la próxima vez que vengas seguirán aquí.', 'Carta Mediterránea'),
('reels', 'carta_likes_empty', 'es', 'Toca el corazón, o el vídeo dos veces, para guardar un plato y decidir luego.', 'Carta Mediterránea'),
('reels', 'carta_add_all', 'es', 'Añadir todos a pedir', 'Carta Mediterránea'),
('reels', 'carta_top_liked', 'es', 'Lo que más gusta', 'Carta Mediterránea'),
('reels', 'carta_top_liked_sub', 'es', 'Según los me gusta de quienes han comido aquí', 'Carta Mediterránea'),
('reels', 'carta_dish_one', 'es', '1 plato', 'Carta Mediterránea'),
('reels', 'carta_dish_other', 'es', '{n} platos', 'Carta Mediterránea'),
('reels', 'carta_menu_count', 'es', '{n} platos en la carta', 'Carta Mediterránea'),
('reels', 'carta_avoid_title', 'es', '¿Qué evitas?', 'Carta Mediterránea'),
('reels', 'carta_avoid_sub', 'es', 'Marca lo que no puedes comer y te avisamos en cada plato que lo lleve. Se guarda solo en este móvil.', 'Carta Mediterránea'),
('reels', 'carta_avoid_on', 'es', 'Evito', 'Carta Mediterránea'),
('reels', 'carta_this_dish', 'es', 'Este plato lleva', 'Carta Mediterránea'),
('reels', 'carta_contains', 'es', 'Lleva', 'Carta Mediterránea'),
('reels', 'carta_avoid_warn', 'es', 'lo has marcado para evitar', 'Carta Mediterránea'),
('reels', 'carta_ask_waiter', 'es', 'Si tienes una alergia grave, confírmalo siempre con el camarero.', 'Carta Mediterránea'),
('reels', 'carta_see_allergens', 'es', 'Ver alérgenos', 'Carta Mediterránea'),
('reels', 'carta_menu_allergens', 'es', 'Alérgenos de esta carta', 'Carta Mediterránea'),
('reels', 'carta_no_menu_allergens', 'es', 'Este restaurante aún no ha marcado los alérgenos en su carta digital. Pregunta al camarero antes de pedir.', 'Carta Mediterránea'),
('reels', 'carta_done', 'es', 'Listo', 'Carta Mediterránea'),
('reels', 'carta_notif_title', 'es', 'Avisos', 'Carta Mediterránea'),
('reels', 'carta_notif_lead', 'es', 'Te avisamos de lo nuevo, sin darnos tu nombre ni tu teléfono.', 'Carta Mediterránea'),
('reels', 'carta_notif_1', 'es', 'Platos nuevos', 'Carta Mediterránea'),
('reels', 'carta_notif_1_sub', 'es', 'Cuando entra algo en la carta', 'Carta Mediterránea'),
('reels', 'carta_notif_2', 'es', 'Ofertas', 'Carta Mediterránea'),
('reels', 'carta_notif_2_sub', 'es', 'Solo las de esta casa', 'Carta Mediterránea'),
('reels', 'carta_notif_3', 'es', 'Tu tarjeta de sellos', 'Carta Mediterránea'),
('reels', 'carta_notif_3_sub', 'es', 'Cuando te falte poco para el premio', 'Carta Mediterránea'),
('reels', 'carta_notif_on', 'es', 'Activar avisos', 'Carta Mediterránea'),
('reels', 'carta_notif_active', 'es', 'Avisos activados', 'Carta Mediterránea'),
('reels', 'carta_notif_off', 'es', 'Desactivar avisos', 'Carta Mediterránea'),
('reels', 'carta_notif_note', 'es', 'Tu navegador te pedirá permiso. Puedes quitarlos cuando quieras desde aquí.', 'Carta Mediterránea'),
('reels', 'carta_notif_ios', 'es', 'En iPhone, primero añade la carta a tu pantalla de inicio.', 'Carta Mediterránea'),
('reels', 'carta_notif_ask', 'es', '¿Te avisamos cuando haya platos nuevos u ofertas?', 'Carta Mediterránea'),
('reels', 'carta_notif_denied', 'es', 'Tu navegador tiene los avisos bloqueados para esta web. Puedes permitirlos en sus ajustes.', 'Carta Mediterránea'),
('reels', 'carta_notif_sub_off', 'es', 'Platos nuevos y ofertas', 'Carta Mediterránea'),
('reels', 'carta_notif_sub_on', 'es', 'Activados', 'Carta Mediterránea'),
('reels', 'carta_reserve', 'es', 'Reservar mesa', 'Carta Mediterránea'),
('reels', 'carta_reserve_sub', 'es', 'Elige día y hora', 'Carta Mediterránea'),
('reels', 'carta_takeaway', 'es', 'Pedir para llevar', 'Carta Mediterránea'),
('reels', 'carta_takeaway_sub', 'es', 'Recoge en el local o te lo llevamos', 'Carta Mediterránea'),
('reels', 'carta_stamps', 'es', 'Tarjeta de sellos', 'Carta Mediterránea'),
('reels', 'carta_stamps_sub', 'es', 'Suma un sello en cada visita', 'Carta Mediterránea'),
('reels', 'carta_offer', 'es', 'Oferta de bienvenida', 'Carta Mediterránea'),
('reels', 'carta_offer_sub', 'es', 'Tienes una esperándote', 'Carta Mediterránea'),
('reels', 'carta_rate', 'es', 'Valóranos', 'Carta Mediterránea'),
('reels', 'carta_rate_sub', 'es', 'Un minuto, y nos ayuda mucho', 'Carta Mediterránea'),
('reels', 'carta_web', 'es', 'Nuestra web', 'Carta Mediterránea'),
('reels', 'carta_web_sub', 'es', 'Historia, eventos y contacto', 'Carta Mediterránea'),
('reels', 'carta_whatsapp', 'es', 'WhatsApp', 'Carta Mediterránea'),
('reels', 'carta_whatsapp_sub', 'es', 'Escríbenos', 'Carta Mediterránea'),
('reels', 'carta_instagram', 'es', 'Instagram', 'Carta Mediterránea'),
('reels', 'carta_language', 'es', 'Idioma', 'Carta Mediterránea'),
('reels', 'carta_current', 'es', 'Actual', 'Carta Mediterránea'),
('reels', 'carta_privacy', 'es', 'Privacidad', 'Carta Mediterránea'),
('reels', 'carta_minus', 'es', 'Quitar uno', 'Carta Mediterránea'),
('reels', 'carta_plus', 'es', 'Añadir uno', 'Carta Mediterránea'),
('reels', 'carta_dish_n', 'es', 'Plato {n}', 'Carta Mediterránea'),
('reels', 'carta_empty_menu', 'es', 'No hay carta disponible en este momento', 'Carta Mediterránea'),
('reels', 'carta_menu', 'en', 'Menu', 'Carta Mediterránea'),
('reels', 'carta_house_hint', 'en', 'Bookings, notifications and more', 'Carta Mediterránea'),
('reels', 'carta_welcome_kicker', 'en', 'Welcome to', 'Carta Mediterránea'),
('reels', 'carta_start', 'en', 'See the menu', 'Carta Mediterránea'),
('reels', 'carta_more_languages', 'en', 'More languages', 'Carta Mediterránea'),
('reels', 'carta_full_portion', 'en', 'Full portion', 'Carta Mediterránea'),
('reels', 'carta_choose_portion', 'en', 'Choose a portion', 'Carta Mediterránea'),
('reels', 'carta_quantity', 'en', 'Quantity', 'Carta Mediterránea'),
('reels', 'carta_no_allergens', 'en', 'No declared allergens', 'Carta Mediterránea'),
('reels', 'carta_back', 'en', 'Back', 'Carta Mediterránea'),
('reels', 'carta_back_videos', 'en', 'Back to videos', 'Carta Mediterránea'),
('reels', 'carta_videos', 'en', 'Videos', 'Carta Mediterránea'),
('reels', 'carta_selection', 'en', 'Your selection', 'Carta Mediterránea'),
('reels', 'carta_to_order', 'en', 'To order', 'Carta Mediterránea'),
('reels', 'carta_total', 'en', 'Total', 'Carta Mediterránea'),
('reels', 'carta_staff_note', 'en', 'Nothing is sent: show it to your waiter to order.', 'Carta Mediterránea'),
('reels', 'carta_show_waiter', 'en', 'Show the waiter', 'Carta Mediterránea'),
('reels', 'carta_keep_browsing', 'en', 'Keep browsing', 'Carta Mediterránea'),
('reels', 'carta_empty', 'en', 'Nothing chosen yet.', 'Carta Mediterránea'),
('reels', 'carta_for_waiter', 'en', 'For the waiter', 'Carta Mediterránea'),
('reels', 'carta_badge_featured', 'en', 'Featured', 'Carta Mediterránea'),
('reels', 'carta_badge_new', 'en', 'New', 'Carta Mediterránea'),
('reels', 'carta_badge_vegetarian', 'en', 'Vegetarian', 'Carta Mediterránea'),
('reels', 'carta_badge_vegan', 'en', 'Vegan', 'Carta Mediterránea'),
('reels', 'carta_badge_gluten_free', 'en', 'Gluten-free', 'Carta Mediterránea'),
('reels', 'carta_no_video', 'en', 'No video for this dish yet', 'Carta Mediterránea'),
('reels', 'carta_added', 'en', 'Added', 'Carta Mediterránea'),
('reels', 'carta_liked', 'en', 'Saved to your likes', 'Carta Mediterránea'),
('reels', 'carta_unliked', 'en', 'Removed from your likes', 'Carta Mediterránea'),
('reels', 'carta_likes_note', 'en', 'We keep them on this phone: they will still be here next time you come.', 'Carta Mediterránea'),
('reels', 'carta_likes_empty', 'en', 'Tap the heart, or double-tap the video, to save a dish and decide later.', 'Carta Mediterránea'),
('reels', 'carta_add_all', 'en', 'Add all to order', 'Carta Mediterránea'),
('reels', 'carta_top_liked', 'en', 'Most liked', 'Carta Mediterránea'),
('reels', 'carta_top_liked_sub', 'en', 'From the likes of people who have eaten here', 'Carta Mediterránea'),
('reels', 'carta_dish_one', 'en', '1 dish', 'Carta Mediterránea'),
('reels', 'carta_dish_other', 'en', '{n} dishes', 'Carta Mediterránea'),
('reels', 'carta_menu_count', 'en', '{n} dishes on the menu', 'Carta Mediterránea'),
('reels', 'carta_avoid_title', 'en', 'What do you avoid?', 'Carta Mediterránea'),
('reels', 'carta_avoid_sub', 'en', 'Mark what you can’t eat and we’ll warn you on every dish that contains it. Saved only on this phone.', 'Carta Mediterránea'),
('reels', 'carta_avoid_on', 'en', 'Avoid', 'Carta Mediterránea'),
('reels', 'carta_this_dish', 'en', 'This dish contains', 'Carta Mediterránea'),
('reels', 'carta_contains', 'en', 'Contains', 'Carta Mediterránea'),
('reels', 'carta_avoid_warn', 'en', 'you marked it to avoid', 'Carta Mediterránea'),
('reels', 'carta_ask_waiter', 'en', 'If you have a severe allergy, always check with your waiter.', 'Carta Mediterránea'),
('reels', 'carta_see_allergens', 'en', 'See allergens', 'Carta Mediterránea'),
('reels', 'carta_menu_allergens', 'en', 'Allergens on this menu', 'Carta Mediterránea'),
('reels', 'carta_no_menu_allergens', 'en', 'This restaurant hasn’t marked allergens on its digital menu yet. Ask your waiter before ordering.', 'Carta Mediterránea'),
('reels', 'carta_done', 'en', 'Done', 'Carta Mediterránea'),
('reels', 'carta_notif_title', 'en', 'Notifications', 'Carta Mediterránea'),
('reels', 'carta_notif_lead', 'en', 'We tell you what’s new, without your name or phone number.', 'Carta Mediterránea'),
('reels', 'carta_notif_1', 'en', 'New dishes', 'Carta Mediterránea'),
('reels', 'carta_notif_1_sub', 'en', 'When something joins the menu', 'Carta Mediterránea'),
('reels', 'carta_notif_2', 'en', 'Offers', 'Carta Mediterránea'),
('reels', 'carta_notif_2_sub', 'en', 'Only from this restaurant', 'Carta Mediterránea'),
('reels', 'carta_notif_3', 'en', 'Your stamp card', 'Carta Mediterránea'),
('reels', 'carta_notif_3_sub', 'en', 'When you’re close to the reward', 'Carta Mediterránea'),
('reels', 'carta_notif_on', 'en', 'Turn on notifications', 'Carta Mediterránea'),
('reels', 'carta_notif_active', 'en', 'Notifications on', 'Carta Mediterránea'),
('reels', 'carta_notif_off', 'en', 'Turn off notifications', 'Carta Mediterránea'),
('reels', 'carta_notif_note', 'en', 'Your browser will ask for permission. You can turn them off here any time.', 'Carta Mediterránea'),
('reels', 'carta_notif_ios', 'en', 'On iPhone, first add the menu to your home screen.', 'Carta Mediterránea'),
('reels', 'carta_notif_ask', 'en', 'Shall we tell you about new dishes and offers?', 'Carta Mediterránea'),
('reels', 'carta_notif_denied', 'en', 'Your browser is blocking notifications for this site. You can allow them in its settings.', 'Carta Mediterránea'),
('reels', 'carta_notif_sub_off', 'en', 'New dishes and offers', 'Carta Mediterránea'),
('reels', 'carta_notif_sub_on', 'en', 'On', 'Carta Mediterránea'),
('reels', 'carta_reserve', 'en', 'Book a table', 'Carta Mediterránea'),
('reels', 'carta_reserve_sub', 'en', 'Pick a day and time', 'Carta Mediterránea'),
('reels', 'carta_takeaway', 'en', 'Order to take away', 'Carta Mediterránea'),
('reels', 'carta_takeaway_sub', 'en', 'Pick it up or we deliver', 'Carta Mediterránea'),
('reels', 'carta_stamps', 'en', 'Stamp card', 'Carta Mediterránea'),
('reels', 'carta_stamps_sub', 'en', 'Earn a stamp on every visit', 'Carta Mediterránea'),
('reels', 'carta_offer', 'en', 'Welcome offer', 'Carta Mediterránea'),
('reels', 'carta_offer_sub', 'en', 'There’s one waiting for you', 'Carta Mediterránea'),
('reels', 'carta_rate', 'en', 'Rate us', 'Carta Mediterránea'),
('reels', 'carta_rate_sub', 'en', 'One minute, and it helps a lot', 'Carta Mediterránea'),
('reels', 'carta_web', 'en', 'Our website', 'Carta Mediterránea'),
('reels', 'carta_web_sub', 'en', 'Story, events and contact', 'Carta Mediterránea'),
('reels', 'carta_whatsapp', 'en', 'WhatsApp', 'Carta Mediterránea'),
('reels', 'carta_whatsapp_sub', 'en', 'Message us', 'Carta Mediterránea'),
('reels', 'carta_instagram', 'en', 'Instagram', 'Carta Mediterránea'),
('reels', 'carta_language', 'en', 'Language', 'Carta Mediterránea'),
('reels', 'carta_current', 'en', 'Current', 'Carta Mediterránea'),
('reels', 'carta_privacy', 'en', 'Privacy', 'Carta Mediterránea'),
('reels', 'carta_minus', 'en', 'Remove one', 'Carta Mediterránea'),
('reels', 'carta_plus', 'en', 'Add one', 'Carta Mediterránea'),
('reels', 'carta_dish_n', 'en', 'Dish {n}', 'Carta Mediterránea'),
('reels', 'carta_empty_menu', 'en', 'No menu available right now', 'Carta Mediterránea'),
('reels', 'carta_menu', 'fr', 'Carte', 'Carta Mediterránea'),
('reels', 'carta_house_hint', 'fr', 'Réservations, alertes et plus', 'Carta Mediterránea'),
('reels', 'carta_welcome_kicker', 'fr', 'Bienvenue à', 'Carta Mediterránea'),
('reels', 'carta_start', 'fr', 'Voir la carte', 'Carta Mediterránea'),
('reels', 'carta_more_languages', 'fr', 'Plus de langues', 'Carta Mediterránea'),
('reels', 'carta_full_portion', 'fr', 'Portion entière', 'Carta Mediterránea'),
('reels', 'carta_choose_portion', 'fr', 'Choisissez la portion', 'Carta Mediterránea'),
('reels', 'carta_quantity', 'fr', 'Quantité', 'Carta Mediterránea'),
('reels', 'carta_no_allergens', 'fr', 'Aucun allergène déclaré', 'Carta Mediterránea'),
('reels', 'carta_back', 'fr', 'Retour', 'Carta Mediterránea'),
('reels', 'carta_back_videos', 'fr', 'Retour aux vidéos', 'Carta Mediterránea'),
('reels', 'carta_videos', 'fr', 'Vidéos', 'Carta Mediterránea'),
('reels', 'carta_selection', 'fr', 'Votre sélection', 'Carta Mediterránea'),
('reels', 'carta_to_order', 'fr', 'À commander', 'Carta Mediterránea'),
('reels', 'carta_total', 'fr', 'Total', 'Carta Mediterránea'),
('reels', 'carta_staff_note', 'fr', 'Rien n’est envoyé : montrez-la au serveur pour commander.', 'Carta Mediterránea'),
('reels', 'carta_show_waiter', 'fr', 'Montrer au serveur', 'Carta Mediterránea'),
('reels', 'carta_keep_browsing', 'fr', 'Continuer à regarder', 'Carta Mediterránea'),
('reels', 'carta_empty', 'fr', 'Vous n’avez encore rien choisi.', 'Carta Mediterránea'),
('reels', 'carta_for_waiter', 'fr', 'Pour le serveur', 'Carta Mediterránea'),
('reels', 'carta_badge_featured', 'fr', 'Coup de cœur', 'Carta Mediterránea'),
('reels', 'carta_badge_new', 'fr', 'Nouveau', 'Carta Mediterránea'),
('reels', 'carta_badge_vegetarian', 'fr', 'Végétarien', 'Carta Mediterránea'),
('reels', 'carta_badge_vegan', 'fr', 'Végan', 'Carta Mediterránea'),
('reels', 'carta_badge_gluten_free', 'fr', 'Sans gluten', 'Carta Mediterránea'),
('reels', 'carta_no_video', 'fr', 'Pas encore de vidéo pour ce plat', 'Carta Mediterránea'),
('reels', 'carta_added', 'fr', 'Ajouté', 'Carta Mediterránea'),
('reels', 'carta_liked', 'fr', 'Ajouté à vos favoris', 'Carta Mediterránea'),
('reels', 'carta_unliked', 'fr', 'Retiré de vos favoris', 'Carta Mediterránea'),
('reels', 'carta_likes_note', 'fr', 'Nous les gardons sur ce téléphone : ils seront encore là à votre prochaine visite.', 'Carta Mediterránea'),
('reels', 'carta_likes_empty', 'fr', 'Touchez le cœur, ou deux fois la vidéo, pour garder un plat et décider plus tard.', 'Carta Mediterránea'),
('reels', 'carta_add_all', 'fr', 'Tout ajouter à la commande', 'Carta Mediterránea'),
('reels', 'carta_top_liked', 'fr', 'Les plus aimés', 'Carta Mediterránea'),
('reels', 'carta_top_liked_sub', 'fr', 'D’après les « j’aime » de ceux qui ont mangé ici', 'Carta Mediterránea'),
('reels', 'carta_dish_one', 'fr', '1 plat', 'Carta Mediterránea'),
('reels', 'carta_dish_other', 'fr', '{n} plats', 'Carta Mediterránea'),
('reels', 'carta_menu_count', 'fr', '{n} plats à la carte', 'Carta Mediterránea'),
('reels', 'carta_avoid_title', 'fr', 'Qu’évitez-vous ?', 'Carta Mediterránea'),
('reels', 'carta_avoid_sub', 'fr', 'Indiquez ce que vous ne pouvez pas manger et nous vous prévenons sur chaque plat qui en contient. Enregistré uniquement sur ce téléphone.', 'Carta Mediterránea'),
('reels', 'carta_avoid_on', 'fr', 'J’évite', 'Carta Mediterránea'),
('reels', 'carta_this_dish', 'fr', 'Ce plat contient', 'Carta Mediterránea'),
('reels', 'carta_contains', 'fr', 'Contient', 'Carta Mediterránea'),
('reels', 'carta_avoid_warn', 'fr', 'vous l’avez marqué à éviter', 'Carta Mediterránea'),
('reels', 'carta_ask_waiter', 'fr', 'En cas d’allergie grave, vérifiez toujours auprès du serveur.', 'Carta Mediterránea'),
('reels', 'carta_see_allergens', 'fr', 'Voir les allergènes', 'Carta Mediterránea'),
('reels', 'carta_menu_allergens', 'fr', 'Allergènes de cette carte', 'Carta Mediterránea'),
('reels', 'carta_no_menu_allergens', 'fr', 'Ce restaurant n’a pas encore indiqué les allergènes sur sa carte numérique. Demandez au serveur avant de commander.', 'Carta Mediterránea'),
('reels', 'carta_done', 'fr', 'Terminé', 'Carta Mediterránea'),
('reels', 'carta_notif_title', 'fr', 'Alertes', 'Carta Mediterránea'),
('reels', 'carta_notif_lead', 'fr', 'Nous vous prévenons des nouveautés, sans votre nom ni votre téléphone.', 'Carta Mediterránea'),
('reels', 'carta_notif_1', 'fr', 'Nouveaux plats', 'Carta Mediterránea'),
('reels', 'carta_notif_1_sub', 'fr', 'Quand un plat arrive à la carte', 'Carta Mediterránea'),
('reels', 'carta_notif_2', 'fr', 'Offres', 'Carta Mediterránea'),
('reels', 'carta_notif_2_sub', 'fr', 'Uniquement celles de cette maison', 'Carta Mediterránea'),
('reels', 'carta_notif_3', 'fr', 'Votre carte de fidélité', 'Carta Mediterránea'),
('reels', 'carta_notif_3_sub', 'fr', 'Quand la récompense est proche', 'Carta Mediterránea'),
('reels', 'carta_notif_on', 'fr', 'Activer les alertes', 'Carta Mediterránea'),
('reels', 'carta_notif_active', 'fr', 'Alertes activées', 'Carta Mediterránea'),
('reels', 'carta_notif_off', 'fr', 'Désactiver les alertes', 'Carta Mediterránea'),
('reels', 'carta_notif_note', 'fr', 'Votre navigateur vous demandera l’autorisation. Vous pouvez les désactiver ici à tout moment.', 'Carta Mediterránea'),
('reels', 'carta_notif_ios', 'fr', 'Sur iPhone, ajoutez d’abord la carte à votre écran d’accueil.', 'Carta Mediterránea'),
('reels', 'carta_notif_ask', 'fr', 'On vous prévient des nouveaux plats et des offres ?', 'Carta Mediterránea'),
('reels', 'carta_notif_denied', 'fr', 'Votre navigateur bloque les alertes pour ce site. Vous pouvez les autoriser dans ses réglages.', 'Carta Mediterránea'),
('reels', 'carta_notif_sub_off', 'fr', 'Nouveaux plats et offres', 'Carta Mediterránea'),
('reels', 'carta_notif_sub_on', 'fr', 'Activées', 'Carta Mediterránea'),
('reels', 'carta_reserve', 'fr', 'Réserver une table', 'Carta Mediterránea'),
('reels', 'carta_reserve_sub', 'fr', 'Choisissez le jour et l’heure', 'Carta Mediterránea'),
('reels', 'carta_takeaway', 'fr', 'Commander à emporter', 'Carta Mediterránea'),
('reels', 'carta_takeaway_sub', 'fr', 'À retirer sur place ou livré', 'Carta Mediterránea'),
('reels', 'carta_stamps', 'fr', 'Carte de fidélité', 'Carta Mediterránea'),
('reels', 'carta_stamps_sub', 'fr', 'Un tampon à chaque visite', 'Carta Mediterránea'),
('reels', 'carta_offer', 'fr', 'Offre de bienvenue', 'Carta Mediterránea'),
('reels', 'carta_offer_sub', 'fr', 'Une offre vous attend', 'Carta Mediterránea'),
('reels', 'carta_rate', 'fr', 'Donnez votre avis', 'Carta Mediterránea'),
('reels', 'carta_rate_sub', 'fr', 'Une minute, et ça nous aide beaucoup', 'Carta Mediterránea'),
('reels', 'carta_web', 'fr', 'Notre site', 'Carta Mediterránea'),
('reels', 'carta_web_sub', 'fr', 'Histoire, événements et contact', 'Carta Mediterránea'),
('reels', 'carta_whatsapp', 'fr', 'WhatsApp', 'Carta Mediterránea'),
('reels', 'carta_whatsapp_sub', 'fr', 'Écrivez-nous', 'Carta Mediterránea'),
('reels', 'carta_instagram', 'fr', 'Instagram', 'Carta Mediterránea'),
('reels', 'carta_language', 'fr', 'Langue', 'Carta Mediterránea'),
('reels', 'carta_current', 'fr', 'Actuelle', 'Carta Mediterránea'),
('reels', 'carta_privacy', 'fr', 'Confidentialité', 'Carta Mediterránea'),
('reels', 'carta_minus', 'fr', 'En retirer un', 'Carta Mediterránea'),
('reels', 'carta_plus', 'fr', 'En ajouter un', 'Carta Mediterránea'),
('reels', 'carta_dish_n', 'fr', 'Plat {n}', 'Carta Mediterránea'),
('reels', 'carta_empty_menu', 'fr', 'Aucune carte disponible pour le moment', 'Carta Mediterránea'),
('reels', 'carta_menu', 'de', 'Karte', 'Carta Mediterránea'),
('reels', 'carta_house_hint', 'de', 'Reservierung, Hinweise und mehr', 'Carta Mediterránea'),
('reels', 'carta_welcome_kicker', 'de', 'Willkommen im', 'Carta Mediterránea'),
('reels', 'carta_start', 'de', 'Zur Karte', 'Carta Mediterránea'),
('reels', 'carta_more_languages', 'de', 'Weitere Sprachen', 'Carta Mediterránea'),
('reels', 'carta_full_portion', 'de', 'Ganze Portion', 'Carta Mediterránea'),
('reels', 'carta_choose_portion', 'de', 'Portion wählen', 'Carta Mediterránea'),
('reels', 'carta_quantity', 'de', 'Menge', 'Carta Mediterránea'),
('reels', 'carta_no_allergens', 'de', 'Keine deklarierten Allergene', 'Carta Mediterránea'),
('reels', 'carta_back', 'de', 'Zurück', 'Carta Mediterránea'),
('reels', 'carta_back_videos', 'de', 'Zurück zu den Videos', 'Carta Mediterránea'),
('reels', 'carta_videos', 'de', 'Videos', 'Carta Mediterránea'),
('reels', 'carta_selection', 'de', 'Deine Auswahl', 'Carta Mediterránea'),
('reels', 'carta_to_order', 'de', 'Bestellen', 'Carta Mediterránea'),
('reels', 'carta_total', 'de', 'Gesamt', 'Carta Mediterránea'),
('reels', 'carta_staff_note', 'de', 'Es wird nichts gesendet: Zeig sie dem Kellner, um zu bestellen.', 'Carta Mediterránea'),
('reels', 'carta_show_waiter', 'de', 'Dem Kellner zeigen', 'Carta Mediterránea'),
('reels', 'carta_keep_browsing', 'de', 'Weiter stöbern', 'Carta Mediterránea'),
('reels', 'carta_empty', 'de', 'Noch nichts ausgewählt.', 'Carta Mediterránea'),
('reels', 'carta_for_waiter', 'de', 'Für den Kellner', 'Carta Mediterránea'),
('reels', 'carta_badge_featured', 'de', 'Empfehlung', 'Carta Mediterránea'),
('reels', 'carta_badge_new', 'de', 'Neu', 'Carta Mediterránea'),
('reels', 'carta_badge_vegetarian', 'de', 'Vegetarisch', 'Carta Mediterránea'),
('reels', 'carta_badge_vegan', 'de', 'Vegan', 'Carta Mediterránea'),
('reels', 'carta_badge_gluten_free', 'de', 'Glutenfrei', 'Carta Mediterránea'),
('reels', 'carta_no_video', 'de', 'Für dieses Gericht gibt es noch kein Video', 'Carta Mediterránea'),
('reels', 'carta_added', 'de', 'Hinzugefügt', 'Carta Mediterránea'),
('reels', 'carta_liked', 'de', 'In deinen Favoriten gespeichert', 'Carta Mediterránea'),
('reels', 'carta_unliked', 'de', 'Aus deinen Favoriten entfernt', 'Carta Mediterránea'),
('reels', 'carta_likes_note', 'de', 'Wir speichern sie auf diesem Handy: Beim nächsten Besuch sind sie noch da.', 'Carta Mediterránea'),
('reels', 'carta_likes_empty', 'de', 'Tippe aufs Herz oder zweimal aufs Video, um ein Gericht zu merken und später zu entscheiden.', 'Carta Mediterránea'),
('reels', 'carta_add_all', 'de', 'Alle zum Bestellen', 'Carta Mediterránea'),
('reels', 'carta_top_liked', 'de', 'Am beliebtesten', 'Carta Mediterránea'),
('reels', 'carta_top_liked_sub', 'de', 'Nach den Likes der Gäste, die hier gegessen haben', 'Carta Mediterránea'),
('reels', 'carta_dish_one', 'de', '1 Gericht', 'Carta Mediterránea'),
('reels', 'carta_dish_other', 'de', '{n} Gerichte', 'Carta Mediterránea'),
('reels', 'carta_menu_count', 'de', '{n} Gerichte auf der Karte', 'Carta Mediterránea'),
('reels', 'carta_avoid_title', 'de', 'Was meidest du?', 'Carta Mediterránea'),
('reels', 'carta_avoid_sub', 'de', 'Markiere, was du nicht essen kannst, und wir warnen dich bei jedem Gericht, das es enthält. Nur auf diesem Handy gespeichert.', 'Carta Mediterránea'),
('reels', 'carta_avoid_on', 'de', 'Meide ich', 'Carta Mediterránea'),
('reels', 'carta_this_dish', 'de', 'Dieses Gericht enthält', 'Carta Mediterránea'),
('reels', 'carta_contains', 'de', 'Enthält', 'Carta Mediterránea'),
('reels', 'carta_avoid_warn', 'de', 'du meidest es', 'Carta Mediterránea'),
('reels', 'carta_ask_waiter', 'de', 'Bei einer schweren Allergie frag immer beim Kellner nach.', 'Carta Mediterránea'),
('reels', 'carta_see_allergens', 'de', 'Allergene ansehen', 'Carta Mediterránea'),
('reels', 'carta_menu_allergens', 'de', 'Allergene dieser Karte', 'Carta Mediterránea'),
('reels', 'carta_no_menu_allergens', 'de', 'Dieses Restaurant hat die Allergene in seiner digitalen Karte noch nicht angegeben. Frag vor dem Bestellen beim Kellner nach.', 'Carta Mediterránea'),
('reels', 'carta_done', 'de', 'Fertig', 'Carta Mediterránea'),
('reels', 'carta_notif_title', 'de', 'Benachrichtigungen', 'Carta Mediterránea'),
('reels', 'carta_notif_lead', 'de', 'Wir sagen dir, was neu ist – ohne deinen Namen oder deine Nummer.', 'Carta Mediterránea'),
('reels', 'carta_notif_1', 'de', 'Neue Gerichte', 'Carta Mediterránea'),
('reels', 'carta_notif_1_sub', 'de', 'Wenn etwas auf die Karte kommt', 'Carta Mediterránea'),
('reels', 'carta_notif_2', 'de', 'Angebote', 'Carta Mediterránea'),
('reels', 'carta_notif_2_sub', 'de', 'Nur von diesem Restaurant', 'Carta Mediterránea'),
('reels', 'carta_notif_3', 'de', 'Deine Stempelkarte', 'Carta Mediterránea'),
('reels', 'carta_notif_3_sub', 'de', 'Wenn die Prämie nah ist', 'Carta Mediterránea'),
('reels', 'carta_notif_on', 'de', 'Benachrichtigungen aktivieren', 'Carta Mediterránea'),
('reels', 'carta_notif_active', 'de', 'Benachrichtigungen aktiv', 'Carta Mediterránea'),
('reels', 'carta_notif_off', 'de', 'Benachrichtigungen deaktivieren', 'Carta Mediterránea'),
('reels', 'carta_notif_note', 'de', 'Dein Browser fragt nach der Erlaubnis. Du kannst sie hier jederzeit abschalten.', 'Carta Mediterránea'),
('reels', 'carta_notif_ios', 'de', 'Auf dem iPhone füge die Karte zuerst zum Home-Bildschirm hinzu.', 'Carta Mediterránea'),
('reels', 'carta_notif_ask', 'de', 'Sollen wir dir neue Gerichte und Angebote melden?', 'Carta Mediterránea'),
('reels', 'carta_notif_denied', 'de', 'Dein Browser blockiert Benachrichtigungen für diese Seite. Du kannst sie in den Einstellungen erlauben.', 'Carta Mediterránea'),
('reels', 'carta_notif_sub_off', 'de', 'Neue Gerichte und Angebote', 'Carta Mediterránea'),
('reels', 'carta_notif_sub_on', 'de', 'Aktiv', 'Carta Mediterránea'),
('reels', 'carta_reserve', 'de', 'Tisch reservieren', 'Carta Mediterránea'),
('reels', 'carta_reserve_sub', 'de', 'Tag und Uhrzeit wählen', 'Carta Mediterránea'),
('reels', 'carta_takeaway', 'de', 'Zum Mitnehmen bestellen', 'Carta Mediterránea'),
('reels', 'carta_takeaway_sub', 'de', 'Abholen oder liefern lassen', 'Carta Mediterránea'),
('reels', 'carta_stamps', 'de', 'Stempelkarte', 'Carta Mediterránea'),
('reels', 'carta_stamps_sub', 'de', 'Ein Stempel bei jedem Besuch', 'Carta Mediterránea'),
('reels', 'carta_offer', 'de', 'Willkommensangebot', 'Carta Mediterránea'),
('reels', 'carta_offer_sub', 'de', 'Eins wartet auf dich', 'Carta Mediterránea'),
('reels', 'carta_rate', 'de', 'Bewerte uns', 'Carta Mediterránea'),
('reels', 'carta_rate_sub', 'de', 'Eine Minute, und es hilft uns sehr', 'Carta Mediterránea'),
('reels', 'carta_web', 'de', 'Unsere Website', 'Carta Mediterránea'),
('reels', 'carta_web_sub', 'de', 'Geschichte, Events und Kontakt', 'Carta Mediterránea'),
('reels', 'carta_whatsapp', 'de', 'WhatsApp', 'Carta Mediterránea'),
('reels', 'carta_whatsapp_sub', 'de', 'Schreib uns', 'Carta Mediterránea'),
('reels', 'carta_instagram', 'de', 'Instagram', 'Carta Mediterránea'),
('reels', 'carta_language', 'de', 'Sprache', 'Carta Mediterránea'),
('reels', 'carta_current', 'de', 'Aktuell', 'Carta Mediterránea'),
('reels', 'carta_privacy', 'de', 'Datenschutz', 'Carta Mediterránea'),
('reels', 'carta_minus', 'de', 'Eins weniger', 'Carta Mediterránea'),
('reels', 'carta_plus', 'de', 'Eins mehr', 'Carta Mediterránea'),
('reels', 'carta_dish_n', 'de', 'Gericht {n}', 'Carta Mediterránea'),
('reels', 'carta_empty_menu', 'de', 'Im Moment ist keine Karte verfügbar', 'Carta Mediterránea'),
('reels', 'carta_menu', 'it', 'Menù', 'Carta Mediterránea'),
('reels', 'carta_house_hint', 'it', 'Prenotazioni, avvisi e altro', 'Carta Mediterránea'),
('reels', 'carta_welcome_kicker', 'it', 'Benvenuti da', 'Carta Mediterránea'),
('reels', 'carta_start', 'it', 'Vedi il menù', 'Carta Mediterránea'),
('reels', 'carta_more_languages', 'it', 'Altre lingue', 'Carta Mediterránea'),
('reels', 'carta_full_portion', 'it', 'Porzione intera', 'Carta Mediterránea'),
('reels', 'carta_choose_portion', 'it', 'Scegli la porzione', 'Carta Mediterránea'),
('reels', 'carta_quantity', 'it', 'Quantità', 'Carta Mediterránea'),
('reels', 'carta_no_allergens', 'it', 'Nessun allergene dichiarato', 'Carta Mediterránea'),
('reels', 'carta_back', 'it', 'Indietro', 'Carta Mediterránea'),
('reels', 'carta_back_videos', 'it', 'Torna ai video', 'Carta Mediterránea'),
('reels', 'carta_videos', 'it', 'Video', 'Carta Mediterránea'),
('reels', 'carta_selection', 'it', 'La tua selezione', 'Carta Mediterránea'),
('reels', 'carta_to_order', 'it', 'Da ordinare', 'Carta Mediterránea'),
('reels', 'carta_total', 'it', 'Totale', 'Carta Mediterránea'),
('reels', 'carta_staff_note', 'it', 'Non si invia nulla: mostrala al cameriere per ordinare.', 'Carta Mediterránea'),
('reels', 'carta_show_waiter', 'it', 'Mostra al cameriere', 'Carta Mediterránea'),
('reels', 'carta_keep_browsing', 'it', 'Continua a guardare', 'Carta Mediterránea'),
('reels', 'carta_empty', 'it', 'Non hai ancora scelto nulla.', 'Carta Mediterránea'),
('reels', 'carta_for_waiter', 'it', 'Per il cameriere', 'Carta Mediterránea'),
('reels', 'carta_badge_featured', 'it', 'In evidenza', 'Carta Mediterránea'),
('reels', 'carta_badge_new', 'it', 'Novità', 'Carta Mediterránea'),
('reels', 'carta_badge_vegetarian', 'it', 'Vegetariano', 'Carta Mediterránea'),
('reels', 'carta_badge_vegan', 'it', 'Vegano', 'Carta Mediterránea'),
('reels', 'carta_badge_gluten_free', 'it', 'Senza glutine', 'Carta Mediterránea'),
('reels', 'carta_no_video', 'it', 'Questo piatto non ha ancora un video', 'Carta Mediterránea'),
('reels', 'carta_added', 'it', 'Aggiunto', 'Carta Mediterránea'),
('reels', 'carta_liked', 'it', 'Salvato nei tuoi preferiti', 'Carta Mediterránea'),
('reels', 'carta_unliked', 'it', 'Tolto dai tuoi preferiti', 'Carta Mediterránea'),
('reels', 'carta_likes_note', 'it', 'Li salviamo su questo telefono: alla prossima visita saranno ancora qui.', 'Carta Mediterránea'),
('reels', 'carta_likes_empty', 'it', 'Tocca il cuore, o due volte il video, per salvare un piatto e decidere dopo.', 'Carta Mediterránea'),
('reels', 'carta_add_all', 'it', 'Aggiungi tutti all’ordine', 'Carta Mediterránea'),
('reels', 'carta_top_liked', 'it', 'I più amati', 'Carta Mediterránea'),
('reels', 'carta_top_liked_sub', 'it', 'Secondo i «mi piace» di chi ha mangiato qui', 'Carta Mediterránea'),
('reels', 'carta_dish_one', 'it', '1 piatto', 'Carta Mediterránea'),
('reels', 'carta_dish_other', 'it', '{n} piatti', 'Carta Mediterránea'),
('reels', 'carta_menu_count', 'it', '{n} piatti nel menù', 'Carta Mediterránea'),
('reels', 'carta_avoid_title', 'it', 'Cosa eviti?', 'Carta Mediterránea'),
('reels', 'carta_avoid_sub', 'it', 'Segna ciò che non puoi mangiare e ti avvisiamo su ogni piatto che lo contiene. Salvato solo su questo telefono.', 'Carta Mediterránea'),
('reels', 'carta_avoid_on', 'it', 'Evito', 'Carta Mediterránea'),
('reels', 'carta_this_dish', 'it', 'Questo piatto contiene', 'Carta Mediterránea'),
('reels', 'carta_contains', 'it', 'Contiene', 'Carta Mediterránea'),
('reels', 'carta_avoid_warn', 'it', 'lo hai segnato da evitare', 'Carta Mediterránea'),
('reels', 'carta_ask_waiter', 'it', 'Se hai un’allergia grave, verifica sempre con il cameriere.', 'Carta Mediterránea'),
('reels', 'carta_see_allergens', 'it', 'Vedi allergeni', 'Carta Mediterránea'),
('reels', 'carta_menu_allergens', 'it', 'Allergeni di questo menù', 'Carta Mediterránea'),
('reels', 'carta_no_menu_allergens', 'it', 'Questo ristorante non ha ancora indicato gli allergeni nel menù digitale. Chiedi al cameriere prima di ordinare.', 'Carta Mediterránea'),
('reels', 'carta_done', 'it', 'Fatto', 'Carta Mediterránea'),
('reels', 'carta_notif_title', 'it', 'Avvisi', 'Carta Mediterránea'),
('reels', 'carta_notif_lead', 'it', 'Ti avvisiamo delle novità, senza nome né telefono.', 'Carta Mediterránea'),
('reels', 'carta_notif_1', 'it', 'Nuovi piatti', 'Carta Mediterránea'),
('reels', 'carta_notif_1_sub', 'it', 'Quando entra qualcosa nel menù', 'Carta Mediterránea'),
('reels', 'carta_notif_2', 'it', 'Offerte', 'Carta Mediterránea'),
('reels', 'carta_notif_2_sub', 'it', 'Solo quelle di questo locale', 'Carta Mediterránea'),
('reels', 'carta_notif_3', 'it', 'La tua tessera timbri', 'Carta Mediterránea'),
('reels', 'carta_notif_3_sub', 'it', 'Quando il premio è vicino', 'Carta Mediterránea'),
('reels', 'carta_notif_on', 'it', 'Attiva gli avvisi', 'Carta Mediterránea'),
('reels', 'carta_notif_active', 'it', 'Avvisi attivi', 'Carta Mediterránea'),
('reels', 'carta_notif_off', 'it', 'Disattiva gli avvisi', 'Carta Mediterránea'),
('reels', 'carta_notif_note', 'it', 'Il browser ti chiederà il permesso. Puoi toglierli da qui quando vuoi.', 'Carta Mediterránea'),
('reels', 'carta_notif_ios', 'it', 'Su iPhone, aggiungi prima il menù alla schermata Home.', 'Carta Mediterránea'),
('reels', 'carta_notif_ask', 'it', 'Ti avvisiamo quando ci sono nuovi piatti od offerte?', 'Carta Mediterránea'),
('reels', 'carta_notif_denied', 'it', 'Il browser blocca gli avvisi per questo sito. Puoi consentirli nelle sue impostazioni.', 'Carta Mediterránea'),
('reels', 'carta_notif_sub_off', 'it', 'Nuovi piatti e offerte', 'Carta Mediterránea'),
('reels', 'carta_notif_sub_on', 'it', 'Attivi', 'Carta Mediterránea'),
('reels', 'carta_reserve', 'it', 'Prenota un tavolo', 'Carta Mediterránea'),
('reels', 'carta_reserve_sub', 'it', 'Scegli giorno e ora', 'Carta Mediterránea'),
('reels', 'carta_takeaway', 'it', 'Ordina da asporto', 'Carta Mediterránea'),
('reels', 'carta_takeaway_sub', 'it', 'Ritira al locale o te lo portiamo', 'Carta Mediterránea'),
('reels', 'carta_stamps', 'it', 'Tessera timbri', 'Carta Mediterránea'),
('reels', 'carta_stamps_sub', 'it', 'Un timbro a ogni visita', 'Carta Mediterránea'),
('reels', 'carta_offer', 'it', 'Offerta di benvenuto', 'Carta Mediterránea'),
('reels', 'carta_offer_sub', 'it', 'Ce n’è una che ti aspetta', 'Carta Mediterránea'),
('reels', 'carta_rate', 'it', 'Valutaci', 'Carta Mediterránea'),
('reels', 'carta_rate_sub', 'it', 'Un minuto, e ci aiuta molto', 'Carta Mediterránea'),
('reels', 'carta_web', 'it', 'Il nostro sito', 'Carta Mediterránea'),
('reels', 'carta_web_sub', 'it', 'Storia, eventi e contatti', 'Carta Mediterránea'),
('reels', 'carta_whatsapp', 'it', 'WhatsApp', 'Carta Mediterránea'),
('reels', 'carta_whatsapp_sub', 'it', 'Scrivici', 'Carta Mediterránea'),
('reels', 'carta_instagram', 'it', 'Instagram', 'Carta Mediterránea'),
('reels', 'carta_language', 'it', 'Lingua', 'Carta Mediterránea'),
('reels', 'carta_current', 'it', 'Attuale', 'Carta Mediterránea'),
('reels', 'carta_privacy', 'it', 'Privacy', 'Carta Mediterránea'),
('reels', 'carta_minus', 'it', 'Togli uno', 'Carta Mediterránea'),
('reels', 'carta_plus', 'it', 'Aggiungi uno', 'Carta Mediterránea'),
('reels', 'carta_dish_n', 'it', 'Piatto {n}', 'Carta Mediterránea'),
('reels', 'carta_empty_menu', 'it', 'Nessun menù disponibile al momento', 'Carta Mediterránea'),
('reels', 'carta_menu', 'pt', 'Menu', 'Carta Mediterránea'),
('reels', 'carta_house_hint', 'pt', 'Reservas, avisos e mais', 'Carta Mediterránea'),
('reels', 'carta_welcome_kicker', 'pt', 'Bem-vindos a', 'Carta Mediterránea'),
('reels', 'carta_start', 'pt', 'Ver o menu', 'Carta Mediterránea'),
('reels', 'carta_more_languages', 'pt', 'Mais idiomas', 'Carta Mediterránea'),
('reels', 'carta_full_portion', 'pt', 'Dose inteira', 'Carta Mediterránea'),
('reels', 'carta_choose_portion', 'pt', 'Escolha a dose', 'Carta Mediterránea'),
('reels', 'carta_quantity', 'pt', 'Quantidade', 'Carta Mediterránea'),
('reels', 'carta_no_allergens', 'pt', 'Sem alergénios declarados', 'Carta Mediterránea'),
('reels', 'carta_back', 'pt', 'Voltar', 'Carta Mediterránea'),
('reels', 'carta_back_videos', 'pt', 'Voltar aos vídeos', 'Carta Mediterránea'),
('reels', 'carta_videos', 'pt', 'Vídeos', 'Carta Mediterránea'),
('reels', 'carta_selection', 'pt', 'A sua seleção', 'Carta Mediterránea'),
('reels', 'carta_to_order', 'pt', 'Para pedir', 'Carta Mediterránea'),
('reels', 'carta_total', 'pt', 'Total', 'Carta Mediterránea'),
('reels', 'carta_staff_note', 'pt', 'Nada é enviado: mostre-a ao empregado para pedir.', 'Carta Mediterránea'),
('reels', 'carta_show_waiter', 'pt', 'Mostrar ao empregado', 'Carta Mediterránea'),
('reels', 'carta_keep_browsing', 'pt', 'Continuar a ver', 'Carta Mediterránea'),
('reels', 'carta_empty', 'pt', 'Ainda não escolheu nada.', 'Carta Mediterránea'),
('reels', 'carta_for_waiter', 'pt', 'Para o empregado', 'Carta Mediterránea'),
('reels', 'carta_badge_featured', 'pt', 'Destaque', 'Carta Mediterránea'),
('reels', 'carta_badge_new', 'pt', 'Novo', 'Carta Mediterránea'),
('reels', 'carta_badge_vegetarian', 'pt', 'Vegetariano', 'Carta Mediterránea'),
('reels', 'carta_badge_vegan', 'pt', 'Vegano', 'Carta Mediterránea'),
('reels', 'carta_badge_gluten_free', 'pt', 'Sem glúten', 'Carta Mediterránea'),
('reels', 'carta_no_video', 'pt', 'Este prato ainda não tem vídeo', 'Carta Mediterránea'),
('reels', 'carta_added', 'pt', 'Adicionado', 'Carta Mediterránea'),
('reels', 'carta_liked', 'pt', 'Guardado nos seus favoritos', 'Carta Mediterránea'),
('reels', 'carta_unliked', 'pt', 'Retirado dos seus favoritos', 'Carta Mediterránea'),
('reels', 'carta_likes_note', 'pt', 'Guardamo-los neste telemóvel: na próxima visita continuam aqui.', 'Carta Mediterránea'),
('reels', 'carta_likes_empty', 'pt', 'Toque no coração, ou duas vezes no vídeo, para guardar um prato e decidir depois.', 'Carta Mediterránea'),
('reels', 'carta_add_all', 'pt', 'Adicionar todos ao pedido', 'Carta Mediterránea'),
('reels', 'carta_top_liked', 'pt', 'Os mais apreciados', 'Carta Mediterránea'),
('reels', 'carta_top_liked_sub', 'pt', 'Segundo os «gosto» de quem já comeu aqui', 'Carta Mediterránea'),
('reels', 'carta_dish_one', 'pt', '1 prato', 'Carta Mediterránea'),
('reels', 'carta_dish_other', 'pt', '{n} pratos', 'Carta Mediterránea'),
('reels', 'carta_menu_count', 'pt', '{n} pratos no menu', 'Carta Mediterránea'),
('reels', 'carta_avoid_title', 'pt', 'O que evita?', 'Carta Mediterránea'),
('reels', 'carta_avoid_sub', 'pt', 'Marque o que não pode comer e avisamos em cada prato que o contenha. Guardado só neste telemóvel.', 'Carta Mediterránea'),
('reels', 'carta_avoid_on', 'pt', 'Evito', 'Carta Mediterránea'),
('reels', 'carta_this_dish', 'pt', 'Este prato contém', 'Carta Mediterránea'),
('reels', 'carta_contains', 'pt', 'Contém', 'Carta Mediterránea'),
('reels', 'carta_avoid_warn', 'pt', 'marcou-o para evitar', 'Carta Mediterránea'),
('reels', 'carta_ask_waiter', 'pt', 'Se tem uma alergia grave, confirme sempre com o empregado.', 'Carta Mediterránea'),
('reels', 'carta_see_allergens', 'pt', 'Ver alergénios', 'Carta Mediterránea'),
('reels', 'carta_menu_allergens', 'pt', 'Alergénios deste menu', 'Carta Mediterránea'),
('reels', 'carta_no_menu_allergens', 'pt', 'Este restaurante ainda não indicou os alergénios no menu digital. Pergunte ao empregado antes de pedir.', 'Carta Mediterránea'),
('reels', 'carta_done', 'pt', 'Pronto', 'Carta Mediterránea'),
('reels', 'carta_notif_title', 'pt', 'Avisos', 'Carta Mediterránea'),
('reels', 'carta_notif_lead', 'pt', 'Avisamos das novidades, sem nos dar o seu nome nem o telefone.', 'Carta Mediterránea'),
('reels', 'carta_notif_1', 'pt', 'Pratos novos', 'Carta Mediterránea'),
('reels', 'carta_notif_1_sub', 'pt', 'Quando entra algo no menu', 'Carta Mediterránea'),
('reels', 'carta_notif_2', 'pt', 'Ofertas', 'Carta Mediterránea'),
('reels', 'carta_notif_2_sub', 'pt', 'Só as desta casa', 'Carta Mediterránea'),
('reels', 'carta_notif_3', 'pt', 'O seu cartão de carimbos', 'Carta Mediterránea'),
('reels', 'carta_notif_3_sub', 'pt', 'Quando o prémio estiver perto', 'Carta Mediterránea'),
('reels', 'carta_notif_on', 'pt', 'Ativar avisos', 'Carta Mediterránea'),
('reels', 'carta_notif_active', 'pt', 'Avisos ativados', 'Carta Mediterránea'),
('reels', 'carta_notif_off', 'pt', 'Desativar avisos', 'Carta Mediterránea'),
('reels', 'carta_notif_note', 'pt', 'O navegador vai pedir permissão. Pode desativá-los aqui quando quiser.', 'Carta Mediterránea'),
('reels', 'carta_notif_ios', 'pt', 'No iPhone, adicione primeiro o menu ao ecrã principal.', 'Carta Mediterránea'),
('reels', 'carta_notif_ask', 'pt', 'Avisamos quando houver pratos novos ou ofertas?', 'Carta Mediterránea'),
('reels', 'carta_notif_denied', 'pt', 'O navegador está a bloquear os avisos deste site. Pode permiti-los nas definições.', 'Carta Mediterránea'),
('reels', 'carta_notif_sub_off', 'pt', 'Pratos novos e ofertas', 'Carta Mediterránea'),
('reels', 'carta_notif_sub_on', 'pt', 'Ativados', 'Carta Mediterránea'),
('reels', 'carta_reserve', 'pt', 'Reservar mesa', 'Carta Mediterránea'),
('reels', 'carta_reserve_sub', 'pt', 'Escolha o dia e a hora', 'Carta Mediterránea'),
('reels', 'carta_takeaway', 'pt', 'Pedir para levar', 'Carta Mediterránea'),
('reels', 'carta_takeaway_sub', 'pt', 'Levante no local ou entregamos', 'Carta Mediterránea'),
('reels', 'carta_stamps', 'pt', 'Cartão de carimbos', 'Carta Mediterránea'),
('reels', 'carta_stamps_sub', 'pt', 'Um carimbo em cada visita', 'Carta Mediterránea'),
('reels', 'carta_offer', 'pt', 'Oferta de boas-vindas', 'Carta Mediterránea'),
('reels', 'carta_offer_sub', 'pt', 'Há uma à sua espera', 'Carta Mediterránea'),
('reels', 'carta_rate', 'pt', 'Avalie-nos', 'Carta Mediterránea'),
('reels', 'carta_rate_sub', 'pt', 'Um minuto, e ajuda-nos muito', 'Carta Mediterránea'),
('reels', 'carta_web', 'pt', 'O nosso site', 'Carta Mediterránea'),
('reels', 'carta_web_sub', 'pt', 'História, eventos e contacto', 'Carta Mediterránea'),
('reels', 'carta_whatsapp', 'pt', 'WhatsApp', 'Carta Mediterránea'),
('reels', 'carta_whatsapp_sub', 'pt', 'Escreva-nos', 'Carta Mediterránea'),
('reels', 'carta_instagram', 'pt', 'Instagram', 'Carta Mediterránea'),
('reels', 'carta_language', 'pt', 'Idioma', 'Carta Mediterránea'),
('reels', 'carta_current', 'pt', 'Atual', 'Carta Mediterránea'),
('reels', 'carta_privacy', 'pt', 'Privacidade', 'Carta Mediterránea'),
('reels', 'carta_minus', 'pt', 'Tirar um', 'Carta Mediterránea'),
('reels', 'carta_plus', 'pt', 'Adicionar um', 'Carta Mediterránea'),
('reels', 'carta_dish_n', 'pt', 'Prato {n}', 'Carta Mediterránea'),
('reels', 'carta_empty_menu', 'pt', 'Não há menu disponível neste momento', 'Carta Mediterránea'),
('reels', 'carta_menu', 'ca', 'Carta', 'Carta Mediterránea'),
('reels', 'carta_house_hint', 'ca', 'Reserves, avisos i més', 'Carta Mediterránea'),
('reels', 'carta_welcome_kicker', 'ca', 'Benvinguts a', 'Carta Mediterránea'),
('reels', 'carta_start', 'ca', 'Veure la carta', 'Carta Mediterránea'),
('reels', 'carta_more_languages', 'ca', 'Més idiomes', 'Carta Mediterránea'),
('reels', 'carta_full_portion', 'ca', 'Ració', 'Carta Mediterránea'),
('reels', 'carta_choose_portion', 'ca', 'Tria la ració', 'Carta Mediterránea'),
('reels', 'carta_quantity', 'ca', 'Quantitat', 'Carta Mediterránea'),
('reels', 'carta_no_allergens', 'ca', 'Sense al·lèrgens declarats', 'Carta Mediterránea'),
('reels', 'carta_back', 'ca', 'Tornar', 'Carta Mediterránea'),
('reels', 'carta_back_videos', 'ca', 'Tornar als vídeos', 'Carta Mediterránea'),
('reels', 'carta_videos', 'ca', 'Vídeos', 'Carta Mediterránea'),
('reels', 'carta_selection', 'ca', 'La teva selecció', 'Carta Mediterránea'),
('reels', 'carta_to_order', 'ca', 'Per demanar', 'Carta Mediterránea'),
('reels', 'carta_total', 'ca', 'Total', 'Carta Mediterránea'),
('reels', 'carta_staff_note', 'ca', 'No s’envia res: ensenya-la al cambrer per demanar.', 'Carta Mediterránea'),
('reels', 'carta_show_waiter', 'ca', 'Ensenyar al cambrer', 'Carta Mediterránea'),
('reels', 'carta_keep_browsing', 'ca', 'Continuar mirant', 'Carta Mediterránea'),
('reels', 'carta_empty', 'ca', 'Encara no has triat res.', 'Carta Mediterránea'),
('reels', 'carta_for_waiter', 'ca', 'Per al cambrer', 'Carta Mediterránea'),
('reels', 'carta_badge_featured', 'ca', 'Destacat', 'Carta Mediterránea'),
('reels', 'carta_badge_new', 'ca', 'Nou', 'Carta Mediterránea'),
('reels', 'carta_badge_vegetarian', 'ca', 'Vegetarià', 'Carta Mediterránea'),
('reels', 'carta_badge_vegan', 'ca', 'Vegà', 'Carta Mediterránea'),
('reels', 'carta_badge_gluten_free', 'ca', 'Sense gluten', 'Carta Mediterránea'),
('reels', 'carta_no_video', 'ca', 'Aquest plat encara no té vídeo', 'Carta Mediterránea'),
('reels', 'carta_added', 'ca', 'Afegit', 'Carta Mediterránea'),
('reels', 'carta_liked', 'ca', 'Desat als teus m’agrada', 'Carta Mediterránea'),
('reels', 'carta_unliked', 'ca', 'Tret dels teus m’agrada', 'Carta Mediterránea'),
('reels', 'carta_likes_note', 'ca', 'Els desem en aquest mòbil: la propera vegada que vinguis encara hi seran.', 'Carta Mediterránea'),
('reels', 'carta_likes_empty', 'ca', 'Toca el cor, o dues vegades el vídeo, per desar un plat i decidir després.', 'Carta Mediterránea'),
('reels', 'carta_add_all', 'ca', 'Afegir-los tots per demanar', 'Carta Mediterránea'),
('reels', 'carta_top_liked', 'ca', 'El que més agrada', 'Carta Mediterránea'),
('reels', 'carta_top_liked_sub', 'ca', 'Segons els m’agrada de qui hi ha menjat', 'Carta Mediterránea'),
('reels', 'carta_dish_one', 'ca', '1 plat', 'Carta Mediterránea'),
('reels', 'carta_dish_other', 'ca', '{n} plats', 'Carta Mediterránea'),
('reels', 'carta_menu_count', 'ca', '{n} plats a la carta', 'Carta Mediterránea'),
('reels', 'carta_avoid_title', 'ca', 'Què evites?', 'Carta Mediterránea'),
('reels', 'carta_avoid_sub', 'ca', 'Marca el que no pots menjar i t’avisarem en cada plat que ho porti. Només es desa en aquest mòbil.', 'Carta Mediterránea'),
('reels', 'carta_avoid_on', 'ca', 'Ho evito', 'Carta Mediterránea'),
('reels', 'carta_this_dish', 'ca', 'Aquest plat porta', 'Carta Mediterránea'),
('reels', 'carta_contains', 'ca', 'Porta', 'Carta Mediterránea'),
('reels', 'carta_avoid_warn', 'ca', 'ho has marcat per evitar-ho', 'Carta Mediterránea'),
('reels', 'carta_ask_waiter', 'ca', 'Si tens una al·lèrgia greu, confirma-ho sempre amb el cambrer.', 'Carta Mediterránea'),
('reels', 'carta_see_allergens', 'ca', 'Veure al·lèrgens', 'Carta Mediterránea'),
('reels', 'carta_menu_allergens', 'ca', 'Al·lèrgens d’aquesta carta', 'Carta Mediterránea'),
('reels', 'carta_no_menu_allergens', 'ca', 'Aquest restaurant encara no ha marcat els al·lèrgens a la carta digital. Pregunta al cambrer abans de demanar.', 'Carta Mediterránea'),
('reels', 'carta_done', 'ca', 'Fet', 'Carta Mediterránea'),
('reels', 'carta_notif_title', 'ca', 'Avisos', 'Carta Mediterránea'),
('reels', 'carta_notif_lead', 'ca', 'T’avisem del que és nou, sense que ens donis el nom ni el telèfon.', 'Carta Mediterránea'),
('reels', 'carta_notif_1', 'ca', 'Plats nous', 'Carta Mediterránea'),
('reels', 'carta_notif_1_sub', 'ca', 'Quan entra alguna cosa a la carta', 'Carta Mediterránea'),
('reels', 'carta_notif_2', 'ca', 'Ofertes', 'Carta Mediterránea'),
('reels', 'carta_notif_2_sub', 'ca', 'Només les d’aquesta casa', 'Carta Mediterránea'),
('reels', 'carta_notif_3', 'ca', 'La teva targeta de segells', 'Carta Mediterránea'),
('reels', 'carta_notif_3_sub', 'ca', 'Quan et falti poc per al premi', 'Carta Mediterránea'),
('reels', 'carta_notif_on', 'ca', 'Activar avisos', 'Carta Mediterránea'),
('reels', 'carta_notif_active', 'ca', 'Avisos activats', 'Carta Mediterránea'),
('reels', 'carta_notif_off', 'ca', 'Desactivar avisos', 'Carta Mediterránea'),
('reels', 'carta_notif_note', 'ca', 'El navegador et demanarà permís. Els pots treure quan vulguis des d’aquí.', 'Carta Mediterránea'),
('reels', 'carta_notif_ios', 'ca', 'A l’iPhone, primer afegeix la carta a la pantalla d’inici.', 'Carta Mediterránea'),
('reels', 'carta_notif_ask', 'ca', 'T’avisem quan hi hagi plats nous o ofertes?', 'Carta Mediterránea'),
('reels', 'carta_notif_denied', 'ca', 'El navegador té els avisos bloquejats per a aquest web. Els pots permetre a la configuració.', 'Carta Mediterránea'),
('reels', 'carta_notif_sub_off', 'ca', 'Plats nous i ofertes', 'Carta Mediterránea'),
('reels', 'carta_notif_sub_on', 'ca', 'Activats', 'Carta Mediterránea'),
('reels', 'carta_reserve', 'ca', 'Reservar taula', 'Carta Mediterránea'),
('reels', 'carta_reserve_sub', 'ca', 'Tria dia i hora', 'Carta Mediterránea'),
('reels', 'carta_takeaway', 'ca', 'Demanar per emportar', 'Carta Mediterránea'),
('reels', 'carta_takeaway_sub', 'ca', 'Recull-ho al local o t’ho portem', 'Carta Mediterránea'),
('reels', 'carta_stamps', 'ca', 'Targeta de segells', 'Carta Mediterránea'),
('reels', 'carta_stamps_sub', 'ca', 'Suma un segell a cada visita', 'Carta Mediterránea'),
('reels', 'carta_offer', 'ca', 'Oferta de benvinguda', 'Carta Mediterránea'),
('reels', 'carta_offer_sub', 'ca', 'En tens una esperant-te', 'Carta Mediterránea'),
('reels', 'carta_rate', 'ca', 'Valora’ns', 'Carta Mediterránea'),
('reels', 'carta_rate_sub', 'ca', 'Un minut, i ens ajuda molt', 'Carta Mediterránea'),
('reels', 'carta_web', 'ca', 'La nostra web', 'Carta Mediterránea'),
('reels', 'carta_web_sub', 'ca', 'Història, esdeveniments i contacte', 'Carta Mediterránea'),
('reels', 'carta_whatsapp', 'ca', 'WhatsApp', 'Carta Mediterránea'),
('reels', 'carta_whatsapp_sub', 'ca', 'Escriu-nos', 'Carta Mediterránea'),
('reels', 'carta_instagram', 'ca', 'Instagram', 'Carta Mediterránea'),
('reels', 'carta_language', 'ca', 'Idioma', 'Carta Mediterránea'),
('reels', 'carta_current', 'ca', 'Actual', 'Carta Mediterránea'),
('reels', 'carta_privacy', 'ca', 'Privacitat', 'Carta Mediterránea'),
('reels', 'carta_minus', 'ca', 'Treure’n un', 'Carta Mediterránea'),
('reels', 'carta_plus', 'ca', 'Afegir-ne un', 'Carta Mediterránea'),
('reels', 'carta_dish_n', 'ca', 'Plat {n}', 'Carta Mediterránea'),
('reels', 'carta_empty_menu', 'ca', 'Ara mateix no hi ha carta disponible', 'Carta Mediterránea'),
('reels', 'carta_menu', 'ar', 'القائمة', 'Carta Mediterránea'),
('reels', 'carta_house_hint', 'ar', 'الحجز والتنبيهات والمزيد', 'Carta Mediterránea'),
('reels', 'carta_welcome_kicker', 'ar', 'أهلًا بكم في', 'Carta Mediterránea'),
('reels', 'carta_start', 'ar', 'اعرض القائمة', 'Carta Mediterránea'),
('reels', 'carta_more_languages', 'ar', 'لغات أخرى', 'Carta Mediterránea'),
('reels', 'carta_full_portion', 'ar', 'حصة كاملة', 'Carta Mediterránea'),
('reels', 'carta_choose_portion', 'ar', 'اختر الحصة', 'Carta Mediterránea'),
('reels', 'carta_quantity', 'ar', 'الكمية', 'Carta Mediterránea'),
('reels', 'carta_no_allergens', 'ar', 'لا توجد مسببات حساسية معلنة', 'Carta Mediterránea'),
('reels', 'carta_back', 'ar', 'رجوع', 'Carta Mediterránea'),
('reels', 'carta_back_videos', 'ar', 'العودة إلى الفيديوهات', 'Carta Mediterránea'),
('reels', 'carta_videos', 'ar', 'الفيديوهات', 'Carta Mediterránea'),
('reels', 'carta_selection', 'ar', 'اختياراتك', 'Carta Mediterránea'),
('reels', 'carta_to_order', 'ar', 'للطلب', 'Carta Mediterránea'),
('reels', 'carta_total', 'ar', 'المجموع', 'Carta Mediterránea'),
('reels', 'carta_staff_note', 'ar', 'لا يُرسل شيء: اعرضها على النادل لتطلب.', 'Carta Mediterránea'),
('reels', 'carta_show_waiter', 'ar', 'اعرضها على النادل', 'Carta Mediterránea'),
('reels', 'carta_keep_browsing', 'ar', 'تابع التصفح', 'Carta Mediterránea'),
('reels', 'carta_empty', 'ar', 'لم تختر شيئًا بعد.', 'Carta Mediterránea'),
('reels', 'carta_for_waiter', 'ar', 'للنادل', 'Carta Mediterránea'),
('reels', 'carta_badge_featured', 'ar', 'مميز', 'Carta Mediterránea'),
('reels', 'carta_badge_new', 'ar', 'جديد', 'Carta Mediterránea'),
('reels', 'carta_badge_vegetarian', 'ar', 'نباتي', 'Carta Mediterránea'),
('reels', 'carta_badge_vegan', 'ar', 'نباتي صرف', 'Carta Mediterránea'),
('reels', 'carta_badge_gluten_free', 'ar', 'خالٍ من الغلوتين', 'Carta Mediterránea'),
('reels', 'carta_no_video', 'ar', 'لا يوجد فيديو لهذا الطبق بعد', 'Carta Mediterránea'),
('reels', 'carta_added', 'ar', 'أُضيف', 'Carta Mediterránea'),
('reels', 'carta_liked', 'ar', 'حُفظ في إعجاباتك', 'Carta Mediterránea'),
('reels', 'carta_unliked', 'ar', 'أُزيل من إعجاباتك', 'Carta Mediterránea'),
('reels', 'carta_likes_note', 'ar', 'نحفظها على هذا الهاتف: ستجدها هنا في زيارتك القادمة.', 'Carta Mediterránea'),
('reels', 'carta_likes_empty', 'ar', 'المس القلب، أو المس الفيديو مرتين، لتحفظ طبقًا وتقرر لاحقًا.', 'Carta Mediterránea'),
('reels', 'carta_add_all', 'ar', 'أضف الكل إلى الطلب', 'Carta Mediterránea'),
('reels', 'carta_top_liked', 'ar', 'الأكثر إعجابًا', 'Carta Mediterránea'),
('reels', 'carta_top_liked_sub', 'ar', 'حسب إعجابات من أكلوا هنا', 'Carta Mediterránea'),
('reels', 'carta_dish_one', 'ar', 'طبق واحد', 'Carta Mediterránea'),
('reels', 'carta_dish_other', 'ar', 'الأطباق: {n}', 'Carta Mediterránea'),
('reels', 'carta_menu_count', 'ar', 'عدد الأطباق في القائمة: {n}', 'Carta Mediterránea'),
('reels', 'carta_avoid_title', 'ar', 'ماذا تتجنب؟', 'Carta Mediterránea'),
('reels', 'carta_avoid_sub', 'ar', 'حدّد ما لا يمكنك أكله وسننبهك في كل طبق يحتويه. يُحفظ على هذا الهاتف فقط.', 'Carta Mediterránea'),
('reels', 'carta_avoid_on', 'ar', 'أتجنبه', 'Carta Mediterránea'),
('reels', 'carta_this_dish', 'ar', 'يحتوي هذا الطبق على', 'Carta Mediterránea'),
('reels', 'carta_contains', 'ar', 'يحتوي على', 'Carta Mediterránea'),
('reels', 'carta_avoid_warn', 'ar', 'حدّدته للتجنب', 'Carta Mediterránea'),
('reels', 'carta_ask_waiter', 'ar', 'إن كانت لديك حساسية شديدة، تأكد دائمًا مع النادل.', 'Carta Mediterránea'),
('reels', 'carta_see_allergens', 'ar', 'عرض مسببات الحساسية', 'Carta Mediterránea'),
('reels', 'carta_menu_allergens', 'ar', 'مسببات الحساسية في هذه القائمة', 'Carta Mediterránea'),
('reels', 'carta_no_menu_allergens', 'ar', 'لم يحدد هذا المطعم بعد مسببات الحساسية في قائمته الرقمية. اسأل النادل قبل الطلب.', 'Carta Mediterránea'),
('reels', 'carta_done', 'ar', 'تم', 'Carta Mediterránea'),
('reels', 'carta_notif_title', 'ar', 'التنبيهات', 'Carta Mediterránea'),
('reels', 'carta_notif_lead', 'ar', 'نخبرك بالجديد دون أن نطلب اسمك أو رقم هاتفك.', 'Carta Mediterránea'),
('reels', 'carta_notif_1', 'ar', 'أطباق جديدة', 'Carta Mediterránea'),
('reels', 'carta_notif_1_sub', 'ar', 'عندما يُضاف شيء إلى القائمة', 'Carta Mediterránea'),
('reels', 'carta_notif_2', 'ar', 'عروض', 'Carta Mediterránea'),
('reels', 'carta_notif_2_sub', 'ar', 'من هذا المطعم فقط', 'Carta Mediterránea'),
('reels', 'carta_notif_3', 'ar', 'بطاقة الأختام', 'Carta Mediterránea'),
('reels', 'carta_notif_3_sub', 'ar', 'عندما تقترب من الجائزة', 'Carta Mediterránea'),
('reels', 'carta_notif_on', 'ar', 'فعّل التنبيهات', 'Carta Mediterránea'),
('reels', 'carta_notif_active', 'ar', 'التنبيهات مفعّلة', 'Carta Mediterránea'),
('reels', 'carta_notif_off', 'ar', 'أوقف التنبيهات', 'Carta Mediterránea'),
('reels', 'carta_notif_note', 'ar', 'سيطلب متصفحك الإذن. يمكنك إيقافها من هنا متى شئت.', 'Carta Mediterránea'),
('reels', 'carta_notif_ios', 'ar', 'على آيفون، أضف القائمة أولًا إلى الشاشة الرئيسية.', 'Carta Mediterránea'),
('reels', 'carta_notif_ask', 'ar', 'هل نخبرك بالأطباق الجديدة والعروض؟', 'Carta Mediterránea'),
('reels', 'carta_notif_denied', 'ar', 'متصفحك يحظر التنبيهات لهذا الموقع. يمكنك السماح بها من الإعدادات.', 'Carta Mediterránea'),
('reels', 'carta_notif_sub_off', 'ar', 'أطباق جديدة وعروض', 'Carta Mediterránea'),
('reels', 'carta_notif_sub_on', 'ar', 'مفعّلة', 'Carta Mediterránea'),
('reels', 'carta_reserve', 'ar', 'احجز طاولة', 'Carta Mediterránea'),
('reels', 'carta_reserve_sub', 'ar', 'اختر اليوم والساعة', 'Carta Mediterránea'),
('reels', 'carta_takeaway', 'ar', 'اطلب للاستلام', 'Carta Mediterránea'),
('reels', 'carta_takeaway_sub', 'ar', 'استلمه من المطعم أو نوصله إليك', 'Carta Mediterránea'),
('reels', 'carta_stamps', 'ar', 'بطاقة الأختام', 'Carta Mediterránea'),
('reels', 'carta_stamps_sub', 'ar', 'ختم في كل زيارة', 'Carta Mediterránea'),
('reels', 'carta_offer', 'ar', 'عرض الترحيب', 'Carta Mediterránea'),
('reels', 'carta_offer_sub', 'ar', 'هناك عرض بانتظارك', 'Carta Mediterránea'),
('reels', 'carta_rate', 'ar', 'قيّمنا', 'Carta Mediterránea'),
('reels', 'carta_rate_sub', 'ar', 'دقيقة واحدة، وتساعدنا كثيرًا', 'Carta Mediterránea'),
('reels', 'carta_web', 'ar', 'موقعنا', 'Carta Mediterránea'),
('reels', 'carta_web_sub', 'ar', 'قصتنا والفعاليات والتواصل', 'Carta Mediterránea'),
('reels', 'carta_whatsapp', 'ar', 'واتساب', 'Carta Mediterránea'),
('reels', 'carta_whatsapp_sub', 'ar', 'راسلنا', 'Carta Mediterránea'),
('reels', 'carta_instagram', 'ar', 'إنستغرام', 'Carta Mediterránea'),
('reels', 'carta_language', 'ar', 'اللغة', 'Carta Mediterránea'),
('reels', 'carta_current', 'ar', 'الحالية', 'Carta Mediterránea'),
('reels', 'carta_privacy', 'ar', 'الخصوصية', 'Carta Mediterránea'),
('reels', 'carta_minus', 'ar', 'أزل واحدًا', 'Carta Mediterránea'),
('reels', 'carta_plus', 'ar', 'أضف واحدًا', 'Carta Mediterránea'),
('reels', 'carta_dish_n', 'ar', 'الطبق {n}', 'Carta Mediterránea'),
('reels', 'carta_empty_menu', 'ar', 'لا توجد قائمة متاحة حاليًا', 'Carta Mediterránea'),
('reels', 'carta_menu', 'ru', 'Меню', 'Carta Mediterránea'),
('reels', 'carta_house_hint', 'ru', 'Бронирование, уведомления и другое', 'Carta Mediterránea'),
('reels', 'carta_welcome_kicker', 'ru', 'Добро пожаловать в', 'Carta Mediterránea'),
('reels', 'carta_start', 'ru', 'Открыть меню', 'Carta Mediterránea'),
('reels', 'carta_more_languages', 'ru', 'Другие языки', 'Carta Mediterránea'),
('reels', 'carta_full_portion', 'ru', 'Целая порция', 'Carta Mediterránea'),
('reels', 'carta_choose_portion', 'ru', 'Выберите порцию', 'Carta Mediterránea'),
('reels', 'carta_quantity', 'ru', 'Количество', 'Carta Mediterránea'),
('reels', 'carta_no_allergens', 'ru', 'Аллергены не указаны', 'Carta Mediterránea'),
('reels', 'carta_back', 'ru', 'Назад', 'Carta Mediterránea'),
('reels', 'carta_back_videos', 'ru', 'Назад к видео', 'Carta Mediterránea'),
('reels', 'carta_videos', 'ru', 'Видео', 'Carta Mediterránea'),
('reels', 'carta_selection', 'ru', 'Ваш выбор', 'Carta Mediterránea'),
('reels', 'carta_to_order', 'ru', 'К заказу', 'Carta Mediterránea'),
('reels', 'carta_total', 'ru', 'Итого', 'Carta Mediterránea'),
('reels', 'carta_staff_note', 'ru', 'Ничего не отправляется: покажите это официанту, чтобы заказать.', 'Carta Mediterránea'),
('reels', 'carta_show_waiter', 'ru', 'Показать официанту', 'Carta Mediterránea'),
('reels', 'carta_keep_browsing', 'ru', 'Смотреть дальше', 'Carta Mediterránea'),
('reels', 'carta_empty', 'ru', 'Вы пока ничего не выбрали.', 'Carta Mediterránea'),
('reels', 'carta_for_waiter', 'ru', 'Для официанта', 'Carta Mediterránea'),
('reels', 'carta_badge_featured', 'ru', 'Рекомендуем', 'Carta Mediterránea'),
('reels', 'carta_badge_new', 'ru', 'Новинка', 'Carta Mediterránea'),
('reels', 'carta_badge_vegetarian', 'ru', 'Вегетарианское', 'Carta Mediterránea'),
('reels', 'carta_badge_vegan', 'ru', 'Веганское', 'Carta Mediterránea'),
('reels', 'carta_badge_gluten_free', 'ru', 'Без глютена', 'Carta Mediterránea'),
('reels', 'carta_no_video', 'ru', 'У этого блюда пока нет видео', 'Carta Mediterránea'),
('reels', 'carta_added', 'ru', 'Добавлено', 'Carta Mediterránea'),
('reels', 'carta_liked', 'ru', 'Сохранено в избранном', 'Carta Mediterránea'),
('reels', 'carta_unliked', 'ru', 'Удалено из избранного', 'Carta Mediterránea'),
('reels', 'carta_likes_note', 'ru', 'Мы храним их на этом телефоне: в следующий раз они будут здесь.', 'Carta Mediterránea'),
('reels', 'carta_likes_empty', 'ru', 'Нажмите на сердце или дважды на видео, чтобы сохранить блюдо и решить позже.', 'Carta Mediterránea'),
('reels', 'carta_add_all', 'ru', 'Добавить всё к заказу', 'Carta Mediterránea'),
('reels', 'carta_top_liked', 'ru', 'Самое любимое', 'Carta Mediterránea'),
('reels', 'carta_top_liked_sub', 'ru', 'По отметкам тех, кто здесь ел', 'Carta Mediterránea'),
('reels', 'carta_dish_one', 'ru', '1 блюдо', 'Carta Mediterránea'),
('reels', 'carta_dish_other', 'ru', 'Блюд: {n}', 'Carta Mediterránea'),
('reels', 'carta_menu_count', 'ru', 'Блюд в меню: {n}', 'Carta Mediterránea'),
('reels', 'carta_avoid_title', 'ru', 'Чего вы избегаете?', 'Carta Mediterránea'),
('reels', 'carta_avoid_sub', 'ru', 'Отметьте, что вам нельзя, и мы предупредим о каждом блюде, где это есть. Сохраняется только на этом телефоне.', 'Carta Mediterránea'),
('reels', 'carta_avoid_on', 'ru', 'Избегаю', 'Carta Mediterránea'),
('reels', 'carta_this_dish', 'ru', 'В этом блюде есть', 'Carta Mediterránea'),
('reels', 'carta_contains', 'ru', 'Содержит', 'Carta Mediterránea'),
('reels', 'carta_avoid_warn', 'ru', 'вы отметили это как нежелательное', 'Carta Mediterránea'),
('reels', 'carta_ask_waiter', 'ru', 'При серьёзной аллергии всегда уточняйте у официанта.', 'Carta Mediterránea'),
('reels', 'carta_see_allergens', 'ru', 'Аллергены', 'Carta Mediterránea'),
('reels', 'carta_menu_allergens', 'ru', 'Аллергены в этом меню', 'Carta Mediterránea'),
('reels', 'carta_no_menu_allergens', 'ru', 'Этот ресторан ещё не указал аллергены в цифровом меню. Спросите официанта перед заказом.', 'Carta Mediterránea'),
('reels', 'carta_done', 'ru', 'Готово', 'Carta Mediterránea'),
('reels', 'carta_notif_title', 'ru', 'Уведомления', 'Carta Mediterránea'),
('reels', 'carta_notif_lead', 'ru', 'Сообщаем о новинках — без вашего имени и телефона.', 'Carta Mediterránea'),
('reels', 'carta_notif_1', 'ru', 'Новые блюда', 'Carta Mediterránea'),
('reels', 'carta_notif_1_sub', 'ru', 'Когда в меню появляется что-то новое', 'Carta Mediterránea'),
('reels', 'carta_notif_2', 'ru', 'Предложения', 'Carta Mediterránea'),
('reels', 'carta_notif_2_sub', 'ru', 'Только от этого ресторана', 'Carta Mediterránea'),
('reels', 'carta_notif_3', 'ru', 'Ваша карта со штампами', 'Carta Mediterránea'),
('reels', 'carta_notif_3_sub', 'ru', 'Когда награда уже близко', 'Carta Mediterránea'),
('reels', 'carta_notif_on', 'ru', 'Включить уведомления', 'Carta Mediterránea'),
('reels', 'carta_notif_active', 'ru', 'Уведомления включены', 'Carta Mediterránea'),
('reels', 'carta_notif_off', 'ru', 'Выключить уведомления', 'Carta Mediterránea'),
('reels', 'carta_notif_note', 'ru', 'Браузер попросит разрешение. Выключить их можно здесь в любой момент.', 'Carta Mediterránea'),
('reels', 'carta_notif_ios', 'ru', 'На iPhone сначала добавьте меню на экран «Домой».', 'Carta Mediterránea'),
('reels', 'carta_notif_ask', 'ru', 'Сообщать о новых блюдах и предложениях?', 'Carta Mediterránea'),
('reels', 'carta_notif_denied', 'ru', 'Браузер блокирует уведомления для этого сайта. Разрешить их можно в настройках.', 'Carta Mediterránea'),
('reels', 'carta_notif_sub_off', 'ru', 'Новые блюда и предложения', 'Carta Mediterránea'),
('reels', 'carta_notif_sub_on', 'ru', 'Включены', 'Carta Mediterránea'),
('reels', 'carta_reserve', 'ru', 'Забронировать столик', 'Carta Mediterránea'),
('reels', 'carta_reserve_sub', 'ru', 'Выберите день и время', 'Carta Mediterránea'),
('reels', 'carta_takeaway', 'ru', 'Заказать с собой', 'Carta Mediterránea'),
('reels', 'carta_takeaway_sub', 'ru', 'Заберите сами или мы привезём', 'Carta Mediterránea'),
('reels', 'carta_stamps', 'ru', 'Карта со штампами', 'Carta Mediterránea'),
('reels', 'carta_stamps_sub', 'ru', 'Штамп за каждый визит', 'Carta Mediterránea'),
('reels', 'carta_offer', 'ru', 'Приветственное предложение', 'Carta Mediterránea'),
('reels', 'carta_offer_sub', 'ru', 'Вас ждёт подарок', 'Carta Mediterránea'),
('reels', 'carta_rate', 'ru', 'Оцените нас', 'Carta Mediterránea'),
('reels', 'carta_rate_sub', 'ru', 'Одна минута — и это нам очень поможет', 'Carta Mediterránea'),
('reels', 'carta_web', 'ru', 'Наш сайт', 'Carta Mediterránea'),
('reels', 'carta_web_sub', 'ru', 'История, события и контакты', 'Carta Mediterránea'),
('reels', 'carta_whatsapp', 'ru', 'WhatsApp', 'Carta Mediterránea'),
('reels', 'carta_whatsapp_sub', 'ru', 'Напишите нам', 'Carta Mediterránea'),
('reels', 'carta_instagram', 'ru', 'Instagram', 'Carta Mediterránea'),
('reels', 'carta_language', 'ru', 'Язык', 'Carta Mediterránea'),
('reels', 'carta_current', 'ru', 'Текущий', 'Carta Mediterránea'),
('reels', 'carta_privacy', 'ru', 'Конфиденциальность', 'Carta Mediterránea'),
('reels', 'carta_minus', 'ru', 'Убрать одно', 'Carta Mediterránea'),
('reels', 'carta_plus', 'ru', 'Добавить одно', 'Carta Mediterránea'),
('reels', 'carta_dish_n', 'ru', 'Блюдо {n}', 'Carta Mediterránea'),
('reels', 'carta_empty_menu', 'ru', 'Сейчас меню недоступно', 'Carta Mediterránea'),
('reels', 'carta_menu', 'uk', 'Меню', 'Carta Mediterránea'),
('reels', 'carta_house_hint', 'uk', 'Бронювання, сповіщення та інше', 'Carta Mediterránea'),
('reels', 'carta_welcome_kicker', 'uk', 'Ласкаво просимо до', 'Carta Mediterránea'),
('reels', 'carta_start', 'uk', 'Відкрити меню', 'Carta Mediterránea'),
('reels', 'carta_more_languages', 'uk', 'Інші мови', 'Carta Mediterránea'),
('reels', 'carta_full_portion', 'uk', 'Ціла порція', 'Carta Mediterránea'),
('reels', 'carta_choose_portion', 'uk', 'Оберіть порцію', 'Carta Mediterránea'),
('reels', 'carta_quantity', 'uk', 'Кількість', 'Carta Mediterránea'),
('reels', 'carta_no_allergens', 'uk', 'Алергени не вказані', 'Carta Mediterránea'),
('reels', 'carta_back', 'uk', 'Назад', 'Carta Mediterránea'),
('reels', 'carta_back_videos', 'uk', 'Назад до відео', 'Carta Mediterránea'),
('reels', 'carta_videos', 'uk', 'Відео', 'Carta Mediterránea'),
('reels', 'carta_selection', 'uk', 'Ваш вибір', 'Carta Mediterránea'),
('reels', 'carta_to_order', 'uk', 'До замовлення', 'Carta Mediterránea'),
('reels', 'carta_total', 'uk', 'Разом', 'Carta Mediterránea'),
('reels', 'carta_staff_note', 'uk', 'Нічого не надсилається: покажіть це офіціанту, щоб замовити.', 'Carta Mediterránea'),
('reels', 'carta_show_waiter', 'uk', 'Показати офіціанту', 'Carta Mediterránea'),
('reels', 'carta_keep_browsing', 'uk', 'Дивитися далі', 'Carta Mediterránea'),
('reels', 'carta_empty', 'uk', 'Ви ще нічого не обрали.', 'Carta Mediterránea'),
('reels', 'carta_for_waiter', 'uk', 'Для офіціанта', 'Carta Mediterránea'),
('reels', 'carta_badge_featured', 'uk', 'Рекомендуємо', 'Carta Mediterránea'),
('reels', 'carta_badge_new', 'uk', 'Новинка', 'Carta Mediterránea'),
('reels', 'carta_badge_vegetarian', 'uk', 'Вегетаріанське', 'Carta Mediterránea'),
('reels', 'carta_badge_vegan', 'uk', 'Веганське', 'Carta Mediterránea'),
('reels', 'carta_badge_gluten_free', 'uk', 'Без глютену', 'Carta Mediterránea'),
('reels', 'carta_no_video', 'uk', 'Ця страва ще не має відео', 'Carta Mediterránea'),
('reels', 'carta_added', 'uk', 'Додано', 'Carta Mediterránea'),
('reels', 'carta_liked', 'uk', 'Збережено в улюблених', 'Carta Mediterránea'),
('reels', 'carta_unliked', 'uk', 'Видалено з улюблених', 'Carta Mediterránea'),
('reels', 'carta_likes_note', 'uk', 'Ми зберігаємо їх на цьому телефоні: наступного разу вони будуть тут.', 'Carta Mediterránea'),
('reels', 'carta_likes_empty', 'uk', 'Торкніться серця або двічі відео, щоб зберегти страву й вирішити пізніше.', 'Carta Mediterránea'),
('reels', 'carta_add_all', 'uk', 'Додати все до замовлення', 'Carta Mediterránea'),
('reels', 'carta_top_liked', 'uk', 'Найулюбленіше', 'Carta Mediterránea'),
('reels', 'carta_top_liked_sub', 'uk', 'За вподобаннями тих, хто тут їв', 'Carta Mediterránea'),
('reels', 'carta_dish_one', 'uk', '1 страва', 'Carta Mediterránea'),
('reels', 'carta_dish_other', 'uk', 'Страв: {n}', 'Carta Mediterránea'),
('reels', 'carta_menu_count', 'uk', 'Страв у меню: {n}', 'Carta Mediterránea'),
('reels', 'carta_avoid_title', 'uk', 'Чого ви уникаєте?', 'Carta Mediterránea'),
('reels', 'carta_avoid_sub', 'uk', 'Позначте, що вам не можна, і ми попередимо про кожну страву, де це є. Зберігається лише на цьому телефоні.', 'Carta Mediterránea'),
('reels', 'carta_avoid_on', 'uk', 'Уникаю', 'Carta Mediterránea'),
('reels', 'carta_this_dish', 'uk', 'У цій страві є', 'Carta Mediterránea'),
('reels', 'carta_contains', 'uk', 'Містить', 'Carta Mediterránea'),
('reels', 'carta_avoid_warn', 'uk', 'ви позначили це як небажане', 'Carta Mediterránea'),
('reels', 'carta_ask_waiter', 'uk', 'Якщо у вас сильна алергія, завжди уточнюйте в офіціанта.', 'Carta Mediterránea'),
('reels', 'carta_see_allergens', 'uk', 'Алергени', 'Carta Mediterránea'),
('reels', 'carta_menu_allergens', 'uk', 'Алергени в цьому меню', 'Carta Mediterránea'),
('reels', 'carta_no_menu_allergens', 'uk', 'Цей ресторан ще не вказав алергени в цифровому меню. Запитайте офіціанта перед замовленням.', 'Carta Mediterránea'),
('reels', 'carta_done', 'uk', 'Готово', 'Carta Mediterránea'),
('reels', 'carta_notif_title', 'uk', 'Сповіщення', 'Carta Mediterránea'),
('reels', 'carta_notif_lead', 'uk', 'Повідомляємо про новинки — без вашого імені й телефону.', 'Carta Mediterránea'),
('reels', 'carta_notif_1', 'uk', 'Нові страви', 'Carta Mediterránea'),
('reels', 'carta_notif_1_sub', 'uk', 'Коли в меню з’являється щось нове', 'Carta Mediterránea'),
('reels', 'carta_notif_2', 'uk', 'Пропозиції', 'Carta Mediterránea'),
('reels', 'carta_notif_2_sub', 'uk', 'Лише від цього ресторану', 'Carta Mediterránea'),
('reels', 'carta_notif_3', 'uk', 'Ваша картка зі штампами', 'Carta Mediterránea'),
('reels', 'carta_notif_3_sub', 'uk', 'Коли нагорода вже близько', 'Carta Mediterránea'),
('reels', 'carta_notif_on', 'uk', 'Увімкнути сповіщення', 'Carta Mediterránea'),
('reels', 'carta_notif_active', 'uk', 'Сповіщення увімкнено', 'Carta Mediterránea'),
('reels', 'carta_notif_off', 'uk', 'Вимкнути сповіщення', 'Carta Mediterránea'),
('reels', 'carta_notif_note', 'uk', 'Браузер попросить дозвіл. Вимкнути їх можна тут будь-коли.', 'Carta Mediterránea'),
('reels', 'carta_notif_ios', 'uk', 'На iPhone спочатку додайте меню на початковий екран.', 'Carta Mediterránea'),
('reels', 'carta_notif_ask', 'uk', 'Повідомляти про нові страви й пропозиції?', 'Carta Mediterránea'),
('reels', 'carta_notif_denied', 'uk', 'Браузер блокує сповіщення для цього сайту. Дозволити їх можна в налаштуваннях.', 'Carta Mediterránea'),
('reels', 'carta_notif_sub_off', 'uk', 'Нові страви й пропозиції', 'Carta Mediterránea'),
('reels', 'carta_notif_sub_on', 'uk', 'Увімкнено', 'Carta Mediterránea'),
('reels', 'carta_reserve', 'uk', 'Забронювати столик', 'Carta Mediterránea'),
('reels', 'carta_reserve_sub', 'uk', 'Оберіть день і час', 'Carta Mediterránea'),
('reels', 'carta_takeaway', 'uk', 'Замовити з собою', 'Carta Mediterránea'),
('reels', 'carta_takeaway_sub', 'uk', 'Заберіть самі або ми привеземо', 'Carta Mediterránea'),
('reels', 'carta_stamps', 'uk', 'Картка зі штампами', 'Carta Mediterránea'),
('reels', 'carta_stamps_sub', 'uk', 'Штамп за кожен візит', 'Carta Mediterránea'),
('reels', 'carta_offer', 'uk', 'Вітальна пропозиція', 'Carta Mediterránea'),
('reels', 'carta_offer_sub', 'uk', 'На вас чекає подарунок', 'Carta Mediterránea'),
('reels', 'carta_rate', 'uk', 'Оцініть нас', 'Carta Mediterránea'),
('reels', 'carta_rate_sub', 'uk', 'Одна хвилина — і це нам дуже допоможе', 'Carta Mediterránea'),
('reels', 'carta_web', 'uk', 'Наш сайт', 'Carta Mediterránea'),
('reels', 'carta_web_sub', 'uk', 'Історія, події та контакти', 'Carta Mediterránea'),
('reels', 'carta_whatsapp', 'uk', 'WhatsApp', 'Carta Mediterránea'),
('reels', 'carta_whatsapp_sub', 'uk', 'Напишіть нам', 'Carta Mediterránea'),
('reels', 'carta_instagram', 'uk', 'Instagram', 'Carta Mediterránea'),
('reels', 'carta_language', 'uk', 'Мова', 'Carta Mediterránea'),
('reels', 'carta_current', 'uk', 'Поточна', 'Carta Mediterránea'),
('reels', 'carta_privacy', 'uk', 'Конфіденційність', 'Carta Mediterránea'),
('reels', 'carta_minus', 'uk', 'Прибрати одну', 'Carta Mediterránea'),
('reels', 'carta_plus', 'uk', 'Додати одну', 'Carta Mediterránea'),
('reels', 'carta_dish_n', 'uk', 'Страва {n}', 'Carta Mediterránea'),
('reels', 'carta_empty_menu', 'uk', 'Зараз меню недоступне', 'Carta Mediterránea'),
('reels', 'carta_menu', 'zh', '菜单', 'Carta Mediterránea'),
('reels', 'carta_house_hint', 'zh', '预订、通知及更多', 'Carta Mediterránea'),
('reels', 'carta_welcome_kicker', 'zh', '欢迎光临', 'Carta Mediterránea'),
('reels', 'carta_start', 'zh', '查看菜单', 'Carta Mediterránea'),
('reels', 'carta_more_languages', 'zh', '更多语言', 'Carta Mediterránea'),
('reels', 'carta_full_portion', 'zh', '整份', 'Carta Mediterránea'),
('reels', 'carta_choose_portion', 'zh', '选择份量', 'Carta Mediterránea'),
('reels', 'carta_quantity', 'zh', '数量', 'Carta Mediterránea'),
('reels', 'carta_no_allergens', 'zh', '未标注过敏原', 'Carta Mediterránea'),
('reels', 'carta_back', 'zh', '返回', 'Carta Mediterránea'),
('reels', 'carta_back_videos', 'zh', '返回视频', 'Carta Mediterránea'),
('reels', 'carta_videos', 'zh', '视频', 'Carta Mediterránea'),
('reels', 'carta_selection', 'zh', '我的选择', 'Carta Mediterránea'),
('reels', 'carta_to_order', 'zh', '待点', 'Carta Mediterránea'),
('reels', 'carta_total', 'zh', '合计', 'Carta Mediterránea'),
('reels', 'carta_staff_note', 'zh', '不会发送任何内容：请出示给服务员点餐。', 'Carta Mediterránea'),
('reels', 'carta_show_waiter', 'zh', '出示给服务员', 'Carta Mediterránea'),
('reels', 'carta_keep_browsing', 'zh', '继续浏览', 'Carta Mediterránea'),
('reels', 'carta_empty', 'zh', '您还没有选择任何菜品。', 'Carta Mediterránea'),
('reels', 'carta_for_waiter', 'zh', '给服务员', 'Carta Mediterránea'),
('reels', 'carta_badge_featured', 'zh', '推荐', 'Carta Mediterránea'),
('reels', 'carta_badge_new', 'zh', '新品', 'Carta Mediterránea'),
('reels', 'carta_badge_vegetarian', 'zh', '素食', 'Carta Mediterránea'),
('reels', 'carta_badge_vegan', 'zh', '纯素', 'Carta Mediterránea'),
('reels', 'carta_badge_gluten_free', 'zh', '无麸质', 'Carta Mediterránea'),
('reels', 'carta_no_video', 'zh', '这道菜暂无视频', 'Carta Mediterránea'),
('reels', 'carta_added', 'zh', '已添加', 'Carta Mediterránea'),
('reels', 'carta_liked', 'zh', '已加入喜欢', 'Carta Mediterránea'),
('reels', 'carta_unliked', 'zh', '已从喜欢中移除', 'Carta Mediterránea'),
('reels', 'carta_likes_note', 'zh', '保存在这部手机上：下次来时还在。', 'Carta Mediterránea'),
('reels', 'carta_likes_empty', 'zh', '点击爱心，或双击视频，即可收藏菜品稍后再决定。', 'Carta Mediterránea'),
('reels', 'carta_add_all', 'zh', '全部加入待点', 'Carta Mediterránea'),
('reels', 'carta_top_liked', 'zh', '最受喜爱', 'Carta Mediterránea'),
('reels', 'carta_top_liked_sub', 'zh', '根据在这里用过餐的客人点赞', 'Carta Mediterránea'),
('reels', 'carta_dish_one', 'zh', '1 道菜', 'Carta Mediterránea'),
('reels', 'carta_dish_other', 'zh', '{n} 道菜', 'Carta Mediterránea'),
('reels', 'carta_menu_count', 'zh', '菜单共 {n} 道菜', 'Carta Mediterránea'),
('reels', 'carta_avoid_title', 'zh', '您需要避开什么？', 'Carta Mediterránea'),
('reels', 'carta_avoid_sub', 'zh', '标出您不能吃的成分，含有它的每道菜都会提醒您。仅保存在这部手机上。', 'Carta Mediterránea'),
('reels', 'carta_avoid_on', 'zh', '避开', 'Carta Mediterránea'),
('reels', 'carta_this_dish', 'zh', '这道菜含有', 'Carta Mediterránea'),
('reels', 'carta_contains', 'zh', '含有', 'Carta Mediterránea'),
('reels', 'carta_avoid_warn', 'zh', '您已标记避开', 'Carta Mediterránea'),
('reels', 'carta_ask_waiter', 'zh', '如有严重过敏，请务必向服务员确认。', 'Carta Mediterránea'),
('reels', 'carta_see_allergens', 'zh', '查看过敏原', 'Carta Mediterránea'),
('reels', 'carta_menu_allergens', 'zh', '本菜单的过敏原', 'Carta Mediterránea'),
('reels', 'carta_no_menu_allergens', 'zh', '这家餐厅尚未在电子菜单中标注过敏原。点餐前请询问服务员。', 'Carta Mediterránea'),
('reels', 'carta_done', 'zh', '完成', 'Carta Mediterránea'),
('reels', 'carta_notif_title', 'zh', '通知', 'Carta Mediterránea'),
('reels', 'carta_notif_lead', 'zh', '有新鲜事就告诉您，无需留下姓名或电话。', 'Carta Mediterránea'),
('reels', 'carta_notif_1', 'zh', '新菜品', 'Carta Mediterránea'),
('reels', 'carta_notif_1_sub', 'zh', '菜单上新时', 'Carta Mediterránea'),
('reels', 'carta_notif_2', 'zh', '优惠', 'Carta Mediterránea'),
('reels', 'carta_notif_2_sub', 'zh', '仅限本店', 'Carta Mediterránea'),
('reels', 'carta_notif_3', 'zh', '您的集章卡', 'Carta Mediterránea'),
('reels', 'carta_notif_3_sub', 'zh', '快要获得奖励时', 'Carta Mediterránea'),
('reels', 'carta_notif_on', 'zh', '开启通知', 'Carta Mediterránea'),
('reels', 'carta_notif_active', 'zh', '通知已开启', 'Carta Mediterránea'),
('reels', 'carta_notif_off', 'zh', '关闭通知', 'Carta Mediterránea'),
('reels', 'carta_notif_note', 'zh', '浏览器会请求权限。您可随时在这里关闭。', 'Carta Mediterránea'),
('reels', 'carta_notif_ios', 'zh', '在 iPhone 上，请先将菜单添加到主屏幕。', 'Carta Mediterránea'),
('reels', 'carta_notif_ask', 'zh', '有新菜品或优惠时通知您吗？', 'Carta Mediterránea'),
('reels', 'carta_notif_denied', 'zh', '您的浏览器已屏蔽此网站的通知，可在浏览器设置中允许。', 'Carta Mediterránea'),
('reels', 'carta_notif_sub_off', 'zh', '新菜品和优惠', 'Carta Mediterránea'),
('reels', 'carta_notif_sub_on', 'zh', '已开启', 'Carta Mediterránea'),
('reels', 'carta_reserve', 'zh', '预订餐桌', 'Carta Mediterránea'),
('reels', 'carta_reserve_sub', 'zh', '选择日期和时间', 'Carta Mediterránea'),
('reels', 'carta_takeaway', 'zh', '外带点餐', 'Carta Mediterránea'),
('reels', 'carta_takeaway_sub', 'zh', '到店自取或送餐上门', 'Carta Mediterránea'),
('reels', 'carta_stamps', 'zh', '集章卡', 'Carta Mediterránea'),
('reels', 'carta_stamps_sub', 'zh', '每次光临集一个章', 'Carta Mediterránea'),
('reels', 'carta_offer', 'zh', '欢迎优惠', 'Carta Mediterránea'),
('reels', 'carta_offer_sub', 'zh', '有一份优惠在等您', 'Carta Mediterránea'),
('reels', 'carta_rate', 'zh', '给我们评分', 'Carta Mediterránea'),
('reels', 'carta_rate_sub', 'zh', '只需一分钟，对我们帮助很大', 'Carta Mediterránea'),
('reels', 'carta_web', 'zh', '我们的网站', 'Carta Mediterránea'),
('reels', 'carta_web_sub', 'zh', '品牌故事、活动和联系方式', 'Carta Mediterránea'),
('reels', 'carta_whatsapp', 'zh', 'WhatsApp', 'Carta Mediterránea'),
('reels', 'carta_whatsapp_sub', 'zh', '给我们留言', 'Carta Mediterránea'),
('reels', 'carta_instagram', 'zh', 'Instagram', 'Carta Mediterránea'),
('reels', 'carta_language', 'zh', '语言', 'Carta Mediterránea'),
('reels', 'carta_current', 'zh', '当前', 'Carta Mediterránea'),
('reels', 'carta_privacy', 'zh', '隐私', 'Carta Mediterránea'),
('reels', 'carta_minus', 'zh', '减少一份', 'Carta Mediterránea'),
('reels', 'carta_plus', 'zh', '增加一份', 'Carta Mediterránea'),
('reels', 'carta_dish_n', 'zh', '第 {n} 道菜', 'Carta Mediterránea'),
('reels', 'carta_empty_menu', 'zh', '目前没有可用的菜单', 'Carta Mediterránea'),
('reels', 'carta_menu', 'ja', 'メニュー', 'Carta Mediterránea'),
('reels', 'carta_house_hint', 'ja', '予約・お知らせなど', 'Carta Mediterránea'),
('reels', 'carta_welcome_kicker', 'ja', 'ようこそ', 'Carta Mediterránea'),
('reels', 'carta_start', 'ja', 'メニューを見る', 'Carta Mediterránea'),
('reels', 'carta_more_languages', 'ja', 'ほかの言語', 'Carta Mediterránea'),
('reels', 'carta_full_portion', 'ja', 'レギュラー', 'Carta Mediterránea'),
('reels', 'carta_choose_portion', 'ja', 'サイズを選ぶ', 'Carta Mediterránea'),
('reels', 'carta_quantity', 'ja', '数量', 'Carta Mediterránea'),
('reels', 'carta_no_allergens', 'ja', 'アレルゲンの表示なし', 'Carta Mediterránea'),
('reels', 'carta_back', 'ja', '戻る', 'Carta Mediterránea'),
('reels', 'carta_back_videos', 'ja', '動画に戻る', 'Carta Mediterránea'),
('reels', 'carta_videos', 'ja', '動画', 'Carta Mediterránea'),
('reels', 'carta_selection', 'ja', 'あなたの選択', 'Carta Mediterránea'),
('reels', 'carta_to_order', 'ja', '注文する', 'Carta Mediterránea'),
('reels', 'carta_total', 'ja', '合計', 'Carta Mediterránea'),
('reels', 'carta_staff_note', 'ja', '送信はされません。注文するときはスタッフに見せてください。', 'Carta Mediterránea'),
('reels', 'carta_show_waiter', 'ja', 'スタッフに見せる', 'Carta Mediterránea'),
('reels', 'carta_keep_browsing', 'ja', '続けて見る', 'Carta Mediterránea'),
('reels', 'carta_empty', 'ja', 'まだ何も選んでいません。', 'Carta Mediterránea'),
('reels', 'carta_for_waiter', 'ja', 'スタッフ用', 'Carta Mediterránea'),
('reels', 'carta_badge_featured', 'ja', 'おすすめ', 'Carta Mediterránea'),
('reels', 'carta_badge_new', 'ja', '新メニュー', 'Carta Mediterránea'),
('reels', 'carta_badge_vegetarian', 'ja', 'ベジタリアン', 'Carta Mediterránea'),
('reels', 'carta_badge_vegan', 'ja', 'ヴィーガン', 'Carta Mediterránea'),
('reels', 'carta_badge_gluten_free', 'ja', 'グルテンフリー', 'Carta Mediterránea'),
('reels', 'carta_no_video', 'ja', 'この料理の動画はまだありません', 'Carta Mediterránea'),
('reels', 'carta_added', 'ja', '追加しました', 'Carta Mediterránea'),
('reels', 'carta_liked', 'ja', 'お気に入りに保存しました', 'Carta Mediterránea'),
('reels', 'carta_unliked', 'ja', 'お気に入りから外しました', 'Carta Mediterránea'),
('reels', 'carta_likes_note', 'ja', 'このスマホに保存されます。次に来たときも残っています。', 'Carta Mediterránea'),
('reels', 'carta_likes_empty', 'ja', 'ハートをタップするか動画をダブルタップすると、料理を保存してあとで決められます。', 'Carta Mediterránea'),
('reels', 'carta_add_all', 'ja', 'すべて注文に追加', 'Carta Mediterránea'),
('reels', 'carta_top_liked', 'ja', 'いちばん人気', 'Carta Mediterránea'),
('reels', 'carta_top_liked_sub', 'ja', 'ここで食事をした人の「いいね」より', 'Carta Mediterránea'),
('reels', 'carta_dish_one', 'ja', '1品', 'Carta Mediterránea'),
('reels', 'carta_dish_other', 'ja', '{n}品', 'Carta Mediterránea'),
('reels', 'carta_menu_count', 'ja', 'メニューは全{n}品', 'Carta Mediterránea'),
('reels', 'carta_avoid_title', 'ja', '避けたいものは？', 'Carta Mediterránea'),
('reels', 'carta_avoid_sub', 'ja', '食べられないものを選ぶと、それを含む料理ごとにお知らせします。このスマホにだけ保存されます。', 'Carta Mediterránea'),
('reels', 'carta_avoid_on', 'ja', '避ける', 'Carta Mediterránea'),
('reels', 'carta_this_dish', 'ja', 'この料理に含まれるもの', 'Carta Mediterránea'),
('reels', 'carta_contains', 'ja', '含む', 'Carta Mediterránea'),
('reels', 'carta_avoid_warn', 'ja', '避けたいものに選んでいます', 'Carta Mediterránea'),
('reels', 'carta_ask_waiter', 'ja', '重いアレルギーがある場合は、必ずスタッフに確認してください。', 'Carta Mediterránea'),
('reels', 'carta_see_allergens', 'ja', 'アレルゲンを見る', 'Carta Mediterránea'),
('reels', 'carta_menu_allergens', 'ja', 'このメニューのアレルゲン', 'Carta Mediterránea'),
('reels', 'carta_no_menu_allergens', 'ja', 'このお店はまだデジタルメニューにアレルゲンを表示していません。注文の前にスタッフに確認してください。', 'Carta Mediterránea'),
('reels', 'carta_done', 'ja', '完了', 'Carta Mediterránea'),
('reels', 'carta_notif_title', 'ja', 'お知らせ', 'Carta Mediterránea'),
('reels', 'carta_notif_lead', 'ja', '名前や電話番号なしで、新しい情報をお届けします。', 'Carta Mediterránea'),
('reels', 'carta_notif_1', 'ja', '新メニュー', 'Carta Mediterránea'),
('reels', 'carta_notif_1_sub', 'ja', 'メニューに加わったとき', 'Carta Mediterránea'),
('reels', 'carta_notif_2', 'ja', 'お得な情報', 'Carta Mediterránea'),
('reels', 'carta_notif_2_sub', 'ja', 'このお店のものだけ', 'Carta Mediterránea'),
('reels', 'carta_notif_3', 'ja', 'スタンプカード', 'Carta Mediterránea'),
('reels', 'carta_notif_3_sub', 'ja', '特典まであと少しのとき', 'Carta Mediterránea'),
('reels', 'carta_notif_on', 'ja', 'お知らせをオン', 'Carta Mediterránea'),
('reels', 'carta_notif_active', 'ja', 'お知らせはオンです', 'Carta Mediterránea'),
('reels', 'carta_notif_off', 'ja', 'お知らせをオフ', 'Carta Mediterránea'),
('reels', 'carta_notif_note', 'ja', 'ブラウザから許可を求められます。ここからいつでもオフにできます。', 'Carta Mediterránea'),
('reels', 'carta_notif_ios', 'ja', 'iPhoneでは、先にメニューをホーム画面に追加してください。', 'Carta Mediterránea'),
('reels', 'carta_notif_ask', 'ja', '新メニューやお得な情報をお知らせしましょうか？', 'Carta Mediterránea'),
('reels', 'carta_notif_denied', 'ja', 'ブラウザがこのサイトのお知らせをブロックしています。設定から許可できます。', 'Carta Mediterránea'),
('reels', 'carta_notif_sub_off', 'ja', '新メニューとお得な情報', 'Carta Mediterránea'),
('reels', 'carta_notif_sub_on', 'ja', 'オン', 'Carta Mediterránea'),
('reels', 'carta_reserve', 'ja', '席を予約', 'Carta Mediterránea'),
('reels', 'carta_reserve_sub', 'ja', '日にちと時間を選ぶ', 'Carta Mediterránea'),
('reels', 'carta_takeaway', 'ja', 'テイクアウト注文', 'Carta Mediterránea'),
('reels', 'carta_takeaway_sub', 'ja', 'お店で受け取りまたは配達', 'Carta Mediterránea'),
('reels', 'carta_stamps', 'ja', 'スタンプカード', 'Carta Mediterránea'),
('reels', 'carta_stamps_sub', 'ja', '来店ごとにスタンプ1つ', 'Carta Mediterránea'),
('reels', 'carta_offer', 'ja', 'ウェルカム特典', 'Carta Mediterránea'),
('reels', 'carta_offer_sub', 'ja', '特典があなたを待っています', 'Carta Mediterránea'),
('reels', 'carta_rate', 'ja', '評価する', 'Carta Mediterránea'),
('reels', 'carta_rate_sub', 'ja', '1分で、とても助かります', 'Carta Mediterránea'),
('reels', 'carta_web', 'ja', '公式サイト', 'Carta Mediterránea'),
('reels', 'carta_web_sub', 'ja', 'ストーリー・イベント・連絡先', 'Carta Mediterránea'),
('reels', 'carta_whatsapp', 'ja', 'WhatsApp', 'Carta Mediterránea'),
('reels', 'carta_whatsapp_sub', 'ja', 'メッセージを送る', 'Carta Mediterránea'),
('reels', 'carta_instagram', 'ja', 'Instagram', 'Carta Mediterránea'),
('reels', 'carta_language', 'ja', '言語', 'Carta Mediterránea'),
('reels', 'carta_current', 'ja', '選択中', 'Carta Mediterránea'),
('reels', 'carta_privacy', 'ja', 'プライバシー', 'Carta Mediterránea'),
('reels', 'carta_minus', 'ja', '1つ減らす', 'Carta Mediterránea'),
('reels', 'carta_plus', 'ja', '1つ増やす', 'Carta Mediterránea'),
('reels', 'carta_dish_n', 'ja', '{n}品目', 'Carta Mediterránea'),
('reels', 'carta_empty_menu', 'ja', '現在ご利用いただけるメニューはありません', 'Carta Mediterránea'),
('reels', 'carta_menu', 'ko', '메뉴', 'Carta Mediterránea'),
('reels', 'carta_house_hint', 'ko', '예약, 알림 등', 'Carta Mediterránea'),
('reels', 'carta_welcome_kicker', 'ko', '어서 오세요', 'Carta Mediterránea'),
('reels', 'carta_start', 'ko', '메뉴 보기', 'Carta Mediterránea'),
('reels', 'carta_more_languages', 'ko', '다른 언어', 'Carta Mediterránea'),
('reels', 'carta_full_portion', 'ko', '1인분', 'Carta Mediterránea'),
('reels', 'carta_choose_portion', 'ko', '양 선택', 'Carta Mediterránea'),
('reels', 'carta_quantity', 'ko', '수량', 'Carta Mediterránea'),
('reels', 'carta_no_allergens', 'ko', '표시된 알레르기 유발 성분 없음', 'Carta Mediterránea'),
('reels', 'carta_back', 'ko', '뒤로', 'Carta Mediterránea'),
('reels', 'carta_back_videos', 'ko', '영상으로 돌아가기', 'Carta Mediterránea'),
('reels', 'carta_videos', 'ko', '영상', 'Carta Mediterránea'),
('reels', 'carta_selection', 'ko', '나의 선택', 'Carta Mediterránea'),
('reels', 'carta_to_order', 'ko', '주문할 메뉴', 'Carta Mediterránea'),
('reels', 'carta_total', 'ko', '합계', 'Carta Mediterránea'),
('reels', 'carta_staff_note', 'ko', '아무것도 전송되지 않아요. 직원에게 보여 주고 주문하세요.', 'Carta Mediterránea'),
('reels', 'carta_show_waiter', 'ko', '직원에게 보여 주기', 'Carta Mediterránea'),
('reels', 'carta_keep_browsing', 'ko', '계속 보기', 'Carta Mediterránea'),
('reels', 'carta_empty', 'ko', '아직 선택한 메뉴가 없어요.', 'Carta Mediterránea'),
('reels', 'carta_for_waiter', 'ko', '직원용', 'Carta Mediterránea'),
('reels', 'carta_badge_featured', 'ko', '추천', 'Carta Mediterránea'),
('reels', 'carta_badge_new', 'ko', '신메뉴', 'Carta Mediterránea'),
('reels', 'carta_badge_vegetarian', 'ko', '채식', 'Carta Mediterránea'),
('reels', 'carta_badge_vegan', 'ko', '비건', 'Carta Mediterránea'),
('reels', 'carta_badge_gluten_free', 'ko', '글루텐 프리', 'Carta Mediterránea'),
('reels', 'carta_no_video', 'ko', '이 메뉴는 아직 영상이 없어요', 'Carta Mediterránea'),
('reels', 'carta_added', 'ko', '추가했어요', 'Carta Mediterránea'),
('reels', 'carta_liked', 'ko', '좋아요에 저장했어요', 'Carta Mediterránea'),
('reels', 'carta_unliked', 'ko', '좋아요에서 뺐어요', 'Carta Mediterránea'),
('reels', 'carta_likes_note', 'ko', '이 휴대폰에 저장돼요. 다음에 오셔도 그대로 있어요.', 'Carta Mediterránea'),
('reels', 'carta_likes_empty', 'ko', '하트를 누르거나 영상을 두 번 탭하면 메뉴를 저장해 두고 나중에 고를 수 있어요.', 'Carta Mediterránea'),
('reels', 'carta_add_all', 'ko', '모두 주문에 추가', 'Carta Mediterránea'),
('reels', 'carta_top_liked', 'ko', '가장 인기 있는 메뉴', 'Carta Mediterránea'),
('reels', 'carta_top_liked_sub', 'ko', '이곳에서 식사한 분들의 좋아요 기준', 'Carta Mediterránea'),
('reels', 'carta_dish_one', 'ko', '메뉴 1개', 'Carta Mediterránea'),
('reels', 'carta_dish_other', 'ko', '메뉴 {n}개', 'Carta Mediterránea'),
('reels', 'carta_menu_count', 'ko', '메뉴 총 {n}개', 'Carta Mediterránea'),
('reels', 'carta_avoid_title', 'ko', '피해야 할 성분이 있나요?', 'Carta Mediterránea'),
('reels', 'carta_avoid_sub', 'ko', '드실 수 없는 성분을 표시하면 그 성분이 든 메뉴마다 알려 드려요. 이 휴대폰에만 저장돼요.', 'Carta Mediterránea'),
('reels', 'carta_avoid_on', 'ko', '피함', 'Carta Mediterránea'),
('reels', 'carta_this_dish', 'ko', '이 메뉴에 들어 있는 성분', 'Carta Mediterránea'),
('reels', 'carta_contains', 'ko', '포함', 'Carta Mediterránea'),
('reels', 'carta_avoid_warn', 'ko', '피하기로 표시한 성분이에요', 'Carta Mediterránea'),
('reels', 'carta_ask_waiter', 'ko', '심한 알레르기가 있다면 꼭 직원에게 확인하세요.', 'Carta Mediterránea'),
('reels', 'carta_see_allergens', 'ko', '알레르기 성분 보기', 'Carta Mediterránea'),
('reels', 'carta_menu_allergens', 'ko', '이 메뉴의 알레르기 유발 성분', 'Carta Mediterránea'),
('reels', 'carta_no_menu_allergens', 'ko', '이 식당은 아직 디지털 메뉴에 알레르기 성분을 표시하지 않았어요. 주문 전에 직원에게 물어보세요.', 'Carta Mediterránea'),
('reels', 'carta_done', 'ko', '완료', 'Carta Mediterránea'),
('reels', 'carta_notif_title', 'ko', '알림', 'Carta Mediterránea'),
('reels', 'carta_notif_lead', 'ko', '이름이나 전화번호 없이 새 소식을 알려 드려요.', 'Carta Mediterránea'),
('reels', 'carta_notif_1', 'ko', '신메뉴', 'Carta Mediterránea'),
('reels', 'carta_notif_1_sub', 'ko', '메뉴에 새로 추가될 때', 'Carta Mediterránea'),
('reels', 'carta_notif_2', 'ko', '혜택', 'Carta Mediterránea'),
('reels', 'carta_notif_2_sub', 'ko', '이 식당의 혜택만', 'Carta Mediterránea'),
('reels', 'carta_notif_3', 'ko', '스탬프 카드', 'Carta Mediterránea'),
('reels', 'carta_notif_3_sub', 'ko', '보상이 가까워졌을 때', 'Carta Mediterránea'),
('reels', 'carta_notif_on', 'ko', '알림 켜기', 'Carta Mediterránea'),
('reels', 'carta_notif_active', 'ko', '알림이 켜져 있어요', 'Carta Mediterránea'),
('reels', 'carta_notif_off', 'ko', '알림 끄기', 'Carta Mediterránea'),
('reels', 'carta_notif_note', 'ko', '브라우저가 권한을 요청해요. 언제든 여기에서 끌 수 있어요.', 'Carta Mediterránea'),
('reels', 'carta_notif_ios', 'ko', 'iPhone에서는 먼저 메뉴를 홈 화면에 추가하세요.', 'Carta Mediterránea'),
('reels', 'carta_notif_ask', 'ko', '신메뉴나 혜택이 있을 때 알려 드릴까요?', 'Carta Mediterránea'),
('reels', 'carta_notif_denied', 'ko', '브라우저가 이 사이트의 알림을 차단하고 있어요. 설정에서 허용할 수 있어요.', 'Carta Mediterránea'),
('reels', 'carta_notif_sub_off', 'ko', '신메뉴와 혜택', 'Carta Mediterránea'),
('reels', 'carta_notif_sub_on', 'ko', '켜짐', 'Carta Mediterránea'),
('reels', 'carta_reserve', 'ko', '테이블 예약', 'Carta Mediterránea'),
('reels', 'carta_reserve_sub', 'ko', '날짜와 시간 선택', 'Carta Mediterránea'),
('reels', 'carta_takeaway', 'ko', '포장 주문', 'Carta Mediterránea'),
('reels', 'carta_takeaway_sub', 'ko', '매장 픽업 또는 배달', 'Carta Mediterránea'),
('reels', 'carta_stamps', 'ko', '스탬프 카드', 'Carta Mediterránea'),
('reels', 'carta_stamps_sub', 'ko', '방문할 때마다 스탬프 1개', 'Carta Mediterránea'),
('reels', 'carta_offer', 'ko', '웰컴 혜택', 'Carta Mediterránea'),
('reels', 'carta_offer_sub', 'ko', '혜택이 기다리고 있어요', 'Carta Mediterránea'),
('reels', 'carta_rate', 'ko', '평가하기', 'Carta Mediterránea'),
('reels', 'carta_rate_sub', 'ko', '1분이면 큰 도움이 돼요', 'Carta Mediterránea'),
('reels', 'carta_web', 'ko', '홈페이지', 'Carta Mediterránea'),
('reels', 'carta_web_sub', 'ko', '이야기, 이벤트, 연락처', 'Carta Mediterránea'),
('reels', 'carta_whatsapp', 'ko', 'WhatsApp', 'Carta Mediterránea'),
('reels', 'carta_whatsapp_sub', 'ko', '메시지 보내기', 'Carta Mediterránea'),
('reels', 'carta_instagram', 'ko', 'Instagram', 'Carta Mediterránea'),
('reels', 'carta_language', 'ko', '언어', 'Carta Mediterránea'),
('reels', 'carta_current', 'ko', '현재', 'Carta Mediterránea'),
('reels', 'carta_privacy', 'ko', '개인정보', 'Carta Mediterránea'),
('reels', 'carta_minus', 'ko', '하나 빼기', 'Carta Mediterránea'),
('reels', 'carta_plus', 'ko', '하나 더하기', 'Carta Mediterránea'),
('reels', 'carta_dish_n', 'ko', '메뉴 {n}', 'Carta Mediterránea'),
('reels', 'carta_empty_menu', 'ko', '지금은 이용할 수 있는 메뉴가 없어요', 'Carta Mediterránea');
