-- =====================================================
-- POI MEDIA — WIKIMEDIA COMMONS IMAGES + CREDIT — MIGRATION 0100
-- =====================================================
-- 0061 gave 37 of the original 70 POIs a Wikipedia lead image. The 2026-10 POI
-- batch (scripts/poi-seed) added ~110 POIs in 10 zones without any photo, so
-- every zone but Málaga looked empty. This fills 128 of the 149 POIs
-- that had no media, one PRIMARY_IMAGE each, uploaded to R2 under guide/pois/.
--
-- Source: Wikimedia Commons, free licences only (CC0, CC BY, CC BY-SA). Found via
-- the POI's Wikipedia article (es/en) or its Wikidata P18, matched on name AND
-- distance to the POI's coordinates, or by a Commons search reviewed by hand.
-- Every image was checked by eye: maps, logos, signs, statues, wrong places and
-- duplicates were dropped. 21 POIs have no usable free photo (theme parks,
-- small museums, viewpoints) and stay without media until uploaded in the admin.
--
-- CC BY / CC BY-SA require crediting author + licence, which 0061 never stored.
-- The new columns keep it per image so the guide can show it; 0061's 27 rows
-- still have them NULL.
-- =====================================================

ALTER TABLE guide_poi_media ADD COLUMN source_url TEXT;
ALTER TABLE guide_poi_media ADD COLUMN author TEXT;
ALTER TABLE guide_poi_media ADD COLUMN license TEXT;
ALTER TABLE guide_poi_media ADD COLUMN license_url TEXT;

INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_mt0qfcfn_r5wfmx', 'poi_mt0qfcfn_r5wfmx', 'guide/pois/poi_mt0qfcfn_r5wfmx.jpg', 'image', 'PRIMARY_IMAGE', 1280, 634, 240226, 0, 'https://commons.wikimedia.org/wiki/File:Benalmadena_-_Puerto_Marina.jpg', 'Tiia Monto', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_mt0qfcfn_r5wfmx') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_mt0qfcfn_r5wfmx');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_mtybk2re_h1jmd9', 'poi_mtybk2re_h1jmd9', 'guide/pois/poi_mtybk2re_h1jmd9.jpg', 'image', 'PRIMARY_IMAGE', 1280, 1014, 363102, 0, 'https://commons.wikimedia.org/wiki/File:Templo_hind%C3%BA_de_Benalm%C3%A1dena.jpg', 'Keke999', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_mtybk2re_h1jmd9') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_mtybk2re_h1jmd9');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_mubz2iph_biiuod', 'poi_mubz2iph_biiuod', 'guide/pois/poi_mubz2iph_biiuod.jpg', 'image', 'PRIMARY_IMAGE', 1280, 1280, 471404, 0, 'https://commons.wikimedia.org/wiki/File:Castillo_de_Colomares,_Benalm%C3%A1dena,_M%C3%A1laga,_Espa%C3%B1a,_2023-05-18,_DD_76.jpg', 'Diego Delso', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_mubz2iph_biiuod') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_mubz2iph_biiuod');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_mubz2izo_jirste', 'poi_mubz2izo_jirste', 'guide/pois/poi_mubz2izo_jirste.jpg', 'image', 'PRIMARY_IMAGE', 1280, 853, 159886, 0, 'https://commons.wikimedia.org/wiki/File:Benalm%C3%A1dena_Stupa_(51948752654).jpg', 'Kent Wang from Barcelona, Spain', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_mubz2izo_jirste') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_mubz2izo_jirste');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_mubz2j8b_dm8c8t', 'poi_mubz2j8b_dm8c8t', 'guide/pois/poi_mubz2j8b_dm8c8t.jpg', 'image', 'PRIMARY_IMAGE', 720, 1280, 191087, 0, 'https://commons.wikimedia.org/wiki/File:Benalm%C3%A1dena_(15).jpg', 'JamesNarmer', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_mubz2j8b_dm8c8t') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_mubz2j8b_dm8c8t');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_mubz2jf8_k9tk83', 'poi_mubz2jf8_k9tk83', 'guide/pois/poi_mubz2jf8_k9tk83.jpg', 'image', 'PRIMARY_IMAGE', 1200, 1600, 479769, 0, 'https://commons.wikimedia.org/wiki/File:Museo_Benalmadena.jpg', 'Miwipedia', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_mubz2jf8_k9tk83') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_mubz2jf8_k9tk83');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_mubz2k0o_b0qi5w', 'poi_mubz2k0o_b0qi5w', 'guide/pois/poi_mubz2k0o_b0qi5w.jpg', 'image', 'PRIMARY_IMAGE', 1196, 1189, 228915, 0, 'https://commons.wikimedia.org/wiki/File:Benalm%C3%A1dena_Pueblo_-_Iglesia_de_Santo_Domingo_de_Guzm%C3%A1n_01.jpg', 'Zarateman', 'CC0', 'http://creativecommons.org/publicdomain/zero/1.0/deed.en'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_mubz2k0o_b0qi5w') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_mubz2k0o_b0qi5w');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_mubz2k95_4eni0z', 'poi_mubz2k95_4eni0z', 'guide/pois/poi_mubz2k95_4eni0z.jpg', 'image', 'PRIMARY_IMAGE', 1600, 1200, 471519, 0, 'https://commons.wikimedia.org/wiki/File:Benalm%C3%A1dena_Pueblo_-_Jardines_del_Muro_12.jpg', 'Zarateman', 'CC0', 'http://creativecommons.org/publicdomain/zero/1.0/deed.en'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_mubz2k95_4eni0z') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_mubz2k95_4eni0z');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_mubz2kqb_6pwjme', 'poi_mubz2kqb_6pwjme', 'guide/pois/poi_mubz2kqb_6pwjme.jpg', 'image', 'PRIMARY_IMAGE', 1280, 683, 219278, 0, 'https://commons.wikimedia.org/wiki/File:Paloma_Park_Benalm%C3%A1dena_(cropped).JPG', 'Hombre1896', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_mubz2kqb_6pwjme') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_mubz2kqb_6pwjme');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_mubz2l7a_dc0x28', 'poi_mubz2l7a_dc0x28', 'guide/pois/poi_mubz2l7a_dc0x28.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 445103, 0, 'https://commons.wikimedia.org/wiki/File:Delfines_Selwo_Marina.jpg', '__Lolo__', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_mubz2l7a_dc0x28') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_mubz2l7a_dc0x28');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_mubz2lft_rfy382', 'poi_mubz2lft_rfy382', 'guide/pois/poi_mubz2lft_rfy382.jpg', 'image', 'PRIMARY_IMAGE', 1024, 768, 168298, 0, 'https://commons.wikimedia.org/wiki/File:Monte_Calamorro.jpg', 'Miwipedia', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_mubz2lft_rfy382') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_mubz2lft_rfy382');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_mubz2loo_dsnwmv', 'poi_mubz2loo_dsnwmv', 'guide/pois/poi_mubz2loo_dsnwmv.jpg', 'image', 'PRIMARY_IMAGE', 1200, 1600, 238337, 0, 'https://commons.wikimedia.org/wiki/File:Benalm%C3%A1dena_-_Arroyo_de_la_Miel,_Casa_de_la_Cultura_de_Benalm%C3%A1dena_2.jpg', 'Zarateman', 'CC0', 'http://creativecommons.org/publicdomain/zero/1.0/deed.en'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_mubz2loo_dsnwmv') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_mubz2loo_dsnwmv');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_mubz2m5i_629of3', 'poi_mubz2m5i_629of3', 'guide/pois/poi_mubz2m5i_629of3.jpg', 'image', 'PRIMARY_IMAGE', 1280, 853, 160443, 0, 'https://commons.wikimedia.org/wiki/File:Castillo_El_Bil_Bil,_Benalm%C3%A1dena,_M%C3%A1laga,_Espa%C3%B1a,_2023-05-18,_DD_62.jpg', 'Diego Delso', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_mubz2m5i_629of3') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_mubz2m5i_629of3');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_mubz2n0p_dxuukc', 'poi_mubz2n0p_dxuukc', 'guide/pois/poi_mubz2n0p_dxuukc.jpg', 'image', 'PRIMARY_IMAGE', 1600, 1200, 390426, 0, 'https://commons.wikimedia.org/wiki/File:Benalm%C3%A1dena_-_Villa_romana_de_Los_Molinillos.jpg', 'Zarateman', 'CC0', 'http://creativecommons.org/publicdomain/zero/1.0/deed.en'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_mubz2n0p_dxuukc') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_mubz2n0p_dxuukc');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_fuengirola_museo_ciudad', 'poi_fuengirola_museo_ciudad', 'guide/pois/poi_fuengirola_museo_ciudad.jpg', 'image', 'PRIMARY_IMAGE', 1594, 1134, 290084, 0, 'https://commons.wikimedia.org/wiki/File:Fuengirola_-_Museo_de_Historia_de_la_Ciudad_2.jpg', 'Zarateman', 'CC0', 'http://creativecommons.org/publicdomain/zero/1.0/deed.en'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_fuengirola_museo_ciudad') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_fuengirola_museo_ciudad');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_fuengirola_paseo_maritimo', 'poi_fuengirola_paseo_maritimo', 'guide/pois/poi_fuengirola_paseo_maritimo.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 353941, 0, 'https://commons.wikimedia.org/wiki/File:Fuengirola_Playa_07.jpg', 'Olaf Tausch', 'CC BY 3.0', 'https://creativecommons.org/licenses/by/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_fuengirola_paseo_maritimo') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_fuengirola_paseo_maritimo');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_fuengirola_santa_amalia', 'poi_fuengirola_santa_amalia', 'guide/pois/poi_fuengirola_santa_amalia.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 319293, 0, 'https://commons.wikimedia.org/wiki/File:Fuengirola_Playa_08.jpg', 'Olaf Tausch', 'CC BY 3.0', 'https://creativecommons.org/licenses/by/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_fuengirola_santa_amalia') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_fuengirola_santa_amalia');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_malaga_artes_costumbres', 'poi_malaga_artes_costumbres', 'guide/pois/poi_malaga_artes_costumbres.jpg', 'image', 'PRIMARY_IMAGE', 1280, 958, 240340, 0, 'https://commons.wikimedia.org/wiki/File:Mes%C3%B3n_de_la_Victoria-rear.jpg', 'Tyk', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_malaga_artes_costumbres') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_malaga_artes_costumbres');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_malaga_guadalhorce', 'poi_malaga_guadalhorce', 'guide/pois/poi_malaga_guadalhorce.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 211317, 0, 'https://commons.wikimedia.org/wiki/File:Desembocadura_del_Guadalhorce_at_dusk_08.jpg', 'Té y kriptonita', 'CC BY-SA 3.0', 'http://creativecommons.org/licenses/by-sa/3.0/'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_malaga_guadalhorce') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_malaga_guadalhorce');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_malaga_iglesia_martires', 'poi_malaga_iglesia_martires', 'guide/pois/poi_malaga_iglesia_martires.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 382211, 0, 'https://commons.wikimedia.org/wiki/File:Iglesia_M%C3%A1rtires_M%C3%A1laga.JPG', 'Miwipedia', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_malaga_iglesia_martires') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_malaga_iglesia_martires');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_malaga_iglesia_san_juan', 'poi_malaga_iglesia_san_juan', 'guide/pois/poi_malaga_iglesia_san_juan.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 389771, 0, 'https://commons.wikimedia.org/wiki/File:Catedral_de_Malaga_(Andalucia,_Espa%C3%B1a_2022)_(52061317071).jpg', 'Paul Arps from The Netherlands', 'CC BY 2.0', 'https://creativecommons.org/licenses/by/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_malaga_iglesia_san_juan') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_malaga_iglesia_san_juan');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_malaga_iglesia_santiago', 'poi_malaga_iglesia_santiago', 'guide/pois/poi_malaga_iglesia_santiago.jpg', 'image', 'PRIMARY_IMAGE', 680, 1024, 453940, 0, 'https://commons.wikimedia.org/wiki/File:Iglesia_Parroquial_de_Santiago_Ap%C3%B3stol_3.jpg', 'Maksym Abramov', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_malaga_iglesia_santiago') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_malaga_iglesia_santiago');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_malaga_jardines_pedro_luis_alonso', 'poi_malaga_jardines_pedro_luis_alonso', 'guide/pois/poi_malaga_jardines_pedro_luis_alonso.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 521662, 0, 'https://commons.wikimedia.org/wiki/File:M%C3%A1laga_Jardines_01.jpg', 'Olaf Tausch', 'CC BY 3.0', 'https://creativecommons.org/licenses/by/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_malaga_jardines_pedro_luis_alonso') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_malaga_jardines_pedro_luis_alonso');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_malaga_jorge_rando', 'poi_malaga_jorge_rando', 'guide/pois/poi_malaga_jorge_rando.jpg', 'image', 'PRIMARY_IMAGE', 1280, 1927, 380500, 0, 'https://commons.wikimedia.org/wiki/File:Museumjorgerando.JPG', 'ArteNova21', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_malaga_jorge_rando') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_malaga_jorge_rando');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_malaga_la_farola', 'poi_malaga_la_farola', 'guide/pois/poi_malaga_la_farola.jpg', 'image', 'PRIMARY_IMAGE', 1280, 849, 382086, 0, 'https://commons.wikimedia.org/wiki/File:Farola_de_malaga.JPG', 'Danielmlg86', 'CC BY-SA 3.0 es', 'https://creativecommons.org/licenses/by-sa/3.0/es/deed.en'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_malaga_la_farola') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_malaga_la_farola');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_malaga_montes_malaga', 'poi_malaga_montes_malaga', 'guide/pois/poi_malaga_montes_malaga.jpg', 'image', 'PRIMARY_IMAGE', 1280, 720, 344354, 0, 'https://commons.wikimedia.org/wiki/File:Contadoras_%C3%A1rbol.jpg', 'Marcos cortes troman', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_malaga_montes_malaga') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_malaga_montes_malaga');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_malaga_museo_aeronautico', 'poi_malaga_museo_aeronautico', 'guide/pois/poi_malaga_museo_aeronautico.jpg', 'image', 'PRIMARY_IMAGE', 1280, 853, 273213, 0, 'https://commons.wikimedia.org/wiki/File:Museo_Aeronautico_Malaga_-_Terminal_Historica.jpg', 'Álvaro Rojas', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_malaga_museo_aeronautico') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_malaga_museo_aeronautico');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_malaga_museo_malaga', 'poi_malaga_museo_malaga', 'guide/pois/poi_malaga_museo_malaga.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 374838, 0, 'https://commons.wikimedia.org/wiki/File:Palacio_de_la_Aduana,_M%C3%A1laga_01.JPG', 'Tyk', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_malaga_museo_malaga') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_malaga_museo_malaga');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_malaga_museo_ruso', 'poi_malaga_museo_ruso', 'guide/pois/poi_malaga_museo_ruso.jpg', 'image', 'PRIMARY_IMAGE', 1280, 917, 342735, 0, 'https://commons.wikimedia.org/wiki/File:MLG2010_053.jpg', 'Tyk', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_malaga_museo_ruso') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_malaga_museo_ruso');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_malaga_museo_vidrio', 'poi_malaga_museo_vidrio', 'guide/pois/poi_malaga_museo_vidrio.jpg', 'image', 'PRIMARY_IMAGE', 1280, 1707, 562286, 0, 'https://commons.wikimedia.org/wiki/File:Museo_del_Vidrio_y_Cristal,_M%C3%A1laga-patio.jpg', 'Tyk', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_malaga_museo_vidrio') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_malaga_museo_vidrio');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_malaga_museo_vino', 'poi_malaga_museo_vino', 'guide/pois/poi_malaga_museo_vino.jpg', 'image', 'PRIMARY_IMAGE', 1280, 853, 296390, 0, 'https://commons.wikimedia.org/wiki/File:Museo_del_Vino_M%C3%A1laga_2012_HQ.jpg', 'Emilio J. Rodríguez-Posada', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_malaga_museo_vino') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_malaga_museo_vino');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_malaga_oxo', 'poi_malaga_oxo', 'guide/pois/poi_malaga_oxo.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 337604, 0, 'https://commons.wikimedia.org/wiki/File:OXO_Museo_del_Videojuego.jpg', 'Daniel Capilla', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_malaga_oxo') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_malaga_oxo');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_malaga_parque_malaga', 'poi_malaga_parque_malaga', 'guide/pois/poi_malaga_parque_malaga.jpg', 'image', 'PRIMARY_IMAGE', 1800, 956, 2826881, 0, 'https://commons.wikimedia.org/wiki/File:El_Parque_de_M%C3%A1laga.JPG', 'Frog17', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_malaga_parque_malaga') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_malaga_parque_malaga');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_malaga_pasaje_chinitas', 'poi_malaga_pasaje_chinitas', 'guide/pois/poi_malaga_pasaje_chinitas.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 499484, 0, 'https://commons.wikimedia.org/wiki/File:M%C3%A1laga_-_Pasaje_de_Chinitas_4.jpg', 'Zarateman', 'CC0', 'http://creativecommons.org/publicdomain/zero/1.0/deed.en'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_malaga_pasaje_chinitas') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_malaga_pasaje_chinitas');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_malaga_pedregalejo', 'poi_malaga_pedregalejo', 'guide/pois/poi_malaga_pedregalejo.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 254351, 0, 'https://commons.wikimedia.org/wiki/File:Street_Pedregalejo_Playa.jpg', 'Tyk', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_malaga_pedregalejo') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_malaga_pedregalejo');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_malaga_pena_juan_breva', 'poi_malaga_pena_juan_breva', 'guide/pois/poi_malaga_pena_juan_breva.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 281277, 0, 'https://commons.wikimedia.org/wiki/File:Pe%C3%B1a_Juan_Breva_02.jpg', 'Daniel Capilla', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_malaga_pena_juan_breva') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_malaga_pena_juan_breva');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_malaga_plaza_obispo', 'poi_malaga_plaza_obispo', 'guide/pois/poi_malaga_plaza_obispo.jpg', 'image', 'PRIMARY_IMAGE', 1024, 680, 481874, 0, 'https://commons.wikimedia.org/wiki/File:PalacioEpiscopalMalaga1.jpg', 'Maxim.Fotos', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_malaga_plaza_obispo') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_malaga_plaza_obispo');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_malaga_revello_toro', 'poi_malaga_revello_toro', 'guide/pois/poi_malaga_revello_toro.jpg', 'image', 'PRIMARY_IMAGE', 1280, 1700, 395959, 0, 'https://commons.wikimedia.org/wiki/File:Mueso_Revello_de_Toro.jpg', 'Tyk', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_malaga_revello_toro') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_malaga_revello_toro');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_malaga_sagrado_corazon', 'poi_malaga_sagrado_corazon', 'guide/pois/poi_malaga_sagrado_corazon.jpg', 'image', 'PRIMARY_IMAGE', 1920, 2560, 1958856, 0, 'https://commons.wikimedia.org/wiki/File:Iglesia_de_los_Jesuitas_Malaga.jpg', 'gastromartini', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_malaga_sagrado_corazon') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_malaga_sagrado_corazon');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_marbella_avenida_del_mar', 'poi_marbella_avenida_del_mar', 'guide/pois/poi_marbella_avenida_del_mar.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 319925, 0, 'https://commons.wikimedia.org/wiki/File:Marbella_(25989803004).jpg', 'Konrad Hädener from Thun, Switzerland', 'CC BY 2.0', 'https://creativecommons.org/licenses/by/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_marbella_avenida_del_mar') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_marbella_avenida_del_mar');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_marbella_banus', 'poi_marbella_banus', 'guide/pois/poi_marbella_banus.jpg', 'image', 'PRIMARY_IMAGE', 1280, 853, 341849, 0, 'https://commons.wikimedia.org/wiki/File:Marbella3.jpg', 'Tomas Fano', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_marbella_banus') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_marbella_banus');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_marbella_basilica_vega_mar', 'poi_marbella_basilica_vega_mar', 'guide/pois/poi_marbella_basilica_vega_mar.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 522836, 0, 'https://commons.wikimedia.org/wiki/File:Bas%C3%ADlica_Paleocristiana_de_Vega_del_Mar.JPG', 'Ikusitaikasi', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_marbella_basilica_vega_mar') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_marbella_basilica_vega_mar');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_marbella_bulevar_san_pedro', 'poi_marbella_bulevar_san_pedro', 'guide/pois/poi_marbella_bulevar_san_pedro.jpg', 'image', 'PRIMARY_IMAGE', 1280, 851, 266544, 0, 'https://commons.wikimedia.org/wiki/File:Bulevar_de_San_Pedro_Alc%C3%A1ntara_(22962669494).jpg', 'Bulevar San Pedro Alcántara from San Pedro Alcántara, España', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_marbella_bulevar_san_pedro') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_marbella_bulevar_san_pedro');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_marbella_capilla_san_juan_dios', 'poi_marbella_capilla_san_juan_dios', 'guide/pois/poi_marbella_capilla_san_juan_dios.jpg', 'image', 'PRIMARY_IMAGE', 1280, 1920, 557020, 0, 'https://commons.wikimedia.org/wiki/File:Capilla_de_San_Juan-Marbella.jpg', 'fernando0', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_marbella_capilla_san_juan_dios') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_marbella_capilla_san_juan_dios');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_marbella_cortijo_miraflores', 'poi_marbella_cortijo_miraflores', 'guide/pois/poi_marbella_cortijo_miraflores.jpg', 'image', 'PRIMARY_IMAGE', 1280, 720, 154831, 0, 'https://commons.wikimedia.org/wiki/File:Cortijo_de_Miraflores_172534.jpg', 'Tyk', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_marbella_cortijo_miraflores') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_marbella_cortijo_miraflores');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_marbella_cruz_juanar', 'poi_marbella_cruz_juanar', 'guide/pois/poi_marbella_cruz_juanar.jpg', 'image', 'PRIMARY_IMAGE', 1024, 768, 282742, 0, 'https://commons.wikimedia.org/wiki/File:Cerro_de_la_Cruz_del_Juanar_(3335401686).jpg', 'Por los caminos de Málaga', 'CC BY 2.0', 'https://creativecommons.org/licenses/by/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_marbella_cruz_juanar') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_marbella_cruz_juanar');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_marbella_dunas_artola', 'poi_marbella_dunas_artola', 'guide/pois/poi_marbella_dunas_artola.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 483640, 0, 'https://commons.wikimedia.org/wiki/File:Artola-Cabopino_03.jpg', 'Olaf Tausch', 'CC BY 3.0', 'https://creativecommons.org/licenses/by/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_marbella_dunas_artola') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_marbella_dunas_artola');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_marbella_ermita_santo_cristo', 'poi_marbella_ermita_santo_cristo', 'guide/pois/poi_marbella_ermita_santo_cristo.jpg', 'image', 'PRIMARY_IMAGE', 768, 1024, 107908, 0, 'https://commons.wikimedia.org/wiki/File:Ermita_del_Sto_Cristo_de_la_Vera_Cruz-Marbella.jpg', 'Samu73', 'CC BY 2.0', 'https://creativecommons.org/licenses/by/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_marbella_ermita_santo_cristo') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_marbella_ermita_santo_cristo');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_marbella_grabado', 'poi_marbella_grabado', 'guide/pois/poi_marbella_grabado.jpg', 'image', 'PRIMARY_IMAGE', 1280, 1700, 528863, 0, 'https://commons.wikimedia.org/wiki/File:Hospital_Baz%C3%A1n.jpg', 'Té y kriptonita', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_marbella_grabado') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_marbella_grabado');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_marbella_iglesia_encarnacion', 'poi_marbella_iglesia_encarnacion', 'guide/pois/poi_marbella_iglesia_encarnacion.jpg', 'image', 'PRIMARY_IMAGE', 1280, 1700, 523968, 0, 'https://commons.wikimedia.org/wiki/File:Iglesia_de_la_Encarnaci%C3%B3n.jpg', 'Tyk', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_marbella_iglesia_encarnacion') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_marbella_iglesia_encarnacion');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_marbella_la_concha', 'poi_marbella_la_concha', 'guide/pois/poi_marbella_la_concha.jpg', 'image', 'PRIMARY_IMAGE', 1600, 1200, 271271, 0, 'https://commons.wikimedia.org/wiki/File:Marbella_-_Picho_de_la_Concha_(Sierra_Blanca).jpg', 'Zarateman', 'CC0', 'http://creativecommons.org/publicdomain/zero/1.0/deed.en'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_marbella_la_concha') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_marbella_la_concha');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_marbella_parque_alameda', 'poi_marbella_parque_alameda', 'guide/pois/poi_marbella_parque_alameda.jpg', 'image', 'PRIMARY_IMAGE', 1280, 719, 488768, 0, 'https://commons.wikimedia.org/wiki/File:Spain_-_Marbella,_Andalucia_-_panoramio_(2).jpg', 'randreu', 'CC BY 3.0', 'https://creativecommons.org/licenses/by/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_marbella_parque_alameda') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_marbella_parque_alameda');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_marbella_parque_constitucion', 'poi_marbella_parque_constitucion', 'guide/pois/poi_marbella_parque_constitucion.jpg', 'image', 'PRIMARY_IMAGE', 1280, 854, 562783, 0, 'https://commons.wikimedia.org/wiki/File:Marbella_2015_10_20_1840_(24740872485).jpg', 'Harvey Barrison from Massapequa, NY, USA', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_marbella_parque_constitucion') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_marbella_parque_constitucion');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_marbella_plaza_naranjos', 'poi_marbella_plaza_naranjos', 'guide/pois/poi_marbella_plaza_naranjos.jpg', 'image', 'PRIMARY_IMAGE', 1280, 853, 421259, 0, 'https://commons.wikimedia.org/wiki/File:Plaza_De_Los_Naranjos,_Marbella.jpg', 'Mark Gilbert', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_marbella_plaza_naranjos') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_marbella_plaza_naranjos');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_marbella_ralli', 'poi_marbella_ralli', 'guide/pois/poi_marbella_ralli.jpg', 'image', 'PRIMARY_IMAGE', 1280, 733, 228425, 0, 'https://commons.wikimedia.org/wiki/File:Mrallifotofachada.jpg', 'Museo Ralli Marbella', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_marbella_ralli') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_marbella_ralli');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_marbella_termas_bovedas', 'poi_marbella_termas_bovedas', 'guide/pois/poi_marbella_termas_bovedas.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 454881, 0, 'https://commons.wikimedia.org/wiki/File:Termas_romanas_de_las_B%C3%B3vedas.JPG', 'Ikusitaikasi', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_marbella_termas_bovedas') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_marbella_termas_bovedas');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_marbella_villa_romana_rio_verde', 'poi_marbella_villa_romana_rio_verde', 'guide/pois/poi_marbella_villa_romana_rio_verde.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 396020, 0, 'https://commons.wikimedia.org/wiki/File:Villa_romana_R%C3%ADo_Verde_4.JPG', 'Ikusitaikasi', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_marbella_villa_romana_rio_verde') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_marbella_villa_romana_rio_verde');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_mijas_calle_san_sebastian', 'poi_mijas_calle_san_sebastian', 'guide/pois/poi_mijas_calle_san_sebastian.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 346362, 0, 'https://commons.wikimedia.org/wiki/File:Calle_San_Sebastian_Mijas_Spain_-_panoramio.jpg', 'Hiroki Ogawa', 'CC BY 3.0', 'https://creativecommons.org/licenses/by/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_mijas_calle_san_sebastian') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_mijas_calle_san_sebastian');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_mijas_carromato', 'poi_mijas_carromato', 'guide/pois/poi_mijas_carromato.jpg', 'image', 'PRIMARY_IMAGE', 1280, 850, 1052727, 0, 'https://commons.wikimedia.org/wiki/File:MUSEO_DE_MINIATURAS_%22CARROMATO_DE_MIJAS%22.jpg', 'FELIPE CRESPO', 'CC0', 'http://creativecommons.org/publicdomain/zero/1.0/deed.en'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_mijas_carromato') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_mijas_carromato');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_mijas_ermita_calvario', 'poi_mijas_ermita_calvario', 'guide/pois/poi_mijas_ermita_calvario.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 374433, 0, 'https://commons.wikimedia.org/wiki/File:Ermita_del_Calvario_Mijas.jpg', 'Tyk', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_mijas_ermita_calvario') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_mijas_ermita_calvario');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_mijas_ermita_peña', 'poi_mijas_ermita_peña', 'guide/pois/poi_mijas_ermita_pena.jpg', 'image', 'PRIMARY_IMAGE', 1280, 961, 566151, 0, 'https://commons.wikimedia.org/wiki/File:Mijas_05.jpg', 'Olaf Tausch', 'CC BY 3.0', 'https://creativecommons.org/licenses/by/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_mijas_ermita_peña') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_mijas_ermita_peña');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_mijas_iglesia_inmaculada', 'poi_mijas_iglesia_inmaculada', 'guide/pois/poi_mijas_iglesia_inmaculada.jpg', 'image', 'PRIMARY_IMAGE', 1280, 1706, 701263, 0, 'https://commons.wikimedia.org/wiki/File:Mijas_12.jpg', 'Olaf Tausch', 'CC BY 3.0', 'https://creativecommons.org/licenses/by/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_mijas_iglesia_inmaculada') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_mijas_iglesia_inmaculada');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_mijas_jardines_muralla', 'poi_mijas_jardines_muralla', 'guide/pois/poi_mijas_jardines_muralla.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 607519, 0, 'https://commons.wikimedia.org/wiki/File:Jardines_de_la_Muralla_Mijas.jpg', 'Tyk', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_mijas_jardines_muralla') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_mijas_jardines_muralla');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_mijas_museo_historico', 'poi_mijas_museo_historico', 'guide/pois/poi_mijas_museo_historico.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 292742, 0, 'https://commons.wikimedia.org/wiki/File:Museo_de_Mijas.jpg', 'Tyk', 'CC BY-SA 3.0', 'http://creativecommons.org/licenses/by-sa/3.0/'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_mijas_museo_historico') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_mijas_museo_historico');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_mijas_plaza_toros', 'poi_mijas_plaza_toros', 'guide/pois/poi_mijas_plaza_toros.jpg', 'image', 'PRIMARY_IMAGE', 1024, 768, 284275, 0, 'https://commons.wikimedia.org/wiki/File:Plaza_de_toros_de_Mijas-247890123.jpg', 'Hunda', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_mijas_plaza_toros') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_mijas_plaza_toros');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_balcon', 'poi_balcon', 'guide/pois/poi_balcon.jpg', 'image', 'PRIMARY_IMAGE', 1280, 853, 391531, 0, 'https://commons.wikimedia.org/wiki/File:City_of_Nerja.jpg', 'Olga1969', 'CC BY 4.0', 'https://creativecommons.org/licenses/by/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_balcon') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_balcon');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_burriana', 'poi_burriana', 'guide/pois/poi_burriana.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 390082, 0, 'https://commons.wikimedia.org/wiki/File:Burriana_(6861858288).jpg', 'michael clarke stuff', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_burriana') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_burriana');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_cuevas', 'poi_cuevas', 'guide/pois/poi_cuevas.jpg', 'image', 'PRIMARY_IMAGE', 1280, 1024, 621168, 0, 'https://commons.wikimedia.org/wiki/File:Cueva_de_Nerja_2020.jpg', 'Fernando', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_cuevas') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_cuevas');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_nerja_acantilados_maro', 'poi_nerja_acantilados_maro', 'guide/pois/poi_nerja_acantilados_maro.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 259487, 0, 'https://commons.wikimedia.org/wiki/File:Acantilados_de_Maro.jpg', 'Cayetano', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_nerja_acantilados_maro') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_nerja_acantilados_maro');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_nerja_acueducto_aguila', 'poi_nerja_acueducto_aguila', 'guide/pois/poi_nerja_acueducto_aguila.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 477845, 0, 'https://commons.wikimedia.org/wiki/File:Aquaduct_Nerja_(7007988881).jpg', 'michael clarke stuff', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_nerja_acueducto_aguila') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_nerja_acueducto_aguila');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_nerja_ermita_angustias', 'poi_nerja_ermita_angustias', 'guide/pois/poi_nerja_ermita_angustias.jpg', 'image', 'PRIMARY_IMAGE', 1280, 854, 477343, 0, 'https://commons.wikimedia.org/wiki/File:Nerja,_the_church_%22Ermita_de_Nuestra_Se%C3%B1ora_de_las_Angustias%22.jpg', 'Dguendel', 'CC BY 3.0', 'https://creativecommons.org/licenses/by/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_nerja_ermita_angustias') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_nerja_ermita_angustias');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_nerja_frigiliana', 'poi_nerja_frigiliana', 'guide/pois/poi_nerja_frigiliana.jpg', 'image', 'PRIMARY_IMAGE', 1280, 413, 200132, 0, 'https://commons.wikimedia.org/wiki/File:FrigilianaPano3.jpg', 'Aqwis', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_nerja_frigiliana') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_nerja_frigiliana');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_nerja_maro', 'poi_nerja_maro', 'guide/pois/poi_nerja_maro.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 299239, 0, 'https://commons.wikimedia.org/wiki/File:Maro.jpg', 'Trucknroll', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_nerja_maro') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_nerja_maro');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_nerja_museo_nerja', 'poi_nerja_museo_nerja', 'guide/pois/poi_nerja_museo_nerja.jpg', 'image', 'PRIMARY_IMAGE', 1280, 859, 250267, 0, 'https://commons.wikimedia.org/wiki/File:Plaza_de_Espa%C3%B1a_en_Nerja_-_DSC_2948.JPG', 'Juanje 2712', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_nerja_museo_nerja') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_nerja_museo_nerja');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_rincon_de_la_victoria_benagalbon', 'poi_rincon_de_la_victoria_benagalbon', 'guide/pois/poi_rincon_de_la_victoria_benagalbon.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 435612, 0, 'https://commons.wikimedia.org/wiki/File:Benagalb%C3%B3n.jpg', 'Juan Pablo Olmo', 'CC BY 2.0', 'https://creativecommons.org/licenses/by/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_rincon_de_la_victoria_benagalbon') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_rincon_de_la_victoria_benagalbon');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_rincon_de_la_victoria_casa_fuerte_bezmiliana', 'poi_rincon_de_la_victoria_casa_fuerte_bezmiliana', 'guide/pois/poi_rincon_de_la_victoria_casa_fuerte_bezmiliana.jpg', 'image', 'PRIMARY_IMAGE', 1280, 917, 407040, 0, 'https://commons.wikimedia.org/wiki/File:Castillo_de_Bezmiliana1.jpg', 'Miwipedia', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_rincon_de_la_victoria_casa_fuerte_bezmiliana') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_rincon_de_la_victoria_casa_fuerte_bezmiliana');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_rincon_de_la_victoria_cueva_tesoro', 'poi_rincon_de_la_victoria_cueva_tesoro', 'guide/pois/poi_rincon_de_la_victoria_cueva_tesoro.jpg', 'image', 'PRIMARY_IMAGE', 1280, 1707, 506994, 0, 'https://commons.wikimedia.org/wiki/File:Cueva_del_Tesoro_2.jpg', 'JamesNarmer', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_rincon_de_la_victoria_cueva_tesoro') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_rincon_de_la_victoria_cueva_tesoro');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_ronda_alameda_tajo', 'poi_ronda_alameda_tajo', 'guide/pois/poi_ronda_alameda_tajo.jpg', 'image', 'PRIMARY_IMAGE', 1280, 902, 534574, 0, 'https://commons.wikimedia.org/wiki/File:Alameda_del_Tajo.jpg', 'Britanglishman', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_ronda_alameda_tajo') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_ronda_alameda_tajo');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_ronda_banos_arabes', 'poi_ronda_banos_arabes', 'guide/pois/poi_ronda_banos_arabes.jpg', 'image', 'PRIMARY_IMAGE', 1280, 920, 332080, 0, 'https://commons.wikimedia.org/wiki/File:Ba%C3%B1os_Arabes3.jpg', 'Pedro J Pacheco', 'CC BY-SA 3.0 es', 'https://creativecommons.org/licenses/by-sa/3.0/es/deed.en'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_ronda_banos_arabes') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_ronda_banos_arabes');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_ronda_casa_don_bosco', 'poi_ronda_casa_don_bosco', 'guide/pois/poi_ronda_casa_don_bosco.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 507235, 0, 'https://commons.wikimedia.org/wiki/File:Casa_Museo_Don_Bosco_Ronda_-_jard%C3%ADn,_fuente.jpg', 'CasaMuseoDonBosco', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_ronda_casa_don_bosco') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_ronda_casa_don_bosco');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_ronda_casa_rey_moro', 'poi_ronda_casa_rey_moro', 'guide/pois/poi_ronda_casa_rey_moro.jpg', 'image', 'PRIMARY_IMAGE', 1409, 1193, 1058696, 0, 'https://commons.wikimedia.org/wiki/File:Casa_del_Rey_Moro.jpg', 'cloudsoup', 'CC BY 2.0', 'https://creativecommons.org/licenses/by/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_ronda_casa_rey_moro') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_ronda_casa_rey_moro');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_ronda_convento_merced', 'poi_ronda_convento_merced', 'guide/pois/poi_ronda_convento_merced.jpg', 'image', 'PRIMARY_IMAGE', 1280, 995, 273065, 0, 'https://commons.wikimedia.org/wiki/File:Convento_de_la_Merced_(1).jpg', 'Vanbasten 23', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_ronda_convento_merced') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_ronda_convento_merced');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_ronda_cueva_pileta', 'poi_ronda_cueva_pileta', 'guide/pois/poi_ronda_cueva_pileta.jpg', 'image', 'PRIMARY_IMAGE', 1280, 1920, 1089687, 0, 'https://commons.wikimedia.org/wiki/File:Entrada_pileta.jpg', 'user:falconaumanni', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_ronda_cueva_pileta') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_ronda_cueva_pileta');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_ronda_espiritu_santo', 'poi_ronda_espiritu_santo', 'guide/pois/poi_ronda_espiritu_santo.jpg', 'image', 'PRIMARY_IMAGE', 1600, 1200, 559751, 0, 'https://commons.wikimedia.org/wiki/File:Eglise_Ronda_(23537403229).jpg', 'IMBiblio', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_ronda_espiritu_santo') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_ronda_espiritu_santo');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_ronda_jardines_cuenca', 'poi_ronda_jardines_cuenca', 'guide/pois/poi_ronda_jardines_cuenca.jpg', 'image', 'PRIMARY_IMAGE', 1280, 854, 487722, 0, 'https://commons.wikimedia.org/wiki/File:Ronda_2015_10_21_2429_(24248860524).jpg', 'Harvey Barrison from Massapequa, NY, USA', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_ronda_jardines_cuenca') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_ronda_jardines_cuenca');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_ronda_mirador_camino_molinos', 'poi_ronda_mirador_camino_molinos', 'guide/pois/poi_ronda_mirador_camino_molinos.jpg', 'image', 'PRIMARY_IMAGE', 1280, 1919, 1031860, 0, 'https://commons.wikimedia.org/wiki/File:%22Puente_Nuevo%22_de_Ronda.jpg', 'Andbog', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_ronda_mirador_camino_molinos') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_ronda_mirador_camino_molinos');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_ronda_museo_lara', 'poi_ronda_museo_lara', 'guide/pois/poi_ronda_museo_lara.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 302597, 0, 'https://commons.wikimedia.org/wiki/File:Lara_Museum-01.JPG', 'Andras Vadas', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_ronda_museo_lara') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_ronda_museo_lara');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_ronda_palacio_mondragon', 'poi_ronda_palacio_mondragon', 'guide/pois/poi_ronda_palacio_mondragon.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 365741, 0, 'https://commons.wikimedia.org/wiki/File:Palacio_de_Mondragon_-_Plaza_Mondrag%C3%B3n,_Ronda_(14661139774).jpg', 'Elliott Brown from Birmingham, United Kingdom', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_ronda_palacio_mondragon') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_ronda_palacio_mondragon');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_ronda_plaza_socorro', 'poi_ronda_plaza_socorro', 'guide/pois/poi_ronda_plaza_socorro.jpg', 'image', 'PRIMARY_IMAGE', 1280, 851, 247897, 0, 'https://commons.wikimedia.org/wiki/File:DSC_0280_(24539946027).jpg', 'Michael Gaylard from Horsham, UK', 'CC BY 2.0', 'https://creativecommons.org/licenses/by/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_ronda_plaza_socorro') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_ronda_plaza_socorro');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_ronda_plaza_toros', 'poi_ronda_plaza_toros', 'guide/pois/poi_ronda_plaza_toros.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 216271, 0, 'https://commons.wikimedia.org/wiki/File:La_Plaza_de_Toros_-_panoramio_-_Itto_Ogami_(5).jpg', 'Itto Ogami', 'CC BY 3.0', 'https://creativecommons.org/licenses/by/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_ronda_plaza_toros') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_ronda_plaza_toros');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_ronda_puente_nuevo', 'poi_ronda_puente_nuevo', 'guide/pois/poi_ronda_puente_nuevo.jpg', 'image', 'PRIMARY_IMAGE', 1919, 2558, 1395972, 0, 'https://commons.wikimedia.org/wiki/File:Punte_Nuevo_Bridge,_Ronda_-_Spain.jpg', 'Mark Gilbert', 'CC BY 3.0', 'https://creativecommons.org/licenses/by/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_ronda_puente_nuevo') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_ronda_puente_nuevo');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_ronda_puente_romano', 'poi_ronda_puente_romano', 'guide/pois/poi_ronda_puente_romano.jpg', 'image', 'PRIMARY_IMAGE', 1280, 1707, 1018478, 0, 'https://commons.wikimedia.org/wiki/File:29400_Ronda,_M%C3%A1laga,_Spain_-_panoramio_(4).jpg', 'John Zederkof Jessen', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_ronda_puente_romano') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_ronda_puente_romano');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_ronda_puente_viejo', 'poi_ronda_puente_viejo', 'guide/pois/poi_ronda_puente_viejo.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 403491, 0, 'https://commons.wikimedia.org/wiki/File:Ronda_Puente_Viejo_1.jpg', 'Andrzej Otrębski', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_ronda_puente_viejo') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_ronda_puente_viejo');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_ronda_puerta_almocabar', 'poi_ronda_puerta_almocabar', 'guide/pois/poi_ronda_puerta_almocabar.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 325224, 0, 'https://commons.wikimedia.org/wiki/File:Puerta_de_Carlos_V_y_puerta_del_Almoc%C3%A1bar.JPG', 'Aldo Ardetti', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_ronda_puerta_almocabar') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_ronda_puerta_almocabar');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_ronda_santa_maria_mayor', 'poi_ronda_santa_maria_mayor', 'guide/pois/poi_ronda_santa_maria_mayor.jpg', 'image', 'PRIMARY_IMAGE', 1280, 1708, 538669, 0, 'https://commons.wikimedia.org/wiki/File:Ronda_Santa_Mar%C3%ADa_la_Mayor_05.jpg', 'Olaf Tausch', 'CC BY 3.0', 'https://creativecommons.org/licenses/by/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_ronda_santa_maria_mayor') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_ronda_santa_maria_mayor');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_msb1rniw_077bzs', 'poi_msb1rniw_077bzs', 'guide/pois/poi_msb1rniw_077bzs.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 507935, 0, 'https://commons.wikimedia.org/wiki/File:Casa_de_los_Navajas.jpg', 'Terry Wha', 'CC BY 2.0', 'https://creativecommons.org/licenses/by/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_msb1rniw_077bzs') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_msb1rniw_077bzs');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_torremolinos_bateria', 'poi_torremolinos_bateria', 'guide/pois/poi_torremolinos_bateria.jpg', 'image', 'PRIMARY_IMAGE', 1600, 1200, 667401, 0, 'https://commons.wikimedia.org/wiki/File:Parque_de_la_Bater%C3%ADa.jpg', 'Miwipedia', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_torremolinos_bateria') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_torremolinos_bateria');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_torremolinos_centro_cultural_picasso', 'poi_torremolinos_centro_cultural_picasso', 'guide/pois/poi_torremolinos_centro_cultural_picasso.jpg', 'image', 'PRIMARY_IMAGE', 1280, 964, 407590, 0, 'https://commons.wikimedia.org/wiki/File:Torremolinos_099.jpg', 'Tyk', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_torremolinos_centro_cultural_picasso') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_torremolinos_centro_cultural_picasso');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_torremolinos_iglesia_san_miguel', 'poi_torremolinos_iglesia_san_miguel', 'guide/pois/poi_torremolinos_iglesia_san_miguel.jpg', 'image', 'PRIMARY_IMAGE', 1600, 1200, 220915, 0, 'https://commons.wikimedia.org/wiki/File:Torremolinos_-_Iglesia_de_San_Miguel_Arc%C3%A1ngel_2.jpg', 'Zarateman', 'CC0', 'http://creativecommons.org/publicdomain/zero/1.0/deed.en'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_torremolinos_iglesia_san_miguel') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_torremolinos_iglesia_san_miguel');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_torremolinos_molino_inca', 'poi_torremolinos_molino_inca', 'guide/pois/poi_torremolinos_molino_inca.jpg', 'image', 'PRIMARY_IMAGE', 1024, 768, 620871, 0, 'https://commons.wikimedia.org/wiki/File:Molino_de_Inca.jpg', 'tree-species', 'CC BY 2.0', 'https://creativecommons.org/licenses/by/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_torremolinos_molino_inca') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_torremolinos_molino_inca');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_torremolinos_torre_pimentel', 'poi_torremolinos_torre_pimentel', 'guide/pois/poi_torremolinos_torre_pimentel.jpg', 'image', 'PRIMARY_IMAGE', 1280, 1707, 560108, 0, 'https://commons.wikimedia.org/wiki/File:Torre_de_los_Molinos.jpg', 'Tyk', 'CC BY-SA 3.0', 'http://creativecommons.org/licenses/by-sa/3.0/'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_torremolinos_torre_pimentel') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_torremolinos_torre_pimentel');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_torrox_ermita_nieves', 'poi_torrox_ermita_nieves', 'guide/pois/poi_torrox_ermita_nieves.jpg', 'image', 'PRIMARY_IMAGE', 1280, 952, 422032, 0, 'https://commons.wikimedia.org/wiki/File:Torrox_-_14.jpg', 'Wayne77', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_torrox_ermita_nieves') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_torrox_ermita_nieves');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_torrox_iglesia_encarnacion', 'poi_torrox_iglesia_encarnacion', 'guide/pois/poi_torrox_iglesia_encarnacion.jpg', 'image', 'PRIMARY_IMAGE', 1280, 1707, 536289, 0, 'https://commons.wikimedia.org/wiki/File:Ntra._Sr._de_la_Encarnaci%C3%B3n_Torrox.jpg', 'Cayetano', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_torrox_iglesia_encarnacion') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_torrox_iglesia_encarnacion');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_torrox_torrox_pueblo', 'poi_torrox_torrox_pueblo', 'guide/pois/poi_torrox_torrox_pueblo.jpg', 'image', 'PRIMARY_IMAGE', 1280, 853, 407922, 0, 'https://commons.wikimedia.org/wiki/File:Torrox_Pueblo.jpg', 'Grenzlandstern', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_torrox_torrox_pueblo') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_torrox_torrox_pueblo');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_fuengirola_casco_antiguo', 'poi_fuengirola_casco_antiguo', 'guide/pois/poi_fuengirola_casco_antiguo.jpg', 'image', 'PRIMARY_IMAGE', 1280, 848, 258290, 0, 'https://commons.wikimedia.org/wiki/File:Fuengirola_-_Pfarrkirche_Unserer_Lieben_Frau_vom_Rosenkranz.JPG', 'Scorpion54', 'CC0', 'http://creativecommons.org/publicdomain/zero/1.0/deed.en'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_fuengirola_casco_antiguo') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_fuengirola_casco_antiguo');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_mijas_cala', 'poi_mijas_cala', 'guide/pois/poi_mijas_cala.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 281010, 0, 'https://commons.wikimedia.org/wiki/File:Playa_de_la_Cala,_Mijas_04.JPG', 'Tyk', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_mijas_cala') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_mijas_cala');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_nerja_iglesia_salvador', 'poi_nerja_iglesia_salvador', 'guide/pois/poi_nerja_iglesia_salvador.jpg', 'image', 'PRIMARY_IMAGE', 1280, 1734, 509595, 0, 'https://commons.wikimedia.org/wiki/File:Church_of_El_Salvador_Nerja_2014.jpg', 'Tuxyso', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_nerja_iglesia_salvador') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_nerja_iglesia_salvador');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_torremolinos_cocodrilos', 'poi_torremolinos_cocodrilos', 'guide/pois/poi_torremolinos_cocodrilos.jpg', 'image', 'PRIMARY_IMAGE', 1280, 853, 441082, 0, 'https://commons.wikimedia.org/wiki/File:Crocodile_in_Torremolinos_04.jpg', 'Schnobby', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_torremolinos_cocodrilos') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_torremolinos_cocodrilos');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_fuengirola_termas_torreblanca', 'poi_fuengirola_termas_torreblanca', 'guide/pois/poi_fuengirola_termas_torreblanca.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 674053, 0, 'https://commons.wikimedia.org/wiki/File:Termas_de_Torreblanca_20251108_104315.jpg', 'Tyk', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_fuengirola_termas_torreblanca') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_fuengirola_termas_torreblanca');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_fuengirola_finca_secretario', 'poi_fuengirola_finca_secretario', 'guide/pois/poi_fuengirola_finca_secretario.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 602179, 0, 'https://commons.wikimedia.org/wiki/File:Finca_del_Secretario_20251106_133946.jpg', 'Tyk', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_fuengirola_finca_secretario') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_fuengirola_finca_secretario');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_rincon_de_la_victoria_villa_antiopa', 'poi_rincon_de_la_victoria_villa_antiopa', 'guide/pois/poi_rincon_de_la_victoria_villa_antiopa.jpg', 'image', 'PRIMARY_IMAGE', 1280, 2276, 936363, 0, 'https://commons.wikimedia.org/wiki/File:Villa_romana_Rinc%C3%B3n_de_la_Victoria.jpg', 'JamesNarmer', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_rincon_de_la_victoria_villa_antiopa') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_rincon_de_la_victoria_villa_antiopa');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_torrox_faro_torrox', 'poi_torrox_faro_torrox', 'guide/pois/poi_torrox_faro_torrox.jpg', 'image', 'PRIMARY_IMAGE', 1280, 576, 148343, 0, 'https://commons.wikimedia.org/wiki/File:Conjunto_arqueologico_El_Faro_de_Torrox.jpg', 'AGP a tope', 'CC0', 'http://creativecommons.org/publicdomain/zero/1.0/deed.en'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_torrox_faro_torrox') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_torrox_faro_torrox');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_rincon_de_la_victoria_iglesia_victoria', 'poi_rincon_de_la_victoria_iglesia_victoria', 'guide/pois/poi_rincon_de_la_victoria_iglesia_victoria.jpg', 'image', 'PRIMARY_IMAGE', 1280, 997, 304587, 0, 'https://commons.wikimedia.org/wiki/File:Rinc%C3%B3n_de_la_Victoria_-_Parroquia_de_Nuestra_Se%C3%B1ora_de_la_Victoria_1.jpg', 'Zarateman', 'CC0', 'http://creativecommons.org/publicdomain/zero/1.0/deed.en'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_rincon_de_la_victoria_iglesia_victoria') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_rincon_de_la_victoria_iglesia_victoria');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_mijas_burro_taxi', 'poi_mijas_burro_taxi', 'guide/pois/poi_mijas_burro_taxi.jpg', 'image', 'PRIMARY_IMAGE', 1280, 959, 546322, 0, 'https://commons.wikimedia.org/wiki/File:Mijas_03.jpg', 'Olaf Tausch', 'CC BY 3.0', 'https://creativecommons.org/licenses/by/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_mijas_burro_taxi') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_mijas_burro_taxi');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_nerja_verano_azul', 'poi_nerja_verano_azul', 'guide/pois/poi_nerja_verano_azul.jpg', 'image', 'PRIMARY_IMAGE', 1280, 854, 374986, 0, 'https://commons.wikimedia.org/wiki/File:Parque_Verano_Azul_(41268226332).jpg', 'Haydn Blackey from Cardiff, Wales', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_nerja_verano_azul') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_nerja_verano_azul');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_rincon_de_la_victoria_santuario_carmen', 'poi_rincon_de_la_victoria_santuario_carmen', 'guide/pois/poi_rincon_de_la_victoria_santuario_carmen.jpg', 'image', 'PRIMARY_IMAGE', 1280, 1707, 693124, 0, 'https://commons.wikimedia.org/wiki/File:Santuario_de_la_Virgen_del_Carmen.jpg', 'Cerámica Artística Javier Postigo = Rincon dela Victoria', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_rincon_de_la_victoria_santuario_carmen') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_rincon_de_la_victoria_santuario_carmen');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_ronda_paseo_blas_infante', 'poi_ronda_paseo_blas_infante', 'guide/pois/poi_ronda_paseo_blas_infante.jpg', 'image', 'PRIMARY_IMAGE', 1280, 1707, 1175766, 0, 'https://commons.wikimedia.org/wiki/File:Paseo_de_Blas_Infante_(51041157166).jpg', 'F Delventhal from Outside Washington, D.C., US', 'CC BY 2.0', 'https://creativecommons.org/licenses/by/2.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_ronda_paseo_blas_infante') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_ronda_paseo_blas_infante');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_ronda_plaza_duquesa_parcent', 'poi_ronda_plaza_duquesa_parcent', 'guide/pois/poi_ronda_plaza_duquesa_parcent.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 335836, 0, 'https://commons.wikimedia.org/wiki/File:Plaza_Duquesa_de_Parcent_Ronda_124114.jpg', 'Tyk', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_ronda_plaza_duquesa_parcent') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_ronda_plaza_duquesa_parcent');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_fuengirola_parque_fluvial', 'poi_fuengirola_parque_fluvial', 'guide/pois/poi_fuengirola_parque_fluvial.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 551988, 0, 'https://commons.wikimedia.org/wiki/File:Rio_Fuengirola_1.jpg', 'Numeroalto', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_fuengirola_parque_fluvial') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_fuengirola_parque_fluvial');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_torremolinos_cuesta_tajo', 'poi_torremolinos_cuesta_tajo', 'guide/pois/poi_torremolinos_cuesta_tajo.jpg', 'image', 'PRIMARY_IMAGE', 1200, 1600, 216155, 0, 'https://commons.wikimedia.org/wiki/File:Torremolinos_05.jpg', 'Zarateman', 'CC0', 'http://creativecommons.org/publicdomain/zero/1.0/deed.en'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_torremolinos_cuesta_tajo') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_torremolinos_cuesta_tajo');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_torremolinos_san_miguel', 'poi_torremolinos_san_miguel', 'guide/pois/poi_torremolinos_san_miguel.jpg', 'image', 'PRIMARY_IMAGE', 1200, 1600, 186063, 0, 'https://commons.wikimedia.org/wiki/File:Torremolinos_-_Calle.jpg', 'Zarateman', 'CC0', 'http://creativecommons.org/publicdomain/zero/1.0/deed.en'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_torremolinos_san_miguel') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_torremolinos_san_miguel');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_marbella_murallas_castillo', 'poi_marbella_murallas_castillo', 'guide/pois/poi_marbella_murallas_castillo.jpg', 'image', 'PRIMARY_IMAGE', 1280, 964, 476206, 0, 'https://commons.wikimedia.org/wiki/File:Marbella_castle.jpg', 'Tyk', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_marbella_murallas_castillo') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_marbella_murallas_castillo');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_mubz2n83_sub71a', 'poi_mubz2n83_sub71a', 'guide/pois/poi_mubz2n83_sub71a.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 368215, 0, 'https://commons.wikimedia.org/wiki/File:Benalroma.jpg', 'Gpdelasinfantas', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_mubz2n83_sub71a') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_mubz2n83_sub71a');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_ronda_museo_joaquin_peinado', 'poi_ronda_museo_joaquin_peinado', 'guide/pois/poi_ronda_museo_joaquin_peinado.jpg', 'image', 'PRIMARY_IMAGE', 1280, 1920, 467053, 0, 'https://commons.wikimedia.org/wiki/File:Museo_Unicaja_Joaqu%C3%ADn_Peinado.jpg', 'Vanbasten 23', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_ronda_museo_joaquin_peinado') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_ronda_museo_joaquin_peinado');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_ronda_tajo', 'poi_ronda_tajo', 'guide/pois/poi_ronda_tajo.jpg', 'image', 'PRIMARY_IMAGE', 1279, 989, 625850, 0, 'https://commons.wikimedia.org/wiki/File:Puente_Nuevo_and_El_Tajo_gorge_-_Ronda,_Spain_-_panoramio.jpg', 'Sergey Ashmarin', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_ronda_tajo') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_ronda_tajo');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_marbella_casco_antiguo', 'poi_marbella_casco_antiguo', 'guide/pois/poi_marbella_casco_antiguo.jpg', 'image', 'PRIMARY_IMAGE', 1280, 1707, 478966, 0, 'https://commons.wikimedia.org/wiki/File:Marbella_Old_town_1.JPG', 'Ypsilon from Finland', 'CC0', 'http://creativecommons.org/publicdomain/zero/1.0/deed.en'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_marbella_casco_antiguo') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_marbella_casco_antiguo');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_mijas_casco_antiguo', 'poi_mijas_casco_antiguo', 'guide/pois/poi_mijas_casco_antiguo.jpg', 'image', 'PRIMARY_IMAGE', 1280, 1707, 397609, 0, 'https://commons.wikimedia.org/wiki/File:Mijas_street_3113.JPG', 'Tyk', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_mijas_casco_antiguo') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_mijas_casco_antiguo');
INSERT INTO guide_poi_media (id, poi_id, r2_key, media_type, role, width, height, file_size, order_index, source_url, author, license, license_url)
SELECT 'poimedia_poi_torremolinos_el_morro', 'poi_torremolinos_el_morro', 'guide/pois/poi_torremolinos_el_morro.jpg', 'image', 'PRIMARY_IMAGE', 1280, 960, 232385, 0, 'https://commons.wikimedia.org/wiki/File:Punta_de_Torremolinos.jpg', 'Tyk', 'CC BY-SA 3.0', 'http://creativecommons.org/licenses/by-sa/3.0/'
WHERE EXISTS (SELECT 1 FROM guide_pois WHERE id = 'poi_torremolinos_el_morro') AND NOT EXISTS (SELECT 1 FROM guide_poi_media WHERE poi_id = 'poi_torremolinos_el_morro');
