-- 0102: textos de la carta que faltaban en los 13 idiomas (apps/client/src/carta/strings.ts, bloque 0102):
--   - "¿Te reconocemos la próxima vez que vengas?" (carta_remember_*): el permiso para reconocer al
--     comensal entre visitas, que ahora se pide en la bienvenida de la carta y no en un splash en español.
--   - Los diálogos heredados que la carta abre (pedido a domicilio, tarjeta de sellos, valoración,
--     instalar en iPhone): salían siempre en español porque no tenían claves (carta_dlv_*, carta_loy_*,
--     carta_rt_*, carta_ios_*).
-- Claves nuevas, prefijo carta_. Idempotente (INSERT OR REPLACE). Un INSERT por idioma: D1 rechaza una
-- sentencia demasiado grande (SQLITE_TOOBIG, ver 0099).
-- La respuesta de /restaurants/:slug/reels va cacheada en KV (menu:{slug}:{lang}:v{ver}): tras aplicarla
-- hay que subir ver:restaurant:{slug} de cada carta.
-- es
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('reels', 'carta_notif_error', 'es', 'No se han podido activar los avisos', 'Carta Mediterránea'),
('reels', 'carta_remember_q', 'es', '¿Te reconocemos la próxima vez que vengas?', 'Carta Mediterránea'),
('reels', 'carta_remember_sub', 'es', 'Guardamos un número al azar en este móvil durante 12 meses para que el restaurante sepa que has vuelto. Sin tu nombre y sin publicidad.', 'Carta Mediterránea'),
('reels', 'carta_remember_more', 'es', 'Más información', 'Carta Mediterránea'),
('reels', 'carta_remember_yes', 'es', 'Sí', 'Carta Mediterránea'),
('reels', 'carta_remember_no', 'es', 'No', 'Carta Mediterránea'),
('reels', 'carta_remember_done_yes', 'es', 'Te reconoceremos', 'Carta Mediterránea'),
('reels', 'carta_remember_done_no', 'es', 'De acuerdo, no te recordamos', 'Carta Mediterránea'),
('reels', 'carta_confirm', 'es', 'Confirmar', 'Carta Mediterránea'),
('reels', 'carta_rt_title', 'es', '¿Qué te ha parecido?', 'Carta Mediterránea'),
('reels', 'carta_rt_title_prev', 'es', 'Tu valoración', 'Carta Mediterránea'),
('reels', 'carta_rt_sub', 'es', 'Tu opinión nos ayuda a mejorar.', 'Carta Mediterránea'),
('reels', 'carta_rt_improve', 'es', '¿En qué podemos mejorar?', 'Carta Mediterránea'),
('reels', 'carta_rt_send', 'es', 'Enviar', 'Carta Mediterránea'),
('reels', 'carta_rt_star', 'es', '{n} de 5', 'Carta Mediterránea'),
('reels', 'carta_rt_glad', 'es', '¡Nos alegra que te haya gustado!', 'Carta Mediterránea'),
('reels', 'carta_rt_google_invite', 'es', 'Te invitamos a compartir tu experiencia en Google para ayudarnos a crecer.', 'Carta Mediterránea'),
('reels', 'carta_rt_google_btn', 'es', 'Escribir reseña en Google', 'Carta Mediterránea'),
('reels', 'carta_rt_thanks', 'es', '¡Gracias por tu opinión!', 'Carta Mediterránea'),
('reels', 'carta_rt_thanks_sub', 'es', 'Tomamos nota para seguir mejorando.', 'Carta Mediterránea'),
('reels', 'carta_loy_title', 'es', 'Tu tarjeta de fidelidad', 'Carta Mediterránea'),
('reels', 'carta_loy_reward', 'es', 'Completa la tarjeta y consigue: {reward}', 'Carta Mediterránea'),
('reels', 'carta_loy_generic', 'es', 'Junta sellos en cada visita y consigue tu premio', 'Carta Mediterránea'),
('reels', 'carta_loy_count', 'es', '{n} de {total} sellos', 'Carta Mediterránea'),
('reels', 'carta_loy_redeemed', 'es', 'Ya canjeaste esta tarjeta. ¡Gracias por volver!', 'Carta Mediterránea'),
('reels', 'carta_loy_view_reward', 'es', 'Ver mi premio', 'Carta Mediterránea'),
('reels', 'carta_loy_ask_staff', 'es', 'Pide al camarero que introduzca el PIN', 'Carta Mediterránea'),
('reels', 'carta_loy_add', 'es', 'Sumar sello', 'Carta Mediterránea'),
('reels', 'carta_loy_pin_required', 'es', 'Introduce el PIN de 4 dígitos', 'Carta Mediterránea'),
('reels', 'carta_loy_pin_wrong', 'es', 'PIN incorrecto', 'Carta Mediterránea'),
('reels', 'carta_ios_offers', 'es', 'Ofertas VIP', 'Carta Mediterránea'),
('reels', 'carta_ios_fast', 'es', 'Más rápido', 'Carta Mediterránea'),
('reels', 'carta_ios_title', 'es', 'Añade la carta a tu iPhone', 'Carta Mediterránea'),
('reels', 'carta_ios_body', 'es', 'En iPhone los avisos solo llegan si la carta está en tu pantalla de inicio. Ábrela desde allí y actívalos.', 'Carta Mediterránea'),
('reels', 'carta_ios_step1', 'es', 'Pulsa «Compartir» abajo', 'Carta Mediterránea'),
('reels', 'carta_ios_step2', 'es', 'Elige «Añadir a pantalla de inicio»', 'Carta Mediterránea'),
('reels', 'carta_ios_never', 'es', 'No volver a mostrar', 'Carta Mediterránea'),
('reels', 'carta_dlv_title', 'es', 'Pedir a domicilio', 'Carta Mediterránea'),
('reels', 'carta_dlv_closed_today', 'es', 'Hoy no hay servicio de reparto', 'Carta Mediterránea'),
('reels', 'carta_dlv_outside_hours', 'es', 'Fuera del horario de reparto', 'Carta Mediterránea'),
('reels', 'carta_dlv_unavailable', 'es', 'Servicio no disponible', 'Carta Mediterránea'),
('reels', 'carta_dlv_empty', 'es', 'Aún no has añadido nada al pedido', 'Carta Mediterránea'),
('reels', 'carta_dlv_minimum', 'es', 'Pedido mínimo: {amount}', 'Carta Mediterránea'),
('reels', 'carta_dlv_details', 'es', 'Datos de entrega', 'Carta Mediterránea'),
('reels', 'carta_dlv_name', 'es', 'Nombre (opcional)', 'Carta Mediterránea'),
('reels', 'carta_dlv_phone', 'es', 'Teléfono *', 'Carta Mediterránea'),
('reels', 'carta_dlv_address', 'es', 'Dirección completa *', 'Carta Mediterránea'),
('reels', 'carta_dlv_address_ph', 'es', 'Calle, número, piso, código postal…', 'Carta Mediterránea'),
('reels', 'carta_dlv_notes', 'es', 'Notas (opcional)', 'Carta Mediterránea'),
('reels', 'carta_dlv_notes_ph', 'es', 'Instrucciones de entrega, alergias…', 'Carta Mediterránea'),
('reels', 'carta_dlv_privacy', 'es', '{restaurant} tratará tu nombre, teléfono y dirección para preparar y entregar este pedido y para cumplir sus obligaciones fiscales. No se usan para publicidad. Puedes ejercer tus derechos de acceso, rectificación y supresión.', 'Carta Mediterránea'),
('reels', 'carta_dlv_privacy_link', 'es', 'Política de privacidad', 'Carta Mediterránea'),
('reels', 'carta_dlv_allergy', 'es', 'Si tienes alergias, indícalo en las notas y confírmalo también por teléfono: los platos se elaboran en cocinas donde se manipulan todos los alérgenos.', 'Carta Mediterránea'),
('reels', 'carta_dlv_payment', 'es', 'Cómo vas a pagar *', 'Carta Mediterránea'),
('reels', 'carta_dlv_cash', 'es', 'Efectivo', 'Carta Mediterránea'),
('reels', 'carta_dlv_card', 'es', 'Tarjeta', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_phone', 'es', 'El teléfono es obligatorio', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_phone_bad', 'es', 'Teléfono no válido', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_address', 'es', 'La dirección es obligatoria', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_payment', 'es', 'Elige cómo vas a pagar', 'Carta Mediterránea'),
('reels', 'carta_dlv_area', 'es', 'Zona de reparto', 'Carta Mediterránea'),
('reels', 'carta_dlv_order', 'es', 'Tu pedido', 'Carta Mediterránea'),
('reels', 'carta_dlv_shipping', 'es', 'Envío', 'Carta Mediterránea'),
('reels', 'carta_dlv_free', 'es', 'Gratis', 'Carta Mediterránea'),
('reels', 'carta_dlv_free_from', 'es', 'Gratis a partir de {amount}', 'Carta Mediterránea'),
('reels', 'carta_dlv_vat', 'es', 'IVA incluido. Al enviar el pedido confirmas que deseas contratarlo y que conlleva la obligación de pagar este importe al restaurante.', 'Carta Mediterránea'),
('reels', 'carta_dlv_send_wa', 'es', 'Enviar pedido por WhatsApp', 'Carta Mediterránea'),
('reels', 'carta_dlv_call', 'es', 'Llamar al restaurante', 'Carta Mediterránea');
-- en
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('reels', 'carta_notif_error', 'en', 'Couldn’t turn on notifications', 'Carta Mediterránea'),
('reels', 'carta_remember_q', 'en', 'Shall we recognise you next time you come?', 'Carta Mediterránea'),
('reels', 'carta_remember_sub', 'en', 'We save a random number on this phone for 12 months so the restaurant knows you’ve come back. No name, no advertising.', 'Carta Mediterránea'),
('reels', 'carta_remember_more', 'en', 'More information', 'Carta Mediterránea'),
('reels', 'carta_remember_yes', 'en', 'Yes', 'Carta Mediterránea'),
('reels', 'carta_remember_no', 'en', 'No', 'Carta Mediterránea'),
('reels', 'carta_remember_done_yes', 'en', 'We’ll recognise you', 'Carta Mediterránea'),
('reels', 'carta_remember_done_no', 'en', 'OK, we won’t remember you', 'Carta Mediterránea'),
('reels', 'carta_confirm', 'en', 'Confirm', 'Carta Mediterránea'),
('reels', 'carta_rt_title', 'en', 'How was it?', 'Carta Mediterránea'),
('reels', 'carta_rt_title_prev', 'en', 'Your rating', 'Carta Mediterránea'),
('reels', 'carta_rt_sub', 'en', 'Your feedback helps us improve.', 'Carta Mediterránea'),
('reels', 'carta_rt_improve', 'en', 'What could we do better?', 'Carta Mediterránea'),
('reels', 'carta_rt_send', 'en', 'Send', 'Carta Mediterránea'),
('reels', 'carta_rt_star', 'en', '{n} out of 5', 'Carta Mediterránea'),
('reels', 'carta_rt_glad', 'en', 'We’re glad you liked it!', 'Carta Mediterránea'),
('reels', 'carta_rt_google_invite', 'en', 'Would you share your experience on Google? It helps us grow.', 'Carta Mediterránea'),
('reels', 'carta_rt_google_btn', 'en', 'Write a Google review', 'Carta Mediterránea'),
('reels', 'carta_rt_thanks', 'en', 'Thanks for your feedback!', 'Carta Mediterránea'),
('reels', 'carta_rt_thanks_sub', 'en', 'We’ve taken note and will keep improving.', 'Carta Mediterránea'),
('reels', 'carta_loy_title', 'en', 'Your loyalty card', 'Carta Mediterránea'),
('reels', 'carta_loy_reward', 'en', 'Fill the card and get: {reward}', 'Carta Mediterránea'),
('reels', 'carta_loy_generic', 'en', 'Collect stamps on every visit and earn your reward', 'Carta Mediterránea'),
('reels', 'carta_loy_count', 'en', '{n} of {total} stamps', 'Carta Mediterránea'),
('reels', 'carta_loy_redeemed', 'en', 'You’ve already redeemed this card. Thanks for coming back!', 'Carta Mediterránea'),
('reels', 'carta_loy_view_reward', 'en', 'See my reward', 'Carta Mediterránea'),
('reels', 'carta_loy_ask_staff', 'en', 'Ask your waiter to enter the PIN', 'Carta Mediterránea'),
('reels', 'carta_loy_add', 'en', 'Add a stamp', 'Carta Mediterránea'),
('reels', 'carta_loy_pin_required', 'en', 'Enter the 4-digit PIN', 'Carta Mediterránea'),
('reels', 'carta_loy_pin_wrong', 'en', 'Wrong PIN', 'Carta Mediterránea'),
('reels', 'carta_ios_offers', 'en', 'VIP offers', 'Carta Mediterránea'),
('reels', 'carta_ios_fast', 'en', 'Faster', 'Carta Mediterránea'),
('reels', 'carta_ios_title', 'en', 'Add the menu to your iPhone', 'Carta Mediterránea'),
('reels', 'carta_ios_body', 'en', 'On iPhone, notifications only arrive if the menu is on your home screen. Open it from there and turn them on.', 'Carta Mediterránea'),
('reels', 'carta_ios_step1', 'en', 'Tap “Share” below', 'Carta Mediterránea'),
('reels', 'carta_ios_step2', 'en', 'Choose “Add to Home Screen”', 'Carta Mediterránea'),
('reels', 'carta_ios_never', 'en', 'Don’t show again', 'Carta Mediterránea'),
('reels', 'carta_dlv_title', 'en', 'Order delivery', 'Carta Mediterránea'),
('reels', 'carta_dlv_closed_today', 'en', 'No delivery service today', 'Carta Mediterránea'),
('reels', 'carta_dlv_outside_hours', 'en', 'Outside delivery hours', 'Carta Mediterránea'),
('reels', 'carta_dlv_unavailable', 'en', 'Service unavailable', 'Carta Mediterránea'),
('reels', 'carta_dlv_empty', 'en', 'You haven’t added anything to your order yet', 'Carta Mediterránea'),
('reels', 'carta_dlv_minimum', 'en', 'Minimum order: {amount}', 'Carta Mediterránea'),
('reels', 'carta_dlv_details', 'en', 'Delivery details', 'Carta Mediterránea'),
('reels', 'carta_dlv_name', 'en', 'Name (optional)', 'Carta Mediterránea'),
('reels', 'carta_dlv_phone', 'en', 'Phone *', 'Carta Mediterránea'),
('reels', 'carta_dlv_address', 'en', 'Full address *', 'Carta Mediterránea'),
('reels', 'carta_dlv_address_ph', 'en', 'Street, number, floor, postcode…', 'Carta Mediterránea'),
('reels', 'carta_dlv_notes', 'en', 'Notes (optional)', 'Carta Mediterránea'),
('reels', 'carta_dlv_notes_ph', 'en', 'Delivery instructions, allergies…', 'Carta Mediterránea'),
('reels', 'carta_dlv_privacy', 'en', '{restaurant} will use your name, phone and address to prepare and deliver this order and to meet its tax obligations. They are not used for advertising. You can exercise your rights of access, rectification and erasure.', 'Carta Mediterránea'),
('reels', 'carta_dlv_privacy_link', 'en', 'Privacy policy', 'Carta Mediterránea'),
('reels', 'carta_dlv_allergy', 'en', 'If you have allergies, say so in the notes and also confirm by phone: dishes are prepared in kitchens where all allergens are handled.', 'Carta Mediterránea'),
('reels', 'carta_dlv_payment', 'en', 'How will you pay? *', 'Carta Mediterránea'),
('reels', 'carta_dlv_cash', 'en', 'Cash', 'Carta Mediterránea'),
('reels', 'carta_dlv_card', 'en', 'Card', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_phone', 'en', 'Phone number is required', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_phone_bad', 'en', 'Invalid phone number', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_address', 'en', 'Address is required', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_payment', 'en', 'Choose how you’ll pay', 'Carta Mediterránea'),
('reels', 'carta_dlv_area', 'en', 'Delivery area', 'Carta Mediterránea'),
('reels', 'carta_dlv_order', 'en', 'Your order', 'Carta Mediterránea'),
('reels', 'carta_dlv_shipping', 'en', 'Delivery', 'Carta Mediterránea'),
('reels', 'carta_dlv_free', 'en', 'Free', 'Carta Mediterránea'),
('reels', 'carta_dlv_free_from', 'en', 'Free from {amount}', 'Carta Mediterránea'),
('reels', 'carta_dlv_vat', 'en', 'VAT included. By sending the order you confirm that you wish to place it and that it entails an obligation to pay this amount to the restaurant.', 'Carta Mediterránea'),
('reels', 'carta_dlv_send_wa', 'en', 'Send order via WhatsApp', 'Carta Mediterránea'),
('reels', 'carta_dlv_call', 'en', 'Call the restaurant', 'Carta Mediterránea');
-- fr
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('reels', 'carta_notif_error', 'fr', 'Impossible d’activer les notifications', 'Carta Mediterránea'),
('reels', 'carta_remember_q', 'fr', 'On vous reconnaît la prochaine fois ?', 'Carta Mediterránea'),
('reels', 'carta_remember_sub', 'fr', 'Nous enregistrons un numéro aléatoire sur ce téléphone pendant 12 mois pour que le restaurant sache que vous êtes revenu. Sans votre nom et sans publicité.', 'Carta Mediterránea'),
('reels', 'carta_remember_more', 'fr', 'En savoir plus', 'Carta Mediterránea'),
('reels', 'carta_remember_yes', 'fr', 'Oui', 'Carta Mediterránea'),
('reels', 'carta_remember_no', 'fr', 'Non', 'Carta Mediterránea'),
('reels', 'carta_remember_done_yes', 'fr', 'Nous vous reconnaîtrons', 'Carta Mediterránea'),
('reels', 'carta_remember_done_no', 'fr', 'D’accord, nous ne vous mémorisons pas', 'Carta Mediterránea'),
('reels', 'carta_confirm', 'fr', 'Confirmer', 'Carta Mediterránea'),
('reels', 'carta_rt_title', 'fr', 'Qu’en avez-vous pensé ?', 'Carta Mediterránea'),
('reels', 'carta_rt_title_prev', 'fr', 'Votre note', 'Carta Mediterránea'),
('reels', 'carta_rt_sub', 'fr', 'Votre avis nous aide à nous améliorer.', 'Carta Mediterránea'),
('reels', 'carta_rt_improve', 'fr', 'Que pouvons-nous améliorer ?', 'Carta Mediterránea'),
('reels', 'carta_rt_send', 'fr', 'Envoyer', 'Carta Mediterránea'),
('reels', 'carta_rt_star', 'fr', '{n} sur 5', 'Carta Mediterránea'),
('reels', 'carta_rt_glad', 'fr', 'Ravis que cela vous ait plu !', 'Carta Mediterránea'),
('reels', 'carta_rt_google_invite', 'fr', 'Partagez votre expérience sur Google pour nous aider à grandir.', 'Carta Mediterránea'),
('reels', 'carta_rt_google_btn', 'fr', 'Écrire un avis sur Google', 'Carta Mediterránea'),
('reels', 'carta_rt_thanks', 'fr', 'Merci pour votre avis !', 'Carta Mediterránea'),
('reels', 'carta_rt_thanks_sub', 'fr', 'Nous en prenons note pour continuer à nous améliorer.', 'Carta Mediterránea'),
('reels', 'carta_loy_title', 'fr', 'Votre carte de fidélité', 'Carta Mediterránea'),
('reels', 'carta_loy_reward', 'fr', 'Complétez la carte et obtenez : {reward}', 'Carta Mediterránea'),
('reels', 'carta_loy_generic', 'fr', 'Cumulez des tampons à chaque visite et gagnez votre récompense', 'Carta Mediterránea'),
('reels', 'carta_loy_count', 'fr', '{n} tampons sur {total}', 'Carta Mediterránea'),
('reels', 'carta_loy_redeemed', 'fr', 'Vous avez déjà utilisé cette carte. Merci d’être revenu !', 'Carta Mediterránea'),
('reels', 'carta_loy_view_reward', 'fr', 'Voir ma récompense', 'Carta Mediterránea'),
('reels', 'carta_loy_ask_staff', 'fr', 'Demandez au serveur de saisir le code PIN', 'Carta Mediterránea'),
('reels', 'carta_loy_add', 'fr', 'Ajouter un tampon', 'Carta Mediterránea'),
('reels', 'carta_loy_pin_required', 'fr', 'Saisissez le code PIN à 4 chiffres', 'Carta Mediterránea'),
('reels', 'carta_loy_pin_wrong', 'fr', 'Code PIN incorrect', 'Carta Mediterránea'),
('reels', 'carta_ios_offers', 'fr', 'Offres VIP', 'Carta Mediterránea'),
('reels', 'carta_ios_fast', 'fr', 'Plus rapide', 'Carta Mediterránea'),
('reels', 'carta_ios_title', 'fr', 'Ajoutez la carte à votre iPhone', 'Carta Mediterránea'),
('reels', 'carta_ios_body', 'fr', 'Sur iPhone, les notifications n’arrivent que si la carte est sur votre écran d’accueil. Ouvrez-la depuis là et activez-les.', 'Carta Mediterránea'),
('reels', 'carta_ios_step1', 'fr', 'Touchez « Partager » en bas', 'Carta Mediterránea'),
('reels', 'carta_ios_step2', 'fr', 'Choisissez « Sur l’écran d’accueil »', 'Carta Mediterránea'),
('reels', 'carta_ios_never', 'fr', 'Ne plus afficher', 'Carta Mediterránea'),
('reels', 'carta_dlv_title', 'fr', 'Commander en livraison', 'Carta Mediterránea'),
('reels', 'carta_dlv_closed_today', 'fr', 'Pas de livraison aujourd’hui', 'Carta Mediterránea'),
('reels', 'carta_dlv_outside_hours', 'fr', 'En dehors des horaires de livraison', 'Carta Mediterránea'),
('reels', 'carta_dlv_unavailable', 'fr', 'Service indisponible', 'Carta Mediterránea'),
('reels', 'carta_dlv_empty', 'fr', 'Vous n’avez encore rien ajouté à la commande', 'Carta Mediterránea'),
('reels', 'carta_dlv_minimum', 'fr', 'Commande minimum : {amount}', 'Carta Mediterránea'),
('reels', 'carta_dlv_details', 'fr', 'Informations de livraison', 'Carta Mediterránea'),
('reels', 'carta_dlv_name', 'fr', 'Nom (facultatif)', 'Carta Mediterránea'),
('reels', 'carta_dlv_phone', 'fr', 'Téléphone *', 'Carta Mediterránea'),
('reels', 'carta_dlv_address', 'fr', 'Adresse complète *', 'Carta Mediterránea'),
('reels', 'carta_dlv_address_ph', 'fr', 'Rue, numéro, étage, code postal…', 'Carta Mediterránea'),
('reels', 'carta_dlv_notes', 'fr', 'Remarques (facultatif)', 'Carta Mediterránea'),
('reels', 'carta_dlv_notes_ph', 'fr', 'Instructions de livraison, allergies…', 'Carta Mediterránea'),
('reels', 'carta_dlv_privacy', 'fr', '{restaurant} utilisera votre nom, votre téléphone et votre adresse pour préparer et livrer cette commande et pour respecter ses obligations fiscales. Ils ne sont pas utilisés à des fins publicitaires. Vous pouvez exercer vos droits d’accès, de rectification et d’effacement.', 'Carta Mediterránea'),
('reels', 'carta_dlv_privacy_link', 'fr', 'Politique de confidentialité', 'Carta Mediterránea'),
('reels', 'carta_dlv_allergy', 'fr', 'Si vous avez des allergies, indiquez-le dans les remarques et confirmez-le aussi par téléphone : les plats sont préparés dans des cuisines où tous les allergènes sont manipulés.', 'Carta Mediterránea'),
('reels', 'carta_dlv_payment', 'fr', 'Mode de paiement *', 'Carta Mediterránea'),
('reels', 'carta_dlv_cash', 'fr', 'Espèces', 'Carta Mediterránea'),
('reels', 'carta_dlv_card', 'fr', 'Carte', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_phone', 'fr', 'Le téléphone est obligatoire', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_phone_bad', 'fr', 'Téléphone non valide', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_address', 'fr', 'L’adresse est obligatoire', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_payment', 'fr', 'Choisissez votre mode de paiement', 'Carta Mediterránea'),
('reels', 'carta_dlv_area', 'fr', 'Zone de livraison', 'Carta Mediterránea'),
('reels', 'carta_dlv_order', 'fr', 'Votre commande', 'Carta Mediterránea'),
('reels', 'carta_dlv_shipping', 'fr', 'Livraison', 'Carta Mediterránea'),
('reels', 'carta_dlv_free', 'fr', 'Gratuite', 'Carta Mediterránea'),
('reels', 'carta_dlv_free_from', 'fr', 'Gratuite à partir de {amount}', 'Carta Mediterránea'),
('reels', 'carta_dlv_vat', 'fr', 'TVA incluse. En envoyant la commande, vous confirmez vouloir la passer et qu’elle implique l’obligation de payer ce montant au restaurant.', 'Carta Mediterránea'),
('reels', 'carta_dlv_send_wa', 'fr', 'Envoyer la commande par WhatsApp', 'Carta Mediterránea'),
('reels', 'carta_dlv_call', 'fr', 'Appeler le restaurant', 'Carta Mediterránea');
-- de
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('reels', 'carta_notif_error', 'de', 'Benachrichtigungen konnten nicht aktiviert werden', 'Carta Mediterránea'),
('reels', 'carta_remember_q', 'de', 'Sollen wir dich beim nächsten Besuch wiedererkennen?', 'Carta Mediterránea'),
('reels', 'carta_remember_sub', 'de', 'Wir speichern 12 Monate lang eine Zufallszahl auf diesem Handy, damit das Restaurant weiß, dass du wiedergekommen bist. Ohne deinen Namen und ohne Werbung.', 'Carta Mediterránea'),
('reels', 'carta_remember_more', 'de', 'Mehr erfahren', 'Carta Mediterránea'),
('reels', 'carta_remember_yes', 'de', 'Ja', 'Carta Mediterránea'),
('reels', 'carta_remember_no', 'de', 'Nein', 'Carta Mediterránea'),
('reels', 'carta_remember_done_yes', 'de', 'Wir erkennen dich wieder', 'Carta Mediterránea'),
('reels', 'carta_remember_done_no', 'de', 'Alles klar, wir merken uns nichts', 'Carta Mediterránea'),
('reels', 'carta_confirm', 'de', 'Bestätigen', 'Carta Mediterránea'),
('reels', 'carta_rt_title', 'de', 'Wie hat es dir gefallen?', 'Carta Mediterránea'),
('reels', 'carta_rt_title_prev', 'de', 'Deine Bewertung', 'Carta Mediterránea'),
('reels', 'carta_rt_sub', 'de', 'Deine Meinung hilft uns, besser zu werden.', 'Carta Mediterránea'),
('reels', 'carta_rt_improve', 'de', 'Was können wir besser machen?', 'Carta Mediterránea'),
('reels', 'carta_rt_send', 'de', 'Senden', 'Carta Mediterránea'),
('reels', 'carta_rt_star', 'de', '{n} von 5', 'Carta Mediterránea'),
('reels', 'carta_rt_glad', 'de', 'Schön, dass es dir gefallen hat!', 'Carta Mediterránea'),
('reels', 'carta_rt_google_invite', 'de', 'Teile deine Erfahrung auf Google und hilf uns zu wachsen.', 'Carta Mediterránea'),
('reels', 'carta_rt_google_btn', 'de', 'Google-Bewertung schreiben', 'Carta Mediterránea'),
('reels', 'carta_rt_thanks', 'de', 'Danke für dein Feedback!', 'Carta Mediterránea'),
('reels', 'carta_rt_thanks_sub', 'de', 'Wir nehmen es mit, um besser zu werden.', 'Carta Mediterránea'),
('reels', 'carta_loy_title', 'de', 'Deine Treuekarte', 'Carta Mediterránea'),
('reels', 'carta_loy_reward', 'de', 'Mach die Karte voll und erhalte: {reward}', 'Carta Mediterránea'),
('reels', 'carta_loy_generic', 'de', 'Sammle bei jedem Besuch Stempel und hol dir deine Prämie', 'Carta Mediterránea'),
('reels', 'carta_loy_count', 'de', '{n} von {total} Stempeln', 'Carta Mediterránea'),
('reels', 'carta_loy_redeemed', 'de', 'Du hast diese Karte schon eingelöst. Danke, dass du wiederkommst!', 'Carta Mediterránea'),
('reels', 'carta_loy_view_reward', 'de', 'Meine Prämie ansehen', 'Carta Mediterránea'),
('reels', 'carta_loy_ask_staff', 'de', 'Bitte den Kellner, die PIN einzugeben', 'Carta Mediterránea'),
('reels', 'carta_loy_add', 'de', 'Stempel hinzufügen', 'Carta Mediterránea'),
('reels', 'carta_loy_pin_required', 'de', 'Gib die 4-stellige PIN ein', 'Carta Mediterránea'),
('reels', 'carta_loy_pin_wrong', 'de', 'Falsche PIN', 'Carta Mediterránea'),
('reels', 'carta_ios_offers', 'de', 'VIP-Angebote', 'Carta Mediterránea'),
('reels', 'carta_ios_fast', 'de', 'Schneller', 'Carta Mediterránea'),
('reels', 'carta_ios_title', 'de', 'Füge die Karte zu deinem iPhone hinzu', 'Carta Mediterránea'),
('reels', 'carta_ios_body', 'de', 'Auf dem iPhone kommen Benachrichtigungen nur an, wenn die Karte auf deinem Home-Bildschirm ist. Öffne sie dort und aktiviere sie.', 'Carta Mediterránea'),
('reels', 'carta_ios_step1', 'de', 'Tippe unten auf „Teilen“', 'Carta Mediterránea'),
('reels', 'carta_ios_step2', 'de', 'Wähle „Zum Home-Bildschirm“', 'Carta Mediterránea'),
('reels', 'carta_ios_never', 'de', 'Nicht mehr anzeigen', 'Carta Mediterránea'),
('reels', 'carta_dlv_title', 'de', 'Lieferung bestellen', 'Carta Mediterránea'),
('reels', 'carta_dlv_closed_today', 'de', 'Heute kein Lieferservice', 'Carta Mediterránea'),
('reels', 'carta_dlv_outside_hours', 'de', 'Außerhalb der Lieferzeiten', 'Carta Mediterránea'),
('reels', 'carta_dlv_unavailable', 'de', 'Service nicht verfügbar', 'Carta Mediterránea'),
('reels', 'carta_dlv_empty', 'de', 'Du hast noch nichts zur Bestellung hinzugefügt', 'Carta Mediterránea'),
('reels', 'carta_dlv_minimum', 'de', 'Mindestbestellwert: {amount}', 'Carta Mediterránea'),
('reels', 'carta_dlv_details', 'de', 'Lieferdaten', 'Carta Mediterránea'),
('reels', 'carta_dlv_name', 'de', 'Name (optional)', 'Carta Mediterránea'),
('reels', 'carta_dlv_phone', 'de', 'Telefon *', 'Carta Mediterránea'),
('reels', 'carta_dlv_address', 'de', 'Vollständige Adresse *', 'Carta Mediterránea'),
('reels', 'carta_dlv_address_ph', 'de', 'Straße, Hausnummer, Etage, PLZ…', 'Carta Mediterránea'),
('reels', 'carta_dlv_notes', 'de', 'Hinweise (optional)', 'Carta Mediterránea'),
('reels', 'carta_dlv_notes_ph', 'de', 'Lieferhinweise, Allergien…', 'Carta Mediterránea'),
('reels', 'carta_dlv_privacy', 'de', '{restaurant} verwendet deinen Namen, deine Telefonnummer und Adresse, um diese Bestellung zuzubereiten und zu liefern und seine steuerlichen Pflichten zu erfüllen. Sie werden nicht für Werbung genutzt. Du kannst deine Rechte auf Auskunft, Berichtigung und Löschung ausüben.', 'Carta Mediterránea'),
('reels', 'carta_dlv_privacy_link', 'de', 'Datenschutzerklärung', 'Carta Mediterránea'),
('reels', 'carta_dlv_allergy', 'de', 'Wenn du Allergien hast, gib sie in den Hinweisen an und bestätige sie auch telefonisch: Die Gerichte werden in Küchen zubereitet, in denen alle Allergene verarbeitet werden.', 'Carta Mediterránea'),
('reels', 'carta_dlv_payment', 'de', 'Wie zahlst du? *', 'Carta Mediterránea'),
('reels', 'carta_dlv_cash', 'de', 'Bar', 'Carta Mediterránea'),
('reels', 'carta_dlv_card', 'de', 'Karte', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_phone', 'de', 'Telefonnummer ist erforderlich', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_phone_bad', 'de', 'Ungültige Telefonnummer', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_address', 'de', 'Adresse ist erforderlich', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_payment', 'de', 'Wähle, wie du zahlst', 'Carta Mediterránea'),
('reels', 'carta_dlv_area', 'de', 'Liefergebiet', 'Carta Mediterránea'),
('reels', 'carta_dlv_order', 'de', 'Deine Bestellung', 'Carta Mediterránea'),
('reels', 'carta_dlv_shipping', 'de', 'Lieferung', 'Carta Mediterránea'),
('reels', 'carta_dlv_free', 'de', 'Kostenlos', 'Carta Mediterránea'),
('reels', 'carta_dlv_free_from', 'de', 'Kostenlos ab {amount}', 'Carta Mediterránea'),
('reels', 'carta_dlv_vat', 'de', 'Inkl. MwSt. Mit dem Absenden bestätigst du, dass du die Bestellung aufgeben möchtest und dass sie dich zur Zahlung dieses Betrags an das Restaurant verpflichtet.', 'Carta Mediterránea'),
('reels', 'carta_dlv_send_wa', 'de', 'Bestellung per WhatsApp senden', 'Carta Mediterránea'),
('reels', 'carta_dlv_call', 'de', 'Restaurant anrufen', 'Carta Mediterránea');
-- it
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('reels', 'carta_notif_error', 'it', 'Non è stato possibile attivare gli avvisi', 'Carta Mediterránea'),
('reels', 'carta_remember_q', 'it', 'Ti riconosciamo la prossima volta che torni?', 'Carta Mediterránea'),
('reels', 'carta_remember_sub', 'it', 'Salviamo un numero casuale su questo telefono per 12 mesi, così il ristorante sa che sei tornato. Senza il tuo nome e senza pubblicità.', 'Carta Mediterránea'),
('reels', 'carta_remember_more', 'it', 'Più informazioni', 'Carta Mediterránea'),
('reels', 'carta_remember_yes', 'it', 'Sì', 'Carta Mediterránea'),
('reels', 'carta_remember_no', 'it', 'No', 'Carta Mediterránea'),
('reels', 'carta_remember_done_yes', 'it', 'Ti riconosceremo', 'Carta Mediterránea'),
('reels', 'carta_remember_done_no', 'it', 'D’accordo, non ti ricordiamo', 'Carta Mediterránea'),
('reels', 'carta_confirm', 'it', 'Conferma', 'Carta Mediterránea'),
('reels', 'carta_rt_title', 'it', 'Com’è andata?', 'Carta Mediterránea'),
('reels', 'carta_rt_title_prev', 'it', 'La tua valutazione', 'Carta Mediterránea'),
('reels', 'carta_rt_sub', 'it', 'La tua opinione ci aiuta a migliorare.', 'Carta Mediterránea'),
('reels', 'carta_rt_improve', 'it', 'In cosa possiamo migliorare?', 'Carta Mediterránea'),
('reels', 'carta_rt_send', 'it', 'Invia', 'Carta Mediterránea'),
('reels', 'carta_rt_star', 'it', '{n} su 5', 'Carta Mediterránea'),
('reels', 'carta_rt_glad', 'it', 'Siamo felici che ti sia piaciuto!', 'Carta Mediterránea'),
('reels', 'carta_rt_google_invite', 'it', 'Condividi la tua esperienza su Google per aiutarci a crescere.', 'Carta Mediterránea'),
('reels', 'carta_rt_google_btn', 'it', 'Scrivi una recensione su Google', 'Carta Mediterránea'),
('reels', 'carta_rt_thanks', 'it', 'Grazie per la tua opinione!', 'Carta Mediterránea'),
('reels', 'carta_rt_thanks_sub', 'it', 'Ne prendiamo nota per continuare a migliorare.', 'Carta Mediterránea'),
('reels', 'carta_loy_title', 'it', 'La tua carta fedeltà', 'Carta Mediterránea'),
('reels', 'carta_loy_reward', 'it', 'Completa la carta e ottieni: {reward}', 'Carta Mediterránea'),
('reels', 'carta_loy_generic', 'it', 'Raccogli timbri a ogni visita e ottieni il tuo premio', 'Carta Mediterránea'),
('reels', 'carta_loy_count', 'it', '{n} timbri su {total}', 'Carta Mediterránea'),
('reels', 'carta_loy_redeemed', 'it', 'Hai già riscattato questa carta. Grazie di essere tornato!', 'Carta Mediterránea'),
('reels', 'carta_loy_view_reward', 'it', 'Vedi il mio premio', 'Carta Mediterránea'),
('reels', 'carta_loy_ask_staff', 'it', 'Chiedi al cameriere di inserire il PIN', 'Carta Mediterránea'),
('reels', 'carta_loy_add', 'it', 'Aggiungi timbro', 'Carta Mediterránea'),
('reels', 'carta_loy_pin_required', 'it', 'Inserisci il PIN di 4 cifre', 'Carta Mediterránea'),
('reels', 'carta_loy_pin_wrong', 'it', 'PIN errato', 'Carta Mediterránea'),
('reels', 'carta_ios_offers', 'it', 'Offerte VIP', 'Carta Mediterránea'),
('reels', 'carta_ios_fast', 'it', 'Più veloce', 'Carta Mediterránea'),
('reels', 'carta_ios_title', 'it', 'Aggiungi il menù al tuo iPhone', 'Carta Mediterránea'),
('reels', 'carta_ios_body', 'it', 'Su iPhone gli avvisi arrivano solo se il menù è nella schermata Home. Aprilo da lì e attivali.', 'Carta Mediterránea'),
('reels', 'carta_ios_step1', 'it', 'Tocca «Condividi» in basso', 'Carta Mediterránea'),
('reels', 'carta_ios_step2', 'it', 'Scegli «Aggiungi alla schermata Home»', 'Carta Mediterránea'),
('reels', 'carta_ios_never', 'it', 'Non mostrare più', 'Carta Mediterránea'),
('reels', 'carta_dlv_title', 'it', 'Ordina a domicilio', 'Carta Mediterránea'),
('reels', 'carta_dlv_closed_today', 'it', 'Oggi niente servizio di consegna', 'Carta Mediterránea'),
('reels', 'carta_dlv_outside_hours', 'it', 'Fuori dall’orario di consegna', 'Carta Mediterránea'),
('reels', 'carta_dlv_unavailable', 'it', 'Servizio non disponibile', 'Carta Mediterránea'),
('reels', 'carta_dlv_empty', 'it', 'Non hai ancora aggiunto nulla all’ordine', 'Carta Mediterránea'),
('reels', 'carta_dlv_minimum', 'it', 'Ordine minimo: {amount}', 'Carta Mediterránea'),
('reels', 'carta_dlv_details', 'it', 'Dati di consegna', 'Carta Mediterránea'),
('reels', 'carta_dlv_name', 'it', 'Nome (facoltativo)', 'Carta Mediterránea'),
('reels', 'carta_dlv_phone', 'it', 'Telefono *', 'Carta Mediterránea'),
('reels', 'carta_dlv_address', 'it', 'Indirizzo completo *', 'Carta Mediterránea'),
('reels', 'carta_dlv_address_ph', 'it', 'Via, numero civico, piano, CAP…', 'Carta Mediterránea'),
('reels', 'carta_dlv_notes', 'it', 'Note (facoltative)', 'Carta Mediterránea'),
('reels', 'carta_dlv_notes_ph', 'it', 'Istruzioni di consegna, allergie…', 'Carta Mediterránea'),
('reels', 'carta_dlv_privacy', 'it', '{restaurant} tratterà nome, telefono e indirizzo per preparare e consegnare questo ordine e per adempiere ai propri obblighi fiscali. Non vengono usati per pubblicità. Puoi esercitare i tuoi diritti di accesso, rettifica e cancellazione.', 'Carta Mediterránea'),
('reels', 'carta_dlv_privacy_link', 'it', 'Informativa sulla privacy', 'Carta Mediterránea'),
('reels', 'carta_dlv_allergy', 'it', 'Se hai allergie, indicalo nelle note e confermalo anche per telefono: i piatti sono preparati in cucine dove si manipolano tutti gli allergeni.', 'Carta Mediterránea'),
('reels', 'carta_dlv_payment', 'it', 'Come paghi? *', 'Carta Mediterránea'),
('reels', 'carta_dlv_cash', 'it', 'Contanti', 'Carta Mediterránea'),
('reels', 'carta_dlv_card', 'it', 'Carta', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_phone', 'it', 'Il telefono è obbligatorio', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_phone_bad', 'it', 'Telefono non valido', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_address', 'it', 'L’indirizzo è obbligatorio', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_payment', 'it', 'Scegli come pagare', 'Carta Mediterránea'),
('reels', 'carta_dlv_area', 'it', 'Zona di consegna', 'Carta Mediterránea'),
('reels', 'carta_dlv_order', 'it', 'Il tuo ordine', 'Carta Mediterránea'),
('reels', 'carta_dlv_shipping', 'it', 'Consegna', 'Carta Mediterránea'),
('reels', 'carta_dlv_free', 'it', 'Gratis', 'Carta Mediterránea'),
('reels', 'carta_dlv_free_from', 'it', 'Gratis da {amount}', 'Carta Mediterránea'),
('reels', 'carta_dlv_vat', 'it', 'IVA inclusa. Inviando l’ordine confermi di volerlo effettuare e che comporta l’obbligo di pagare questo importo al ristorante.', 'Carta Mediterránea'),
('reels', 'carta_dlv_send_wa', 'it', 'Invia l’ordine via WhatsApp', 'Carta Mediterránea'),
('reels', 'carta_dlv_call', 'it', 'Chiama il ristorante', 'Carta Mediterránea');
-- pt
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('reels', 'carta_notif_error', 'pt', 'Não foi possível ativar os avisos', 'Carta Mediterránea'),
('reels', 'carta_remember_q', 'pt', 'Lembramo-nos de si da próxima vez que vier?', 'Carta Mediterránea'),
('reels', 'carta_remember_sub', 'pt', 'Guardamos um número aleatório neste telemóvel durante 12 meses para que o restaurante saiba que voltou. Sem o seu nome e sem publicidade.', 'Carta Mediterránea'),
('reels', 'carta_remember_more', 'pt', 'Mais informações', 'Carta Mediterránea'),
('reels', 'carta_remember_yes', 'pt', 'Sim', 'Carta Mediterránea'),
('reels', 'carta_remember_no', 'pt', 'Não', 'Carta Mediterránea'),
('reels', 'carta_remember_done_yes', 'pt', 'Vamos lembrar-nos de si', 'Carta Mediterránea'),
('reels', 'carta_remember_done_no', 'pt', 'Combinado, não guardamos nada', 'Carta Mediterránea'),
('reels', 'carta_confirm', 'pt', 'Confirmar', 'Carta Mediterránea'),
('reels', 'carta_rt_title', 'pt', 'O que achou?', 'Carta Mediterránea'),
('reels', 'carta_rt_title_prev', 'pt', 'A sua avaliação', 'Carta Mediterránea'),
('reels', 'carta_rt_sub', 'pt', 'A sua opinião ajuda-nos a melhorar.', 'Carta Mediterránea'),
('reels', 'carta_rt_improve', 'pt', 'Em que podemos melhorar?', 'Carta Mediterránea'),
('reels', 'carta_rt_send', 'pt', 'Enviar', 'Carta Mediterránea'),
('reels', 'carta_rt_star', 'pt', '{n} de 5', 'Carta Mediterránea'),
('reels', 'carta_rt_glad', 'pt', 'Ainda bem que gostou!', 'Carta Mediterránea'),
('reels', 'carta_rt_google_invite', 'pt', 'Partilhe a sua experiência no Google para nos ajudar a crescer.', 'Carta Mediterránea'),
('reels', 'carta_rt_google_btn', 'pt', 'Escrever avaliação no Google', 'Carta Mediterránea'),
('reels', 'carta_rt_thanks', 'pt', 'Obrigado pela sua opinião!', 'Carta Mediterránea'),
('reels', 'carta_rt_thanks_sub', 'pt', 'Tomamos nota para continuar a melhorar.', 'Carta Mediterránea'),
('reels', 'carta_loy_title', 'pt', 'O seu cartão de fidelização', 'Carta Mediterránea'),
('reels', 'carta_loy_reward', 'pt', 'Complete o cartão e receba: {reward}', 'Carta Mediterránea'),
('reels', 'carta_loy_generic', 'pt', 'Junte carimbos em cada visita e ganhe o seu prémio', 'Carta Mediterránea'),
('reels', 'carta_loy_count', 'pt', '{n} de {total} carimbos', 'Carta Mediterránea'),
('reels', 'carta_loy_redeemed', 'pt', 'Já trocou este cartão. Obrigado por voltar!', 'Carta Mediterránea'),
('reels', 'carta_loy_view_reward', 'pt', 'Ver o meu prémio', 'Carta Mediterránea'),
('reels', 'carta_loy_ask_staff', 'pt', 'Peça ao empregado que introduza o PIN', 'Carta Mediterránea'),
('reels', 'carta_loy_add', 'pt', 'Adicionar carimbo', 'Carta Mediterránea'),
('reels', 'carta_loy_pin_required', 'pt', 'Introduza o PIN de 4 dígitos', 'Carta Mediterránea'),
('reels', 'carta_loy_pin_wrong', 'pt', 'PIN incorreto', 'Carta Mediterránea'),
('reels', 'carta_ios_offers', 'pt', 'Ofertas VIP', 'Carta Mediterránea'),
('reels', 'carta_ios_fast', 'pt', 'Mais rápido', 'Carta Mediterránea'),
('reels', 'carta_ios_title', 'pt', 'Adicione o menu ao seu iPhone', 'Carta Mediterránea'),
('reels', 'carta_ios_body', 'pt', 'No iPhone, os avisos só chegam se o menu estiver no ecrã principal. Abra-o a partir daí e ative-os.', 'Carta Mediterránea'),
('reels', 'carta_ios_step1', 'pt', 'Toque em «Partilhar» em baixo', 'Carta Mediterránea'),
('reels', 'carta_ios_step2', 'pt', 'Escolha «Adicionar ao ecrã principal»', 'Carta Mediterránea'),
('reels', 'carta_ios_never', 'pt', 'Não voltar a mostrar', 'Carta Mediterránea'),
('reels', 'carta_dlv_title', 'pt', 'Encomendar ao domicílio', 'Carta Mediterránea'),
('reels', 'carta_dlv_closed_today', 'pt', 'Hoje não há serviço de entregas', 'Carta Mediterránea'),
('reels', 'carta_dlv_outside_hours', 'pt', 'Fora do horário de entregas', 'Carta Mediterránea'),
('reels', 'carta_dlv_unavailable', 'pt', 'Serviço indisponível', 'Carta Mediterránea'),
('reels', 'carta_dlv_empty', 'pt', 'Ainda não adicionou nada à encomenda', 'Carta Mediterránea'),
('reels', 'carta_dlv_minimum', 'pt', 'Encomenda mínima: {amount}', 'Carta Mediterránea'),
('reels', 'carta_dlv_details', 'pt', 'Dados de entrega', 'Carta Mediterránea'),
('reels', 'carta_dlv_name', 'pt', 'Nome (opcional)', 'Carta Mediterránea'),
('reels', 'carta_dlv_phone', 'pt', 'Telefone *', 'Carta Mediterránea'),
('reels', 'carta_dlv_address', 'pt', 'Morada completa *', 'Carta Mediterránea'),
('reels', 'carta_dlv_address_ph', 'pt', 'Rua, número, andar, código postal…', 'Carta Mediterránea'),
('reels', 'carta_dlv_notes', 'pt', 'Notas (opcional)', 'Carta Mediterránea'),
('reels', 'carta_dlv_notes_ph', 'pt', 'Instruções de entrega, alergias…', 'Carta Mediterránea'),
('reels', 'carta_dlv_privacy', 'pt', '{restaurant} tratará o seu nome, telefone e morada para preparar e entregar esta encomenda e cumprir as suas obrigações fiscais. Não são usados para publicidade. Pode exercer os seus direitos de acesso, retificação e apagamento.', 'Carta Mediterránea'),
('reels', 'carta_dlv_privacy_link', 'pt', 'Política de privacidade', 'Carta Mediterránea'),
('reels', 'carta_dlv_allergy', 'pt', 'Se tem alergias, indique-o nas notas e confirme também por telefone: os pratos são preparados em cozinhas onde se manipulam todos os alergénios.', 'Carta Mediterránea'),
('reels', 'carta_dlv_payment', 'pt', 'Como vai pagar? *', 'Carta Mediterránea'),
('reels', 'carta_dlv_cash', 'pt', 'Dinheiro', 'Carta Mediterránea'),
('reels', 'carta_dlv_card', 'pt', 'Cartão', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_phone', 'pt', 'O telefone é obrigatório', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_phone_bad', 'pt', 'Telefone inválido', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_address', 'pt', 'A morada é obrigatória', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_payment', 'pt', 'Escolha como vai pagar', 'Carta Mediterránea'),
('reels', 'carta_dlv_area', 'pt', 'Zona de entrega', 'Carta Mediterránea'),
('reels', 'carta_dlv_order', 'pt', 'A sua encomenda', 'Carta Mediterránea'),
('reels', 'carta_dlv_shipping', 'pt', 'Entrega', 'Carta Mediterránea'),
('reels', 'carta_dlv_free', 'pt', 'Grátis', 'Carta Mediterránea'),
('reels', 'carta_dlv_free_from', 'pt', 'Grátis a partir de {amount}', 'Carta Mediterránea'),
('reels', 'carta_dlv_vat', 'pt', 'IVA incluído. Ao enviar a encomenda confirma que a deseja fazer e que implica a obrigação de pagar este valor ao restaurante.', 'Carta Mediterránea'),
('reels', 'carta_dlv_send_wa', 'pt', 'Enviar encomenda por WhatsApp', 'Carta Mediterránea'),
('reels', 'carta_dlv_call', 'pt', 'Ligar para o restaurante', 'Carta Mediterránea');
-- ca
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('reels', 'carta_notif_error', 'ca', 'No s’han pogut activar els avisos', 'Carta Mediterránea'),
('reels', 'carta_remember_q', 'ca', 'Et reconeixem la propera vegada que vinguis?', 'Carta Mediterránea'),
('reels', 'carta_remember_sub', 'ca', 'Guardem un número a l’atzar en aquest mòbil durant 12 mesos perquè el restaurant sàpiga que has tornat. Sense el teu nom i sense publicitat.', 'Carta Mediterránea'),
('reels', 'carta_remember_more', 'ca', 'Més informació', 'Carta Mediterránea'),
('reels', 'carta_remember_yes', 'ca', 'Sí', 'Carta Mediterránea'),
('reels', 'carta_remember_no', 'ca', 'No', 'Carta Mediterránea'),
('reels', 'carta_remember_done_yes', 'ca', 'Et reconeixerem', 'Carta Mediterránea'),
('reels', 'carta_remember_done_no', 'ca', 'D’acord, no et recordem', 'Carta Mediterránea'),
('reels', 'carta_confirm', 'ca', 'Confirmar', 'Carta Mediterránea'),
('reels', 'carta_rt_title', 'ca', 'Què t’ha semblat?', 'Carta Mediterránea'),
('reels', 'carta_rt_title_prev', 'ca', 'La teva valoració', 'Carta Mediterránea'),
('reels', 'carta_rt_sub', 'ca', 'La teva opinió ens ajuda a millorar.', 'Carta Mediterránea'),
('reels', 'carta_rt_improve', 'ca', 'En què podem millorar?', 'Carta Mediterránea'),
('reels', 'carta_rt_send', 'ca', 'Envia', 'Carta Mediterránea'),
('reels', 'carta_rt_star', 'ca', '{n} de 5', 'Carta Mediterránea'),
('reels', 'carta_rt_glad', 'ca', 'Ens alegra que t’hagi agradat!', 'Carta Mediterránea'),
('reels', 'carta_rt_google_invite', 'ca', 'Et convidem a compartir la teva experiència a Google per ajudar-nos a créixer.', 'Carta Mediterránea'),
('reels', 'carta_rt_google_btn', 'ca', 'Escriu una ressenya a Google', 'Carta Mediterránea'),
('reels', 'carta_rt_thanks', 'ca', 'Gràcies per la teva opinió!', 'Carta Mediterránea'),
('reels', 'carta_rt_thanks_sub', 'ca', 'En prenem nota per continuar millorant.', 'Carta Mediterránea'),
('reels', 'carta_loy_title', 'ca', 'La teva targeta de fidelitat', 'Carta Mediterránea'),
('reels', 'carta_loy_reward', 'ca', 'Completa la targeta i aconsegueix: {reward}', 'Carta Mediterránea'),
('reels', 'carta_loy_generic', 'ca', 'Aplega segells a cada visita i aconsegueix el teu premi', 'Carta Mediterránea'),
('reels', 'carta_loy_count', 'ca', '{n} de {total} segells', 'Carta Mediterránea'),
('reels', 'carta_loy_redeemed', 'ca', 'Ja has bescanviat aquesta targeta. Gràcies per tornar!', 'Carta Mediterránea'),
('reels', 'carta_loy_view_reward', 'ca', 'Veure el meu premi', 'Carta Mediterránea'),
('reels', 'carta_loy_ask_staff', 'ca', 'Demana al cambrer que introdueixi el PIN', 'Carta Mediterránea'),
('reels', 'carta_loy_add', 'ca', 'Afegir segell', 'Carta Mediterránea'),
('reels', 'carta_loy_pin_required', 'ca', 'Introdueix el PIN de 4 xifres', 'Carta Mediterránea'),
('reels', 'carta_loy_pin_wrong', 'ca', 'PIN incorrecte', 'Carta Mediterránea'),
('reels', 'carta_ios_offers', 'ca', 'Ofertes VIP', 'Carta Mediterránea'),
('reels', 'carta_ios_fast', 'ca', 'Més ràpid', 'Carta Mediterránea'),
('reels', 'carta_ios_title', 'ca', 'Afegeix la carta al teu iPhone', 'Carta Mediterránea'),
('reels', 'carta_ios_body', 'ca', 'A l’iPhone, els avisos només arriben si la carta és a la pantalla d’inici. Obre-la des d’allà i activa’ls.', 'Carta Mediterránea'),
('reels', 'carta_ios_step1', 'ca', 'Toca «Comparteix» a baix', 'Carta Mediterránea'),
('reels', 'carta_ios_step2', 'ca', 'Tria «Afegeix a la pantalla d’inici»', 'Carta Mediterránea'),
('reels', 'carta_ios_never', 'ca', 'No ho tornis a mostrar', 'Carta Mediterránea'),
('reels', 'carta_dlv_title', 'ca', 'Demanar a domicili', 'Carta Mediterránea'),
('reels', 'carta_dlv_closed_today', 'ca', 'Avui no hi ha servei de repartiment', 'Carta Mediterránea'),
('reels', 'carta_dlv_outside_hours', 'ca', 'Fora de l’horari de repartiment', 'Carta Mediterránea'),
('reels', 'carta_dlv_unavailable', 'ca', 'Servei no disponible', 'Carta Mediterránea'),
('reels', 'carta_dlv_empty', 'ca', 'Encara no has afegit res a la comanda', 'Carta Mediterránea'),
('reels', 'carta_dlv_minimum', 'ca', 'Comanda mínima: {amount}', 'Carta Mediterránea'),
('reels', 'carta_dlv_details', 'ca', 'Dades d’entrega', 'Carta Mediterránea'),
('reels', 'carta_dlv_name', 'ca', 'Nom (opcional)', 'Carta Mediterránea'),
('reels', 'carta_dlv_phone', 'ca', 'Telèfon *', 'Carta Mediterránea'),
('reels', 'carta_dlv_address', 'ca', 'Adreça completa *', 'Carta Mediterránea'),
('reels', 'carta_dlv_address_ph', 'ca', 'Carrer, número, pis, codi postal…', 'Carta Mediterránea'),
('reels', 'carta_dlv_notes', 'ca', 'Notes (opcional)', 'Carta Mediterránea'),
('reels', 'carta_dlv_notes_ph', 'ca', 'Instruccions d’entrega, al·lèrgies…', 'Carta Mediterránea'),
('reels', 'carta_dlv_privacy', 'ca', '{restaurant} tractarà el teu nom, telèfon i adreça per preparar i lliurar aquesta comanda i per complir les seves obligacions fiscals. No s’utilitzen per a publicitat. Pots exercir els teus drets d’accés, rectificació i supressió.', 'Carta Mediterránea'),
('reels', 'carta_dlv_privacy_link', 'ca', 'Política de privacitat', 'Carta Mediterránea'),
('reels', 'carta_dlv_allergy', 'ca', 'Si tens al·lèrgies, indica-ho a les notes i confirma-ho també per telèfon: els plats s’elaboren en cuines on es manipulen tots els al·lèrgens.', 'Carta Mediterránea'),
('reels', 'carta_dlv_payment', 'ca', 'Com pagaràs? *', 'Carta Mediterránea'),
('reels', 'carta_dlv_cash', 'ca', 'Efectiu', 'Carta Mediterránea'),
('reels', 'carta_dlv_card', 'ca', 'Targeta', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_phone', 'ca', 'El telèfon és obligatori', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_phone_bad', 'ca', 'Telèfon no vàlid', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_address', 'ca', 'L’adreça és obligatòria', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_payment', 'ca', 'Tria com pagaràs', 'Carta Mediterránea'),
('reels', 'carta_dlv_area', 'ca', 'Zona de repartiment', 'Carta Mediterránea'),
('reels', 'carta_dlv_order', 'ca', 'La teva comanda', 'Carta Mediterránea'),
('reels', 'carta_dlv_shipping', 'ca', 'Enviament', 'Carta Mediterránea'),
('reels', 'carta_dlv_free', 'ca', 'Gratis', 'Carta Mediterránea'),
('reels', 'carta_dlv_free_from', 'ca', 'Gratis a partir de {amount}', 'Carta Mediterránea'),
('reels', 'carta_dlv_vat', 'ca', 'IVA inclòs. En enviar la comanda confirmes que vols contractar-la i que comporta l’obligació de pagar aquest import al restaurant.', 'Carta Mediterránea'),
('reels', 'carta_dlv_send_wa', 'ca', 'Enviar la comanda per WhatsApp', 'Carta Mediterránea'),
('reels', 'carta_dlv_call', 'ca', 'Trucar al restaurant', 'Carta Mediterránea');
-- ar
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('reels', 'carta_notif_error', 'ar', 'تعذّر تفعيل الإشعارات', 'Carta Mediterránea'),
('reels', 'carta_remember_q', 'ar', 'هل نتعرّف عليك في زيارتك القادمة؟', 'Carta Mediterránea'),
('reels', 'carta_remember_sub', 'ar', 'نحفظ رقمًا عشوائيًا على هذا الهاتف لمدة 12 شهرًا ليعرف المطعم أنك عدت. دون اسمك ودون إعلانات.', 'Carta Mediterránea'),
('reels', 'carta_remember_more', 'ar', 'مزيد من المعلومات', 'Carta Mediterránea'),
('reels', 'carta_remember_yes', 'ar', 'نعم', 'Carta Mediterránea'),
('reels', 'carta_remember_no', 'ar', 'لا', 'Carta Mediterránea'),
('reels', 'carta_remember_done_yes', 'ar', 'سنتعرّف عليك', 'Carta Mediterránea'),
('reels', 'carta_remember_done_no', 'ar', 'حسنًا، لن نتذكرك', 'Carta Mediterránea'),
('reels', 'carta_confirm', 'ar', 'تأكيد', 'Carta Mediterránea'),
('reels', 'carta_rt_title', 'ar', 'ما رأيك؟', 'Carta Mediterránea'),
('reels', 'carta_rt_title_prev', 'ar', 'تقييمك', 'Carta Mediterránea'),
('reels', 'carta_rt_sub', 'ar', 'رأيك يساعدنا على التحسّن.', 'Carta Mediterránea'),
('reels', 'carta_rt_improve', 'ar', 'ما الذي يمكننا تحسينه؟', 'Carta Mediterránea'),
('reels', 'carta_rt_send', 'ar', 'إرسال', 'Carta Mediterránea'),
('reels', 'carta_rt_star', 'ar', '{n} من 5', 'Carta Mediterránea'),
('reels', 'carta_rt_glad', 'ar', 'يسعدنا أنه أعجبك!', 'Carta Mediterránea'),
('reels', 'carta_rt_google_invite', 'ar', 'ندعوك لمشاركة تجربتك على Google لمساعدتنا على النمو.', 'Carta Mediterránea'),
('reels', 'carta_rt_google_btn', 'ar', 'اكتب مراجعة على Google', 'Carta Mediterránea'),
('reels', 'carta_rt_thanks', 'ar', 'شكرًا على رأيك!', 'Carta Mediterránea'),
('reels', 'carta_rt_thanks_sub', 'ar', 'أخذنا ملاحظتك لنواصل التحسّن.', 'Carta Mediterránea'),
('reels', 'carta_loy_title', 'ar', 'بطاقة الولاء الخاصة بك', 'Carta Mediterránea'),
('reels', 'carta_loy_reward', 'ar', 'أكمل البطاقة واحصل على: {reward}', 'Carta Mediterránea'),
('reels', 'carta_loy_generic', 'ar', 'اجمع الأختام في كل زيارة واحصل على مكافأتك', 'Carta Mediterránea'),
('reels', 'carta_loy_count', 'ar', '{n} من {total} أختام', 'Carta Mediterránea'),
('reels', 'carta_loy_redeemed', 'ar', 'لقد استبدلت هذه البطاقة بالفعل. شكرًا لعودتك!', 'Carta Mediterránea'),
('reels', 'carta_loy_view_reward', 'ar', 'عرض مكافأتي', 'Carta Mediterránea'),
('reels', 'carta_loy_ask_staff', 'ar', 'اطلب من النادل إدخال الرمز', 'Carta Mediterránea'),
('reels', 'carta_loy_add', 'ar', 'إضافة ختم', 'Carta Mediterránea'),
('reels', 'carta_loy_pin_required', 'ar', 'أدخل الرمز المكوّن من 4 أرقام', 'Carta Mediterránea'),
('reels', 'carta_loy_pin_wrong', 'ar', 'رمز غير صحيح', 'Carta Mediterránea'),
('reels', 'carta_ios_offers', 'ar', 'عروض VIP', 'Carta Mediterránea'),
('reels', 'carta_ios_fast', 'ar', 'أسرع', 'Carta Mediterránea'),
('reels', 'carta_ios_title', 'ar', 'أضف القائمة إلى آيفون', 'Carta Mediterránea'),
('reels', 'carta_ios_body', 'ar', 'على آيفون، لا تصل الإشعارات إلا إذا كانت القائمة على الشاشة الرئيسية. افتحها من هناك وفعّلها.', 'Carta Mediterránea'),
('reels', 'carta_ios_step1', 'ar', 'اضغط «مشاركة» في الأسفل', 'Carta Mediterránea'),
('reels', 'carta_ios_step2', 'ar', 'اختر «إضافة إلى الشاشة الرئيسية»', 'Carta Mediterránea'),
('reels', 'carta_ios_never', 'ar', 'عدم الإظهار مرة أخرى', 'Carta Mediterránea'),
('reels', 'carta_dlv_title', 'ar', 'اطلب توصيلًا إلى المنزل', 'Carta Mediterránea'),
('reels', 'carta_dlv_closed_today', 'ar', 'لا توجد خدمة توصيل اليوم', 'Carta Mediterránea'),
('reels', 'carta_dlv_outside_hours', 'ar', 'خارج ساعات التوصيل', 'Carta Mediterránea'),
('reels', 'carta_dlv_unavailable', 'ar', 'الخدمة غير متاحة', 'Carta Mediterránea'),
('reels', 'carta_dlv_empty', 'ar', 'لم تضف شيئًا إلى الطلب بعد', 'Carta Mediterránea'),
('reels', 'carta_dlv_minimum', 'ar', 'الحد الأدنى للطلب: {amount}', 'Carta Mediterránea'),
('reels', 'carta_dlv_details', 'ar', 'بيانات التوصيل', 'Carta Mediterránea'),
('reels', 'carta_dlv_name', 'ar', 'الاسم (اختياري)', 'Carta Mediterránea'),
('reels', 'carta_dlv_phone', 'ar', 'الهاتف *', 'Carta Mediterránea'),
('reels', 'carta_dlv_address', 'ar', 'العنوان الكامل *', 'Carta Mediterránea'),
('reels', 'carta_dlv_address_ph', 'ar', 'الشارع، الرقم، الطابق، الرمز البريدي…', 'Carta Mediterránea'),
('reels', 'carta_dlv_notes', 'ar', 'ملاحظات (اختياري)', 'Carta Mediterránea'),
('reels', 'carta_dlv_notes_ph', 'ar', 'تعليمات التوصيل، الحساسية…', 'Carta Mediterránea'),
('reels', 'carta_dlv_privacy', 'ar', 'سيعالج {restaurant} اسمك وهاتفك وعنوانك لتحضير هذا الطلب وتوصيله وللوفاء بالتزاماته الضريبية. لا تُستخدم للإعلانات. يمكنك ممارسة حقوقك في الوصول والتصحيح والحذف.', 'Carta Mediterránea'),
('reels', 'carta_dlv_privacy_link', 'ar', 'سياسة الخصوصية', 'Carta Mediterránea'),
('reels', 'carta_dlv_allergy', 'ar', 'إن كانت لديك حساسية، اذكرها في الملاحظات وأكّدها أيضًا عبر الهاتف: تُحضَّر الأطباق في مطابخ تُستخدم فيها جميع مسببات الحساسية.', 'Carta Mediterránea'),
('reels', 'carta_dlv_payment', 'ar', 'كيف ستدفع؟ *', 'Carta Mediterránea'),
('reels', 'carta_dlv_cash', 'ar', 'نقدًا', 'Carta Mediterránea'),
('reels', 'carta_dlv_card', 'ar', 'بطاقة', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_phone', 'ar', 'رقم الهاتف مطلوب', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_phone_bad', 'ar', 'رقم هاتف غير صالح', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_address', 'ar', 'العنوان مطلوب', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_payment', 'ar', 'اختر طريقة الدفع', 'Carta Mediterránea'),
('reels', 'carta_dlv_area', 'ar', 'منطقة التوصيل', 'Carta Mediterránea'),
('reels', 'carta_dlv_order', 'ar', 'طلبك', 'Carta Mediterránea'),
('reels', 'carta_dlv_shipping', 'ar', 'التوصيل', 'Carta Mediterránea'),
('reels', 'carta_dlv_free', 'ar', 'مجاني', 'Carta Mediterránea'),
('reels', 'carta_dlv_free_from', 'ar', 'مجاني ابتداءً من {amount}', 'Carta Mediterránea'),
('reels', 'carta_dlv_vat', 'ar', 'شامل ضريبة القيمة المضافة. بإرسال الطلب تؤكد رغبتك في إتمامه وأنه يُلزمك بدفع هذا المبلغ للمطعم.', 'Carta Mediterránea'),
('reels', 'carta_dlv_send_wa', 'ar', 'إرسال الطلب عبر واتساب', 'Carta Mediterránea'),
('reels', 'carta_dlv_call', 'ar', 'الاتصال بالمطعم', 'Carta Mediterránea');
-- ru
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('reels', 'carta_notif_error', 'ru', 'Не удалось включить уведомления', 'Carta Mediterránea'),
('reels', 'carta_remember_q', 'ru', 'Узнать вас в следующий раз?', 'Carta Mediterránea'),
('reels', 'carta_remember_sub', 'ru', 'Мы сохраняем на этом телефоне случайный номер на 12 месяцев, чтобы ресторан знал, что вы вернулись. Без вашего имени и без рекламы.', 'Carta Mediterránea'),
('reels', 'carta_remember_more', 'ru', 'Подробнее', 'Carta Mediterránea'),
('reels', 'carta_remember_yes', 'ru', 'Да', 'Carta Mediterránea'),
('reels', 'carta_remember_no', 'ru', 'Нет', 'Carta Mediterránea'),
('reels', 'carta_remember_done_yes', 'ru', 'Мы вас узнаем', 'Carta Mediterránea'),
('reels', 'carta_remember_done_no', 'ru', 'Хорошо, мы вас не запоминаем', 'Carta Mediterránea'),
('reels', 'carta_confirm', 'ru', 'Подтвердить', 'Carta Mediterránea'),
('reels', 'carta_rt_title', 'ru', 'Как вам?', 'Carta Mediterránea'),
('reels', 'carta_rt_title_prev', 'ru', 'Ваша оценка', 'Carta Mediterránea'),
('reels', 'carta_rt_sub', 'ru', 'Ваше мнение помогает нам стать лучше.', 'Carta Mediterránea'),
('reels', 'carta_rt_improve', 'ru', 'Что нам улучшить?', 'Carta Mediterránea'),
('reels', 'carta_rt_send', 'ru', 'Отправить', 'Carta Mediterránea'),
('reels', 'carta_rt_star', 'ru', '{n} из 5', 'Carta Mediterránea'),
('reels', 'carta_rt_glad', 'ru', 'Рады, что вам понравилось!', 'Carta Mediterránea'),
('reels', 'carta_rt_google_invite', 'ru', 'Поделитесь впечатлениями в Google — это поможет нам расти.', 'Carta Mediterránea'),
('reels', 'carta_rt_google_btn', 'ru', 'Написать отзыв в Google', 'Carta Mediterránea'),
('reels', 'carta_rt_thanks', 'ru', 'Спасибо за ваше мнение!', 'Carta Mediterránea'),
('reels', 'carta_rt_thanks_sub', 'ru', 'Мы учтём это, чтобы становиться лучше.', 'Carta Mediterránea'),
('reels', 'carta_loy_title', 'ru', 'Ваша карта лояльности', 'Carta Mediterránea'),
('reels', 'carta_loy_reward', 'ru', 'Заполните карту и получите: {reward}', 'Carta Mediterránea'),
('reels', 'carta_loy_generic', 'ru', 'Собирайте штампы при каждом визите и получите награду', 'Carta Mediterránea'),
('reels', 'carta_loy_count', 'ru', 'Штампов: {n} из {total}', 'Carta Mediterránea'),
('reels', 'carta_loy_redeemed', 'ru', 'Вы уже использовали эту карту. Спасибо, что вернулись!', 'Carta Mediterránea'),
('reels', 'carta_loy_view_reward', 'ru', 'Посмотреть награду', 'Carta Mediterránea'),
('reels', 'carta_loy_ask_staff', 'ru', 'Попросите официанта ввести PIN-код', 'Carta Mediterránea'),
('reels', 'carta_loy_add', 'ru', 'Добавить штамп', 'Carta Mediterránea'),
('reels', 'carta_loy_pin_required', 'ru', 'Введите 4-значный PIN-код', 'Carta Mediterránea'),
('reels', 'carta_loy_pin_wrong', 'ru', 'Неверный PIN-код', 'Carta Mediterránea'),
('reels', 'carta_ios_offers', 'ru', 'VIP-предложения', 'Carta Mediterránea'),
('reels', 'carta_ios_fast', 'ru', 'Быстрее', 'Carta Mediterránea'),
('reels', 'carta_ios_title', 'ru', 'Добавьте меню на iPhone', 'Carta Mediterránea'),
('reels', 'carta_ios_body', 'ru', 'На iPhone уведомления приходят, только если меню на экране «Домой». Откройте его оттуда и включите их.', 'Carta Mediterránea'),
('reels', 'carta_ios_step1', 'ru', 'Нажмите «Поделиться» внизу', 'Carta Mediterránea'),
('reels', 'carta_ios_step2', 'ru', 'Выберите «На экран „Домой“»', 'Carta Mediterránea'),
('reels', 'carta_ios_never', 'ru', 'Больше не показывать', 'Carta Mediterránea'),
('reels', 'carta_dlv_title', 'ru', 'Заказать доставку', 'Carta Mediterránea'),
('reels', 'carta_dlv_closed_today', 'ru', 'Сегодня доставки нет', 'Carta Mediterránea'),
('reels', 'carta_dlv_outside_hours', 'ru', 'Вне часов доставки', 'Carta Mediterránea'),
('reels', 'carta_dlv_unavailable', 'ru', 'Сервис недоступен', 'Carta Mediterránea'),
('reels', 'carta_dlv_empty', 'ru', 'Вы ещё ничего не добавили в заказ', 'Carta Mediterránea'),
('reels', 'carta_dlv_minimum', 'ru', 'Минимальный заказ: {amount}', 'Carta Mediterránea'),
('reels', 'carta_dlv_details', 'ru', 'Данные для доставки', 'Carta Mediterránea'),
('reels', 'carta_dlv_name', 'ru', 'Имя (необязательно)', 'Carta Mediterránea'),
('reels', 'carta_dlv_phone', 'ru', 'Телефон *', 'Carta Mediterránea'),
('reels', 'carta_dlv_address', 'ru', 'Полный адрес *', 'Carta Mediterránea'),
('reels', 'carta_dlv_address_ph', 'ru', 'Улица, дом, этаж, индекс…', 'Carta Mediterránea'),
('reels', 'carta_dlv_notes', 'ru', 'Примечания (необязательно)', 'Carta Mediterránea'),
('reels', 'carta_dlv_notes_ph', 'ru', 'Указания для доставки, аллергии…', 'Carta Mediterránea'),
('reels', 'carta_dlv_privacy', 'ru', '{restaurant} обработает ваше имя, телефон и адрес, чтобы приготовить и доставить этот заказ и выполнить свои налоговые обязательства. Они не используются для рекламы. Вы можете воспользоваться правом на доступ, исправление и удаление данных.', 'Carta Mediterránea'),
('reels', 'carta_dlv_privacy_link', 'ru', 'Политика конфиденциальности', 'Carta Mediterránea'),
('reels', 'carta_dlv_allergy', 'ru', 'Если у вас аллергия, укажите это в примечаниях и подтвердите по телефону: блюда готовятся на кухнях, где используются все аллергены.', 'Carta Mediterránea'),
('reels', 'carta_dlv_payment', 'ru', 'Как будете платить? *', 'Carta Mediterránea'),
('reels', 'carta_dlv_cash', 'ru', 'Наличные', 'Carta Mediterránea'),
('reels', 'carta_dlv_card', 'ru', 'Карта', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_phone', 'ru', 'Укажите телефон', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_phone_bad', 'ru', 'Неверный номер телефона', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_address', 'ru', 'Укажите адрес', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_payment', 'ru', 'Выберите способ оплаты', 'Carta Mediterránea'),
('reels', 'carta_dlv_area', 'ru', 'Зона доставки', 'Carta Mediterránea'),
('reels', 'carta_dlv_order', 'ru', 'Ваш заказ', 'Carta Mediterránea'),
('reels', 'carta_dlv_shipping', 'ru', 'Доставка', 'Carta Mediterránea'),
('reels', 'carta_dlv_free', 'ru', 'Бесплатно', 'Carta Mediterránea'),
('reels', 'carta_dlv_free_from', 'ru', 'Бесплатно от {amount}', 'Carta Mediterránea'),
('reels', 'carta_dlv_vat', 'ru', 'НДС включён. Отправляя заказ, вы подтверждаете, что хотите его оформить и обязуетесь оплатить эту сумму ресторану.', 'Carta Mediterránea'),
('reels', 'carta_dlv_send_wa', 'ru', 'Отправить заказ в WhatsApp', 'Carta Mediterránea'),
('reels', 'carta_dlv_call', 'ru', 'Позвонить в ресторан', 'Carta Mediterránea');
-- uk
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('reels', 'carta_notif_error', 'uk', 'Не вдалося увімкнути сповіщення', 'Carta Mediterránea'),
('reels', 'carta_remember_q', 'uk', 'Впізнати вас наступного разу?', 'Carta Mediterránea'),
('reels', 'carta_remember_sub', 'uk', 'Ми зберігаємо на цьому телефоні випадкове число на 12 місяців, щоб ресторан знав, що ви повернулися. Без вашого імені й без реклами.', 'Carta Mediterránea'),
('reels', 'carta_remember_more', 'uk', 'Докладніше', 'Carta Mediterránea'),
('reels', 'carta_remember_yes', 'uk', 'Так', 'Carta Mediterránea'),
('reels', 'carta_remember_no', 'uk', 'Ні', 'Carta Mediterránea'),
('reels', 'carta_remember_done_yes', 'uk', 'Ми вас впізнаємо', 'Carta Mediterránea'),
('reels', 'carta_remember_done_no', 'uk', 'Гаразд, ми вас не запам’ятовуємо', 'Carta Mediterránea'),
('reels', 'carta_confirm', 'uk', 'Підтвердити', 'Carta Mediterránea'),
('reels', 'carta_rt_title', 'uk', 'Як вам?', 'Carta Mediterránea'),
('reels', 'carta_rt_title_prev', 'uk', 'Ваша оцінка', 'Carta Mediterránea'),
('reels', 'carta_rt_sub', 'uk', 'Ваша думка допомагає нам ставати кращими.', 'Carta Mediterránea'),
('reels', 'carta_rt_improve', 'uk', 'Що нам покращити?', 'Carta Mediterránea'),
('reels', 'carta_rt_send', 'uk', 'Надіслати', 'Carta Mediterránea'),
('reels', 'carta_rt_star', 'uk', '{n} з 5', 'Carta Mediterránea'),
('reels', 'carta_rt_glad', 'uk', 'Раді, що вам сподобалося!', 'Carta Mediterránea'),
('reels', 'carta_rt_google_invite', 'uk', 'Поділіться враженнями в Google — це допоможе нам рости.', 'Carta Mediterránea'),
('reels', 'carta_rt_google_btn', 'uk', 'Написати відгук у Google', 'Carta Mediterránea'),
('reels', 'carta_rt_thanks', 'uk', 'Дякуємо за вашу думку!', 'Carta Mediterránea'),
('reels', 'carta_rt_thanks_sub', 'uk', 'Ми це врахуємо, щоб ставати кращими.', 'Carta Mediterránea'),
('reels', 'carta_loy_title', 'uk', 'Ваша картка лояльності', 'Carta Mediterránea'),
('reels', 'carta_loy_reward', 'uk', 'Заповніть картку й отримайте: {reward}', 'Carta Mediterránea'),
('reels', 'carta_loy_generic', 'uk', 'Збирайте штампи під час кожного візиту й отримайте нагороду', 'Carta Mediterránea'),
('reels', 'carta_loy_count', 'uk', 'Штампів: {n} з {total}', 'Carta Mediterránea'),
('reels', 'carta_loy_redeemed', 'uk', 'Ви вже використали цю картку. Дякуємо, що повернулися!', 'Carta Mediterránea'),
('reels', 'carta_loy_view_reward', 'uk', 'Переглянути нагороду', 'Carta Mediterránea'),
('reels', 'carta_loy_ask_staff', 'uk', 'Попросіть офіціанта ввести PIN-код', 'Carta Mediterránea'),
('reels', 'carta_loy_add', 'uk', 'Додати штамп', 'Carta Mediterránea'),
('reels', 'carta_loy_pin_required', 'uk', 'Введіть 4-значний PIN-код', 'Carta Mediterránea'),
('reels', 'carta_loy_pin_wrong', 'uk', 'Неправильний PIN-код', 'Carta Mediterránea'),
('reels', 'carta_ios_offers', 'uk', 'VIP-пропозиції', 'Carta Mediterránea'),
('reels', 'carta_ios_fast', 'uk', 'Швидше', 'Carta Mediterránea'),
('reels', 'carta_ios_title', 'uk', 'Додайте меню на iPhone', 'Carta Mediterránea'),
('reels', 'carta_ios_body', 'uk', 'На iPhone сповіщення надходять, лише якщо меню на початковому екрані. Відкрийте його звідти й увімкніть їх.', 'Carta Mediterránea'),
('reels', 'carta_ios_step1', 'uk', 'Торкніться «Поширити» внизу', 'Carta Mediterránea'),
('reels', 'carta_ios_step2', 'uk', 'Виберіть «На початковий екран»', 'Carta Mediterránea'),
('reels', 'carta_ios_never', 'uk', 'Більше не показувати', 'Carta Mediterránea'),
('reels', 'carta_dlv_title', 'uk', 'Замовити доставку', 'Carta Mediterránea'),
('reels', 'carta_dlv_closed_today', 'uk', 'Сьогодні доставки немає', 'Carta Mediterránea'),
('reels', 'carta_dlv_outside_hours', 'uk', 'Поза годинами доставки', 'Carta Mediterránea'),
('reels', 'carta_dlv_unavailable', 'uk', 'Сервіс недоступний', 'Carta Mediterránea'),
('reels', 'carta_dlv_empty', 'uk', 'Ви ще нічого не додали до замовлення', 'Carta Mediterránea'),
('reels', 'carta_dlv_minimum', 'uk', 'Мінімальне замовлення: {amount}', 'Carta Mediterránea'),
('reels', 'carta_dlv_details', 'uk', 'Дані для доставки', 'Carta Mediterránea'),
('reels', 'carta_dlv_name', 'uk', 'Ім’я (необов’язково)', 'Carta Mediterránea'),
('reels', 'carta_dlv_phone', 'uk', 'Телефон *', 'Carta Mediterránea'),
('reels', 'carta_dlv_address', 'uk', 'Повна адреса *', 'Carta Mediterránea'),
('reels', 'carta_dlv_address_ph', 'uk', 'Вулиця, будинок, поверх, індекс…', 'Carta Mediterránea'),
('reels', 'carta_dlv_notes', 'uk', 'Примітки (необов’язково)', 'Carta Mediterránea'),
('reels', 'carta_dlv_notes_ph', 'uk', 'Вказівки для доставки, алергії…', 'Carta Mediterránea'),
('reels', 'carta_dlv_privacy', 'uk', '{restaurant} оброблятиме ваше ім’я, телефон і адресу, щоб приготувати й доставити це замовлення та виконати свої податкові зобов’язання. Вони не використовуються для реклами. Ви можете скористатися правом на доступ, виправлення й видалення даних.', 'Carta Mediterránea'),
('reels', 'carta_dlv_privacy_link', 'uk', 'Політика конфіденційності', 'Carta Mediterránea'),
('reels', 'carta_dlv_allergy', 'uk', 'Якщо у вас алергія, зазначте це в примітках і підтвердьте телефоном: страви готують на кухнях, де використовують усі алергени.', 'Carta Mediterránea'),
('reels', 'carta_dlv_payment', 'uk', 'Як платитимете? *', 'Carta Mediterránea'),
('reels', 'carta_dlv_cash', 'uk', 'Готівка', 'Carta Mediterránea'),
('reels', 'carta_dlv_card', 'uk', 'Картка', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_phone', 'uk', 'Вкажіть телефон', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_phone_bad', 'uk', 'Неправильний номер телефону', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_address', 'uk', 'Вкажіть адресу', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_payment', 'uk', 'Виберіть спосіб оплати', 'Carta Mediterránea'),
('reels', 'carta_dlv_area', 'uk', 'Зона доставки', 'Carta Mediterránea'),
('reels', 'carta_dlv_order', 'uk', 'Ваше замовлення', 'Carta Mediterránea'),
('reels', 'carta_dlv_shipping', 'uk', 'Доставка', 'Carta Mediterránea'),
('reels', 'carta_dlv_free', 'uk', 'Безкоштовно', 'Carta Mediterránea'),
('reels', 'carta_dlv_free_from', 'uk', 'Безкоштовно від {amount}', 'Carta Mediterránea'),
('reels', 'carta_dlv_vat', 'uk', 'ПДВ включено. Надсилаючи замовлення, ви підтверджуєте, що хочете його оформити, і зобов’язуєтеся сплатити цю суму ресторану.', 'Carta Mediterránea'),
('reels', 'carta_dlv_send_wa', 'uk', 'Надіслати замовлення у WhatsApp', 'Carta Mediterránea'),
('reels', 'carta_dlv_call', 'uk', 'Зателефонувати в ресторан', 'Carta Mediterránea');
-- zh
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('reels', 'carta_notif_error', 'zh', '无法开启通知', 'Carta Mediterránea'),
('reels', 'carta_remember_q', 'zh', '下次来时要认出您吗？', 'Carta Mediterránea'),
('reels', 'carta_remember_sub', 'zh', '我们会在这部手机上保存一个随机编号 12 个月，让餐厅知道您再次光临。不涉及您的姓名，也没有广告。', 'Carta Mediterránea'),
('reels', 'carta_remember_more', 'zh', '了解更多', 'Carta Mediterránea'),
('reels', 'carta_remember_yes', 'zh', '要', 'Carta Mediterránea'),
('reels', 'carta_remember_no', 'zh', '不用', 'Carta Mediterránea'),
('reels', 'carta_remember_done_yes', 'zh', '我们会认出您', 'Carta Mediterránea'),
('reels', 'carta_remember_done_no', 'zh', '好的，我们不会记住您', 'Carta Mediterránea'),
('reels', 'carta_confirm', 'zh', '确认', 'Carta Mediterránea'),
('reels', 'carta_rt_title', 'zh', '您觉得怎么样？', 'Carta Mediterránea'),
('reels', 'carta_rt_title_prev', 'zh', '您的评分', 'Carta Mediterránea'),
('reels', 'carta_rt_sub', 'zh', '您的意见帮助我们做得更好。', 'Carta Mediterránea'),
('reels', 'carta_rt_improve', 'zh', '我们可以在哪些方面改进？', 'Carta Mediterránea'),
('reels', 'carta_rt_send', 'zh', '发送', 'Carta Mediterránea'),
('reels', 'carta_rt_star', 'zh', '{n} 分（满分 5 分）', 'Carta Mediterránea'),
('reels', 'carta_rt_glad', 'zh', '很高兴您喜欢！', 'Carta Mediterránea'),
('reels', 'carta_rt_google_invite', 'zh', '欢迎在 Google 上分享您的体验，帮助我们成长。', 'Carta Mediterránea'),
('reels', 'carta_rt_google_btn', 'zh', '在 Google 上写评价', 'Carta Mediterránea'),
('reels', 'carta_rt_thanks', 'zh', '感谢您的意见！', 'Carta Mediterránea'),
('reels', 'carta_rt_thanks_sub', 'zh', '我们已记下，会继续改进。', 'Carta Mediterránea'),
('reels', 'carta_loy_title', 'zh', '您的会员卡', 'Carta Mediterránea'),
('reels', 'carta_loy_reward', 'zh', '集满印章即可获得：{reward}', 'Carta Mediterránea'),
('reels', 'carta_loy_generic', 'zh', '每次光临集印章，赢取奖励', 'Carta Mediterránea'),
('reels', 'carta_loy_count', 'zh', '已集 {n}/{total} 个印章', 'Carta Mediterránea'),
('reels', 'carta_loy_redeemed', 'zh', '您已兑换过这张卡。感谢再次光临！', 'Carta Mediterránea'),
('reels', 'carta_loy_view_reward', 'zh', '查看我的奖励', 'Carta Mediterránea'),
('reels', 'carta_loy_ask_staff', 'zh', '请服务员输入 PIN 码', 'Carta Mediterránea'),
('reels', 'carta_loy_add', 'zh', '盖章', 'Carta Mediterránea'),
('reels', 'carta_loy_pin_required', 'zh', '请输入 4 位 PIN 码', 'Carta Mediterránea'),
('reels', 'carta_loy_pin_wrong', 'zh', 'PIN 码错误', 'Carta Mediterránea'),
('reels', 'carta_ios_offers', 'zh', 'VIP 优惠', 'Carta Mediterránea'),
('reels', 'carta_ios_fast', 'zh', '更快', 'Carta Mediterránea'),
('reels', 'carta_ios_title', 'zh', '将菜单添加到您的 iPhone', 'Carta Mediterránea'),
('reels', 'carta_ios_body', 'zh', '在 iPhone 上，只有菜单在主屏幕上时才能收到通知。请从主屏幕打开并开启通知。', 'Carta Mediterránea'),
('reels', 'carta_ios_step1', 'zh', '点按下方的“共享”', 'Carta Mediterránea'),
('reels', 'carta_ios_step2', 'zh', '选择“添加到主屏幕”', 'Carta Mediterránea'),
('reels', 'carta_ios_never', 'zh', '不再显示', 'Carta Mediterránea'),
('reels', 'carta_dlv_title', 'zh', '外卖送餐', 'Carta Mediterránea'),
('reels', 'carta_dlv_closed_today', 'zh', '今天不提供送餐服务', 'Carta Mediterránea'),
('reels', 'carta_dlv_outside_hours', 'zh', '不在送餐时间内', 'Carta Mediterránea'),
('reels', 'carta_dlv_unavailable', 'zh', '服务暂不可用', 'Carta Mediterránea'),
('reels', 'carta_dlv_empty', 'zh', '您还没有添加任何菜品', 'Carta Mediterránea'),
('reels', 'carta_dlv_minimum', 'zh', '最低起送：{amount}', 'Carta Mediterránea'),
('reels', 'carta_dlv_details', 'zh', '送餐信息', 'Carta Mediterránea'),
('reels', 'carta_dlv_name', 'zh', '姓名（选填）', 'Carta Mediterránea'),
('reels', 'carta_dlv_phone', 'zh', '电话 *', 'Carta Mediterránea'),
('reels', 'carta_dlv_address', 'zh', '详细地址 *', 'Carta Mediterránea'),
('reels', 'carta_dlv_address_ph', 'zh', '街道、门牌号、楼层、邮编…', 'Carta Mediterránea'),
('reels', 'carta_dlv_notes', 'zh', '备注（选填）', 'Carta Mediterránea'),
('reels', 'carta_dlv_notes_ph', 'zh', '送餐说明、过敏信息…', 'Carta Mediterránea'),
('reels', 'carta_dlv_privacy', 'zh', '{restaurant} 将使用您的姓名、电话和地址来准备和配送此订单，并履行其税务义务。这些信息不会用于广告。您可以行使访问、更正和删除的权利。', 'Carta Mediterránea'),
('reels', 'carta_dlv_privacy_link', 'zh', '隐私政策', 'Carta Mediterránea'),
('reels', 'carta_dlv_allergy', 'zh', '如有过敏，请在备注中注明并电话确认：菜品在处理所有过敏原的厨房中制作。', 'Carta Mediterránea'),
('reels', 'carta_dlv_payment', 'zh', '付款方式 *', 'Carta Mediterránea'),
('reels', 'carta_dlv_cash', 'zh', '现金', 'Carta Mediterránea'),
('reels', 'carta_dlv_card', 'zh', '银行卡', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_phone', 'zh', '请填写电话', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_phone_bad', 'zh', '电话号码无效', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_address', 'zh', '请填写地址', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_payment', 'zh', '请选择付款方式', 'Carta Mediterránea'),
('reels', 'carta_dlv_area', 'zh', '配送范围', 'Carta Mediterránea'),
('reels', 'carta_dlv_order', 'zh', '您的订单', 'Carta Mediterránea'),
('reels', 'carta_dlv_shipping', 'zh', '配送费', 'Carta Mediterránea'),
('reels', 'carta_dlv_free', 'zh', '免费', 'Carta Mediterránea'),
('reels', 'carta_dlv_free_from', 'zh', '满 {amount} 免配送费', 'Carta Mediterránea'),
('reels', 'carta_dlv_vat', 'zh', '已含增值税。发送订单即表示您确认下单，并有义务向餐厅支付此金额。', 'Carta Mediterránea'),
('reels', 'carta_dlv_send_wa', 'zh', '通过 WhatsApp 发送订单', 'Carta Mediterránea'),
('reels', 'carta_dlv_call', 'zh', '致电餐厅', 'Carta Mediterránea');
-- ja
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('reels', 'carta_notif_error', 'ja', '通知をオンにできませんでした', 'Carta Mediterránea'),
('reels', 'carta_remember_q', 'ja', '次回のご来店時に、お客様を認識してもよいですか？', 'Carta Mediterránea'),
('reels', 'carta_remember_sub', 'ja', 'この端末にランダムな番号を12か月保存し、再来店したことがお店にわかるようにします。お名前は不要で、広告もありません。', 'Carta Mediterránea'),
('reels', 'carta_remember_more', 'ja', '詳しく見る', 'Carta Mediterránea'),
('reels', 'carta_remember_yes', 'ja', 'はい', 'Carta Mediterránea'),
('reels', 'carta_remember_no', 'ja', 'いいえ', 'Carta Mediterránea'),
('reels', 'carta_remember_done_yes', 'ja', '次回から認識します', 'Carta Mediterránea'),
('reels', 'carta_remember_done_no', 'ja', 'わかりました。記録しません', 'Carta Mediterránea'),
('reels', 'carta_confirm', 'ja', '確認', 'Carta Mediterránea'),
('reels', 'carta_rt_title', 'ja', 'いかがでしたか？', 'Carta Mediterránea'),
('reels', 'carta_rt_title_prev', 'ja', 'あなたの評価', 'Carta Mediterránea'),
('reels', 'carta_rt_sub', 'ja', 'ご意見はサービス向上に役立ちます。', 'Carta Mediterránea'),
('reels', 'carta_rt_improve', 'ja', '改善すべき点を教えてください', 'Carta Mediterránea'),
('reels', 'carta_rt_send', 'ja', '送信', 'Carta Mediterránea'),
('reels', 'carta_rt_star', 'ja', '5点中{n}点', 'Carta Mediterránea'),
('reels', 'carta_rt_glad', 'ja', '気に入っていただけてうれしいです！', 'Carta Mediterránea'),
('reels', 'carta_rt_google_invite', 'ja', 'Googleで体験をシェアして、私たちの成長を応援してください。', 'Carta Mediterránea'),
('reels', 'carta_rt_google_btn', 'ja', 'Googleにレビューを書く', 'Carta Mediterránea'),
('reels', 'carta_rt_thanks', 'ja', 'ご意見ありがとうございます！', 'Carta Mediterránea'),
('reels', 'carta_rt_thanks_sub', 'ja', '今後の改善に生かします。', 'Carta Mediterránea'),
('reels', 'carta_loy_title', 'ja', 'ポイントカード', 'Carta Mediterránea'),
('reels', 'carta_loy_reward', 'ja', 'カードを完成させると：{reward}', 'Carta Mediterránea'),
('reels', 'carta_loy_generic', 'ja', '来店ごとにスタンプを集めて特典をゲット', 'Carta Mediterránea'),
('reels', 'carta_loy_count', 'ja', 'スタンプ {n}/{total}', 'Carta Mediterránea'),
('reels', 'carta_loy_redeemed', 'ja', 'このカードは使用済みです。またのご来店ありがとうございます！', 'Carta Mediterránea'),
('reels', 'carta_loy_view_reward', 'ja', '特典を見る', 'Carta Mediterránea'),
('reels', 'carta_loy_ask_staff', 'ja', 'スタッフにPINを入力してもらってください', 'Carta Mediterránea'),
('reels', 'carta_loy_add', 'ja', 'スタンプを押す', 'Carta Mediterránea'),
('reels', 'carta_loy_pin_required', 'ja', '4桁のPINを入力してください', 'Carta Mediterránea'),
('reels', 'carta_loy_pin_wrong', 'ja', 'PINが違います', 'Carta Mediterránea'),
('reels', 'carta_ios_offers', 'ja', 'VIP特典', 'Carta Mediterránea'),
('reels', 'carta_ios_fast', 'ja', 'より速く', 'Carta Mediterránea'),
('reels', 'carta_ios_title', 'ja', 'メニューをiPhoneに追加', 'Carta Mediterránea'),
('reels', 'carta_ios_body', 'ja', 'iPhoneでは、メニューをホーム画面に追加した場合のみ通知が届きます。ホーム画面から開いてオンにしてください。', 'Carta Mediterránea'),
('reels', 'carta_ios_step1', 'ja', '下の「共有」をタップ', 'Carta Mediterránea'),
('reels', 'carta_ios_step2', 'ja', '「ホーム画面に追加」を選択', 'Carta Mediterránea'),
('reels', 'carta_ios_never', 'ja', '今後表示しない', 'Carta Mediterránea'),
('reels', 'carta_dlv_title', 'ja', 'デリバリーを注文', 'Carta Mediterránea'),
('reels', 'carta_dlv_closed_today', 'ja', '本日はデリバリーを行っていません', 'Carta Mediterránea'),
('reels', 'carta_dlv_outside_hours', 'ja', 'デリバリー時間外です', 'Carta Mediterránea'),
('reels', 'carta_dlv_unavailable', 'ja', 'サービスは利用できません', 'Carta Mediterránea'),
('reels', 'carta_dlv_empty', 'ja', 'まだ注文に何も追加されていません', 'Carta Mediterránea'),
('reels', 'carta_dlv_minimum', 'ja', '最低注文金額：{amount}', 'Carta Mediterránea'),
('reels', 'carta_dlv_details', 'ja', 'お届け先情報', 'Carta Mediterránea'),
('reels', 'carta_dlv_name', 'ja', 'お名前（任意）', 'Carta Mediterránea'),
('reels', 'carta_dlv_phone', 'ja', '電話番号 *', 'Carta Mediterránea'),
('reels', 'carta_dlv_address', 'ja', '住所（すべて） *', 'Carta Mediterránea'),
('reels', 'carta_dlv_address_ph', 'ja', '通り、番地、階、郵便番号…', 'Carta Mediterránea'),
('reels', 'carta_dlv_notes', 'ja', '備考（任意）', 'Carta Mediterránea'),
('reels', 'carta_dlv_notes_ph', 'ja', '配達時の指示、アレルギー…', 'Carta Mediterránea'),
('reels', 'carta_dlv_privacy', 'ja', '{restaurant}は、この注文の調理と配達、および税務上の義務の履行のために、お名前・電話番号・住所を取り扱います。広告には使用しません。アクセス、訂正、削除の権利を行使できます。', 'Carta Mediterránea'),
('reels', 'carta_dlv_privacy_link', 'ja', 'プライバシーポリシー', 'Carta Mediterránea'),
('reels', 'carta_dlv_allergy', 'ja', 'アレルギーがある場合は備考に記入し、電話でも確認してください。料理はすべてのアレルゲンを扱う厨房で調理されます。', 'Carta Mediterránea'),
('reels', 'carta_dlv_payment', 'ja', 'お支払い方法 *', 'Carta Mediterránea'),
('reels', 'carta_dlv_cash', 'ja', '現金', 'Carta Mediterránea'),
('reels', 'carta_dlv_card', 'ja', 'カード', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_phone', 'ja', '電話番号は必須です', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_phone_bad', 'ja', '電話番号が正しくありません', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_address', 'ja', '住所は必須です', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_payment', 'ja', 'お支払い方法を選んでください', 'Carta Mediterránea'),
('reels', 'carta_dlv_area', 'ja', '配達エリア', 'Carta Mediterránea'),
('reels', 'carta_dlv_order', 'ja', 'ご注文内容', 'Carta Mediterránea'),
('reels', 'carta_dlv_shipping', 'ja', '配送料', 'Carta Mediterránea'),
('reels', 'carta_dlv_free', 'ja', '無料', 'Carta Mediterránea'),
('reels', 'carta_dlv_free_from', 'ja', '{amount}以上で無料', 'Carta Mediterránea'),
('reels', 'carta_dlv_vat', 'ja', '税込。注文を送信すると、注文の意思と、この金額を店舗に支払う義務があることを確認したことになります。', 'Carta Mediterránea'),
('reels', 'carta_dlv_send_wa', 'ja', 'WhatsAppで注文を送る', 'Carta Mediterránea'),
('reels', 'carta_dlv_call', 'ja', 'お店に電話する', 'Carta Mediterránea');
-- ko
INSERT OR REPLACE INTO localization_strings (context, key_name, language_code, label, description) VALUES
('reels', 'carta_notif_error', 'ko', '알림을 켤 수 없었어요', 'Carta Mediterránea'),
('reels', 'carta_remember_q', 'ko', '다음 방문 때 알아봐 드릴까요?', 'Carta Mediterránea'),
('reels', 'carta_remember_sub', 'ko', '이 휴대폰에 12개월 동안 임의의 번호를 저장해 다시 방문하신 걸 식당이 알 수 있게 해요. 이름은 받지 않고 광고도 없어요.', 'Carta Mediterránea'),
('reels', 'carta_remember_more', 'ko', '자세히 보기', 'Carta Mediterránea'),
('reels', 'carta_remember_yes', 'ko', '네', 'Carta Mediterránea'),
('reels', 'carta_remember_no', 'ko', '아니요', 'Carta Mediterránea'),
('reels', 'carta_remember_done_yes', 'ko', '다음에 알아볼게요', 'Carta Mediterránea'),
('reels', 'carta_remember_done_no', 'ko', '알겠어요, 기억하지 않을게요', 'Carta Mediterránea'),
('reels', 'carta_confirm', 'ko', '확인', 'Carta Mediterránea'),
('reels', 'carta_rt_title', 'ko', '어떠셨어요?', 'Carta Mediterránea'),
('reels', 'carta_rt_title_prev', 'ko', '내 평가', 'Carta Mediterránea'),
('reels', 'carta_rt_sub', 'ko', '의견을 주시면 더 나아질 수 있어요.', 'Carta Mediterránea'),
('reels', 'carta_rt_improve', 'ko', '어떤 점을 개선하면 좋을까요?', 'Carta Mediterránea'),
('reels', 'carta_rt_send', 'ko', '보내기', 'Carta Mediterránea'),
('reels', 'carta_rt_star', 'ko', '5점 중 {n}점', 'Carta Mediterránea'),
('reels', 'carta_rt_glad', 'ko', '마음에 드셨다니 기뻐요!', 'Carta Mediterránea'),
('reels', 'carta_rt_google_invite', 'ko', 'Google에 경험을 공유해 저희가 성장하도록 도와주세요.', 'Carta Mediterránea'),
('reels', 'carta_rt_google_btn', 'ko', 'Google에 리뷰 쓰기', 'Carta Mediterránea'),
('reels', 'carta_rt_thanks', 'ko', '의견 감사해요!', 'Carta Mediterránea'),
('reels', 'carta_rt_thanks_sub', 'ko', '계속 개선할 수 있도록 참고할게요.', 'Carta Mediterránea'),
('reels', 'carta_loy_title', 'ko', '내 적립 카드', 'Carta Mediterránea'),
('reels', 'carta_loy_reward', 'ko', '카드를 다 채우면 받을 수 있어요: {reward}', 'Carta Mediterránea'),
('reels', 'carta_loy_generic', 'ko', '방문할 때마다 도장을 모아 혜택을 받으세요', 'Carta Mediterránea'),
('reels', 'carta_loy_count', 'ko', '도장 {n}/{total}개', 'Carta Mediterránea'),
('reels', 'carta_loy_redeemed', 'ko', '이미 사용한 카드예요. 다시 와 주셔서 감사해요!', 'Carta Mediterránea'),
('reels', 'carta_loy_view_reward', 'ko', '내 혜택 보기', 'Carta Mediterránea'),
('reels', 'carta_loy_ask_staff', 'ko', '직원에게 PIN 입력을 요청하세요', 'Carta Mediterránea'),
('reels', 'carta_loy_add', 'ko', '도장 찍기', 'Carta Mediterránea'),
('reels', 'carta_loy_pin_required', 'ko', '4자리 PIN을 입력하세요', 'Carta Mediterránea'),
('reels', 'carta_loy_pin_wrong', 'ko', 'PIN이 올바르지 않아요', 'Carta Mediterránea'),
('reels', 'carta_ios_offers', 'ko', 'VIP 혜택', 'Carta Mediterránea'),
('reels', 'carta_ios_fast', 'ko', '더 빠르게', 'Carta Mediterránea'),
('reels', 'carta_ios_title', 'ko', 'iPhone에 메뉴 추가하기', 'Carta Mediterránea'),
('reels', 'carta_ios_body', 'ko', 'iPhone에서는 메뉴가 홈 화면에 있어야 알림을 받을 수 있어요. 홈 화면에서 열고 알림을 켜세요.', 'Carta Mediterránea'),
('reels', 'carta_ios_step1', 'ko', '아래의 ‘공유’를 누르세요', 'Carta Mediterránea'),
('reels', 'carta_ios_step2', 'ko', '‘홈 화면에 추가’를 선택하세요', 'Carta Mediterránea'),
('reels', 'carta_ios_never', 'ko', '다시 보지 않기', 'Carta Mediterránea'),
('reels', 'carta_dlv_title', 'ko', '배달 주문', 'Carta Mediterránea'),
('reels', 'carta_dlv_closed_today', 'ko', '오늘은 배달하지 않아요', 'Carta Mediterránea'),
('reels', 'carta_dlv_outside_hours', 'ko', '배달 시간이 아니에요', 'Carta Mediterránea'),
('reels', 'carta_dlv_unavailable', 'ko', '서비스를 이용할 수 없어요', 'Carta Mediterránea'),
('reels', 'carta_dlv_empty', 'ko', '아직 주문에 담은 메뉴가 없어요', 'Carta Mediterránea'),
('reels', 'carta_dlv_minimum', 'ko', '최소 주문 금액: {amount}', 'Carta Mediterránea'),
('reels', 'carta_dlv_details', 'ko', '배달 정보', 'Carta Mediterránea'),
('reels', 'carta_dlv_name', 'ko', '이름(선택)', 'Carta Mediterránea'),
('reels', 'carta_dlv_phone', 'ko', '전화번호 *', 'Carta Mediterránea'),
('reels', 'carta_dlv_address', 'ko', '전체 주소 *', 'Carta Mediterránea'),
('reels', 'carta_dlv_address_ph', 'ko', '도로명, 번지, 층, 우편번호…', 'Carta Mediterránea'),
('reels', 'carta_dlv_notes', 'ko', '요청 사항(선택)', 'Carta Mediterránea'),
('reels', 'carta_dlv_notes_ph', 'ko', '배달 요청, 알레르기…', 'Carta Mediterránea'),
('reels', 'carta_dlv_privacy', 'ko', '{restaurant}은(는) 이 주문을 준비·배달하고 세무 의무를 이행하기 위해 이름, 전화번호, 주소를 처리해요. 광고에는 사용하지 않아요. 열람, 정정, 삭제 권리를 행사할 수 있어요.', 'Carta Mediterránea'),
('reels', 'carta_dlv_privacy_link', 'ko', '개인정보 처리방침', 'Carta Mediterránea'),
('reels', 'carta_dlv_allergy', 'ko', '알레르기가 있으면 요청 사항에 적고 전화로도 확인해 주세요. 모든 알레르기 유발 물질을 다루는 주방에서 조리해요.', 'Carta Mediterránea'),
('reels', 'carta_dlv_payment', 'ko', '결제 방법 *', 'Carta Mediterránea'),
('reels', 'carta_dlv_cash', 'ko', '현금', 'Carta Mediterránea'),
('reels', 'carta_dlv_card', 'ko', '카드', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_phone', 'ko', '전화번호를 입력하세요', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_phone_bad', 'ko', '전화번호가 올바르지 않아요', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_address', 'ko', '주소를 입력하세요', 'Carta Mediterránea'),
('reels', 'carta_dlv_err_payment', 'ko', '결제 방법을 선택하세요', 'Carta Mediterránea'),
('reels', 'carta_dlv_area', 'ko', '배달 지역', 'Carta Mediterránea'),
('reels', 'carta_dlv_order', 'ko', '주문 내역', 'Carta Mediterránea'),
('reels', 'carta_dlv_shipping', 'ko', '배달비', 'Carta Mediterránea'),
('reels', 'carta_dlv_free', 'ko', '무료', 'Carta Mediterránea'),
('reels', 'carta_dlv_free_from', 'ko', '{amount} 이상 무료', 'Carta Mediterránea'),
('reels', 'carta_dlv_vat', 'ko', '부가세 포함. 주문을 보내면 주문 의사와 이 금액을 식당에 지불할 의무가 있음을 확인하는 거예요.', 'Carta Mediterránea'),
('reels', 'carta_dlv_send_wa', 'ko', 'WhatsApp으로 주문 보내기', 'Carta Mediterránea'),
('reels', 'carta_dlv_call', 'ko', '식당에 전화하기', 'Carta Mediterránea');
