// Textos de la carta. Viven en D1 (`localization_strings`, context 'reels', 13 idiomas:
// migración 0099); aquí solo está el español como respaldo si una clave aún no ha llegado.
// Las claves que ya existían antes del rediseño (button_add, allergens, see_more…) se reutilizan.

export const ES = {
  // ya existentes
  button_add: 'Añadir',
  button_cancel: 'Cancelar',
  half_portion_label: 'Media ración',
  allergens: 'Alérgenos',
  ingredients: 'Ingredientes',
  see_more: 'Ver más',
  likes_label: 'Me gusta',
  loading: 'Cargando',
  dish_untitled: 'Plato sin nombre',
  // nuevas (rediseño)
  carta_menu: 'Carta',
  carta_house_hint: 'Reservas, avisos y más',
  carta_welcome_kicker: 'Bienvenidos a',
  carta_start: 'Ver la carta',
  carta_more_languages: 'Más idiomas',
  carta_full_portion: 'Ración',
  carta_choose_portion: 'Elige ración',
  carta_quantity: 'Cantidad',
  carta_no_allergens: 'Sin alérgenos declarados',
  carta_back: 'Volver',
  carta_back_videos: 'Volver a los vídeos',
  carta_videos: 'Vídeos',
  carta_selection: 'Tu selección',
  carta_to_order: 'Para pedir',
  carta_total: 'Total',
  carta_staff_note: 'No se envía nada: enséñasela al camarero para pedir.',
  carta_show_waiter: 'Enseñar al camarero',
  carta_keep_browsing: 'Seguir mirando',
  carta_empty: 'Aún no has elegido nada.',
  carta_for_waiter: 'Para el camarero',
  carta_badge_featured: 'Destacado',
  carta_badge_new: 'Nuevo',
  carta_badge_vegetarian: 'Vegetariano',
  carta_badge_vegan: 'Vegano',
  carta_badge_gluten_free: 'Sin gluten',
  carta_no_video: 'Este plato aún no tiene vídeo',
  carta_added: 'Añadido',
  carta_liked: 'Guardado en tus me gusta',
  carta_unliked: 'Quitado de tus me gusta',
  carta_likes_note: 'Los guardamos en este móvil: la próxima vez que vengas seguirán aquí.',
  carta_likes_empty: 'Toca el corazón, o el vídeo dos veces, para guardar un plato y decidir luego.',
  carta_add_all: 'Añadir todos a pedir',
  carta_top_liked: 'Lo que más gusta',
  carta_top_liked_sub: 'Según los me gusta de quienes han comido aquí',
  carta_dish_one: '1 plato',
  carta_dish_other: '{n} platos',
  carta_menu_count: '{n} platos en la carta',
  carta_avoid_title: '¿Qué evitas?',
  carta_avoid_sub: 'Marca lo que no puedes comer y te avisamos en cada plato que lo lleve. Se guarda solo en este móvil.',
  carta_avoid_on: 'Evito',
  carta_this_dish: 'Este plato lleva',
  carta_contains: 'Lleva',
  carta_avoid_warn: 'lo has marcado para evitar',
  carta_ask_waiter: 'Si tienes una alergia grave, confírmalo siempre con el camarero.',
  carta_see_allergens: 'Ver alérgenos',
  carta_menu_allergens: 'Alérgenos de esta carta',
  carta_no_menu_allergens: 'Este restaurante aún no ha marcado los alérgenos en su carta digital. Pregunta al camarero antes de pedir.',
  carta_done: 'Listo',
  carta_notif_title: 'Avisos',
  carta_notif_lead: 'Te avisamos de lo nuevo, sin darnos tu nombre ni tu teléfono.',
  carta_notif_1: 'Platos nuevos',
  carta_notif_1_sub: 'Cuando entra algo en la carta',
  carta_notif_2: 'Ofertas',
  carta_notif_2_sub: 'Solo las de esta casa',
  carta_notif_3: 'Tu tarjeta de sellos',
  carta_notif_3_sub: 'Cuando te falte poco para el premio',
  carta_notif_on: 'Activar avisos',
  carta_notif_active: 'Avisos activados',
  carta_notif_off: 'Desactivar avisos',
  carta_notif_note: 'Tu navegador te pedirá permiso. Puedes quitarlos cuando quieras desde aquí.',
  carta_notif_ios: 'En iPhone, primero añade la carta a tu pantalla de inicio.',
  carta_notif_ask: '¿Te avisamos cuando haya platos nuevos u ofertas?',
  carta_notif_denied: 'Tu navegador tiene los avisos bloqueados para esta web. Puedes permitirlos en sus ajustes.',
  carta_notif_sub_off: 'Platos nuevos y ofertas',
  carta_notif_sub_on: 'Activados',
  carta_reserve: 'Reservar mesa',
  carta_reserve_sub: 'Elige día y hora',
  carta_takeaway: 'Pedir para llevar',
  carta_takeaway_sub: 'Recoge en el local o te lo llevamos',
  carta_stamps: 'Tarjeta de sellos',
  carta_stamps_sub: 'Suma un sello en cada visita',
  carta_offer: 'Oferta de bienvenida',
  carta_offer_sub: 'Tienes una esperándote',
  carta_rate: 'Valóranos',
  carta_rate_sub: 'Un minuto, y nos ayuda mucho',
  carta_web: 'Nuestra web',
  carta_web_sub: 'Historia, eventos y contacto',
  carta_whatsapp: 'WhatsApp',
  carta_whatsapp_sub: 'Escríbenos',
  carta_instagram: 'Instagram',
  carta_language: 'Idioma',
  carta_current: 'Actual',
  carta_privacy: 'Privacidad',
  carta_minus: 'Quitar uno',
  carta_plus: 'Añadir uno',
  carta_dish_n: 'Plato {n}',
  carta_empty_menu: 'No hay carta disponible en este momento',
  // migración 0102: avisos, "¿te reconocemos?" y los diálogos heredados (pedido, sellos,
  // valoración, iPhone), que antes salían siempre en español
  carta_notif_error: 'No se han podido activar los avisos',
  carta_remember_q: '¿Te reconocemos la próxima vez que vengas?',
  carta_remember_sub: 'Guardamos un número al azar en este móvil durante 12 meses para que el restaurante sepa que has vuelto. Sin tu nombre y sin publicidad.',
  carta_remember_more: 'Más información',
  carta_remember_yes: 'Sí',
  carta_remember_no: 'No',
  carta_remember_done_yes: 'Te reconoceremos',
  carta_remember_done_no: 'De acuerdo, no te recordamos',
  carta_confirm: 'Confirmar',
  carta_rt_title: '¿Qué te ha parecido?',
  carta_rt_title_prev: 'Tu valoración',
  carta_rt_sub: 'Tu opinión nos ayuda a mejorar.',
  carta_rt_improve: '¿En qué podemos mejorar?',
  carta_rt_send: 'Enviar',
  carta_rt_star: '{n} de 5',
  carta_rt_glad: '¡Nos alegra que te haya gustado!',
  carta_rt_google_invite: 'Te invitamos a compartir tu experiencia en Google para ayudarnos a crecer.',
  carta_rt_google_btn: 'Escribir reseña en Google',
  carta_rt_thanks: '¡Gracias por tu opinión!',
  carta_rt_thanks_sub: 'Tomamos nota para seguir mejorando.',
  carta_loy_title: 'Tu tarjeta de fidelidad',
  carta_loy_reward: 'Completa la tarjeta y consigue: {reward}',
  carta_loy_generic: 'Junta sellos en cada visita y consigue tu premio',
  carta_loy_count: '{n} de {total} sellos',
  carta_loy_redeemed: 'Ya canjeaste esta tarjeta. ¡Gracias por volver!',
  carta_loy_view_reward: 'Ver mi premio',
  carta_loy_ask_staff: 'Pide al camarero que introduzca el PIN',
  carta_loy_add: 'Sumar sello',
  carta_loy_pin_required: 'Introduce el PIN de 4 dígitos',
  carta_loy_pin_wrong: 'PIN incorrecto',
  carta_ios_offers: 'Ofertas VIP',
  carta_ios_fast: 'Más rápido',
  carta_ios_title: 'Añade la carta a tu iPhone',
  carta_ios_body: 'En iPhone los avisos solo llegan si la carta está en tu pantalla de inicio. Ábrela desde allí y actívalos.',
  carta_ios_step1: 'Pulsa «Compartir» abajo',
  carta_ios_step2: 'Elige «Añadir a pantalla de inicio»',
  carta_ios_never: 'No volver a mostrar',
  carta_dlv_title: 'Pedir a domicilio',
  carta_dlv_closed_today: 'Hoy no hay servicio de reparto',
  carta_dlv_outside_hours: 'Fuera del horario de reparto',
  carta_dlv_unavailable: 'Servicio no disponible',
  carta_dlv_empty: 'Aún no has añadido nada al pedido',
  carta_dlv_minimum: 'Pedido mínimo: {amount}',
  carta_dlv_details: 'Datos de entrega',
  carta_dlv_name: 'Nombre (opcional)',
  carta_dlv_phone: 'Teléfono *',
  carta_dlv_address: 'Dirección completa *',
  carta_dlv_address_ph: 'Calle, número, piso, código postal…',
  carta_dlv_notes: 'Notas (opcional)',
  carta_dlv_notes_ph: 'Instrucciones de entrega, alergias…',
  carta_dlv_privacy: '{restaurant} tratará tu nombre, teléfono y dirección para preparar y entregar este pedido y para cumplir sus obligaciones fiscales. No se usan para publicidad. Puedes ejercer tus derechos de acceso, rectificación y supresión.',
  carta_dlv_privacy_link: 'Política de privacidad',
  carta_dlv_allergy: 'Si tienes alergias, indícalo en las notas y confírmalo también por teléfono: los platos se elaboran en cocinas donde se manipulan todos los alérgenos.',
  carta_dlv_payment: 'Cómo vas a pagar *',
  carta_dlv_cash: 'Efectivo',
  carta_dlv_card: 'Tarjeta',
  carta_dlv_err_phone: 'El teléfono es obligatorio',
  carta_dlv_err_phone_bad: 'Teléfono no válido',
  carta_dlv_err_address: 'La dirección es obligatoria',
  carta_dlv_err_payment: 'Elige cómo vas a pagar',
  carta_dlv_area: 'Zona de reparto',
  carta_dlv_order: 'Tu pedido',
  carta_dlv_shipping: 'Envío',
  carta_dlv_free: 'Gratis',
  carta_dlv_free_from: 'Gratis a partir de {amount}',
  carta_dlv_vat: 'IVA incluido. Al enviar el pedido confirmas que deseas contratarlo y que conlleva la obligación de pagar este importe al restaurante.',
  carta_dlv_send_wa: 'Enviar pedido por WhatsApp',
  carta_dlv_call: 'Llamar al restaurante',
} as const;

export type StringKey = keyof typeof ES;
export type T = (key: StringKey, vars?: Record<string, string | number>) => string;

export function makeT(translations: Record<string, string> | undefined | null): T {
  return (key, vars) => {
    let s = translations?.[key] || ES[key];
    if (vars) for (const [k, v] of Object.entries(vars)) s = s.split(`{${k}}`).join(String(v));
    return s;
  };
}
